### ISSUE TITLE
When reading data from DuckDB in to pandas Dataframe, the cases of column names are not consistently preserved.

### ISSUE THREAD

**Issue by qiuwei** [cwida/duckdb#1012]
Following the documents, I save a  pandas Dataframe with all column names in uppercase in  DuckDB. 
Loading back the data into pandas dataFrame, I do get all column names in uppercase if I run:
```
df = conn.execute(select * from tablename).fetchdf()
```
However, all of the column names will be in lowercase if I run
```
df = conn.execute(select column_name1, column_name2 ... from tablename).fetchdf()
```

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm this goes wrong here. As a temporary fix you can fix it by quoting the column names (e.g. `df = conn.execute(select "A", "B" ... from tablename).fetchdf()`), or by providing a quoted alias (e.g. `df = conn.execute(select column_name1 AS "COLUMN_NAME_1" ... from tablename).fetchdf()`)
