### ISSUE TITLE
Parquet pushdown with statistics/metadata on row groups?

### ISSUE THREAD

**Issue by dforsber** [cwida/duckdb#1013]
> DuckDB supports projection pushdown into the Parquet file itself. That is to say, when querying a Parquet file, only the columns required for the query are read. This allows you to read only the part of the Parquet file that you are interested in. This will be done automatically by the system.

Does the Parquet reader support Parquet metadata (row groups with min/max etc.) when it is planning the queries or does it read the whole column? I started to be curious since I was reading rows from Parquet that had `rownum` min/max values in the metadata and the whole Parquet files was basically ordered by the `rownum` column. However, reading first 100 rows is fast (with LIMIT 100), but reading the last 100 rows is very slow (with LIMIT). I would assume that if the Parquet reader was reading the "statistics", then it would be able to skip all the row groups except the last one to get the last 100 rows, and thus reading 100 rows from start or the end should be almost equally fast.

**Comment by hannesmuehleisen** [comment]
Statistics usage for Parquet still needs to be implemented.

**Comment by dforsber** [comment]
> Statistics usage for Parquet still needs to be implemented.

Will DuckDB support dynamic extension loading at some point?

Like for SQLite3, there is this parquet vtable extension: https://github.com/cldellow/sqlite-parquet-vtable. I did PR against it to show that the Arrow libs are now part of OS distribution. I guess the Parquet Arrow library should be good(?).

**Comment by hannesmuehleisen** [comment]
This should work now
