### ISSUE TITLE
Memory leak with Q18 subquery fragment in paragght3 branch

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#1016]
Noticed a significant memory leak with Q18, appears to be about 5Gb per execution as SF10.  
select  c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice, sum(l_quantity)
from customer, orders, lineitem
where o_orderkey in (select l_orderkey from lineitem group by l_orderkey having
 sum(l_quantity) > 300) and c_custkey = o_custkey and o_orderkey = l_orderkey
group by c_name, c_custkey, o_orderkey, o_orderdate, o_totalprice
order by o_totalprice desc, o_orderdate limit 100;

Running this frament in isolation also shows the memory leak:

select l_orderkey from lineitem group by l_orderkey having sum(l_quantity) > 300;

ran under 
pragma threads=1;
pragma threads=16;

**Comment by hannesmuehleisen** [comment]
Yup thanks for reporting this. Major changes still happening there.

**Comment by hannesmuehleisen** [comment]
This should be fixed now, thanks for spotting
