### ISSUE TITLE
Performance opportunity with BufferManager Pin/UnPin

### ISSUE THREAD

**Issue by jtommaney1** [cwida/duckdb#1018]
Test scenario:

create table l_2048m as select l_partkey, l_linenumber, l_extendedprice, l_quantity from lineitem limit 1024000000;
delete from l_2048m where l_partkey = 478373;
PRAGMA threads=8; 
select count(*) from l_2048m where l_partkey = 478373;

Linux version 3.10.0-327.ali2011.alios7.x86_64 (admin@ba7ee01966d8) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Tue Jun 6 14:29:12 CST 2017

Performance with 1,2,4,8 threads shows impact of Lock/Unlock within BufferManager
1 thread    2 thread    4 thread     8 thread   16 threads
2.692         1.642         1.011            0.911       1.307

Pragma threads=8;
select count(*) from l_2048m where l_partkey = 478373;
Run Time: real 0.911 user 3.949651 sys 2.938208
pragma threads=16;
select count(*) from l_2048m where l_partkey = 478373;
Run Time: real 1.307 user 3.755393 sys 16.608485

vtune shows significant spin impact:

<img width="2125" alt="Screen Shot 2020-10-16 at 10 49 01 AM" src="https://user-images.githubusercontent.com/41884051/96293389-832e5300-0f9f-11eb-80e3-bbca33ff3c72.png">

<img width="2136" alt="Screen Shot 2020-10-16 at 10 52 26 AM" src="https://user-images.githubusercontent.com/41884051/96293403-8aedf780-0f9f-11eb-9c4d-559f77353778.png">

**Comment by jtommaney-alibaba** [comment]
Simplest use case to demonstrate:

```
create temporary table d as select mod(range, 100000) g, 42 p from range(1000000000);
D pragma threads=1;
Run Time: real 0.001 user 0.000153 sys 0.000022
D select count(*) from d where g = 50000;
┌─────────┐
│ count() │
├─────────┤
│ 10000   │
└─────────┘
Run Time: real 1.680 user 1.680765 sys 0.000322
D 
D 
D pragma threads=4;
Run Time: real 0.001 user 0.000517 sys 0.000000
D select count(*) from d where g = 50000;
┌─────────┐
│ count() │
├─────────┤
│ 10000   │
└─────────┘
Run Time: real 1.545 user 3.488256 sys 1.838499
D 
D 
D pragma threads=16;
Run Time: real 0.001 user 0.001025 sys 0.000015
D select count(*) from d where g = 50000;
┌─────────┐
│ count() │
├─────────┤
│ 10000   │
└─────────┘
Run Time: real 1.734 user 2.866002 sys 24.230703
```

vtune output for this query:

<img width="1847" alt="Screen Shot 2020-10-23 at 5 09 17 PM" src="https://user-images.githubusercontent.com/41884051/97063206-2f011100-1553-11eb-999b-97971f898347.png">


vtune for tpch Q6 at threads-8:

<img width="2297" alt="Screen Shot 2020-10-23 at 4 59 00 PM" src="https://user-images.githubusercontent.com/41884051/97063230-4b04b280-1553-11eb-959c-530fa32a3309.png">

**Comment by Mytherin** [comment]
This should be addressed now, feel free to re-open if there are still problems.
