### ISSUE TITLE
Amalgamation error R 3.6.0 Installation

### ISSUE THREAD

**Issue by cchen-ops** [cwida/duckdb#1021]
I've been trying to install the duckdb package in R 3.6.0 running on Linux using install.packages('duckdb'). I'm getting the following error message, which I have truncated. 

  #line 0 "src/catalog/catalog.cpp"
        ^
duckdb/amalgamation-1.cpp(4): error: invalid line number
  #line 0 "src/catalog/catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(7): error: invalid line number
  #line 0 "src/catalog/catalog_entry/copy_function_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(10): error: invalid line number
  #line 0 "src/catalog/catalog_entry/index_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(13): error: invalid line number
  #line 0 "src/catalog/catalog_entry/schema_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(16): error: invalid line number
  #line 0 "src/catalog/catalog_entry/sequence_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(19): error: invalid line number
  #line 0 "src/catalog/catalog_entry/table_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(22): error: invalid line number
  #line 0 "src/catalog/catalog_entry/table_function_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(25): error: invalid line number
  #line 0 "src/catalog/catalog_entry/view_catalog_entry.cpp"
        ^
duckdb/amalgamation-1.cpp(28): error: invalid line number
  #line 0 "src/catalog/catalog_set.cpp"
        ^
duckdb/amalgamation-1.cpp(31): error: invalid line number
  #line 0 "src/catalog/dependency_manager.cpp"
        ^
duckdb/amalgamation-1.cpp(34): error: invalid line number
  #line 0 "src/common/checksum.cpp"
        ^
duckdb/amalgamation-1.cpp(37): error: invalid line number
  #line 0 "src/common/constants.cpp"
        ^
duckdb/amalgamation-1.cpp(40): error: invalid line number
  #line 0 "src/common/enums/catalog_type.cpp"
        ^
duckdb/amalgamation-1.cpp(43): error: invalid line number
  #line 0 "src/common/enums/expression_type.cpp"
        ^
duckdb/amalgamation-1.cpp(46): error: invalid line number
  #line 0 "src/common/enums/join_type.cpp"
        ^
duckdb/amalgamation-1.cpp(49): error: invalid line number
  #line 0 "src/common/enums/logical_operator_type.cpp"
        ^
duckdb/amalgamation-1.cpp(52): error: invalid line number
  #line 0 "src/common/enums/physical_operator_type.cpp"
        ^
duckdb/amalgamation-1.cpp(55): error: invalid line number
  #line 0 "src/common/enums/relation_type.cpp"
        ^
duckdb/amalgamation-1.cpp(58): error: invalid line number
  #line 0 "src/common/enums/statement_type.cpp"
        ^
duckdb/amalgamation-1.cpp(61): error: invalid line number
  #line 0 "src/common/exception.cpp"
        ^

I'm not sure how to interpret the error message to begin to debug.

**Comment by hannesmuehleisen** [comment]
This should be fixed in the latest version on CRAN. Could you try again and confirm the version?

**Comment by cchen-ops** [comment]
I've tried to specify version 0.2.1-2 when installing from CRAN. I first get the following warning

In file included from duckdb/amalgamation-3.cpp(89):
duckdb/src/function/scalar/date/strftime.cpp(522): warning #823: reference is to variable "i" (declared at line 385) -- under old for-init scoping rules it would have been variable "i" (declared at line 519)
  					pos = i + 1;
  					      ^


Then it errors out with the following message.

In file included from duckdb/third_party/re2/re2/bitstate.cc(28):
duckdb/third_party/re2/util/pod_array.h(16): error: static assertion failed with "T must be POD"
    static_assert(std::is_pod<T>::value,
    ^
          detected during instantiation of class "duckdb_re2::PODArray<T> [with T=duckdb_re2::Prog::Inst]" at line 415 of "duckdb/third_party/re2/re2/prog.h"

compilation aborted for duckdb/third_party/re2/re2/bitstate.cc (code 2)
make: *** [duckdb/third_party/re2/re2/bitstate.o] Error 2
ERROR: compilation failed for package ‘duckdb’
* removing ‘/geode2/home/u020/cch3/Carbonate/R/x86_64-pc-linux-gnu-library/3.6/duckdb’

The downloaded source packages are in
	‘/tmp/Rtmpepmq9l/downloaded_packages’
Warning message:
In install.packages(pkgs = pkg, lib = lib, repos = repos, ...) :
  installation of package ‘duckdb’ had non-zero exit status

**Comment by hannesmuehleisen** [comment]
Ok something strange is going on here. Could you please post the output of sessionInfo() and which exact Linux is this?

**Comment by cchen-ops** [comment]
Sure thing

> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /geode2/soft/hps/rhel7/python/3.6.8/lib/libmkl_rt.so

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C         LC_MONETARY=C        LC_MESSAGES=C        LC_PAPER=C           LC_NAME=C            LC_ADDRESS=C         LC_TELEPHONE=C       LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] versions_0.3      arrow_1.0.1       data.table_1.12.8 dplyr_1.0.0       haven_2.3.1       doParallel_1.0.15 iterators_1.0.12  foreach_1.5.0     sas7bdat_0.5      feather_0.3.5    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5        pillar_1.4.6      compiler_3.6.0    prettyunits_1.1.1 remotes_2.2.0     forcats_0.5.0     tools_3.6.0       pkgbuild_1.1.0    testthat_2.3.2    bit_4.0.4         pkgload_1.1.0     lifecycle_0.2.0   tibble_3.0.3      pkgconfig_2.0.3   rlang_0.4.7       cli_2.0.2        
[17] rstudioapi_0.11   curl_4.3          yaml_2.2.1        withr_2.2.0       generics_0.0.2    desc_1.2.0        vctrs_0.3.0       hms_0.5.3         bit64_4.0.5       rprojroot_1.3-2   tidyselect_1.1.0  glue_1.4.1        R6_2.4.1          processx_3.4.4    fansi_0.4.1       callr_3.4.3      
[33] readr_1.3.1       purrr_0.3.4       magrittr_1.5      ps_1.3.4          backports_1.1.9   codetools_0.2-16  ellipsis_0.3.1    assertthat_0.2.1  crayon_1.3.4  

The Linux is as follows:
NAME="Red Hat Enterprise Linux Server"
VERSION="7.8 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.8"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

**Comment by hannesmuehleisen** [comment]
Finally it would help if you could tell us which compiler & version you are using.

**Comment by cchen-ops** [comment]
Not sure which compiler is the relevant one, so I'll list the modules I have loaded:
gcc/6.3.0
intel/19.0.5

**Comment by hannesmuehleisen** [comment]
I suspect that the Intel compiler is the culprit here. Will try.

**Comment by cchen-ops** [comment]
I've alternatively tried with Intel/18.0.2 with the same resulting error.

**Comment by hannesmuehleisen** [comment]
So can you try to use GCC for this?

**Comment by cchen-ops** [comment]
I'm not sure how, but I'm currently looking into it

**Comment by hannesmuehleisen** [comment]
I think if you set the `CC` and `CXX`  environment variables to `gcc` and `g++` respectively in your `.R/Makevars` file you should be good to go.
