### ISSUE TITLE
Support FROM clause in UPDATE statement

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#1035]
The FROM clause in the UPDATE statement currently gets silently ignored. It should either throw an error (as in SQLite) or be supported (as in Postgres).

```sql
CREATE TABLE terms(docid INTEGER, term INTEGER);
CREATE TABLE docs(id INTEGER, len INTEGER);
insert into docs values (1, 0), (2, 0);
insert into terms values (1, 1);
insert into terms values (2, 1);
insert into terms values (2, 2);
insert into terms values (2, 3);

UPDATE docs 
SET len = sq.len 
FROM ( 
    SELECT docid AS id, count(term) AS len 
    FROM terms 
    GROUP BY docid 
    ORDER BY docid 
) AS sq 
WHERE docs.id = sq.id;
select * from docs;
-- expected answer:
-- 1, 1
-- 2, 3
```

**Comment by jwills** [comment]
So funny-- I was literally just about to post this issue since I need it for incremental updates in dbt. Is it something I could implement? I'd love to get into the weeds of the query planner.

**Comment by Mytherin** [comment]
Go right ahead! @lnkuiper ran into it and we managed to solve this using a subquery instead, but it would be great if you could have a look.
