### ISSUE TITLE
Zonemap data skipping opportunities (in-clause, join, transitive)  

### ISSUE THREAD

**Issue by jtommaney1** [cwida/duckdb#1063]
**General data skipping cases not yet handled**
happening.  Example below:
1)  In-clause range/boundary zonemap check
      Use min/max values of in-clause for data skipping, potentially limited by large number of in-clause values.
      Transform "in (1,2,3)"  to zonemap check "between 1 and 3" 
      This has some utility and may be easier to implement, but 2) may offer additional data skipping opportunities.
      There is corresponding logic possible for not in clauses

2)  In-clause values zonemap check
      Use each value for data skipping, potentially limited by large number of in-clause values.
      Transform "in (1,2,3)"  to zonemap check "=1"  or "=2" or "=3"  
      There is corresponding logic possible for not in clauses
  Example with ascending dates to show "Singles Day" sale for the last 3 years.  
       o_orderdate in ('11-11-2017',  '11-11-2018',  '11-11-2019')

3)  Transitive filters
     For least 1 condition where data skipping appears to not occur with transitive.  Unsure whether this is just a exception.  
     With data skipping possible on column b, this does not enable data skipping:      b < d and d = 5;
     It does occur here: 
```
     select count(*) from t1 join t2 using (nationkey)
     where t2.n_name = 'Nation_1' and t2.nationkey =1;  /* data skipping occurs with help of transitive behavior */

```
4)  Check zonemap before joins 
      For TPC-DS and many other data models that abstract dates/times into dimension tables (Date_Dim) this allows for data skipping.  Without this optimization fact table data skipping not possible based on a predicate on a dimension.
    pseudo logic using some hard-coded values:  
    -materialize in-memory HT and determine # entries
    - if less than 20 entries then do:     2)  In-clause values zonemap check
    - elseif less than 1000 entries do:   1)  In-clause range/boundary zonemap check
    - introduce zonemap check into fact table scan.  

    The two hard-coded values can be determined via some profiling.  Both the cost and potential benefit scale with table size.

```
SQL examples

#    1) In-clause based on in-clause range/boundary zonemap check
create temporary table t as select range a, length(range) b, mod(range,10000) c, 5 d, 10000 e from range(100000000);
select count(*) from t where b in (1,2,3) ;                       /* no data skipping */
select count(*) from t where b in (1,2,3) and b <= 3;    /* data skipping occurs */

#   2) In-clause based on in-clause range/boundary zonemap check
create temporary table t as select range a, length(range) b, mod(range,10000) c, 5 d, 10000 e from range(100000000);
select count(*) from t where b in (1, 3) ;                         /* no data skipping */
select count(*) from t where b in (1, 3) and (b=1 or b=3);    /* data skipping should occur */

#   3) Transitive Filters
create temporary table t as select range a, length(range) b, mod(range,10000) c, 5 d, 10000 e from range(100000000);
select count(*) from t where b < 5 and d = 5;     /* data skipping occurs */
select count(*) from t where b < d and d = 5;     /* no data skipping */

#   4)  Check zonemap before joins
create temporary table t1 as select range a, length(range) nationkey from range(100000000);
create table t2 as select range  nationkey, concat('Nation_',range) n_name from range(25);

select count(*) from t1 join t2 using (nationkey) 
where t2.n_name = 'Nation_1' and t1.nationkey =1;    /* data skipping occurs */
select count(*) from t1 join t2 using (nationkey)
where t2.n_name = 'Nation_1' and t2.nationkey =1;  /* data skipping occurs with help of transitive behavior */

select count(*) from t1 join t2 using (nationkey) where t2.n_name = 'Nation_1';                               /* data skipping possible */
select count(*) from t1 join t2 using (nationkey) where t2.n_name in ( 'Nation_1', 'Nation_2');        /* data skipping possible */
select count(*) from t1 join t2 using (nationkey) where t2.nationkey =2 or n_name= 'Nation_2';   /* data skipping possible */


```

**Comment by Mytherin** [comment]
Thanks for the very detailed suggestions! These are very good suggestions indeed. Right now our zonemap skipping is rather limited (only triggered on comparison predicates). Nice ideas.

**Comment by hannesmuehleisen** [comment]
This is fixed as well
