### ISSUE TITLE
Support scalar functions with `CREATE FUNCTION`

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#1064]
We would like to support creation of scalar functions from within SQL as essentially a parameterized expression. The expressions will not be bound at function creation time; they will only be bound when used in a query. This allows us to add functions without needing to specify the return type, or the types of the input parameters.

Suggested syntax:
```sql
CREATE FUNCTION IFELSE(a,b,c) AS CASE WHEN a THEN b ELSE c END;
```

The function can then be used as follows:
```sql
SELECT IFELSE(i > 3, i, NULL) FROM integers;
```

The binder will take care of binding the expression and turning it into a case statement.

##### Grammar
First the `CREATE FUNCTION` syntax needs to be added to the parser. For this, you need to look at the yacc files. A simple example of a statement file is here: `third_party/libpg_query/grammar/statements/pragma.y`

I suggest adding a new statement type, `CreateFunctionStmt`, and adding a new yacc file `third_party/libpg_query/grammar/statements/create_function.y`.

New statements also need to be added here: `third_party/libpg_query/grammar/statements.list`, and you might need to add a new type in `third_party/libpg_query/include/nodes/parsenodes.hpp`.

Most of the building blocks are already there and can be re-used, for example, to parse an expression you can use `a_expr`. To parse the function name, you would use `ColId`.

Note that when changing any yacc files, you need to re-generate the cpp files by running `scripts/generate_grammar.py`.

###### Transformer 
After changing the parser, the create statement needs to be bubbled up through the transformer to create one of DuckDB's own SQLStatements (i.e. a CreateStatement, with an accompanying CreateInfo). The create statement then needs to be expanded to support creating scalar functions, and adding them to the catalog.

###### Binder
During binding of the function, you will need to figure out where the parameters are in the expression. You will also want to check (and throw an error) if an unknown parameter is used. For example, the following function should throw an error on creation:

```sql
CREATE FUNCTION add(a) AS a+b;
-- error: "b" not found!
```

###### Catalog
After successful binding, the function should be stored in the catalog. Initially it is fine to only allow temporary storage here, but in the future we will want to add persistent storage of these functions as well. In this step you also need to check if the function already exists or not.

###### Execution
When one of the scalar functions is actually used in a query, we will expand the parsed expression that is stored within the scalar function. After expanding, we replace the column references stored inside the function with the parameters as supplied to the function.

**Comment by mlkersten** [comment]
Isn't this called a macro? 
a.k.o. #define IFELSE(a,b,c) AS CASE WHEN a THEN b ELSE c END;
to be processed at the proper time in SQL parsing

CREATE FUNCTION has specific semantics in the SQL standard.

**Comment by Mytherin** [comment]
It is indeed similar to a C-style macro, but much more limited in scope. As long as the system guarantees the arguments are not evaluated multiple times it should behave the same as a function in SQL. For that reason I think `CREATE FUNCTION` is fine here, but we can add `CREATE MACRO` as an alias. If/when we add the SQL-standard style `CREATE FUNCTION` syntax it should not be a problem for that to exist next to this syntax.

**Comment by Mytherin** [comment]
This is implemented now.
