### ISSUE TITLE
C++ documentation for prepared statements

### ISSUE THREAD

**Issue by chilarai** [cwida/duckdb#1067]
I don't know how to write `prepared statements in C++` the same as in `C API`. The C++ API has a lot of **//TO DO** blocks in the example section. Please complete the example section in C++

I tried this but it throws **_expected body of lambda expression_**
```
duckdb::DuckDB db(nullptr);
duckdb::Connection con(db);

// Rest of the code block
.....
// Rest of the code block


string name = "Mark2";
int id = 1;

// error here: expected body of lambda expression
con.Prepare("UPDATE people SET name = ? WHERE id = ?", [name, id]);

```

**Comment by Mytherin** [comment]
The error thrown is not from us, but rather from the C++ compiler. The bracket operator `[]` indicates the start of a lambda function (e.g. `[](int a, int b) {return a + b}`). The error states that the system expects the rest of the lambda expression. [Read more about it here](https://www.geeksforgeeks.org/lambda-expression-in-c/).

I think what you are trying to do here is:

```cpp
con.Execute("UPDATE people SET name = ? WHERE id = ?", name, id);
```

The `Prepare` method returns a prepared statement object that can be executed, e.g.:
```cpp
auto prepared = con.Prepare("UPDATE people SET name = ? WHERE id = ?");
prepared->Execute(name, id);
```

See [`test/api/test_prepared_api.cpp`](https://github.com/cwida/duckdb/blob/f9f597620ce590d6e65efaa6faf66d5639714cb1/test/api/test_prepared_api.cpp) for some more examples.

**Comment by chilarai** [comment]
Thanks @Mytherin . 

My bad and I should not have mentioned my compiler-specific error here.

**Comment by chilarai** [comment]
Hi @Mytherin, I think there is an issue in the `prepared->Execute(name, id)` statement. It seems, the parameters are not accepted in the order they are mentioned.
I get the desired result only when I write `prepared->Execute(id, name)`. Can you check this issue?

**Comment by Mytherin** [comment]
That's a good point, thanks for the report! Indeed the unmarked parameters should be resolved in the order that they appear in the query. You can circumvent this issue by explicitly marking the prepared statement parameters with their id (e.g. `UPDATE people SET name = $1 WHERE id = $2`).
