### ISSUE TITLE
Qt DuckDB CRUD integration

### ISSUE THREAD

**Issue by chilarai** [cwida/duckdb#1069]
I have written a small project to showcase **CRUD operations with Qt5 and DuckDB**. If anybody wants to learn the integration, here is the project link https://github.com/chilarai/qt-duckdb. Kindly, add my project in the list of `Other Projects`

Feel free to update the code, if you want to extend or enhance the code

**Comment by hannesmuehleisen** [comment]
Thanks, added a reference.

**Comment by chilarai** [comment]
I have just written a small blog on the integration for anyone to read https://dev.to/chilarai/inmemory-columnar-database-duckdb-integration-with-qt-for-data-analytics-3nej
