### ISSUE TITLE
run connect    RuntimeError

### ISSUE THREAD

**Issue by guduxingzou** [cwida/duckdb#1072]
I use  python Spyder run con=duckdb.connect()  then I restart kernel,I dont  con.close().

next time ,when I run  con=duckdb.connect() ,I get  RuntimeError.   two times,I used the same duckdb file...

someone know how to handle this error???

**Comment by hannesmuehleisen** [comment]
Could you please post a reproducible full example that demonstrates the issue? Thanks

**Comment by hannesmuehleisen** [comment]
My first intuition here is that you are trying to open multiple connections to the same database file. You can try to address this by connecting in read-only mode or using the cursor() method on an existing connection to open additional connections to the same running DB

**Comment by guduxingzou** [comment]
yes,your intuition is right! I shutdown restart the spyder kernel,so I lost  the con.  I can't  run con.close(). I test read-only ,but failed.  when I restart spyder kernel,  the   con auto close like sqlite?????
Chinese：
我是用的python的Spyder编辑器，重启kernel的之间没有执行con.close()，导致了这个错误。感觉是数据库还被占用着，能不能像slqlite那样子，重启kernel时con会自动关闭。我测试了使用read-only，但是失败了。因为con已经丢失了，所以没法使用cursor()了
thanks！！

**Comment by hannesmuehleisen** [comment]
Did you possibly create the database with an older version of DuckDB?

**Comment by guduxingzou** [comment]
yes  you are right ! I upgrade to 0.2.2,  It is normal .  ths!!!
  
是的，我更新到0.2.2,程序可以正常运行了，谢谢！
