### ISSUE TITLE
R package version number confusion?

### ISSUE THREAD

**Issue by cboettig** [cwida/duckdb#1074]
CRAN version states it is 0.2.1-2, but the current GitHub DESCRIPTION seems to have the package at 0.2.1-1 https://github.com/cwida/duckdb/blob/master/tools/rpkg/DESCRIPTION#L3.  Is this intentional?

Trying to enforce the use of the most recent github version (since it resolves #973 for me) and it would be handy to have a version string that's newer than the CRAN one I think?

**Comment by hannesmuehleisen** [comment]
bumped the version on gh to 0.2.2

**Comment by hannesmuehleisen** [comment]
@cboettig 0.2.2 has been published on CRAN as well
