### ISSUE TITLE
read_parquet does not interpret datetime64[ns] correctly

### ISSUE THREAD

**Issue by wallflower** [cwida/duckdb#1079]
I was doing some experimentation creating a view of a parquet file.  I noticed that using the `read_parquet` functionality interprets the `datetime64[ns]` type differently than when reading the same data from a pandas dataframe.  

Here is a simple example:
```python
import duckdb
import pandas as pd
from datetime import datetime, timedelta
```

```python
file_name = "date_test.parquet"
con = duckdb.connect(':memory:')
```

## Create dataframe

```python
df = pd.DataFrame([
    {"ts": datetime.now() - timedelta(days=1), "reading":1.05},
    {"ts": datetime.now(), "reading":2.05},
])

df.to_parquet(file_name)

# simple cutoff date for queries below
cutoff_date = str(datetime.now() - timedelta(hours=2))
```

```python
print(df.dtypes)
```

    ts         datetime64[ns]
    reading           float64
    dtype: object

```python
print(df)
```

                              ts  reading
    0 2020-11-02 09:45:20.048459     1.05
    1 2020-11-03 09:45:20.048459     2.05

## Test queries against dataframe

```python
con.register('date_test_df',df)
```

    <duckdb.DuckDBPyConnection at 0x13f24d6ddf0>

```python
print("date_test_df:\n", con.execute("show date_test_df;").fetchall())
```

    date_test_df:
     [('ts', 'TIMESTAMP', 'YES', None, None, None), ('reading', 'DOUBLE', 'YES', None, None, None)]

```python
print("date_test_df:\n", con.execute("select * from date_test_df").fetchall())
```

    date_test_df:
     [(datetime.datetime(2020, 11, 2, 9, 45, 20, 48000), 1.05), (datetime.datetime(2020, 11, 3, 9, 45, 20, 48000), 2.05)]

```python
print("date_test_df:\n", con.execute(f"select * from date_test_df WHERE ts > (?)", (cutoff_date, )).fetchall())
```

    date_test_df:
     [(datetime.datetime(2020, 11, 3, 9, 45, 20, 48000), 2.05)]

## Test queries against parquet file

```python
con.execute(f"CREATE VIEW date_test_parquet AS SELECT * FROM parquet_scan('{file_name}');")
```

    <duckdb.DuckDBPyConnection at 0x13f24d6ddf0>

```python
print("date_test_parquet\n", con.execute("show date_test_parquet;").fetchall())
```

    date_test_parquet
     [('ts', 'BIGINT', 'YES', None, None, None), ('reading', 'DOUBLE', 'YES', None, None, None)]

```python
print("date_test_parquet:\n", con.execute("select * from date_test_parquet").fetchall())
```

    date_test_parquet:
     [(1604310320048459, 1.05), (1604396720048459, 2.05)]

```python
print("date_test_parquet:\n", con.execute(f"select * from date_test_parquet WHERE ts > (?)", (cutoff_date, )).fetchall())
```

    ---------------------------------------------------------------------------
    
    RuntimeError                              Traceback (most recent call last)
    
    <ipython-input-13-a35c38643a85> in <module>
    ----> 1 print("date_test_parquet:\n", con.execute(f"select * from date_test_parquet WHERE ts > (?)", (cutoff_date, )).fetchall())

    RuntimeError: Conversion: Could not convert string '2020-11-03 07:45:20.091474' to INT64

**Comment by hannesmuehleisen** [comment]
Thanks for this report, this indeed looks like a bug when interpreting logical types on parquet, which are a bit of a mess.

**Comment by wallflower** [comment]
Just to complete the circle, I know pandas can load in the parquet and it detects things properly.

## Test reloading parquet into pandas


```python
df2 = pd.read_parquet(file_name)
```


```python
print(df2.dtypes)
```

    ts         datetime64[ns]
    reading           float64
    dtype: object



```python
print(df2)
```

                              ts  reading
    0 2020-11-02 09:45:20.048459     1.05
    1 2020-11-03 09:45:20.048459     2.05

**Comment by Mytherin** [comment]
Which version of DuckDB are you using? I tried to reproduce your example but this seems to work fine for me on the latest master branch:

```sql
D select ts, reading, typeof(ts) from read_parquet('date_test_df');
┌─────────────────────────┬─────────┬────────────┐
│           ts            │ reading │ typeof(ts) │
├─────────────────────────┼─────────┼────────────┤
│ 2020-11-03 19:30:37.318 │ 1.05    │ TIMESTAMP  │
│ 2020-11-04 19:30:37.318 │ 2.05    │ TIMESTAMP  │
└─────────────────────────┴─────────┴────────────┘
```

It also seems to work for me in Python:
```python
>>> import duckdb
>>> con = duckdb.connect(':memory:')
>>> con.execute("select * from parquet_scan('date_test_df')").fetchdf()
                       ts  reading
0 2020-11-03 19:30:37.318     1.05
1 2020-11-04 19:30:37.318     2.05
>>> con.execute("select * from parquet_scan('date_test_df')").fetchall()
[(datetime.datetime(2020, 11, 3, 19, 30, 37, 318000), 1.05), (datetime.datetime(2020, 11, 4, 19, 30, 37, 318000), 2.05)]

```

I suspect this has already been addressed in #986. Could you verify whether or not updating to the latest version of DuckDB fixes it for you?

**Comment by wallflower** [comment]
I am sorry, I did not notice 0.2.2 was released a couple of days ago.  Upgrading from 0.2.1 to 0.2.2 fixed this issue.  I will close.

**Comment by Mytherin** [comment]
No problem! Thanks for the report anyway :) Let us know if you run into other issues.
