### ISSUE TITLE
Support all PostgreSQL CSV import options

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#108]
https://www.postgresql.org/docs/9.2/sql-copy.html

Except the following which don't make much sense for us:

STDIN, STDOUT, OIDS

For now we should enforce that ENCODING is UTF-8

Our current parser also does not support for multi-character delimiters and newlines in quotes. Add more tests with e.g. unicode delimiter, newlines in quotes, and broken CSV files.

**Comment by hannesmuehleisen** [comment]
Also see #284

**Comment by taniabogatsch** [comment]
Just to be sure. We only use `COPY FROM` and `TO` for **CSV files**, I do not need to add support for text and binary formats, thus I can omit the `FORMAT` option?

Also, the link points to the 9.2 documentation. Newer versions additionally support `FORCE_NULL`. Do we need that?

To sum up, we need

- [ ] multi-character delimiters
- [ ] `NULL 'null_string'`, default is unquoted empty string
- [ ] `ESCAPE 'escape_character'` single one-byte character, used to escape quote character, default is same as `QUOTE` value, see #284 
- [ ] `FORCE_QUOTE { ( column_name [,...] ) | * }`
- [ ] `FORCE_NOT_NULL ( column_name [,...] )`, only in `COPY FROM`
- [ ] test cases for each option, especially for newlines in quotes and broken CSV files

Also, we return an error (e.g., as we do if a string cannot be parsed into a statement) if the CSV file is broken? Or do we omit the line or something?

**Comment by Mytherin** [comment]
> Just to be sure. We only use COPY FROM and TO for CSV files, I do not need to add support for text and binary formats, thus I can omit the FORMAT option?

Indeed, it might be good to read the FORMAT option anyway and throw an error message if anything besides CSV is passed in, e.g. if someone explicitly calls "FORMAT BINARY" then state that it is not supported.

> Also, the link points to the 9.2 documentation. Newer versions additionally support FORCE_NULL. Do we need that?

FORCE_NULL seems like it would be the default behavior, hence we can parse it and not do anything if we do find it. Although care must be taken of course that we throw an error message if the config options contain both FORCE_NULL and FORCE_NOT_NULL.

> Also, we return an error (e.g., as we do if a string cannot be parsed into a statement) if the CSV file is broken? Or do we omit the line or something?

I would say return an error, but potentially we can add an option for a more lenient decoder that only skips the offending line (in MonetDB they call this BEST EFFORT, not sure if Postgres has anything similar). I would say it is not very critical right now though.

**Comment by redviking1** [comment]
> FORCE_NULL seems like it would be the default behavior, hence we can parse it and not do anything if we do find it. Although care must be taken of course that we throw an error message if the config options contain both FORCE_NULL and FORCE_NOT_NULL.

Unlike PostgreSQL [`COPY FROM`](https://www.postgresql.org/docs/current/sql-copy.html), why does DuckDB `COPY FROM` not allow both options `FORCE_NULL` and `FORCE_NOT_NULL`?
