### ISSUE TITLE
Documentation for installing "bleeding edge" R package

### ISSUE THREAD

**Issue by mskyttner** [cwida/duckdb#1086]
The web site offers a nice and easy-to-use page with installation instructions for the R package. One can select to install the R package in a stable version or from "bleeding edge" on this page https://duckdb.org/docs/installation/?environment=r

When attempting to install from "bleeding edge", the instruction provided leads to a warning for me:

```r
> install.packages("https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz")
Installing package into ‘/home/markus/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz’ is not available (for R version 3.6.3)
```

It seems to work better when I append `repos=NULL`:

```r
install.packages("https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)
```

It also works well to install when using `devtools::install_url()`:

```r
devtools::install_url("https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz")
```

Attempting to installing directly from the source from GitHub with `remotes::install_github()` gives an error which seems related to a missing date.hpp file:

```r
remotes::install_github("cwida/duckdb/tools/rpkg") 
# duckdbr.cpp:1:10: fatal error: duckdb/common/types/date.hpp: No such file or directory
#include "duckdb/common/types/date.hpp"
```

**Comment by hannesmuehleisen** [comment]
thanks, added the `repos = NULL` to the instructions. I rather not add a dependency on `devtools` for this. Tiny tiny tiny!
