### ISSUE TITLE
Inserting and deleting the same row in a single tx causes an internal exception

### ISSUE THREAD

**Issue by bluezio** [cwida/duckdb#1091]
As part of an internal test suite for new backends in [Eclipse Hawk](https://www.eclipse.org/hawk/), one of our tests inserts and removes a certain row within the same DucksDB transaction. DucksDB will crash with an unhandled exception in this case:

```
terminate called after throwing an instance of 'duckdb::InternalException'
  what():  INTERNAL Error: Could not find node in column segment tree!
```

**Comment by Mytherin** [comment]
Thanks for the report! That indeed seems like a bug (as a rule, any internal exception that gets thrown is a bug). Do you have a set of queries that you could provide so we could reproduce the issue?

**Comment by bluezio** [comment]
Sure - I had the test print out the underlying SQL queries, and I replaced the placeholders in the prepared queries with sample values. [Here](https://gist.github.com/bluezio/0977f2d3b2abb5247bbddcc92c04b7de) are the queries.

If you run it, you'll get something like this:

```
✗ duckdb --version
DuckDB 3222accba
➜  hawk-duckdb git:(main) ✗ duckdb < crash.sql
┌───────────────┬────────────┬───────────┬─────────────┬──────────────┬──────────────┬───────────────────────────┐
│ value_boolean │ value_long │ value_int │ value_float │ value_double │ value_string │ CAST[VARCHAR](value_blob) │
├───────────────┼────────────┼───────────┼─────────────┼──────────────┼──────────────┼───────────────────────────┤
│               │            │ 5         │             │              │              │                           │
└───────────────┴────────────┴───────────┴─────────────┴──────────────┴──────────────┴───────────────────────────┘
┌──────┐
│ name │
├──────┤
│ x    │
└──────┘
[1]    32158 segmentation fault (core dumped)  duckdb < crash.sql
```

**Comment by Mytherin** [comment]
Amazing, thanks! I will look into it.

**Comment by Mytherin** [comment]
This should be fixed now, could you verify that it is fixed on the latest master?

**Comment by bluezio** [comment]
Sure - do you do SNAPSHOT builds in any Maven repository?

**Comment by hannesmuehleisen** [comment]
There are builds from `master` here, but those are plain JARs: https://github.com/cwida/duckdb/releases/tag/master-builds

**Comment by bluezio** [comment]
I'll try swapping manually the Maven dep with the latest JAR later today.

**Comment by bluezio** [comment]
I can confirm that the issue has been fixed with the JAR from ba75d81. Thanks!

**Comment by Mytherin** [comment]
Thanks! Closing this issue then.

**Comment by koenvo** [comment]
I do get a ` INTERNAL Error: Could not find node in column segment tree!` in a simular situation (duckdb version 0.3.4) . As I can't share the code which causes this exception I'm trying to create an minimal example.

Is there maybe a way to export debug information?
