### ISSUE TITLE
RuntimeError: Cannot prepare multiple statements at once

### ISSUE THREAD

**Issue by liulover5** [cwida/duckdb#1100]
Can not IMPORT DATABASE from prev EXPORT DATABASE (export ok)

EXPORT DATABASE file:
--- target_directory
------ load.sql, people.csv, schema.sql

My code:

`import duckdb
conn = duckdb.connect()
cursor = duckdb.connect(database=':memory:', read_only=False).cursor()
print(cursor.execute("CREATE TABLE people(id INTEGER, name VARCHAR);").fetchall())
print(cursor.execute("INSERT INTO people VALUES (1, 'Mark'), (2, 'Hannes');").fetchall())

print(cursor.execute('SHOW TABLES').fetchall())

print(cursor.execute("SELECT * FROM read_csv_auto('mysql-server.csv');").fetchall())

print(cursor.execute("EXPORT DATABASE 'target_directory'").fetchall())
print(cursor.execute("IMPORT DATABASE 'target_directory'").fetchall())

conn.close()`

run output:
`Traceback (most recent call last):
  File "duckdb-python.py", line 41, in <module>
    print(cursor.execute("IMPORT DATABASE 'target_directory'").fetchall())
RuntimeError: Cannot prepare multiple statements at once!
`

When I only connect and import , It is also error ,  the same error, any advice ?

I just want EXPORT data in one program, and IMPORT in same or another program...

**Comment by Mytherin** [comment]
Thanks for the report! This seems to be an error with the Python client not being able to handle multiple statements in the same call to execute. I will have a look at fixing it. For now, as a work-around, you can load the `schema.sql` and `load.sql` files yourself from the database directory, e.g.:

```python
import duckdb
import os
# export database
con = duckdb.connect(":memory:")
con.execute("CREATE TABLE integers(i INTEGER)");
con.execute("CREATE TABLE integers2(j INTEGER)");
con.execute("EXPORT DATABASE 'target_dir'")

def execute_multiple_statements(con, fname):
    with open(fname, 'r') as f:
        statements = f.read()
    for statement in statements.split(';'):
        if len(statement.strip()) == 0:
            continue
        con.execute(statement)

# reload
con = duckdb.connect(":memory:")
execute_multiple_statements(con, os.path.join('target_dir', 'schema.sql'))
execute_multiple_statements(con, os.path.join('target_dir', 'load.sql'))
```

**Comment by Mytherin** [comment]
This should be fixed in the master now, can you install the latest master with `pip3 install duckdb --pre` and check if that fixes the issue for you?

**Comment by liulover5** [comment]
Thanks , sorry, I use python 2.7 building from python source tar.gz ...

**Comment by hannesmuehleisen** [comment]
You can find the latest python source here: https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_python_src.tar.gz

**Comment by liulover5** [comment]
Thanks all, now work well...
