### ISSUE TITLE
Text Functions

### ISSUE THREAD

**Issue by guduxingzou** [cwida/duckdb#1104]
wish  regexp_split  and position function
Chinese:
期待拆分字符串函数(支持正则表达式)和定位字符在字符串中的位置函数

**Comment by Mytherin** [comment]
`regexp_split` exists, althoug it is called `string_split_regex`:

```sql
D select string_split_regex('hellooo world', 'o+');
┌───────────────────────────────────────┐
│ string_split_regex(hellooo world, o+) │
├───────────────────────────────────────┤
│ [hell,  w, rld]                       │
└───────────────────────────────────────┘
```

What exactly do you mean with "position function"? Could you describe the expected behavior there?

**Comment by hannesmuehleisen** [comment]
No response in months, closing for now
