### ISSUE TITLE
Are indices persistent?

### ISSUE THREAD

**Issue by szarnyasg** [cwida/duckdb#1110]
I'm wondering whether indices are persistent in DuckDB. My experiments show that when exiting and restarting the database, the indices are gone – at least `.indexes` returns an empty result.

```console
$ duckdb my
D CREATE TABLE data(x int);
D CREATE INDEX idx ON data(x);
D .indexes
idx
D .quit

$ duckdb my
D .indexes
[no output]
```

**Comment by Mytherin** [comment]
Indexes are currently indeed not persisted. Normal indexes are discarded on reset, and unique and primary key indexes are rebuilt on startup. This is something we hope to address in our upcoming storage rework.

**Comment by bluezio** [comment]
+1 for this :-).

**Comment by szarnyasg** [comment]
Thanks for the quick reply. Indeed, this is mentioned in the roadmap: https://github.com/cwida/duckdb/issues/693#issuecomment-646847487

I've opened a PR in the docs clarifying this: https://github.com/cwida/duckdb-web/pull/9
