### ISSUE TITLE
Question: MVCC Concurrency

### ISSUE THREAD

**Issue by asad-awadia** [cwida/duckdb#1119]
Question more than an issue - I couldn't find any documentation around expected concurrent usage of duckDB?

SQLite is well known to be avoided in environments where many concurrent writes are expected because of the DB lock

But duckDB uses MVCC - so it should be fine to use any number of writers and readers without exceptions or errors?

What are the limitations around concurrent usage of duckDB?

**Comment by Alex-Monahan** [comment]
DuckDB can only perform 1 write at a time (single writer), but can accommodate many readers at the same time without throwing exceptions. It is designed to address that SQLite pain point you mentioned! Those writes can be quite fast too.

However, that is only within the same host process. Across multiple host processes, only multiple read-only connections are supported.

**Comment by asad-awadia** [comment]
so within the same process I can have multiple concurrent writes going to DuckDB and they just get serialised automatically by duckdb?

**Comment by Alex-Monahan** [comment]
Yes, that is my understanding! Essentially, threads should work fine, but not separate processes. (My experience is in the Python client, but I believe that is true in all clients)

**Comment by Mytherin** [comment]
What Alex is saying is correct, but is more about the logistics of how to use concurrency in DuckDB. We don't support multiple different writers from different processes connecting to the same database file. Instead, you need to create multiple different writers from the same process (i.e. writer threads). This is supported.

To expand on the concurrency model and concurrency limitations a bit:

DuckDB uses optimistic concurrency control alongside MVCC. What that means is that, as long as there are no *write conflicts*, multiple concurrent writes work just fine. For example, if you have two threads that update different tables, or different *subsets* of the same table, there are no problems. There are no global locks or anything of the sort - if two clients write to two separate tables, they will have zero conflicts. There are several local mutexes (there is one mutex for around every 20~80k rows, depending on width of the rows), but these are generally only held for a short time (while performing the physical update). There should never be any deadlocks.

Optimistic concurrency control bites you when there are conflicts between writers, that is to say, when two threads try to update the same row at the same time. When this happens, a concurrency conflict exception will be triggered.

To explain this a bit better, suppose you have two transactions. The first transaction executes this:

```sql
-- Transaction #1
BEGIN TRANSACTION;
UPDATE tbl SET val='new_value' WHERE id=3;
```

Now the transaction has edited the row with an id of 3. After the update statement is completed, no locks are held. However, the row with id 3 is marked as **edited** by `Transaction #1`. That means that **if any other transaction tries to edit that row**, a concurrency conflict will be triggered and the that transaction will be aborted. For example:

```sql
-- Transaction #2
BEGIN TRANSACTION;
-- No conflict, this works fine!
UPDATE tbl SET val='new_value' WHERE id=2;
-- TransactionContext Error: Conflict on update!
UPDATE table SET val='new_value' WHERE id=3;
```

This is sort of an "implicit lock", that gets released when `Transaction #1` either uses `rollback` or `commit` to terminate the active transaction. After `Transaction #1` finishes in that way, a new transaction can once again modify the row.

I would add that, despite the fact that we support concurrent writers, DuckDB is not aimed at transactional workloads. That is to say, it is aimed primarily at connections doing *bulk operations* (e.g. inserting a lot of data, updating a lot of data, deleting a lot of data). It is not optimized for scenarios where you have 20 threads updating individual rows. For that scenario it would be better to use Postgres (or another transactional system).

**Comment by Alex-Monahan** [comment]
That is super helpful detail! So, if I have multiple threads that could be writing to the same location in DuckDB, I should implement my own locking in my application code?

**Comment by Alex-Monahan** [comment]
Or, if I were doing append only operations to the same table, would multiple threads be fine without more locks in that case? It would just be updates and deletes that could get me into trouble?

**Comment by asad-awadia** [comment]
```
DuckDB is not aimed at transactional workloads. That is to say, it is aimed primarily at connections doing bulk operations (e.g. inserting a lot of data, updating a lot of data, deleting a lot of data). It is not optimized for scenarios where you have 20 threads updating individual rows.
```

So in the context of a webserver where each request triggers a single new row insert - that is fine?

**Comment by Mytherin** [comment]
> That is super helpful detail! So, if I have multiple threads that could be writing to the same location in DuckDB, I should implement my own locking in my application code?

If they are updating the same rows concurrently, then you could expect a percentage of those transactions to be aborted. You would either need to retry the transaction on abort, or implement locking (retrying is probably easier).

> Or, if I were doing append only operations to the same table, would multiple threads be fine without more locks in that case? It would just be updates and deletes that could get me into trouble?

Appends will never conflict. Only deletes or updates can conflict. Appends create new rows, and conflicts can only happen when two transactions touch the same row. 

> So in the context of a webserver where each request triggers a single new row insert - that is fine?

That should work fine and won't cause any conflicts, as long as you are only doing inserts. However, individual row inserts are not what DuckDB is optimized for. DuckDB is optimized for performing large-scale analytical queries (e.g. aggregations/joins over entire tables). As a webserver backend you are probably looking for an OLTP system, as you are doing individual inserts, updates and deletes. In that case, you will likely get better performance using e.g. Postgres.

**Comment by dforsber** [comment]
> DuckDB can only perform 1 write at a time (single writer), but can accommodate many readers at the same time without throwing exceptions. It is designed to address that SQLite pain point you mentioned! Those writes can be quite fast too.
> 
> However, that is only within the same host process. Across multiple host processes, only multiple read-only connections are supported.

@Mytherin I found out that if there are multiple processes accessing DuckDB db in `readonly` mode, no process can open the db in `readwrite` mode. And vice versa, if a process has the db open in `readwrite`, then no process can open the db file with `readonly`. Is this intended and correct?

I read this thread and understood that it should be possible to read simultaneously from multiple processes while a single writer process is writing. But simply doing `duckdb -readonly test.duckdb` and `duckdb test.duckdb` do not work at the same time, so I'm assuming it is not currently possible?

**Comment by Mytherin** [comment]
That is correct. You can either have multiple readers, **or** a single writer, for the same database file, not both.

Being primarily an in-memory system DuckDB caches a lot of data in RAM rather than continuously going back and forth to disk. This is what makes DuckDB fast. Having separate processes writing to the same thread will cause large complications here - if we have a reader and a writer, how would the reader know when to invalidate its in-memory caches from writes?

SQLite solves this by continuously going back to disk. It effectively caches nothing (not even the catalog), and re-reads what it needs on every single query. When a SQLite query is fired, it obtains a lock on the database, reads the catalog, executes the query, and then unlocks the database file again. In essence, it doesn't allow for concurrent writers at all, it just hides the fact from you that every query opens the database, executes a query, then closes the database again. 

You can do the same thing in DuckDB manually - you can open a database, fire a query, then close the database again. This will allow you to operate on the same file from multiple processes even with writers. However, it will be extremely slow. Unlike SQLite, DuckDB is not optimized for this scenario and performs a bunch of operations on load (e.g. setting up the catalog, setting up table pointers) since it assumes it will be able to re-use those for subsequent queries. Perhaps we would be able to optimize this somewhat (e.g. lazily reading the catalog, using mmap to allow the OS to share buffers between processes), but it is likely to still come with a performance penalty over having a single process accessing the database. 

Of course, multiple readers and writers from within the same process are perfectly well supported, so another solution would be to have a single process access the database. Then you end up going back to the client/server architecture, however. We don't have much support for that right now (aside from the REST server), but it would not be too difficult to build a client/server architecture on top of the DuckDB engine.

**Comment by dforsber** [comment]
> That is correct. You can either have multiple readers, **or** a single writer, for the same database file, not both.
> 
> Being primarily an in-memory system DuckDB caches a lot of data in RAM rather than continuously going back and forth to disk. This is what makes DuckDB fast. Having separate processes writing to the same thread will cause large complications here - if we have a reader and a writer, how would the reader know when to invalidate its in-memory caches from writes?
> 
> SQLite solves this by continuously going back to disk. It effectively caches nothing (not even the catalog), and re-reads what it needs on every single query. When a SQLite query is fired, it obtains a lock on the database, reads the catalog, executes the query, and then unlocks the database file again. In essence, it doesn't allow for concurrent writers at all, it just hides the fact from you that every query opens the database, executes a query, then closes the database again.
> 
> You can do the same thing in DuckDB manually - you can open a database, fire a query, then close the database again. This will allow you to operate on the same file from multiple processes even with writers. However, it will be extremely slow. Unlike SQLite, DuckDB is not optimized for this scenario and performs a bunch of operations on load (e.g. setting up the catalog, setting up table pointers) since it assumes it will be able to re-use those for subsequent queries. Perhaps we would be able to optimize this somewhat (e.g. lazily reading the catalog, using mmap to allow the OS to share buffers between processes), but it is likely to still come with a performance penalty over having a single process accessing the database.
> 
> Of course, multiple readers and writers from within the same process are perfectly well supported, so another solution would be to have a single process access the database. Then you end up going back to the client/server architecture, however. We don't have much support for that right now (aside from the REST server), but it would not be too difficult to build a client/server architecture on top of the DuckDB engine.

Thank you for the verification, appreciated. I guess the discussion would be going towards theorems, but for us, eventual consistency is good enough (we don't need read after write consistency). And to be more precise, just new data only. So, single writer/appender (i.e. new data) is ok with concurrent reader processes accessing the same db file, where a new reader would get the (almost) latest new data.

This would fit nicely analytics workloads, where new data comes along all the time (possibly ending at some point to make the data set complete). There you could run aggregation queries to follow up the process.

**Comment by Alex-Monahan** [comment]
If you are considering a client/server model for DuckDB (which isn't a use case I have at the moment!),  would you consider using Apache Arrow Flight? It is much faster than ODBC and supports C++, Python, and Java. Snowflake just adopted it not too long ago.

**Comment by dforsber** [comment]
I also noticed that it is not possible to retry getting lock from Node as the whole process gets terminated, at least with `node-duckdb`. This was from docker against mounted OSX filesystem.

```
  terminate called after throwing an instance of 'duckdb::IOException'
   what():  IO Error: Could not set lock on file "test.db": Resource temporarily unavailable
```

**Comment by Mytherin** [comment]
> If you are considering a client/server model for DuckDB (which isn't a use case I have at the moment!), would you consider using Apache Arrow Flight? It is much faster than ODBC and supports C++, Python, and Java. Snowflake just adopted it not too long ago.

If we end up adding a client/server mode rest assured that we will use an efficient binary format, [we have written a paper on this after all](https://mytherin.github.io/papers/2017-protocols.pdf) :) For now this is not in our immediate future plans, though.

> I also noticed that it is not possible to retry getting lock from Node as the whole process gets terminated, at least with `node-duckdb`. This was from docker against mounted OSX filesystem.
> 
> ```
>   terminate called after throwing an instance of 'duckdb::IOException'
>    what():  IO Error: Could not set lock on file "test.db": Resource temporarily unavailable
> ```
That seems like an oversight in the JS API, it should be possible to catch this error and retry. Could you open a separate issue for this?

**Comment by dforsber** [comment]
> > ```
> >   terminate called after throwing an instance of 'duckdb::IOException'
> >    what():  IO Error: Could not set lock on file "test.db": Resource temporarily unavailable
> > ```
> 
> That seems like an oversight in the JS API, it should be possible to catch this error and retry. Could you open a separate issue for this?

Will open if it is something related to DuckDB, but for now, I guess we check the code catching exceptions for our module :).

**Comment by dforsber** [comment]
https://github.com/cwida/duckdb/pull/1448

**Comment by jeffreyorihuela** [comment]
> > That is super helpful detail! So, if I have multiple threads that could be writing to the same location in DuckDB, I should implement my own locking in my application code?
> 
> If they are updating the same rows concurrently, then you could expect a percentage of those transactions to be aborted. You would either need to retry the transaction on abort, or implement locking (retrying is probably easier).
> 
> > Or, if I were doing append only operations to the same table, would multiple threads be fine without more locks in that case? It would just be updates and deletes that could get me into trouble?
> 
> Appends will never conflict. Only deletes or updates can conflict. Appends create new rows, and conflicts can only happen when two transactions touch the same row.
> 
> > So in the context of a webserver where each request triggers a single new row insert - that is fine?
> 
> That should work fine and won't cause any conflicts, as long as you are only doing inserts. However, individual row inserts are not what DuckDB is optimized for. DuckDB is optimized for performing large-scale analytical queries (e.g. aggregations/joins over entire tables). As a webserver backend you are probably looking for an OLTP system, as you are doing individual row inserts, updates and deletes. In that case, you will likely get better performance using e.g. Postgres.

It is possible to use the Appender to insert by chunks instead of individual row inserts?

**Comment by Mytherin** [comment]
> > > That is super helpful detail! So, if I have multiple threads that could be writing to the same location in DuckDB, I should implement my own locking in my application code?
> > 
> > 
> > If they are updating the same rows concurrently, then you could expect a percentage of those transactions to be aborted. You would either need to retry the transaction on abort, or implement locking (retrying is probably easier).
> > > Or, if I were doing append only operations to the same table, would multiple threads be fine without more locks in that case? It would just be updates and deletes that could get me into trouble?
> > 
> > 
> > Appends will never conflict. Only deletes or updates can conflict. Appends create new rows, and conflicts can only happen when two transactions touch the same row.
> > > So in the context of a webserver where each request triggers a single new row insert - that is fine?
> > 
> > 
> > That should work fine and won't cause any conflicts, as long as you are only doing inserts. However, individual row inserts are not what DuckDB is optimized for. DuckDB is optimized for performing large-scale analytical queries (e.g. aggregations/joins over entire tables). As a webserver backend you are probably looking for an OLTP system, as you are doing individual row inserts, updates and deletes. In that case, you will likely get better performance using e.g. Postgres.
> 
> It is possible to use the Appender to insert by chunks instead of individual row inserts?

Yes, any method of bulk insertion (e.g. Appender, or reading from a CSV/Parquet file) should work very well.
