### ISSUE TITLE
Add statistic functions

### ISSUE THREAD

**Issue by willium** [cwida/duckdb#1125]
For our use cases, it'd be great to have additional statistic functions [like those provided in monetdb](https://www.monetdb.org/Documentation/SQLReference/DataManipulation/StatisticFunctions). I understand with UDFs it should be possible to approximate most of these, but it would be nice to have a pathway to first-class support or second-class by way of an extension ([as with SQLite](https://github.com/codingforfun/sqlite3-extension-functions)). Has there been any documented discussion around this? I imagine you've considered it given monetdb.

**Comment by Mytherin** [comment]
We have indeed discussed this, but I don't believe there has been any documented discussion on that. Indeed all of these are on the agenda, in fact, several have already been implemented. I will hijack this issue to use as the aggregate compatibility with other systems issue. 

[ ] median
[ ] quantile
[ ] corr
[x] stddev_samp
[x] stddev_pop
[x] covar_pop
[x] covar_samp
[x] var_samp
[x] var_pop

It would be good to look at the [Clickhouse aggregate set](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/reference/quantile/). They support many more aggregates than most systems, and of course [Postgres' set of supported aggregates](https://www.postgresql.org/docs/9.5/functions-aggregate.html).

**Comment by willium** [comment]
@Mytherin great to hear! Indeed, parity with Clickhouse's aggregation set would be tremendous.
 
Do you have an idea of what blockers there are to implementing (and benchmarking) these?

**Comment by Mytherin** [comment]
For simple (one-pass) algorithms there is not really any blockers, besides actually implementing the algorithm. Exact median and quantile are more difficult; they would require materializing the lists, which is tricky when it comes to using them as grouped aggregates. There is already infrastructure to support materialization in the HT (for e.g. `array_agg`), so adding the algorithms there would not require any large infrastructural changes, but some more consideration would need to be given there to how we handle these cases.

**Comment by willium** [comment]
> Exact median and quantile are more difficult; they would require materializing the lists, which is tricky when it comes to using them as grouped aggregates

Do we have a sense of what kind of performance is possible for such aggregations with DuckDB? 

I've run some very basic tests over the weekend, and it seems quite a bit slower than I expected—but I haven't played much with indexes yet, so there is still ample possible upside. 

Additionally, as I believe DuckDB doesn't allow for sub-queries in OFFSET or LIMIT, SQLite approaches [seem less amenable](https://stackoverflow.com/a/15766121).

**Comment by Mytherin** [comment]
> Do we have a sense of what kind of performance is possible for such aggregations with DuckDB?

There are no structural roadblocks for these aggregations to have competitive performance with other columnar systems.

> I've run some very basic tests over the weekend, and it seems quite a bit slower than I expected—but I haven't played much with indexes yet, so there is still ample possible upside.

What kind of queries have you run? If they involved `ORDER BY` statements on large amounts of data, then slow performance is expected right now.  Our current order by operator is very slow and mainly aimed at ordering small amounts of data (in the order of 100s of rows). It is likely around 10~100X slower than it should be if properly optimized. This is just something we haven't gotten to yet. 

> Additionally, as I believe DuckDB doesn't allow for sub-queries in OFFSET or LIMIT, SQLite approaches seem less amenable.

That approach is fine if as a user you want to compute the median or quantile manually in a system that doesn't support it, but it is not efficient. Sorting the entire array of numbers is not required for a quantile or median computation, rather the system should use an algorithm such as quickselect to compute the median/quantiles. This will give much better performance, and is also what other systems use for exact median/quantile computation.

There is also the possibility of adding approximate median/quantile functions, which is sufficient for many use cases and is even faster than exact approaches. I think Clickhouse has both of these, and I think we should have both as well.

**Comment by hannesmuehleisen** [comment]
I'm implementing quantiles right now

**Comment by willium** [comment]
That’s so exciting! Thank you Hannes

**Comment by Mytherin** [comment]
The exact median and quantile are now implemented. I have also expanded the list of aggregates we want to support here.

**Comment by willium** [comment]
@Mytherin what's the best way to test these as you develop them? I'm not sure if you plan on cutting any intermediate releases.

**Comment by willium** [comment]
@Mytherin though it's on the fringes of practical utility, an aggregate that implements a binning algorithm (for histograms) would be incredible!

**Comment by hannesmuehleisen** [comment]
#1346 implements approximate quantiles (and medians)

**Comment by hannesmuehleisen** [comment]
@willium See #1372 for @pdets PR that adds many of those functions

**Comment by pdet** [comment]
@hannesmuehleisen These were already merged:
 arbitrary (alias for first)
 min_by/max_by (alias for argMin, argMax)
 skewness
 entropy
 kurtosis
 regr_intercept/regr_slope

**Comment by hannesmuehleisen** [comment]
I had a look at the combined aggregates of Postgres, Presto, Clickhouse and MonetDB. What remains is fairly obscure. I think this can be closed. Feel free to open additional issues for missing aggregates.
