### ISSUE TITLE
Support non-constant expressions in LIMIT and OFFSET clause

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#1142]
Currently we only support limit values that can be evaluated to a single constant during planning. In the future we would like to add support for using expressions or subqueries here, e.g. the following should all work:

```sql
CREATE TABLE integers(i INTEGER);
INSERT INTO integers VALUES (1), (2), (3), (4), (5);

-- sequence in limit
SELECT * FROM integers LIMIT nextval('seq');
-- non-foldable expression in limit
SELECT * FROM integers LIMIT RANDOM();
-- subquery in limit
SELECT * FROM integers LIMIT (SELECT MIN(i) FROM integers);
```

**Comment by willium** [comment]
this would be outstanding! I ran across this while trying to approximate that median aggregation

**Comment by pdet** [comment]
@hannesmuehleisen I think this is already merged.

**Comment by hannesmuehleisen** [comment]
@pdet No?

**Comment by pdet** [comment]
@hannesmuehleisen this pr adds it for both offset and limit
https://github.com/cwida/duckdb/pull/1355
