### ISSUE TITLE
Improve NodeJS support for Webpack and Electron

### ISSUE THREAD

**Issue by jpkli** [cwida/duckdb#1150]
Thank you very much for adding the [NodeJS support](https://github.com/cwida/duckdb/pull/1112)! 

I am very excited about this! I want to use DuckDB inside a Webpack or Electron app, but it has a problem finding the path for package.json: it shows the following error message when importing DuckDB:

```
webpack:///./node_modules/duckdb/node_modules/node-pre-gyp/lib/pre-binding.js?:18
        throw new Error("package.json does not exist at " + package_json_path);
        ^

Error: package.json does not exist at /package.json
    at Object.exports.find (webpack:///./node_modules/duckdb/node_modules/node-pre-gyp/lib/pre-binding.js?:18:15)
    at Object.eval (webpack:///./node_modules/duckdb/lib/duckdb-binding.js?:3:27)
    at eval (webpack:///./node_modules/duckdb/lib/duckdb-binding.js?:7:30)
    ...
    at eval (webpack:///./node_modules/duckdb/lib/duckdb.js?:2:14)
```

Environment: 
DuckDB version: 0.2.3-999
OS: MacOS 10.15.7
NodeJS: 14.15.0
Webpack: 4.x

**Comment by hannesmuehleisen** [comment]
Can you please post the sequences of commands that you issued that lead to this issue? Never used Electron myself, don't know what "importing DuckDB" means.

**Comment by jpkli** [comment]
Actually, it's working fine if using the [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) plugins when building a web app or Electron app. 

I am going to close this issue. I am still experimenting with the DuckDB NodeAPI, and I will love to contribute some documentation for using it with Webpack and Electron. Thank you very much for this great work!
