### ISSUE TITLE
Inner Join on NULL values results in empty table

### ISSUE THREAD

**Issue by maschere** [cwida/duckdb#1156]
As per title, when I try to join two tables on columns that contain corresponding NULL values I do not get any matches / an empty table as a result. Is this behaviour intended?

MWE (using release 0.2.2):
`
drop table if exists t0;
drop table if exists t1;

CREATE TABLE t0(c0 INT,c1 INT default 1);
CREATE TABLE t1(c0 INT, c2 INT default 2);
INSERT INTO t0(c0) VALUES (NULL);
INSERT INTO t1(c0) VALUES (NULL);

SELECT * FROM t1 INNER JOIN t0 ON t0.c0=t1.c0; -- returns empty table
`

I would expect this example to return a single row containing "NULL,2,NULL,1"

**Comment by Mytherin** [comment]
That behavior is indeed intended. By definition any comparison with `NULL` returns `NULL`. Think about `NULL` as meaning "I don't know what this value is". So for example, `NULL=1` asks, is NULL equal to 1? The answer is, "I don't know", so the answer is `NULL` again. The same with `NULL=NULL`. We don't know what either value is, so we also don't know if they are equal, hence the answer is `NULL`. See [the wikipedia entry on three-valued logic for more information](https://en.wikipedia.org/wiki/Three-valued_logic).

Postgres implements `IS (NOT) DISTINCT FROM` to essentially implement "equality, but NULL is also equal to NULL". We don't implement this yet, but we likely will implement this in the future. Is this question driven by a need for this functionality, or out of curiosity?

**Comment by maschere** [comment]
In one use-case I have two columns A and B where either A has to have a value and then B has to be NULL or the other way round. When I join on these two columns I need the "NULL equals NULL" behaviour. However, I can certainly work around this behaviour (e.g. using default values).

**Comment by Mytherin** [comment]
Closing this issue as the behavior reported here is correct, will open another one with support for `IS (NOT) DISTINCT FROM`.
