### ISSUE TITLE
strptime bug handling consecutive digits

### ISSUE THREAD

**Issue by exaatto** [cwida/duckdb#1158]
`strptime` function in duckdb sql seems having problem handling formats with consecutive digits, such as `"%Y%m"` -> `"202011"`, complaining about:

- `Error: Expected a number` or
- `Error: Month out of range, expected a value between 1 and 12`. 

After digging into the code I believe it's because those consecutive digits are parsed into one number without checking time part field width.

This behavior differs from standard POSIX `strptime` and other common `strptime` implementations (python, etc.), and is inconsistent with duckdb `strftime`, which allows formats with consecutive digits. Thus I guess it should be a bug.

https://github.com/cwida/duckdb/blob/e207e09ff074be8fe57badfada83a5f208e377e7/src/function/scalar/date/strftime.cpp#L747-L756

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm this is bugged. I will have a look at fixing it.

**Comment by Mytherin** [comment]
Should be fixed now

**Comment by exaatto** [comment]
A HUGE thanks for such quick fix! @Mytherin 

We've applied current HEAD and all work fine.
