### ISSUE TITLE
Support loading extensions from python

### ISSUE THREAD

**Issue by Mause** [cwida/duckdb#1164]
It would be great to see this supported, especially for the collations

**Comment by hannesmuehleisen** [comment]
We could also ship the collations with the Python package? Would that be ok for you?

**Comment by Mause** [comment]
I mean, assuming I can load them? It is difficult to let us load the extensions from python?

**Comment by hannesmuehleisen** [comment]
I would just bake icu in by default like the parquet reader?

**Comment by Mause** [comment]
By all means then

**Comment by Mause** [comment]
Looks like this was done in https://github.com/cwida/duckdb/pull/1186, many thanks 😊
