### ISSUE TITLE
duckdb CLI help text identifies itself as sqlite

### ISSUE THREAD

**Issue by rfmeraz** [cwida/duckdb#1170]
First, thank you for this wonderful tool.

A minor thing, but maybe appropriate to change?

$ ~/apps/bin/duckdb --help
Usage: ~/apps/bin/duckdb [OPTIONS] FILENAME [SQL]
FILENAME is the name of an **SQLite** database. A new database is created
if the file does not previously exist.
OPTIONS include:
<snip>
-version             show **SQLite** version

**Comment by hannesmuehleisen** [comment]
Ah this is because we "borrowed" the CLI pretty much as-is from SQLite. But you're right that could be fixed.
