### ISSUE TITLE
[Question] Parallel writes to different tables

### ISSUE THREAD

**Issue by qiuwei** [cwida/duckdb#1171]
According to #867 , concurrent write from different processes has quite some restrictions and is not possible at the moment. However, Is it possible to have parallel writes to different tables?

**Comment by Mytherin** [comment]
Concurrent connections and parallel writes are all possible, just not from separate processes. Separate processes can only open the same database file in read-only mode. This is very unlikely to be changed in the future, as multiple processes writing to the same file complicates in-memory caching significantly, which is critical for highly performing OLAP systems.

Multiple connections to the same database are able to write concurrently to that database file without any problems, whether that is to the same table or to different tables.

**Comment by qiuwei** [comment]
Thanks for the explanation.
