### ISSUE TITLE
Install Python extension in development mode using virtualenv

### ISSUE THREAD

**Issue by amotl** [cwida/duckdb#1175]
Dear Mark,

by following up on your request to test the new Pandas `category` type (https://github.com/cwida/duckdb/issues/569#issuecomment-736310745), I believe it might be a good idea to share an alternative method for installing the DuckDB Python extension locally / in development mode in contrast to the current documentation outlined at [1].

By using [`virtualenv`](https://virtualenv.pypa.io/), the inline installation into the source tree is really easy without having to manipulate `DUCKDB_PREFIX` or `PYTHONPATH` at all:
```bash
# Acquire sources.
git clone https://github.com/cwida/duckdb
cd duckdb

# Create and activate Python virtualenv.
virtualenv .venv
source .venv/bin/activate

# Compile and install DuckDB for Python.
pip install -e tools/pythonpkg --verbose
```

Maybe this will help you or others in this manner. We can close this issue right away and just might want to add a label called "information" beforehand.

Keep up the spirit and with kind regards,
Andreas.

[1] https://github.com/cwida/duckdb/blob/v0.2.2/tools/pythonpkg/README.md#installing-locally

**Comment by Mytherin** [comment]
Thanks! The documentation on that link indeed seems a bit outdated. I have integrated the build of the Python (and R) packages into the cmake, so that you can simply do `BUILD_PYTHON=1 make` to compile and install the Python package. This is what I personally use to develop the Python package. However, that does overwrite any existing installations.

I assume the virtualenv does not do a global package install and instead somewhat sandboxes this, correct? In that case I think both approaches are useful depending on the desired behavior and we should document both.

**Comment by amotl** [comment]
> You can simply do `BUILD_PYTHON=1 make` to compile and install the Python package.

Ah, thanks! And it does a `pip install` under the hood, thus installing it into the system-wide Python environment so it will need superuser permissions? Or where does it actually "install into"?

> I assume the virtualenv does not do a global package install and instead somewhat sandboxes this, correct?

Exactly. This is very convenient and will not require superuser permissions.

---

FWIW, I just tried to run `BUILD_PYTHON=1 make` on macOS and wanted to give you feedback on this. TLDR; Compilation works, linking fails.
```
building 'duckdb' extension
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/lib/python3.9/site-packages/numpy/core/include -I/Users/amo/dev/foss/duckdb/tools/pythonpkg/.eggs/pybind11-2.6.1-py3.9.egg/pybind11/include -I/Users/amo/dev/foss/duckdb/tools/pythonpkg/.eggs/pybind11-2.6.1-py3.9.egg/pybind11/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python@3.9/3.9.0_2/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c duckdb_python.cpp -o build/temp.macosx-10.13-x86_64-3.9/duckdb_python.o -std=c++11 -O3 -DNDEBUG -O3 -DNDEBUG -stdlib=libc++ -mmacosx-version-min=10.7 -I/Users/amo/dev/foss/duckdb/scripts/../src/include -I/Users/amo/dev/foss/duckdb/scripts/../extension/parquet/include
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.9/duckdb_python.o -L/Users/amo/dev/foss/duckdb/build/release/src -L/Users/amo/dev/foss/duckdb/build/release/extension/parquet -L/Users/amo/dev/foss/duckdb/build/release/extension/icu -L/Users/amo/dev/foss/duckdb/build/release/third_party/fmt -L/Users/amo/dev/foss/duckdb/build/release/third_party/libpg_query -L/Users/amo/dev/foss/duckdb/build/release/third_party/re2 -L/Users/amo/dev/foss/duckdb/build/release/third_party/miniz -L/Users/amo/dev/foss/duckdb/build/release/third_party/utf8proc -L/usr/local/lib -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/sqlite/lib -lduckdb_static -lparquet_extension -licu_extension -lfmt -lpg_query -lduckdb_re2 -lminiz -lutf8proc -lpthread -o build/lib.macosx-10.13-x86_64-3.9/duckdb.cpython-39-darwin.so -std=c++11 -O3 -DNDEBUG -O3 -DNDEBUG -stdlib=libc++ -mmacosx-version-min=10.7 -I/Users/amo/dev/foss/duckdb/scripts/../src/include -I/Users/amo/dev/foss/duckdb/scripts/../extension/parquet/include
ld: library not found for -lduckdb_static
clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/usr/bin/clang++' failed with exit code 1
gmake[3]: *** [src/CMakeFiles/duckdb_python.dir/build.make:79: src/CMakeFiles/duckdb_python] Error 1
gmake[3]: Leaving directory '/Users/amo/dev/foss/duckdb/build/release'
gmake[2]: *** [CMakeFiles/Makefile2:2701: src/CMakeFiles/duckdb_python.dir/all] Error 2
gmake[2]: Leaving directory '/Users/amo/dev/foss/duckdb/build/release'
gmake[1]: *** [Makefile:149: all] Error 2
gmake[1]: Leaving directory '/Users/amo/dev/foss/duckdb/build/release'
make: *** [Makefile:106: release] Error 2
```

This might happen because Homebrew decided to use Python 3.9 as a default already. So, I tried again by running this from within a virtualenv using Python 3.8.
```
virtualenv .venv --python=python3.8
source .venv/bin/activate
BUILD_PYTHON=1 make
```

That worked like a charm.
```
$ python
Python 3.8.6 (default, Oct 27 2020, 08:58:03)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import duckdb
>>> duckdb.__file__
'/Users/amo/dev/foss/duckdb/.venv/lib/python3.8/site-packages/duckdb-0.2.3.dev509+gd01396e13-py3.8-macosx-10.13-x86_64.egg/duckdb.cpython-38-darwin.so'
```

So, we can see a virtualenv-based installation can also help on matters like these.

---

For all people reading this yet unaware of [pyenv](https://github.com/pyenv/pyenv): This is yet **another** great tool from the Python ecosystem which will make you install any Python version on your machine without efforts. So, a short recap:

- `virtualenv`: Create isolated Python **package** environments, making you independent from the system-wide `site-packages`.
- `pyenv`: Create isolated Python **distribution** environments, making you independent from the system-wide Python.

**Comment by Mytherin** [comment]
Thanks for the notes and all the effort! I have updated  [the docs](https://github.com/cwida/duckdb/blob/master/tools/pythonpkg/README.md) to include your suggestions. Let me know if you think anything else is missing; if not I think this issue can be closed.

**Comment by amotl** [comment]
Thanks for including this into the documentation so quickly.
