### ISSUE TITLE
Would DuckDB benefit from AXV2 SIMD instructions?

### ISSUE THREAD

**Issue by dforsber** [cwida/duckdb#1177]
Just looking the [AWS Lambda runtime](https://aws.amazon.com/blogs/compute/creating-faster-aws-lambda-functions-with-avx2/) environment now supports the AXV2 SIMD instructions, and seeing that e.g. gcc can be used to utilise SIMD instructions. Is this something that DuckDB can benefit from as well?

**Comment by hannesmuehleisen** [comment]
Sure, I expect that if you compile DuckDB with AVX support the compiler will use those instructions for vector operations and those instructions could also speed up things (a bit).

**Comment by Alex-Monahan** [comment]
I just saw this and got to thinking.... Our servers running DuckDB have AVX512. Do you think the performance delta would be significant if compiled differently? What are the steps to get AVX512 operational in a Python context?

**Comment by hannesmuehleisen** [comment]
You will have to change the compilation flags in `setup.py`
