### ISSUE TITLE
Registering apache arrow table

### ISSUE THREAD

**Issue by joetl** [cwida/duckdb#1185]
Is there anyway to register an apache arrow table in python similar to registering pandas dataframe

duckdb.register('test',test_df)

Reason for this question is I have multiple apache arrow tables that I need to join

**Comment by hannesmuehleisen** [comment]
Try `duckdb.from_arrow_table`

**Comment by joetl** [comment]
Using duckdb.from_arrow_table i can query standalone table but I am not sure how I can join 3 arrow tables using sql.

**Comment by joetl** [comment]
If I have 3 pandas dataframes I can register 3 dataframes and can write execute sql to join all 3 tables and thinking of how to do the same with arrow table

**Comment by akdor1154** [comment]
@hannesmuehleisen as OP says, this lets you query the arrow table standalone, but does not let you use it in `con.execute()` e.g. to join with other tables.
