### ISSUE TITLE
Parquet bug duckdb v 0.2.3

### ISSUE THREAD

**Issue by rostislavdeepcrawl** [cwida/duckdb#1198]
We've encountered a bug with the new version of duckdb (0.2.3) to do with the parquet reader. The following query...

```
SELECT count(url) FROM parquet_scan('<path to file>') WHERE (http_status_code = 200 AND meta_redirect = FALSE AND primary_page = TRUE AND indexable = TRUE AND canonicalized_page = FALSE AND (paginated_page = FALSE OR (paginated_page = TRUE AND page_1 = TRUE))) AND ((css != TRUE AND js != TRUE AND is_image != TRUE AND internal = TRUE) AND (header_content_type = 'text/html' OR header_content_type = '')) ORDER BY count(url) DESC"
```
...gives `Out of buffer` error.

The above test is run against a 22GB parquet file. Some other info:
- Other queries execute without a problem on it. 
- The previous version of duckdb (0.2.2) runs with fine with the query

The error comes from `duckdb/extension/parquet/include/resizable_buffer.hpp`, specifically
```	
	void available(uint64_t req_len) {
		if (req_len > len) {
			throw std::runtime_error("Out of buffer");
		}
	}
```
I can provide the 22GB test file in private.

**Comment by hannesmuehleisen** [comment]
Please do share the file with me hannes@cwi.nl

**Comment by rostislavdeepcrawl** [comment]
> Please do share the file with me [hannes@cwi.nl](mailto:hannes@cwi.nl)

Sent. Thanks a lot 👍

**Comment by hannesmuehleisen** [comment]
Please, for the next issue, do make an effort to create a minimal reproducible example that does not require a 20 GB private dataset. CC @dfosber

**Comment by hannesmuehleisen** [comment]
Indeed that was a recently introduced bug. Thanks for reporting!
