### ISSUE TITLE
strings written as arrow binary in Parquet

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#1199]
loving the new updates to the package, however using the bleeding edge package release, i've run into the case where strings are mangled into "Arrow Binary" when i write a parquet file. therefore, when read back in R, the column type is "arrow binary" and DuckDB can't read it either because it is a "BLOB".  therefore the Parquet file becomes unusable.

i'm debugging why this happens into a reproducible file, but preliminarily i think it's because the file i'm reading and rewriting is large. in the reverse direction, i have seen the R arrow package complain when I try to write a large file with a string column, complaining about how it doesn't support a "large binary". this problem goes away when i break up the file - i imagine some sort of column size issue when the column is too large?

EDIT: Examining this further, indeed breaking the query into smaller pieces DuckDB does not perform the string mangling described above. I can try to provide a test replication file if helpful in a few days.  I imagine the easiest fix is just allowing for chunked output?

**Comment by Mytherin** [comment]
Thanks for the report!

> loving the new updates to the package, however using the bleeding edge package release, i've run into the case where strings are mangled into "Arrow Binary" when i write a parquet file. therefore, when read back in R, the column type is "arrow binary" and DuckDB can't read it either because it is a "BLOB". therefore the Parquet file becomes unusable.

Interesting, could you share one of those Parquet files with us together with some code snippet on how you generated it? It is possible that we can adopt the Parquet reader to correctly read that format.

> i'm debugging why this happens into a reproducible file, but preliminarily i think it's because the file i'm reading and rewriting is large. in the reverse direction, i have seen the R arrow package complain when I try to write a large file with a string column, complaining about how it doesn't support a "large binary". this problem goes away when i break up the file - i imagine some sort of column size issue when the column is too large?

At least from the perspective of DuckDB there is no size limit on columns, and by default things should be chunked up (DuckDB uses block-based execution, which means we never process more than 1024 tuples at a time). I'm not sure how this works on the DuckDB-arrow boundary though. Could you provide any code snippets that result in the behavior you describe?

**Comment by alanpaulkwan** [comment]
Thanks, I'll try to find a time tmrw or the day after to replicate this. The issue is I can't share confidential data but I think I have a sense of how one might - what's your email?

**Comment by Mytherin** [comment]
You can send anything you don't want to publish here to my email at m.raasveldt@cwi.nl. Thanks!

**Comment by alanpaulkwan** [comment]
@Mytherin i saw your other thread, and i think decode(variable_name) fixed it. would it still be helpful to replicate the error?

**Comment by Mytherin** [comment]
Ah great, I didn't realize that these issues were the same. In that case I won't need the file. Thanks for the report!

>  i noticed you pushed a PR to the python API, which i imagine flows through to the R API too. would it still be helpful to replicate the error?

The PR only added blob support to the Python API, but I will have a look at adding blob support to the R API as well.

**Comment by alanpaulkwan** [comment]
Is there any workaround to this? Like if I cast everything as decode should it work?

**Comment by Mytherin** [comment]
Decode converts from a blob to varchar, so then it should work (as long as the column is actually UTF8 - if it is not decode will throw an error). The latest R client should now also support blobs, but maybe not the one on CRAN.

**Comment by alanpaulkwan** [comment]
I'll close this for now, re-open if I encounter any more issues. Seems OK.
