### ISSUE TITLE
Abort on gziped csv files when doing import

### ISSUE THREAD

**Issue by skinkie** [cwida/duckdb#1206]
```
D .import '/mnt/volatile/export/raw/HTM_KV6_20201208.csv.gz' 'kv6_import'
terminate called after throwing an instance of 'duckdb::Exception'
  what():  String value is not valid UTF8
Aborted (core dumped)
```

This works;
```
INSERT INTO kv6_import SELECT * FROM read_csv_auto('/mnt/volatile/export/raw/HTM_KV6_20201208.csv.gz');
```

**Comment by Mytherin** [comment]
Thanks for the report! `.import` uses the SQLite shell's built-in CSV reader rather than DuckDB's csv reader, which is rather barebones and seems to not support `.csv.gz`. It actually correctly throws an exception here but this should be caught and reported rather than crashing the client.
