### ISSUE TITLE
best practices for exploratory analysis and adding columns

### ISSUE THREAD

**Issue by Zelazny7** [cwida/duckdb#1208]
What is the best practice process for what I consider to be a very common need when working with a large, out-of-core dataset: adding new columns as combinations of existing columns.

I am currently using a process where I alter the table and add the new column. I then update the table using SET = (EXPR). This seemed to be working at first but I notice that the database file size consistently grows larger even when I delete and recreate one of the columns.

As a follow-up, is there a way to add a column to a database table from a pandas Series? This also seems like it would be a common need for exploratory data analysis. I am admittedly new to working with databases. Any guidance you can offer is greatly appreciated.

This is what I am currently doing. I have some query logic saved in a YAML file with other metadata:

```python
import yaml
yml = yaml.load(open("mkiv.yaml", "r"), Loader=yaml.Loader)

columns = [Column(**col) for col in yml['features']]

con.begin()
for column in columns:
    con.execute(f"ALTER TABLE test DROP COLUMN IF EXISTS {column.name}")
    con.execute(f"ALTER TABLE test ADD COLUMN {column.name} {column.type}")
    con.execute(f"UPDATE test SET {column.name} = ({column.query})")
con.commit()
```

**Comment by Mytherin** [comment]
For now I think that this is the way to go about doing it. In the future we will add support for directly generating a column from an expression (e.g. `ALTER TABLE test ADD COLUMN j AS i+1`), but for now you can only use constant expressions when generating columns. 

> I am currently using a process where I alter the table and add the new column. I then update the table using SET = (EXPR). This seemed to be working at first but I notice that the database file size consistently grows larger even when I delete and recreate one of the columns.

This has to do with checkpointing not happening until restart, which is a long-standing issue that we will get to when we further rework our storage format. In principle dropping a column should remove all data from that column. In the in-memory situation that is exactly what will happen, but the on-disk file will currently only remove the data on a restart.

> As a follow-up, is there a way to add a column to a database table from a pandas Series? This also seems like it would be a common need for exploratory data analysis. I am admittedly new to working with databases. Any guidance you can offer is greatly appreciated.

Currently the only way in which this is possible would be to convert the series to a pandas DataFrame, and then perform an update with a join on that DataFrame, e.g.:

```sql
UPDATE test
SET column_name={query}
FROM df
WHERE test.id=df.id;
```

This is not ideal as this will actually execute a join. In the future we want to add an implicit join on rowid (i.e. where the first row of "test" is automatically mapped to the first row of "df") which should resolve this, but this is not there yet.
