### ISSUE TITLE
Build with clang resolves missing libasan link error

### ISSUE THREAD

**Issue by arjenpdevries** [cwida/duckdb#122]
My first build was not using `clang` but my system's default of `gcc`, and _linking failed_ on missing `libasan`. I get the impression that the DuckDB developers default is `clang`. Switching to `clang` resolved the linking error, and also gives fewer (only one remaining actually) warnings about type mismatches when building the codebase. _(I only had to add `sqlite-devel` to my Fedora system.)_

I think it would be good to update the README to instruct people to use `clang` (unless they know what they are doing). Perhaps the `cmake` configuration should check for `libasan` and `sqlite-devel` to be installed.

**Comment by hannesmuehleisen** [comment]
Welcome @arjenpdevries , can you give the console output. Also might be worth implementing #94 as a response.

**Comment by Mytherin** [comment]
Both GCC and Clang should work fine. Indeed, defaulting to an optimized build should solve this. Neither libasan nor sqlite-devel are required to build the core of DuckDB. Libasan is used for debugging purposes (address sanitizer) and SQLite is used only for the tests. Then if people want to debug and run the tests they can install these libraries.

**Comment by arjenpdevries** [comment]
Console output:

    build$ cmake -DCMAKE_BUILD_TYPE=Debug --clean-first -j 4 ..
    build$ make > make.log 2> make.err
    [..]
    /usr/bin/ld: cannot find /usr/lib64/libasan.so.5.0.0 inside /
    collect2: error: ld returned 1 exit status
    make[2]: *** [src/CMakeFiles/duckdb.dir/build.make:697: src/libduckdb.so] Error 1
    make[1]: *** [CMakeFiles/Makefile2:173: src/CMakeFiles/duckdb.dir/all] Error 2
    make: *** [Makefile:84: all] Error 2

Attached complete output: [`make.log`](https://github.com/cwida/duckdb/files/2961807/make.log) (uninteresting) and [`make.err`](https://github.com/cwida/duckdb/files/2961820/make.err.txt) (various warnings given by `gcc` that could be addressed).

**Comment by arjenpdevries** [comment]
PS: I just reported it because it is a "first build experience" and I assumed you want that to be as accessible as possible. I understand that maybe I should have chosen `Release` instead of `Debug` and then it might not have happened :smile:. Perhaps suggesting Clang as default is not a bad idea though, especially not if that would be your own default (?).

**Comment by Mytherin** [comment]
Indeed we absolutely want it to work out of the box. However, it should succeed with any C++11 compatible compiler (and we do also run tests on both clang, gcc and msvc).

 In this case it didn't fail because of the compiler, but rather because of the missing dependency (address sanitizer). I think the proper solution therefore would be to disable the address sanitizer by default (i.e. DEBUG compiles only with -O0 -g), we can then make a separate build configuration DebugWithSanitizer that also compiles with the sanitizer.

And indeed those warnings should be fixed, thanks for the list!

**Comment by hannesmuehleisen** [comment]
We now use release build by default
