### ISSUE TITLE
Crash on single-argument COALESCE

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#1222]
I can PM someone the data. This is the valid query:
```{r}

res=dbGetQuery(con,"select recipient_duns,count() as n_contracts,sum(coalesce(potential_total_value_of_award,0)) as award,
              max(action_date_fiscal_year) as year_max,
              min(action_date_fiscal_year) as year_min,
              sum(case when place_of_manufacture like '%OUTSIDE%U%S%' then 1 else 0 end) contracts_outside_usa,
              sum(case when place_of_manufacture like '%OUTSIDE%U%S%' then coalesce(potential_total_value_of_award,0) else 0 end) dollarval_contracts_outside_usa
           from parquet_scan('*201[5-9]*/*parquet') group by recipient_duns")

```
This is the errant query. It should just complain but rather R crashes giving me an option to core dump. The errant query is in the phrase coalesce(potential_total_value_of_award0) e.g. no comma

```{r}
res=dbGetQuery(con,"select recipient_duns,count() as n_contracts,sum(coalesce(potential_total_value_of_award,0)) as award,
              max(action_date_fiscal_year) as year_max,
              min(action_date_fiscal_year) as year_min,
              sum(case when place_of_manufacture like '%OUTSIDE%U%S%' then 1 else 0 end) contracts_outside_usa,
              sum(case when place_of_manufacture like '%OUTSIDE%U%S%' then coalesce(potential_total_value_of_award0) else 0 end) dollarval_contracts_outside_usa
           from parquet_scan('*201[5-9]*/*parquet') group by recipient_duns")

**Comment by hannesmuehleisen** [comment]
Already seeing the issue on `select coalesce(1)`, so no need to share the data for now

**Comment by hannesmuehleisen** [comment]
@alanpaulkwan can you please check and confirm if this is indeed fixed on master?

**Comment by alanpaulkwan** [comment]
@hannesmuehleisen i just installed the bleeding edge via R. It is not as select coalesce(1) just crashed everything.

**Comment by hannesmuehleisen** [comment]
@alanpaulkwan sorry I can't parse that sentence. If it still crashes please do share your files to hannes@cwi.nl

**Comment by alanpaulkwan** [comment]
Sorry, what I mean was: I just reinstalled the latest version via the install instructions on your DuckDB page.

![image](https://user-images.githubusercontent.com/8321252/102178264-16243480-3ee0-11eb-8e2f-2bf9bde137f3.png)

**Comment by hannesmuehleisen** [comment]
This works fine for me, I suspect you still have an old version. Whats your output of `dbGetQuery(con, "pragma version")`? I get

````
  library_version source_id
1    0.2.4-dev103 5eff21830
````

**Comment by alanpaulkwan** [comment]
Works fine now!
