### ISSUE TITLE
exporting single table to flat file

### ISSUE THREAD

**Issue by Zelazny7** [cwida/duckdb#1228]
What is the best way to export a single table to a flat file? Currently it looks like the options for exporting a single table to, say,  a csv file are:

1. use the CLI to change the mode and select the table
2. drop all tables except for the one to be exported and use the EXPORT statement
3. pull the entire table into memory and write it using pandas

My primary use case is data munging on medium size data using windows. I need to process some files and hand them off for further use/machine learning.

**Comment by hannesmuehleisen** [comment]
try the `COPY` command, see here under "export" https://duckdb.org/docs/sql/statements/copy
