### ISSUE TITLE
DuckDB Holiday Break until 12-28

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#1235]
Here at DuckDB we pride ourselves in responding to issues and PRs as quickly as possible. However, this year @Mytherin and I are taking a ho-ho-holiday break until December 28 and take it a bit slower. 

It's been a great year for DuckDB, we added features, greatly improved performance and increased our esteemed user base. But now its time for a break.

**Comment by arjenpdevries** [comment]
Happy ho-ho-holidays everyone!!

Tnx for a great project!!

**Comment by jtommaney** [comment]
Have a great break!   Amazing progress!
