### ISSUE TITLE
support dplyr outside of main schema

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#1238]
If I created a schema (say crsp) to create a table called crsp.dsf, the following would break:
```{r}
tbl(con,'crsp.dsf')
```
This is because the tbl function wraps the name crsp.dsf with "crsp.dsf" which defaults to the main schema. It would be really great to register crsp.dsf correctly.

**Comment by hannesmuehleisen** [comment]
This is not a DuckDB issue. Try `dbplyr`s `in_schema` like so:

````R
library(DBI)
con <- dbConnect(duckdb::duckdb())
dbExecute(con, "CREATE SCHEMA fuu")
dbExecute(con, "CREATE TABLE fuu.bar(i INTEGER)")

library(dplyr)

tbl(con, dbplyr::in_schema("fuu", "bar")) %>% head()

````

**Comment by cmeuli07** [comment]
I'm not sure if this is the right place to put this, or if I should start a new issue, but the code hannes supplied above does not currently work.

`
sessionInfo()

con <- dbConnect(duckdb::duckdb())
dbExecute(con, "CREATE SCHEMA fuu")
dbExecute(con, "CREATE TABLE fuu.bar(i INTEGER)")
tbl(con, dbplyr::in_schema("fuu", "bar")) %>% head()

> sessionInfo()
R version 4.4.2 (2024-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 11 x64 (build 26100)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/Chicago
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dbplyr_2.5.0 duckdb_1.3.0 DBI_1.2.3    dplyr_1.1.4 

loaded via a namespace (and not attached):
 [1] R6_2.6.1          tidyselect_1.2.1  magrittr_2.0.3    glue_1.8.0        tibble_3.2.1      pkgconfig_2.0.3   generics_0.1.3    lifecycle_1.0.4  
 [9] cli_3.6.3         vctrs_0.6.5       compiler_4.4.2    rstudioapi_0.17.1 tools_4.4.2       pillar_1.10.2     rlang_1.1.5      
> con <- dbConnect(duckdb::duckdb())
> dbExecute(con, "CREATE SCHEMA fuu")
[1] 0
> dbExecute(con, "CREATE TABLE fuu.bar(i INTEGER)")
[1] 0
> tbl(con, dbplyr::in_schema("fuu", "bar")) %>% head()
Error in DBI::dbExistsTable(src, from) : 
  Can only have a single name argument
`

additionally, trying to bypass in_schema() by simply supplying tbl(con, 'fuu.bar') also errors out. This reprex is occurring for me on databases created outside of R that I'm simply trying to connect to later.
