### ISSUE TITLE
Bitwise aggregate functions for no input rows

### ISSUE THREAD

**Issue by jesusanaya-fb** [cwida/duckdb#1246]
The current implementation of Bitwise aggregate functions returns initial value for no input rows or when all values are null.

Current Results for no input:
Function      -     Initial Value
  Bit And.                     -1 
  Bit Or.                        0
  Bit Xor.                      0

Should we change it to return a null value? Most company databases return null in these cases. E.g:

Presto  (Facebook)	-> https://prestodb.io/docs/current/functions/aggregate.html 
BigQuery (Google) 	-> https://cloud.google.com/bigquery/docs/reference/standard-sql/aggregate_functions 
RedShift (Amazon)	-> https://docs.aws.amazon.com/redshift/latest/dg/c_bitwise_aggregate_functions.html

**Comment by hannesmuehleisen** [comment]
Thanks, please don't @ individuals directly in issue reports. I agree we should return NULL in those cases as well. Happy to review a PR.

**Comment by mbasmanova** [comment]
CC: @mbasmanova
