### ISSUE TITLE
Segmentation fault on subselects with "recursive"

### ISSUE THREAD

**Issue by mrwilson** [cwida/duckdb#1248]
Hi,

Expected: `"Error: near line 1: Catalog Error: Table with name test does not exist!"` (because it should be `with recursive test(...)`)

Got: Segmentation fault.

### Query to reproduce

```
with test(round) as (
    select 0
    union all
    select round+1 from test where round <= 20
)

select test.round
from
    -- delete the subselect line and it gives the expected error
    (select round from test limit 1) as subselect, 
    test;
```

**Comment by hannesmuehleisen** [comment]
This looks like an infinite recursion in `FindCTE`
