### ISSUE TITLE
Add ascii, chr functions

### ISSUE THREAD

**Issue by jtommaney** [cwida/duckdb#1250]
I don't seem to see the ascii() or chr() functions included.

**Comment by hannesmuehleisen** [comment]
What should happen if someone calls ASCII on an UTF character or parts thereof?

**Comment by jtommaney** [comment]
Postgres: allows conversion with extended character sets.   ascii() effectively behaves as unicode(), returning the unicode code point.  

ASCII ('x') = 120
ASCII ('Ä') = 1234

CHR (64) = 'A'
CHR (1234) = 'Ä'
CHR (NULL) = NULL

SELECT CHR(937);  example:
https://www.postgresqltutorial.com/postgresql-chr/

MySQL has similar behavior other than CHAR() instead of CHR().

**Comment by hannesmuehleisen** [comment]
That seems pretty sane, thanks.

**Comment by hannesmuehleisen** [comment]
This has been implemented, thanks, @pdet
