### ISSUE TITLE
Support for gamma function?

### ISSUE THREAD

**Issue by CreRecombinase** [cwida/duckdb#1251]
Hi,  it would be really swell if DuckDB had support for the [gamma function](https://en.cppreference.com/w/cpp/numeric/math/tgamma) and [log gamma function](https://en.cppreference.com/w/cpp/numeric/math/lgamma).  There are a lot of super useful statistical functions that can be implemented once you have the gamma function, and I don't think it would be a huge amount of work to implement because it's in `cmath.h`.  I'd be happy to make a pull request.

**Comment by hannesmuehleisen** [comment]
Yes, happy to review a PR for this

**Comment by hannesmuehleisen** [comment]
Ended up doing it myself.
