### ISSUE TITLE
Weird parsing on trailing newline in csv

### ISSUE THREAD

**Issue by burtgulash** [cwida/duckdb#1254]
Not sure if this is expected behaviour, but it seems strange to me.

Same csv file, one with and one without trailing newline.
```
% echo "a,b\n1,2" > /tmp/x.csv; duckdb -csv /tmp/x.db "select * from read_csv_auto('/tmp/x.csv')"
a,b
1,2
% echo "a,b\n1,2\n" > /tmp/x.csv; duckdb -csv /tmp/x.db "select * from read_csv_auto('/tmp/x.csv')"
column0
"a,b"
"1,2"

% duckdb --version
DuckDB 3222accba
```

**Comment by tdoehmen** [comment]
Thanks for the report. This should not be expected behavior. I have a suspiscion and will take a look soon.

**Comment by tdoehmen** [comment]
@burtgulash should be fixed now.

**Comment by hannesmuehleisen** [comment]
@burtgulash could you please have a look and confirm this is fixed?

**Comment by burtgulash** [comment]
```
0.2.4-dev393 8cf7abc06
```
Looks good to me. Thanks!
