### ISSUE TITLE
PRAGMA to expose the database size for :memory: databases

### ISSUE THREAD

**Issue by josephernest** [cwida/duckdb#1257]
When doing benchmarks, it is always useful to keep an eye on the database size.  
Do you think a `PRAGMA database_size;` would be possible? or something similar to Sqlite:

    print('size (MB):', next(db.execute('PRAGMA page_count;'))[0] * next(db.execute('PRAGMA page_size;'))[0] / 1024**2)

See also https://github.com/cwida/duckdb/issues/1249#issuecomment-753357058

**Comment by Mytherin** [comment]
PRAGMA database_size now exists in master, and reports the memory usage of the system, together with various statistics about the database in the on-disk case.
