### ISSUE TITLE
Fetch DF in Chunks vs. All at once

### ISSUE THREAD

**Issue by Alex-Monahan** [cwida/duckdb#1261]
It would be helpful to us to control memory usage and prevent infinitely long queries if there was a way to pull query results into Pandas through the Python API in chunks. This could also facilitate loading results into larger-than-memory dataframe libraries like Dask/Modin/Vaex without running out of memory. (We still use DataFrames for operations like pivoting, so we need to swap back and forth in our workflow).

The [pandas.read_sql function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html) is what we use for pulling SQLite results (our fallback/legacy approach pre-DuckDB!), and it accepts a chunksize parameter to indicate the number of rows returned by each chunk. It just returns an iterator of dataframes whenever that parameter is populated. 

Also, I'm assuming the best chunk sizes to choose would be evenly divisible by the vector size (Default of 1024, correct?)?

Thank you!

**Comment by hannesmuehleisen** [comment]
I have no objections to exposing `fetch_df_chunk` or something like that. It would have a default fetch size, which would be equivalent to the default vector size, which is indeed 1024 right now but is likely to increase in the future. Is it necessary for the user to be able to control the fetch size?

**Comment by Alex-Monahan** [comment]
I plan on using the default that you recommend, but the receiving structure may be the bottleneck and need a different sized chunk. It could definitely be handled on the Pandas side if needed with a loop and a concat. If it's much easier to implement as fixed to the vector size, it would work for me!
