### ISSUE TITLE
max memory usage

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#1264]
Is there a way to cap the memory used by DuckDB? I sincerely apologize if this is a duplicate. For me, a sufficient implementation would be

**set MAX_MEMORY_USAGE=10GB** or something like that

I suppose this is useful for obvious reasons. It's also useful if I want to simulate how a query may run in a different environment, such as a student's laptop or a confidential access machine which are usually nerfed computers :(

**Comment by hannesmuehleisen** [comment]
`PRAGMA memory_limit='10GB';` see here: https://duckdb.org/docs/sql/pragmas
