### ISSUE TITLE
JDBC, support for Mathematica

### ISSUE THREAD

**Issue by whatsthecraic** [cwida/duckdb#1268]
Opening a JDBC connection with Mathematica fails with the following exception:
```
db = OpenSQLConnection[  JDBC["org.duckdb.DuckDBDriver", "jdbc:duckdb:/path/to/my/database.duckdb"] ]
Java::excptn: A Java exception occurred: java.sql.SQLFeatureNotSupportedException
	at org.duckdb.DuckDBConnection.getCatalog(DuckDBConnection.java:164)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566).
```

driver v0.2.3

**Comment by hannesmuehleisen** [comment]
We merged a potential fix for this, can you please check whether this is fixed with the JDBC driver from the master branch? The binaries are here: https://github.com/cwida/duckdb/releases/tag/master-builds

I cannot test this since I don't have Mathematica

**Comment by whatsthecraic** [comment]
I suppose that's a different issue but:

```
JDBC::error: IO Error: Trying to read a database file with version number 6, but we can only read version 9.
The database file was created with an older version of DuckDB.

Th\[Ellipsis] that you load the database file in a supported version of DuckDB, and use the EXPORT DATABASE command followed by IMPORT DATABASE on the current version of DuckDB.
```
So, exporting the database:

```
# duckdb data21.duckdb
0.2.4-dev0 436f6455f
Enter ".help" for usage hints.
D EXPORT DATABASE '/tmp/data1';
D .quit
```

And re-importing back:
```
# duckdb data22.duckdb
0.2.4-dev405 7a8dd0945
Enter ".help" for usage hints.
D IMPORT DATABASE '/tmp/data1';
Error: Parser Error: syntax error at or near ")"
LINE 9: ...GINT PRIMARY KEY, exec_id BIGINT NOT NULL, tick BIGINT NOT NULL, memfp_process...
```

I'm copying the problematic database in bricks01:/scratch/dleo/temp/data21.duckdb.tar.gz .


Do you have an utility to transform the database between different versions?

**Comment by Mytherin** [comment]
There is no such utility (besides DuckDB itself). All the `EXPORT DATABASE` does is create a directory with a bunch of CSV files and two sql files (schema.sql and load.sql) that describe how to create the schema and how to load the data respectively. I believe we had a bug some versions ago where identifiers that needed to be quoted were not properly quoted, which might be what is causing the `IMPORT DATABASE` to fail here. Try checking the parser error reported (likely in schema.sql:9) (or copy the contents of that file here so we can check what is going on).

**Comment by whatsthecraic** [comment]
Okay, I'll recreate the schema by hand.

[schema.sql.txt](https://github.com/cwida/duckdb/files/5789395/schema.sql.txt)

**Comment by Mytherin** [comment]
Thanks! Actually this seems to be a different problem, relating to the fact that `current_timestamp` is not a function but a keyword. Changing that line to this fixes the problem for me:

```sql
CREATE TABLE executions(id BIGINT PRIMARY KEY, time_start TIMESTAMP DEFAULT(current_timestamp), time_end TIMESTAMP, magic BIGINT NOT NULL DEFAULT(0));
```

**Comment by whatsthecraic** [comment]
Ah oky, thanks!

Regarding JDBC, there is progress! It is now able to connect to the data source, but it cannot run any SQL:

```
SQLExecute[db, "SELECT * FROM executions LIMIT 5"]
Java::excptn: A Java exception occurred: java.sql.SQLFeatureNotSupportedException
	at org.duckdb.DuckDBConnection.prepareStatement(DuckDBConnection.java:214)
	at com.wolfram.databaselink.SQLStatementProcessor.processSQLStatement(SQLStatementProcessor.java:65)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566).
```

**Comment by hannesmuehleisen** [comment]
I got the Mathematica Trial now ^^ will give it a go later

**Comment by hannesmuehleisen** [comment]
Got this to work, once the tests pass we will merge this
