### ISSUE TITLE
Improve Compilation Time

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#127]
Compilation time is too damn high

Ideas to improve it:

- Split up common headers, no longer include everywhere
- Especially "constants.hpp" which includes a bunch of STL main stuff should be split up, instead make separate files e.g. "common/vector.hpp" that does "#include <vector> => using std::vector" that can then be included in files that need the vector implementation
- For tests, the "catch" framework is very slow to compile because it is a huge header only library. We should use CMake somehow to gather the test code from different files into one file instead of compiling every test as a separate translation unit.

**Comment by hannesmuehleisen** [comment]
we could use precompiled headers to speed up test compilation

**Comment by hannesmuehleisen** [comment]
I think this is solved with the unity builds
