### ISSUE TITLE
JDBC: some emoji character will make the result string shorten

### ISSUE THREAD

**Issue by Baoqi** [cwida/duckdb#1271]
First, thanks for this great project.

When I use duckdb to develop a ETL tool to sync data with some processing between different database, I find some emoji will cause wrong data returned.

It was found when I import some json string from one database into "jsonb" column of postgresql. most records work ok, but one failed with "wrong json format", after investigate more, I found the content returned from duckdb was truncated to shorter string, which cause invalid json error.

Then, I find this is related with JDBC Fetch string column from duckdb, and it is related with some emoji character. 

To reproduce, we can execute the following SQL:

`

select '🦄ྀི123456789'

`

The result will be:

+------------+
|ð¦ྀི123456|
+------------+
|ð¦ྀི123456|
+------------+

The ending 3 characters (7,8,9) will missing

If I debug in Intellij Idea,  the correct data for that emoji read from source database is:

'\uD83E' 55358
'\uDD84' 56708

the wrong data from duckdb will be (2 characters longer)

'ð' 240
'\u009F' 159
'¦' 166
'\u0084' 132

Do you have any clue where maybe wrong, thanks a lot

**Comment by hannesmuehleisen** [comment]
Will have a look

**Comment by hannesmuehleisen** [comment]
We merged a fix for this, can you please check whether this is fixed with the JDBC driver from the master branch? The binaries are here: https://github.com/cwida/duckdb/releases/tag/master-builds

**Comment by Baoqi** [comment]
> We merged a fix for this, can you please check whether this is fixed with the JDBC driver from the master branch? The binaries are here: https://github.com/cwida/duckdb/releases/tag/master-builds

Hi, hannesmuehleisen, thanks a lot. I verified the jdbc cell value works correctly.

Though the column name returned is still wrong.  Can you also help fix the column name returned from ResultSetMetadata

resultSet.getMetaData().getColumnName()     and   resultSet.getMetaData().getColumnLabel()

Although it is rare to have emoji in column names.


currently, the same sql's result on my machine is: (the first line is column name or label)

+-------------+
| ð¦ྀི123456|
+-------------+
|🦄ྀི123456789|
+-------------+

**Comment by Baoqi** [comment]
Hi, hannesmuehleisen, by refer to your previous changes, I also try to make a pull request to fix the column name display issue:  https://github.com/cwida/duckdb/pull/1282

hope I can also do some contribution to duckdb

**Comment by hannesmuehleisen** [comment]
Thanks for fixing this! Indeed I had forgotten column names.
