### ISSUE TITLE
FULL JOIN reports missing values for join key

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#1290]
`
   select * from left_table as a full out joiner right_table as b
      using(key1,key2)
`

Suppose that key1,key2 is missing on the left table, but present in the right table. The resulting table will report key1,key2 as null for those values in the right table. The only way to retrieve them is to type **coalesce(a.key1,b.key1) as key1**

I don't think this is ideal behavior.

**Comment by Mytherin** [comment]
Thanks for the report! I can confirm this behavior is inconsistent with Postgres. I will have a look.

**Comment by alanpaulkwan** [comment]
Here's a replicable example, bleeding edge as of 2 weeks ago

![image](https://user-images.githubusercontent.com/8321252/104251956-de42e980-54ab-11eb-921a-01294115a0be.png)
