### ISSUE TITLE
Date filter hidden from zonemap check with in-clause when not using keyword "date" to cast as date.

### ISSUE THREAD

**Issue by jtommaney** [cwida/duckdb#1303]
Uses Zonemap check:
 l_shipdate = '1995-12-01'
 l_shipdate = date '1995-12-01' or l_shipdate = date '1995-12-02'
 l_shipdate in (date '1995-12-01', date '1995-12-02')

Does not use Zonemap check:
l_shipdate in ( '1995-12-01', '1995-12-02') 

D explain select l_shipdate, count(*) from lineitem where l_shipdate = '1995-12-01'  group by 1 order by 1;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #0 ASC          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│   PERFECT_HASH_GROUP_BY   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│        count_star()       │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          lineitem         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          Filters:         │
│   l_shipdate=1995-12-01   │
└───────────────────────────┘                             
Run Time: real 0.001 user 0.000000 sys 0.000685

explain select l_shipdate, count(*) from lineitem where l_shipdate = date '1995-12-01' or l_shipdate = date '1995-12-02' group by 1 order by 1;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #0 ASC          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│   PERFECT_HASH_GROUP_BY   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│        count_star()       │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ (l_shipdate=1995-12-01 OR │
│   l_shipdate=1995-12-02)  │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          lineitem         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│      Zonemaps Checks:     │
│   l_shipdate>=1995-12-01  │
│   l_shipdate<=1995-12-02  │
└───────────────────────────┘                             
Run Time: real 0.001 user 0.000798 sys 0.000000
D explain select l_shipdate, count(*) from lineitem where l_shipdate in (date '1995-12-01', date '1995-12-02') group by 1 order by 1;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #0 ASC          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│   PERFECT_HASH_GROUP_BY   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│        count_star()       │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ (l_shipdate=1995-12-01 OR │
│   l_shipdate=1995-12-02)  │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          lineitem         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│      Zonemaps Checks:     │
│   l_shipdate>=1995-12-01  │
│   l_shipdate<=1995-12-02  │
└───────────────────────────┘                             
Run Time: real 0.001 user 0.000000 sys 0.000780
D explain select l_shipdate, count(*) from lineitem where l_shipdate in ( '1995-12-01', '1995-12-02') group by 1 order by 1;

┌─────────────────────────────┐
│┌───────────────────────────┐│
││       Physical Plan       ││
│└───────────────────────────┘│
└─────────────────────────────┘
┌───────────────────────────┐
│          ORDER_BY         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│           #0 ASC          │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│   PERFECT_HASH_GROUP_BY   │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│             #0            │
│        count_star()       │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│         PROJECTION        │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│           FILTER          │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│ (CAST[VARCHAR](l_shipdate)│
│=1995-12-01 OR CAST[VA...  │
│  (l_shipdate)=1995-12-02) │
└─────────────┬─────────────┘                             
┌─────────────┴─────────────┐
│          SEQ_SCAN         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│          lineitem         │
│   ─ ─ ─ ─ ─ ─ ─ ─ ─ ─ ─   │
│         l_shipdate        │
└───────────────────────────┘                             
Run Time: real 0.001 user 0.000024 sys 0.000753

**Comment by hannesmuehleisen** [comment]
Maybe @pdet can have a look?

**Comment by hannesmuehleisen** [comment]
This should be fixed
