### ISSUE TITLE
Return empty json array in case of no results returned

### ISSUE THREAD

**Issue by burtgulash** [cwida/duckdb#1305]
I'm using the -json output of the duckdb command as that allows me to send the query result straight to a client application without having to parse through it slowly in python.

The query returns empty string when there are no results, which is not consistent with the case when the query result is non-empty, in which case an array of json objects is returned.

```
% duckdb -json /tmp/xxx.db 'select 1 where 1=1'                   
[{"1":1}]
% duckdb -json /tmp/xxx.db 'select 1 where 1=0'
%
% # ^ empty string returned
```

It's no big deal because I can just wrap it in an if statement, but I think it should be made consistent. Empty result should return 
`[]` instead of empty string.

Alternatively it would be nice if there was an option to receive **jsonlines** output directly, ie. results not wrapped in an array.
Also it would be nice if I could receive json data directly using the python client.

**Comment by hannesmuehleisen** [comment]
This is again the SQLite shell that does this, not DuckDB
