### ISSUE TITLE
Regression Analysis

### ISSUE THREAD

**Issue by waynelapierre** [cwida/duckdb#1306]
Does DuckDB provide regression analysis functions?

**Comment by hannesmuehleisen** [comment]
Could you please be more specific? Which functions are you referring to?

**Comment by waynelapierre** [comment]
I mean the function with which you can regress a column on other columns. Like the lm function in R.

**Comment by hannesmuehleisen** [comment]
Two options, 1) pull those columns into R, and run `lm` there. 2) Implement a recursive CTE that computes the fit.
