### ISSUE TITLE
Auto Increment Primary Key And/or Serial 

### ISSUE THREAD

**Issue by willium** [cwida/duckdb#1308]
While Auto-Incrementing ideas are more useful, common, and idiomatic is an OLTP store, they can be very useful for tracking changesets (especially for caching) in OLAP analytical tasks. Towards that end, it would be great to have the ability to specify an AUTO INCREMENT policy on a column (or something more advanced like PostgreSQLs Serial flag). While It's easy enough to do this manually with a prior `COUNT(*)` query, a write-lock, and bulk insert statements, the only way to add such a column when using a scanner/reader like `read_csv` is to add a new column and manually `UPDATE` into that column (thereby ~defeating the purpose of those fast import mechanisms). Thoughts?

**Comment by hannesmuehleisen** [comment]
How about using a sequence? For example
````SQL
CREATE SEQUENCE seq;
CREATE TABLE a (i INTEGER DEFAULT NEXTVAL('seq'), b INTEGER);
INSERT INTO a (b) VALUES (42), (43);
SELECT * FROM a;
````
Result:
````
┌───┬────┐
│ i │ b  │
├───┼────┤
│ 1 │ 42 │
│ 2 │ 43 │
└───┴────┘
````

**Comment by willium** [comment]
oh neat! is there any way to use this alongside read_csv/COPY?

**Comment by hannesmuehleisen** [comment]
Certainly:
````
echo -e '42\n43\n44' > /tmp/dummy
````
````SQL
COPY a(b) FROM '/tmp/dummy';
SELECT * FROM a;
````

````
┌───┬────┐
│ i │ b  │
├───┼────┤
│ 1 │ 42 │
│ 2 │ 43 │
│ 3 │ 44 │
└───┴────┘
````

**Comment by willium** [comment]
```sql
CREATE SEQUENCE seq;
CREATE TABLE gh (i BIGINT DEFAULT NEXTVAL('seq'), time TIME, count INTEGER);
INSERT INTO gh SELECT * FROM read_csv_auto('github.csv');

Error: Binder Error: table gh has 3 columns but 2 values were supplied

-- Is there a way to handle this in cases where we don't know the column names for the given csv?

INSERT INTO gh(time,count) SELECT * FROM read_csv_auto('github.csv');
SELECT * FROM gh LIMIT 5;
┌───┬──────────┬───────┐
│ i │   time   │ count │
├───┼──────────┼───────┤
│ 1 │ 01:00:00 │ 2     │
│ 2 │ 04:00:00 │ 3     │
│ 3 │ 05:00:00 │ 1     │
│ 4 │ 08:00:00 │ 1     │
│ 5 │ 09:00:00 │ 3     │
└───┴──────────┴───────┘
```

**Comment by willium** [comment]
never mind, this worked well:
```sql
ALTER TABLE gh ADD COLUMN i BIGINT DEFAULT NEXTVAL('seq');
```
