### ISSUE TITLE
Question: using CLI for Api?

### ISSUE THREAD

**Issue by sdmcallister** [cwida/duckdb#1316]
I'm interested in creating an Api in Dart but there isn't currently a Dart library for Duckdb. Dart has ffi support but I'm not really able to create my own wrapper. I've experimented with the Dart io library to access json data via a CLI process. The json output is awesome for js charting libraries. This approach seems to work based on a few small tests, but is it recommended? I imagine this approached could be used in other language that don't have libraries. I'm curious about security and performance implications though.

**Comment by hannesmuehleisen** [comment]
Well I see no fundamental issue with calling the CLI directly if there are no language bindings yet. You may also check if Dart has a way to access C/JDBC libraries, which would be somewhat cleaner.

**Comment by hannesmuehleisen** [comment]
E.g. using something like this: https://dart.dev/guides/libraries/c-interop
