### ISSUE TITLE
JDBC: fail to load duckdb jdbc driver on CentOS 7 due to the libstdc++ library

### ISSUE THREAD

**Issue by Baoqi** [cwida/duckdb#1319]
When I run duckdb JDBC on CentOS 7 ,  it fails to load with exception:

Exception in thread "main" java.lang.UnsatisfiedLinkError: Can't load library: /tmp/libduckdb_java7966367291252824499.so

the ldd command will show:

```
./libduckdb_java.so_linux_amd64: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./libduckdb_java.so_linux_amd64)
./libduckdb_java.so_linux_amd64: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./libduckdb_java.so_linux_amd64)
./libduckdb_java.so_linux_amd64: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libduckdb_java.so_linux_amd64)
	linux-vdso.so.1 =>  (0x00007ffe8af82000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe18a626000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe18a31e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fe18a01c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe189e06000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fe189a39000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fe18b4e8000)
```

This is due to the libstdc++.so.6   only support up to GLIBCXX_3.4.19,   and it is not easy to upgrade CentOS7's libstdc++

So, I think to make the embedded so in JDBC driver support more linux distros, we can static link to libstdc++ etc. instead of dynamically load them.  I will try to submit a pull request for this soon, Thanks.

**Comment by hannesmuehleisen** [comment]
For those ancient linux versions you should probably compile from source there?

**Comment by k138z** [comment]
> 
> 
> For those ancient linux versions you should probably compile from source there?

That did the trick. Thanks!

**Comment by kiwimg** [comment]
CentOS Linux release 7.8.2003 (Core)
Tried to run the compiled linux duckdb binary. seeing messages like version GLIBC_2.23' not found (required by ./duckdb)`.
