### ISSUE TITLE
How to tell DuckDB that the csv is compressed

### ISSUE THREAD

**Issue by djouallah** [cwida/duckdb#1326]
I have a csv file that is compressed using Gzip, when I query it, I get this error
`RuntimeError: String value is not valid UTF8`

but when I rename it to data.csv.gz it works just fine, is there an option to tell DuckDB that the file is compressed ?
I can't rename the files.

**Comment by hannesmuehleisen** [comment]
Indeed we currently derive this from the file name. We should add a flag to force a particular compression method.

**Comment by hannesmuehleisen** [comment]
@tdoehmen perhaps this is something for you?

**Comment by tdoehmen** [comment]
Sure, we could just add a flag for that.

**Comment by hannesmuehleisen** [comment]
This should be fixed, thanks @tdoehmen

**Comment by djouallah** [comment]
Thank you very much
