### ISSUE TITLE
Can you safely copy the file while it’s being written to?

### ISSUE THREAD

**Issue by fintron** [cwida/duckdb#1331]
Somewhat of a follow-up to this question:
https://github.com/cwida/duckdb/issues/1330

if you have one process continually writing to a DB, can you copy that file and be sure that it won’t be in a corrupt or somewhat indeterminate state?

(obviously, it would be hard to predict which writes made it in or not. I’m copying the dB file while it’s being written might lead it to be in a corrupt state. Basically not sure if writes are atomic, etc)

**Comment by hannesmuehleisen** [comment]
The file on disk should always be in a consistent state. The latest data that is being written may still live in transaction buffers or the write-ahead log though, so you might lose that.
