### ISSUE TITLE
Filter issue with `IN` and `NULL`

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#1334]
This was found by SQLancer:

```SQL
CREATE TABLE t0(c0 boolean);
INSERT INTO t0 VALUES (false), (NULL);
SELECT t0.c0 FROM t0 WHERE t0.c0 IN (false, NULL);
````

should return `false` but instead returns no results.

**Comment by pdet** [comment]
Likely caused by my IN optimization.
@hannesmuehleisen please assign me.
