### ISSUE TITLE
Can you provide a row iterator interface in Python for query results?

### ISSUE THREAD

**Issue by fintron** [cwida/duckdb#1340]
All of the row result methods here:
https://duckdb.org/docs/api/python
- fetchdf
- fetchall
- fetchnumpy
will put store the query results into memory. If the DuckDB database is sufficiently large, we will run out of memory. 

Can you provide an iterator-based method that won't create a list like `fetchall`? I would recommend just having fetchall return an iterator. That way, you can still call `list(fetchall)` if you want a list of results.

**Comment by hannesmuehleisen** [comment]
there is `fetchone()` as well.
````Python
import duckdb
con = duckdb.connect(':memory:')
con.execute('values (42), (43)')

while True:
	try:
		row = con.fetchone()
	except:
		break
	print(row)
````

We should probably not make this throw exceptions if you run out of result set at some point, but this will work for now.

**Comment by hannesmuehleisen** [comment]
See also #1261 which may be a better solution
