### ISSUE TITLE
Enable concurrent connection

### ISSUE THREAD

**Issue by nestarz** [cwida/duckdb#1343]
Hello !

I want to access my duckdb database using the PostgreSQL FDW and make a connection using Google Data Studio (or even from two+ remote psql connection), but when a connection is made, none other could be made. I have this error when there is already a connection:
ERROR: failed to open SQLite DB. rc=1 path=/var/lib/postgresql/database.duckdb

Do you know how to make connection to the duckdb database so it can allow multiple reads ?

This is my postgresql config to access duckdb:
```
CREATE EXTENSION duckdb_fdw;
CREATE SERVER t1 FOREIGN DATA WRAPPER duckdb_fdw OPTIONS (database '/var/lib/postgresql/database.duckdb');
IMPORT FOREIGN SCHEMA public FROM SERVER t1 INTO public;
```

Thanks,

duckdb version: v0.2.3 (last release)

**Comment by Alex-Monahan** [comment]
If making multiple connections from different processes, DuckDB requires
you to be in read only mode. Just be sure to connect with the read only
flag set and you can have multiple readers!

Thanks,
Alex

**Comment by Mytherin** [comment]
As Alex said, the database has to be opened in read-only mode to allow for multiple connections. This is a flag that you set when connecting to the database using the database configuration. By default a read-write connection is made. We do not maintain the DuckDB foreign data wrapper so we cannot help you there directly; I recommend checking out the code [here](https://github.com/alitrack/duckdb_fdw) and opening an issue there or opening a PR to add an optional read-only option.

**Comment by nestarz** [comment]
Ok thank you, so just by setting the file as read-only will not be enough right ? It needs to be set from the connection code inside the wrapper if I understand, thanks for the help.

**Comment by chriszrc** [comment]
@Mytherin so what's a reasonable limit of concurrent connections to expect for duckdb in readonly mode and preserve performance?
