### ISSUE TITLE
Parquet reader: unsupported column types

### ISSUE THREAD

**Issue by rostislavdeepcrawl** [cwida/duckdb#1351]
We seem to have found 2 parquet column types that are not supported by duckdb.

The following produces `Not implemented Error: INVALID` error when reading:
```
optional fixed_len_byte_array(5) ga_avg_page_load_time (DECIMAL(10,2));
```

And the following is just getting ignored (i.e. the `chunk` returned from `Fetch` is empty or a null pointer):
```
  optional group raw_header (MAP) {
    repeated group map (MAP_KEY_VALUE) {
      required binary key (STRING);
      optional binary value (STRING);
    }
  }
```

**Comment by hannesmuehleisen** [comment]
Could you please either post the file or code to generate a parquet file that has these column types in it?

**Comment by rostislavdeepcrawl** [comment]
Sent to your email

**Comment by hannesmuehleisen** [comment]
The DECIMAL is something we will have to add support for in a future release, this will happen eventually. I'm looking into the MAP since it fails with an unexpected error.

**Comment by hannesmuehleisen** [comment]
The map issue should be fixed

**Comment by hannesmuehleisen** [comment]
Working on the decimals now.
