### ISSUE TITLE
duckdb compatibility with previous versions?

### ISSUE THREAD

**Issue by cboettig** [cwida/duckdb#1359]
After upgrading `duckdb`, I invariably get the error:

```
error: duckdb_startup_R: Failed to open database
```

if I try to establish a connection to an existing database created by an earlier version of `duckdb`.  Apologies if I'm missing something obvious, but is this expected?  Is there a recommended workaround?  (Usually I end up just removing the database entirely and re-creating it from scratch, but that can be _very_ slow!  Also, we use `duckdb` as a backend in several packages, and end users really don't like when this happens to them!  If I get a better handle on the issue I can perhaps at least write an upgrade helper utility to export and re-import the data after upgrade...)

Thanks for all you do to make an amazing package!

**Comment by Alex-Monahan** [comment]
Hello! I am not a maintainer, but maybe this will help!

When the version of the database storage changes, you can export your old database (with the old DuckDB version) and then import it into a new DB with the new one. The release notes include some more details. 

[Release notes](https://github.com/cwida/duckdb/releases/tag/v0.2.4)

**Comment by cboettig** [comment]
Thanks @Alex-Monahan , I should have checked the release notes, glad to know this is at least expected.

@hannesmuehleisen and team: just a note that I think this is still a significant barrier for the use-case of R packages that want to use duckdb as the local database backend in place of SQLite.  Many R users tend to just run update.packages() to keep packages up-to-date (a pattern that is all the more common with RStudio's packages such as `remotes` and `devtools` which prompt users to do so). Usually this is considered good practice (after all, CRAN runs the full revdep check on package updates).

However, clearly this creates a problem with the duckdb updates, since after the update we don't have the old duckdb version around to export from the old database.  I could possibly hack around this by having a function that attempts to (1) detect the version of the current database, (2) unload duckdb namespace, (3) install the old version, (4) run the export, (5) install the new version, (6) import the db.  Is there a better way?  (Also, is there any clear way to identify the version of the existing db?)

**Comment by hannesmuehleisen** [comment]
We are still updating the on-disk format, so its expected that there are going to be breaking changes between releases. The stabilisation of the format is indeed what keeps us from moving to "Preview Release" to "Release" and towards the 1.0.0 version number. I realise its not what you are used to from SQLite, which has not changed its format in forever. Other people have addressed this by including the DuckDB version into the database file or shipping an exported database instead.

**Comment by hannesmuehleisen** [comment]
That being said we can definitely work on the error message for the R client.

**Comment by hannesmuehleisen** [comment]
Added the failure reason to the error message in #1360

**Comment by cboettig** [comment]
Thanks @hannesmuehleisen!  Yeah, definitely understand that this is unavoidable. The new error message will go a long way towards helping R users realize why things have stopped working and how to remedy the issue.  


Feel free to close this when ready!
