### ISSUE TITLE
duckdb 0.2.4 broke censo2017 check results: unable to find an inherited method for function 'dbSendQuery' for signature 'duckdb_connection'

### ISSUE THREAD

**Issue by pachamaltese** [cwida/duckdb#1368]
see, for example, https://github.com/pachamaltese/censo2017/runs/1835548867?check_suite_focus=true#step:10:546

**Comment by hannesmuehleisen** [comment]
Are you sure duckdb and DBI are even installed in the CI run? Can’t see any attempt in the log.

**Comment by pachamaltese** [comment]
yeah, it was working well with 0.2.3
by now, I rolled back to rsqlite, which will broke more things, because the package on CRAN downloads the bz2 with the database from github
here's the last working commit https://github.com/pachamaltese/censo2017/actions
I shall try to re-create the duckdb file again and see what happens

**Comment by hannesmuehleisen** [comment]
Not sure what we can do to help  here. Feel free to reopen when you know.
