### ISSUE TITLE
sources in v0.2.4/libduckdb-src.zip aren't amalgamated.

### ISSUE THREAD

**Issue by toge** [cwida/duckdb#1371]
I think there are some includes line in duckdb.cpp to be amalgamated.

```
#include <utf8proc_wrapper.hpp>
#include <duckdb/common/operator/cast_operators.hpp>
```
Please fix this problmen.

**Comment by hannesmuehleisen** [comment]
Thanks for reporting this, this is indeed a bug and will be fixed.

**Comment by hannesmuehleisen** [comment]
This was fixed for the next release and the nightly builds

**Comment by lithdew** [comment]
I tried out the nightly build just now, is it intended that `#include "duckdb/common/winapi.hpp"` is included in `duckdb.hpp` instead of `#define DUCKDB_API`?

**Comment by Mytherin** [comment]
This seems related to the C API, not the C++ API, correct? Indeed this is not intended, and the file should be usable stand-alone. I will push a fix.

**Comment by lithdew** [comment]
> This seems related to the C API, not the C++ API, correct? Indeed this is not intended, and the file should be usable stand-alone. I will push a fix.

Yep, this is related to the C API. Thank you for the quick response!
