### ISSUE TITLE
how to use string_split

### ISSUE THREAD

**Issue by tianliuxin** [cwida/duckdb#1376]
hello,I use duckdb,but don't know how to use LIST type.
I read the document,but not found.
![image](https://user-images.githubusercontent.com/25357981/107232131-09ddd300-6a5c-11eb-8a05-281166c30242.png)

**Comment by hannesmuehleisen** [comment]
try:
````SQL
SELECT UNLIST(STRING_SPLIT('1,2,3', ','));
````

**Comment by tianliuxin** [comment]
thanks! I got it!
I like duckdb.I want to learn cpp because of it.
