### ISSUE TITLE
IO Error when reopening a connection in Java

### ISSUE THREAD

**Issue by alitaker** [cwida/duckdb#1378]
If I try to reopen a connection in Java I get the error:
`IO Error: Cannot open file "C:\Temp\duckdb_test.wal": Impossibile accedere al file. Il file è utilizzato da un altro processo.`

Here is a sample code:
```
Connection con;
Class loaded = Class.forName("org.duckdb.DuckDBDriver");
con = DriverManager.getConnection("jdbc:duckdb:C:\\Temp\\duckdb_test", "test", "test");
ResultSet rs = con.createStatement().executeQuery("SELECT * FROM weather;");
rs.close();
con.close();
con = DriverManager.getConnection("jdbc:duckdb:C:\\Temp\\duckdb_test", "test", "test");
[...]
```
I need to put this kind of code in a webservice, but I cannot reuse the connection because the webservice can connect to multiple dbs.
Please note that the above snipped is working with SQLite and many other JDBC drivers.
Please help.

**Comment by Baoqi** [comment]
Hi, alitaker,
   Yes, currently you can only use DriverManager to get one writable connection in one process. But once you get the first connection, you can cast it to DuckDBConnection, and call the "duplicate" to get additional connections.

Or, you can open multiple readonly connections in many processes.   (By call DuckDBDatabase's constructor. DuckDBDatabase(String url, boolean read_only) with read_only as true). 

Hope this can help

> If I try to reopen a connection in Java I get the error:
> `IO Error: Cannot open file "C:\Temp\duckdb_test.wal": Impossibile accedere al file. Il file è utilizzato da un altro processo.`
> 
> Here is a sample code:
> 
> ```
> Connection con;
> Class loaded = Class.forName("org.duckdb.DuckDBDriver");
> con = DriverManager.getConnection("jdbc:duckdb:C:\\Temp\\duckdb_test", "test", "test");
> ResultSet rs = con.createStatement().executeQuery("SELECT * FROM weather;");
> rs.close();
> con.close();
> con = DriverManager.getConnection("jdbc:duckdb:C:\\Temp\\duckdb_test", "test", "test");
> [...]
> ```
> 
> I need to put this kind of code in a webservice, but I cannot reuse the connection because the webservice can connect to multiple dbs.
> Please note that the above snipped is working with SQLite and many other JDBC drivers.
> Please help.

**Comment by k138z** [comment]
Hello, I have a use case just like the original reporter. I currently am not able to open a single read-write connection, execute queries, call Connection.close() and open subsequent read-only connections. However, I _am_ able to open multiple read-write connections (with DuckDBConnection.duplicate()) and multiple read-only connections with the regular JDBC API. Is this a genuine issue or is this a bad access pattern on my end?
