### ISSUE TITLE
No source option on pypi

### ISSUE THREAD

**Issue by zenazn** [cwida/duckdb#1383]
My "actual" problem:
```
~$ pip3 install duckdb==0.2.4
ERROR: Could not find a version that satisfies the requirement duckdb==0.2.4
ERROR: No matching distribution found for duckdb==0.2.4
```

I'm on an Apple Silicon Mac (pip 21.0.1, python 3.9.1), so would need a `macosx_..._arm64` wheel. Unfortunately, I don't think pypi supports these, so I'm forced to install ~all python packages from source. The most recent duckdb version I'm able to install in this way is 0.2.2, which installs successfully.

Many projects offer install-from-source options in addition to wheels (see [numpy](https://pypi.org/project/numpy/#files) for instance). It appears [duckdb doesn't offer this](https://pypi.org/project/duckdb/#files) for 0.2.4. Is this an accidental oversight? Or is there a good reason to not offer this installation option?

**Comment by hannesmuehleisen** [comment]
This is not intentional and should be fixed

**Comment by hannesmuehleisen** [comment]
Next release will have sources again. In the meantime, you can try `pip install duckdb --pre`

**Comment by zenazn** [comment]
Thank you!
