### ISSUE TITLE
Function request: split_part

### ISSUE THREAD

**Issue by zenazn** [cwida/duckdb#1384]
I'm using duckdb 0.2.4, and have read the documentation on [text functions](https://duckdb.org/docs/sql/functions/char).

I tried to use `string_split`, but didn't find it very helpful in the queries I was writing. The return type is a `list<varchar>`, but unfortunately there aren't functions that act on lists, and I wasn't able to find any list-indexing functionality (I tried square brackets). As far as I was able to tell, the only operation I could perform on a list was `UNNEST`, which could probably be used to make my queries work, but would make them significantly more confusing.

A function I find very easy to use in a different SQL dialect is Postgres' `split_part` ([docs](https://www.postgresql.org/docs/9.1/functions-string.html)). The third parameter allows me to specify which segment of the split string I'd like to retain, which is perfect for my use case.

Is `split_part` (or something equivalent) a function you folks would be willing to add to duckdb? I'm happy to help in whatever way I can assuming it's something the maintainers are excited about.

**Comment by hannesmuehleisen** [comment]
I think adding list indexing functionality would be the cleanest solution here.

**Comment by hannesmuehleisen** [comment]
See #1385

**Comment by zenazn** [comment]
That looks like it'll work really well too! Thank you!

**Comment by hannesmuehleisen** [comment]
To elaborate, this now works: `SELECT LIST_ELEMENT(STRING_SPLIT('a,b,c', ','), 2);`

**Comment by aitskovi** [comment]
@hannesmuehleisen Thank you for jumping on this so quick! Any chance you all are going to release a new official version (e.g. 0.2.5) with that soon?
