### ISSUE TITLE
Wrong behavior when including a filter field in the select over a parquet file view

### ISSUE THREAD

**Issue by visar-elmazi-allocate** [cwida/duckdb#1391]
I have a parquet file with the following layout:

ORGUNITID: int64
VALIDFROM: string
VALIDTO: string
ORGUNITNAME: string
**NAMEVALIDFROM: string
NAMEVALIDTO: string**
PARENTID: int64
PARENTNAME: string
PARENTNAMEVALIDFROM: string
PARENTNAMEVALIDTO: string
LEVELID: int64
LEVELNAME: string
PARENTLEVELID: int64
PARENTLEVELNAME: string
ORGSTRUCTVALIDFROM: string
ORGSTRUCTVALIDTO: string
PARENTORGSTRUCTVALIDFROM: string
PARENTORGSTRUCTVALIDTO: string
CUSTOMERCODE: string

The fields VALIDFROM and VALIDTO range from '1900-01-01' to '9999-31-12'. 

In python I create a view of the parquet file:

c = duckdb.connect()
c.execute(f"CREATE VIEW tbl AS SELECT * FROM parquet_scan('table.parquet');")

If I select all fields everything works fine, 

sql = '''
    SELECT * from tbl
    where Namevalidfrom <=  '2017-03-01'
    AND Namevalidto >=  '2017-03-01'
    AND Parentnamevalidfrom <=  '2017-03-01'
    AND Parentnamevalidto >=  '2017-03-01'
    AND Orgunitid IN  (.... numbers ...)
    AND Parentid in (... numbers ...)
    AND CustomerCode = 'code'        
'''
this returns an array of tuples which satisfy criteria

If I select any of these 2 fields alone or in combination with other fields, the response is empty array
NAMEVALIDFROM: string
NAMEVALIDTO: string

sql = '''
    SELECT **Namevalidfrom** from tbl
    where Namevalidfrom <=  '2017-03-01'
    AND Namevalidto >=  '2017-03-01'
    AND Parentnamevalidfrom <=  '2017-03-01'
    AND Parentnamevalidto >=  '2017-03-01'
    AND Orgunitid IN  (.... numbers ...)
    AND Parentid in (... numbers ...)
    AND CustomerCode = 'code'   
'''

^^^ this returns an empty array

Or even if select through a subquery:
sql = '''
    SELECT **Namevalidfrom**  from (
        select * from OrgUnitBridge 
    where Namevalidfrom <=  '2017-03-01'
    AND Namevalidto >=  '2017-03-01'
    AND Parentnamevalidfrom <=  '2017-03-01'
    AND Parentnamevalidto >=  '2017-03-01'
    AND Orgunitid IN  (.... numbers ...)
    AND Parentid in (... numbers ...)
    AND CustomerCode = 'code' ) t
'''
^^^ this returns an empty array

I have changed the data type in the parquet file for these 2 fields to both STRING and TIMESTAMP and I get the same behavior.

Using v.0.2.4 through Python in Ubuntu 20.
 
Here's a sample of the data:
[(10318, '1900-01-01 00:00:00.000', '9999-12-31 00:00:00.000', 'XYZ Admin', '1900-01-01 00:00:00.000', '9999-12-31 00:00:00.000', 10144, 'XYZ', '1900-01-01 00:00:00.000', '9999-12-31 00:00:00.000', 10005, 'unit', 10004, 'department', '2020-04-27 00:00:00.000', '9999-12-31 00:00:00.000', '1900-01-01 00:00:00.000', '2020-04-23 00:00:00.000', 'code')]

I have enabled logs PRAGMA but the file is empty.

**Comment by hannesmuehleisen** [comment]
Could you share a parquet file where you demonstrate the issue? It looks like a problem with selection pushdown.

**Comment by visar-elmazi-allocate** [comment]
The filtering is also involved somehow, take this query for example and comment out filter predicates.

    select Namevalidfrom from tbl 
    where Namevalidfrom <=  '2017-03-01' 
    AND Namevalidto >=  '2017-03-01'
    AND Parentnamevalidfrom <=  '2017-03-01'
    AND Parentnamevalidto >=  '2017-03-01'    
    AND CustomerCode = 'CODE' 

The sample attached.

[sample.zip](https://github.com/cwida/duckdb/files/5971585/sample.zip)

**Comment by hannesmuehleisen** [comment]
Thanks for sharing the file and query, looks like there is indeed a bug here (or wrong statistics).
