### ISSUE TITLE
Error: unable to open database

### ISSUE THREAD

**Issue by c5sire** [cwida/duckdb#1393]
Hello,
I am evaluating and get this notification when trying to use duckdb on a server where I do not have admin rights.
On Ubuntu:
./duckdb db/test.db

or from within duckdb:
.open db/test.db
result in this error.

On a laptop with admin rights no problems to use duckdb under Windows or Ubuntu.
On the server applied: 'chmod +x duckdb' & 'chmod -R 777 db' but still get the same message.

**Comment by hannesmuehleisen** [comment]
Does the test.db file already exist? Was it created with DuckDB or maybe SQLite?

**Comment by c5sire** [comment]
No - trying to create an empty database with duckdb.
It creates an empty file.

**Comment by hannesmuehleisen** [comment]
Something strange is going on there since we of course test this in our CI. Does this work on other computers, other folders, folders owned by you on the same machine etc?

**Comment by c5sire** [comment]
It works on my laptop nicely.
Will try on other folders, too.
Meanwhile, I also installed duckdb via R on the server. However get a similar response:

> library(duckdb)
Loading required package: DBI
> library("DBI")
> con = dbConnect(duckdb::duckdb(), ":memory:")
> dbWriteTable(con, "iris", iris)
> dbGetQuery(con, 'SELECT "Species", MIN("Sepal.Width") FROM iris GROUP BY "Species"')
     Species min(Sepal.Width)
1     setosa              2.3
2 versicolor              2.0
3  virginica              2.2
> con = dbConnect(duckdb::duckdb(), "test.ddb")
Error in initialize(value, ...) :
  duckdb_startup_R: Failed to open database
>

**Comment by hannesmuehleisen** [comment]
Could you somehow try to make this reproducible? E.g. run this on a clean ubuntu install in a VM or so and demonstrate the steps required to reproduce the issue?

**Comment by c5sire** [comment]
Works on another mount on the server! Thanks for the pointer.
