### ISSUE TITLE
What is the maximum size of DuckDB ?

### ISSUE THREAD

**Issue by ramkumarkb** [cwida/duckdb#1394]
From the docs of Sqlite, it is mentioned that the maximum size is about 281 TB - http://www.sqlite.org/releaselog/3_33_0.html

I am interested to know if any specific benchmarks have been done around the maximum size that DuckDB could support?

And thank you for this very interesting project!

**Comment by Mytherin** [comment]
We are still actively revamping the storage, so such a calculation is still very subject to change. Currently blocks are 256KB, and block pointers are 64-bits, so this works out to around 4194304000 PB. We have discussed changing block pointers to 48-bits, which would limit database size to 64000PB. In any case, it should be more than sufficient.

**Comment by ramkumarkb** [comment]
This is incredible ! Thanks for the reply. I will try to give a PR to add this information in the website.
