### ISSUE TITLE
Java example from installation doc should use executeQuery instead of execute

### ISSUE THREAD

**Issue by 2beers** [cwida/duckdb#1399]
Cool database I just found about it, and I started to play and see if I can embedded in my java app.

The example code give in the java installation page: https://duckdb.org/docs/installation/ is wrong though. 

`ResultSet rs = stmt.execute("SELECT 42");`   stmt.execute returns boolean

proper use will be `ResultSet rs = stmt.executeQuery("SELECT 42");` which returns `ResultSet` 

Hope you fix it.

Cheers and keep up the good work

**Comment by hannesmuehleisen** [comment]
Good catch, thanks
