### ISSUE TITLE
Pandas strings

### ISSUE THREAD

**Issue by zenazn** [cwida/duckdb#1401]
It appears duckdb doesn't recognize the (newish) [Pandas string dtype](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html). Instead, duckdb only recognizes `object`, which it fervently hopes is a string:

https://github.com/cwida/duckdb/blob/5cb93caedd7ce9c5923e709f20078beed96d9b4c/tools/pythonpkg/duckdb_python.cpp#L738-L739

I think replacing `col_type == "object"` with `col_type == "object" || col_type == "string"` will work just fine!

For completeness, the text of the error I'm seeing is: `RuntimeError: unsupported python type string`. I'm running duckdb 0.2.4 and pandas 1.0.5

**Comment by zenazn** [comment]
I almost forgot! Here's a short reproducer:

``` python
import pandas as pd
import duckdb

df = pd.DataFrame({'a': pd.Series(['x', 'y', 'z'], dtype='string')})

con = duckdb.connect(database=':memory:', read_only=False)
con.register('df', df)
```

**Comment by hannesmuehleisen** [comment]
Can you send a PR with this change and a test please?

**Comment by zenazn** [comment]
Sorry for the delay—done!
