### ISSUE TITLE
Multithreading access

### ISSUE THREAD

**Issue by TheGiamig** [cwida/duckdb#1402]
Hi, in a read only scenario, can I access the DB from multiple threads?
If yes, the right way is using a different `Connection` object for each thread?
Thanks

**Comment by Mytherin** [comment]
Yes, this is supported. If you want to use the system from multiple threads it is recommended that each thread have their own connection object. While it is safe to use a single connection object from multiple threads, internally it uses a lock and will therefore not allow for actual concurrent operations on the system.
