### ISSUE TITLE
c: bind_blob, value_blob, bind_varchar, appender

### ISSUE THREAD

**Issue by lithdew** [cwida/duckdb#1407]
Just wanted to say beforehand, DuckDB is incredible: its performance is more than satisfactory for my use case. I'm building replication algorithms and have been experimenting with DuckDB as a backend. Tweeted a tiny artificial benchmark I did here: https://twitter.com/lithdew/status/1361700795645759489

I wanted to request some additional methods/changes to the C API:

<hr/>

##### `duckdb_bind_blob(duckdb_prepared_statement, idx_t, const void *, int)`

Binds a blob to a column within a prepared statement. Unlike `duckdb_bind_varchar`, it will not validate that the value only comprises of UTF-8 bytes. The last int argument represents the length of the value `const void *`.

#### `const void *duckdb_value_blob(duckdb_result *result, idx_t col, idx_t row);`

Fetches a blob from a result set column.

#### `duckdb_bind_varchar(duckdb_prepared_statement, idx_t, const char *, int)`

Binds a text value to a column within a prepared statement. The last int argument represents the length of the value `const char *`. This is a breaking change to allow for simpler language bindings where not all strings are suffixed with a null terminator.

<hr/>

Apart from these changes, I also wanted to ask about there being the possibility of exposing the `Appender` C++ API to the C bindings. From what I skimmed online, the rationale for not exposing the `Appender` to other languages is because of implicit memory allocations these languages require performing to prepare data before it gets batched into DuckDB.

Though in the case of C, the `Appender` interface should be suitable since allocations are left up to the user.

**Comment by Mytherin** [comment]
Glad to see you are enjoying DuckDB! I think all the changes you have proposed are more than sensible. Since I was doing something on the C API anyway I implemented the changes you suggested in #1408. 

Exposing the Appender from the C API is certainly possible as well. Happy to review a PR if you want to have a go at it :) Otherwise we might get to it later on.

**Comment by hannesmuehleisen** [comment]
Moved the appender part to #1409 and closing here
