### ISSUE TITLE
Exponential format casting

### ISSUE THREAD

**Issue by barryrowlingson** [cwida/duckdb#1415]
Surprised to find my CSV with ID values like "E41000051" were being read by read_csv_auto as -2147483648.

What seems to be happening is that strings like that can be CAST to integer without a warning:

```
 select cast('E99999' as integer);
┌───────────────────────┐
│ CAST[INTEGER](E99999) │
├───────────────────────┤
│ -2147483648           │
└───────────────────────┘
```

and so the CSV gets a column of those values. 

Figured this might have something to do with exponential notation (eg where "2E3" = 2000). The sqlite3 numeric literal syntax diagram:

 https://sqlite.org/syntax/numeric-literal.html

shows it MUST have something before the E or its invalid, and SQLite does cast these strings to zero (as it seems to do with clearly non-numeric format strings). I can't find a syntax diagram for a numeric literal for duckdb though.

Although duckdb casts 'E1' to integer as 0, it raises a conversion error when converting to numeric (decimal(18,3)). Not sure what's going on there.

I've put together a quick test set with most of the possibilities I can think of, and run on duckdb and sqlite for comparison. Attached is a zip with the test SQL and outputs.

The problem at the moment is I don't know what the correct returned values for these cast operations should be - I'm guessing that "the documentation is the code" at the moment, but I'm also not sure if you are aiming for compatibility with any other SQL dialect.

For now I'll continue experimenting with duckdb but reading my CSVs as all varchars!

Thanks

[parse_E.zip](https://github.com/cwida/duckdb/files/6004077/parse_E.zip)

**Comment by Mytherin** [comment]
Thanks for the report! I completely agree that the scientific notation should fail to parse without a number preceding the E in strict mode. The fact that 'E9999' is parsed as an integer seems like a bug - this should trigger an overflow error similar to how e.g. `cast('10000000000000' as integer);` triggers an overflow. I will investigate.
