### ISSUE TITLE
indexing strsplit

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#1418]
I don't know if this is the right place, but I noticed that the split functions form lists. So, I want to do something like

```{r}

 dbGetQuery("select str_split(country_zip,'/')[0] as country,str_split(country_zip,'/')[1] as zip from table

```

As far as I can tell there's no way to access list values. I tried variants of the normal [1] (1) .[1] syntax to not avail. This would be super useful.

**Comment by Mause** [comment]
`LIST_EXTRACT` was just added and is available in master: https://github.com/cwida/duckdb/pull/1385

**Comment by alanpaulkwan** [comment]
@Mause Amazing timing by the PR...
