### ISSUE TITLE
Closing DB with control-d does not flush the WAL

### ISSUE THREAD

**Issue by rafelafrance** [cwida/duckdb#1434]
If I do the following: (I close the DB with a ctrl-d)
```
$ ls
$ duckdb test.db
v0.2.4 d1b02c270
Enter ".help" for usage hints.
D create table aa (field int);
D pragma show_tables;
┌──────┐
│ name │
├──────┤
│ aa   │
└──────┘
D 
$ ls
test.db  test.db.wal
```

If I `.exit` duckdb, the WAL is flushed.

OS: Pop!_OS 20.10 x86_64 (an Ubuntu variant)
duckdb is pip installed

Edit: Hijacking my own issue
A little python script with the same issue.
```python
import duckdb
cxn = duckdb.connect('ducky.db')
cxn.execute('CREATE TABLE junk (data INT)')
cxn.close()
```
Also does not flush the WAL.

**Comment by hannesmuehleisen** [comment]
This should be fixed in the `master` branch, can you try there?

**Comment by rafelafrance** [comment]
Both work as expected with the master branch.

This isn't a problem -- Well for me it's not. -- just something to note. v2.5 DBs do not seem to work with a v2.4 CLI.
