### ISSUE TITLE
Exact QUANTILE should accept constant LISTs as the second argument

### ISSUE THREAD

**Issue by hawkfish** [cwida/duckdb#1453]
The current implementation of `QUANTILE ` requires a second constant argument in the range `[0.0, 1.0]` and computes the corresponding quantile by accumulating all the values and calling `std::nth_element` on the result. This means that computing quartiles could store four copies of the data; computing deciles would store 10 copies and so on.

A simple fix for this would be to allow the argument to be a `LIST` of constant values and have the function return a list of the values. Not only would this allow the values to be accumulated only once, but the successive calls to `std::nth_element` would be faster as the data would have been partially ordered.

**Comment by hannesmuehleisen** [comment]
We were also thinking to have an optimizer that recaps multiple quantile calls to the list version

**Comment by hannesmuehleisen** [comment]
Also the return type of this function when called with a list should then be a strict, right?

**Comment by hawkfish** [comment]
I was thinking it would be another `LIST`. After all, the values all have the same type, the input is also a list and I'm not sure what the keys to the `STRUCT` would be given that there could be duplicates (from machine generated queries) aliasing (from floating point rounding) and other issues. Plus it just seems more natural to return a `LIST` when given a `LIST`

**Comment by hawkfish** [comment]
Merged.
