### ISSUE TITLE
  unable to find an inherited method for function dbWriteTable

### ISSUE THREAD

**Issue by verajosemanuel** [cwida/duckdb#1463]
Latest version.
R code
```

DBI::dbWriteTable(con,"myData",df)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'dbWriteTable' for signature '"duckdb_connection", "character", "spec_tbl_df"'
```

**Comment by hannesmuehleisen** [comment]
try `DBI::dbWriteTable(con,"myData",as.data.frame(df))`, the error says that df is not a `data.frame` but a `spec_tbl_df`

**Comment by verajosemanuel** [comment]
worked, but I a little confused as this was inside a working script with no issue for months.....

thanks anyway
