### ISSUE TITLE
Regex search/replace

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#147]
Support regex-based string search and manipulation. Ship PCRE?

**Comment by hannesmuehleisen** [comment]
Will ship RE2 instead of PCRE

**Comment by arjenpdevries** [comment]
https://github.com/google/re2 right?

**Comment by hannesmuehleisen** [comment]
yes that one

**Comment by hannesmuehleisen** [comment]
This lives in the re2 branch which should work in principle. REGEXP_MATCH and REGEXP_REPLACE are implemented postgres-style

**Comment by aris-koning** [comment]
Why do you prefer RE2 over PCRE?

**Comment by hannesmuehleisen** [comment]
For regex search we also implemented an extra goodie: The regex library can compute upper and lower bounds (lexicographic) of strings the regex could possibly match on. So we use that to push a range filter under the regex op to avoid running the regex on strings that cannot match anyway. 

For example, 

```SQL
CREATE TABLE regex(s STRING);
INSERT INTO regex VALUES ('asdf'), ('xxxx'), ('aaaa');
SELECT s FROM regex WHERE REGEXP_MATCHES(s, 'as[a-z]f'); 
```
The execution plan for this query is (after optimisation)
````
FILTER[regexp_matches(s, as[a-z]f)]
    FILTER[s>=asaf AND s<=aszf]
        GET(regex)
````

**Comment by hannesmuehleisen** [comment]
@aris-koning Far more modern and better than PCRE, e.g. "[RE2] is based on automata theory and guarantees that searches complete in linear time with respect to the size of the input and in a fixed amount of stack space."
