### ISSUE TITLE
Remove ChunkCollection from LIST type

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#1470]
Currently, `LIST` vectors contain a `ChunkCollection` with a single column that contains the list values. Now (since #1416) that the null mask and vectors can be of arbitrary length, the Chunk Collection should be removed there. This will also improve compatibility with Arrow & others.

Maybe something for @pdet

**Comment by pdet** [comment]
Sounds good. Feel free to assign me :-)

**Comment by pdet** [comment]
Yes, I guess it can be closed
