### ISSUE TITLE
std::vector template data type

### ISSUE THREAD

**Issue by chilarai** [cwida/duckdb#1471]
Hi, is there a way to use my own data type (like std::string) in place of `<duckdb::Value>`  and converting it later using a loop here? Is there is a better way available?
`std::vector<duckdb::Value> stdData = result->collection.GetRow(i)`

**Comment by hannesmuehleisen** [comment]
I am not sure I understand what you are trying to do. Are you trying to not use the `Value` class to retrieve values? That can be achieved by `switch`ing on the column types. Otherwise, please clarify.

**Comment by chilarai** [comment]
Thanks I understand now.  Pardon my bad explanation
