### ISSUE TITLE
Compilation termination

### ISSUE THREAD

**Issue by MarcoFelipeKing** [cwida/duckdb#1474]
I am trying to compile the code on ubuntu 20.10 using:

`install.packages("https://github.com/cwida/duckdb/releases/download/master-builds/duckdb_r_src.tar.gz", repos = NULL)`

I've tried two separate clean R installs and both give the following error:

```
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [/usr/lib/R/etc/Makeconf:176: duckdb/amalgamation-1.o] Error 1
```

**Comment by hannesmuehleisen** [comment]
how much RAM does the machine have that you are doing this on?

**Comment by hannesmuehleisen** [comment]
See also https://stackoverflow.com/questions/66529271/duckdb-wont-compile-on-free-aws-ec2-instance-are-precompiled-packages-the-solu , will see whether we can fix this.

**Comment by hannesmuehleisen** [comment]
Try this:

````R

local({
  if (!("renv" %in% loadedNamespaces())) {
    release <- system2("lsb_release", "-sc", stdout = TRUE)
    if (release != "") {
      options(
        repos=c(CRAN = paste0("https://packagemanager.rstudio.com/all/__linux__/", release, "/latest")),
        HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os))
      )
    }
  }
})

install.packages("duckdb")
````
