### ISSUE TITLE
CREATE TEMP TABLE AS creates the table in the main schema

### ISSUE THREAD

**Issue by hawkfish** [cwida/duckdb#1485]
D create temp table lost as select * from range(0,5);
D select table_schema, table_name from information_schema_tables();
┌──────────────┬────────────┐
│ table_schema │ table_name │
├──────────────┼────────────┤
│ main         │ lost       │
└──────────────┴────────────┘
D

**Comment by hawkfish** [comment]
I'm a bit nervous about trying to fix this because I expect a lot of tests rely on this behaviour?

**Comment by hawkfish** [comment]
Tests all pass. `Transformer::TransformCreateTableAs` was just not setting `info->temporary`.

**Comment by Mytherin** [comment]
This should be fixed now right?

**Comment by hannesmuehleisen** [comment]
I believe so
