### ISSUE TITLE
Would it be useful to have Litestream-for-DuckDB?

### ISSUE THREAD

**Issue by ramkumarkb** [cwida/duckdb#1491]
Hi,

[Litesream](https://github.com/benbjohnson/litestream) is a new and exciting project for SQLite. The usecase is for replication of SQLite.

I was wondering whether it would make sense to have a duckdb `plugin` on Litestream (if Duckdb supports some kind of Change Data Capture APIs...).

Or since the usecase for DuckDB is for Analytics, would it be better to start-off from a fresh import into a new DB? (i.e. Replication is not really interesting for DuckDB).

Thank you,

**Comment by hannesmuehleisen** [comment]
Replication of changes is not something we have really considered yet. There is no change capture API at the moment and indeed it seems a bit far off of our envisioned use cases for now. If there is enough interest we might reconsider, but closing this for now.

**Comment by adsharma** [comment]
https://github.com/duckdb/duckdb/discussions/17200 is a related discussion
