### ISSUE TITLE
Get all column data from db

### ISSUE THREAD

**Issue by barron1** [cwida/duckdb#1493]
Hello everyone, I need a little help here with the cpp API as I could not find any documentations regarding the same. I was looking to get all data from a specific column from my inmemory duck database but I couldn't seem to do so. 

Here is my duckdb inmemory books table
```
+-----------------------------------------------------------------+
|author           | category   | price   | title                  |
+-----------------------------------------------------------------+
|Nigel Rees       | reference  | 790     | Sayings of the Century |
+-----------------------------------------------------------------+
|Evelyn Waugh     | fiction    | 2000    | Sword of Honour        |
+-----------------------------------------------------------------+
|Herman Melville  | fiction    | 200     | Moby Dick              |
+-----------------------------------------------------------------+
|J. R. R. Tolkien | fiction    | 1000    | The Lord of the Rings  |
+-----------------------------------------------------------------+
|Abraham          | fiction    | 2121    |Book1                   |
+-----------------------------------------------------------------+
```
Currently this is how I am getting a column data which I dont think is the right way
```
auto result = duckCon->con.Query("SELECT * FROM books");
for(int i = 0; i < result->collection.Count(); i++){
    stdData = result->collection.GetRow(i);

    for(auto data: stdData){
        // Conditions to get from particular column
    }
}
```

Now, if I print this, it shows columnar data
```
result->collection.Print();
```

How do I get the all data from a particular column, lets say price column?

**Comment by Alex-Monahan** [comment]
Howdy!
The trick is to modify the string parameter to .Query(). DuckDB uses SQL (Structured Query Language) for manipulating data, and that string is a SQL statement. The * in that string stands for all columns. Just use "Select price from books" instead!

**Comment by barron1** [comment]
Thanks @Alex-Monahan. Also is there any method available to get the column data into a vector?

`stdData = result->collection.GetRow(i);` returns only a row data into vector form. But is there any specific method available which does the same for column?

**Comment by hannesmuehleisen** [comment]
Yes, you call `result->Fetch()` which returns a `DataChunk` which contains columns. You will have to repeat calling `Fetch()` until it returns a `nullptr` at which point the query is done.

**Comment by barron1** [comment]
Thanks
