### ISSUE TITLE
duckdb_bind_uint32 declaration wrong

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [cwida/duckdb#1506]
This is original function declaration in 0.25:

DUCKDB_API duckdb_state duckdb_bind_uint32(duckdb_prepared_statement prepared_statement, idx_t param_idx, int32_t val);
DUCKDB_API duckdb_state duckdb_bind_uint64(duckdb_prepared_statement prepared_statement, idx_t param_idx, int64_t val);

Please note the declaration in the cpp file uses unsigned integers, which should be correct.

So we have it changed here to uint32_t and uint64_t to link our project.

**Comment by hannesmuehleisen** [comment]
Thanks for spotting, can you send a PR that fixes this?

**Comment by MonkeybreadSoftware** [comment]
Done:
https://github.com/cwida/duckdb/pull/1508
