### ISSUE TITLE
.schema fails on basic test in CLI

### ISSUE THREAD

**Issue by rfmeraz** [cwida/duckdb#1507]
this should recreate the error and show that otherwise the basics in the CLI work:

D create table test (a int, b varchar);
D insert into test values (1, 'hello');
D .mode json
D select * from test;
[{"a":1,"b":"hello"}]
D .schema test
Error: Parser Error: subquery in FROM must have an alias
LINE 1: SELECT sql FROM(SELECT shell_add_schema(sql,NUL...

**Comment by Mytherin** [comment]
Thanks for the report, I have implemented .schema now in #1517.
