### ISSUE TITLE
[R] Temporary table in read-only mode

### ISSUE THREAD

**Issue by mllg** [cwida/duckdb#1509]
The behavior regarding temporary tables for read-only connections seems to have changed in the last CRAN  release. AFAICT this worked before duckdb-0.2.5:

```r
path = tempfile()

# create empty database
con = DBI::dbConnect(duckdb::duckdb(), dbdir = path, read_only = FALSE)
DBI::dbDisconnect(con, shutdown = TRUE)

# reopen database read-only, try to write temp table
con = DBI::dbConnect(duckdb::duckdb(), dbdir = path, read_only = TRUE)
DBI::dbWriteTable(con, "test", data.frame(x = 1:10), temporary = TRUE)
```

And now errors with the following message:
```
Error: Catalog Error: Table with name _duckdb_append_view_yoftplrmov does not exist!
LINE 1: INSERT INTO "test" SELECT * FROM _duckdb_append_view_yoftplrmov
```

Is this intended?

**Comment by hannesmuehleisen** [comment]
It would seem that you should be able to create temp tables in read only mode. Indeed its possible something changed there.

**Comment by hannesmuehleisen** [comment]
There is indeed a bug here. The relation API the R extension used to create a temporary view to append to the temporary table failed to create in read only mode. There was another issue where that error failed to bubble up. Will fix. Thanks for reporting!

**Comment by hannesmuehleisen** [comment]
@mllg this should be fixed in the `master` branch. Can you confirm this?

**Comment by mllg** [comment]
Confirmed. Thanks!

**Comment by mllg** [comment]
I don't want to be pushy, but will there be a fixed version on CRAN soon?

**Comment by hannesmuehleisen** [comment]
Yes, we should have a release this week. Not sure how long it takes to get on CRAN.
