### ISSUE TITLE
parquet file with hundreds of thousands of row groups crashes parquet_scan

### ISSUE THREAD

**Issue by Prussian1870** [cwida/duckdb#1519]
Hi all:

I'm working with python duckdb version 2.4.0 on windows 10.

I have a 5 gig parquet file with 317,000 row groups. When I create a view based on the file(see below) it never returns. Note that PyArrow is able to read the file.

CREATE VIEW jsonlogfile AS select * from parquet_scan('c:/working/testing/json.parquet')

Is there a limit to the number of row groups?

**Comment by hannesmuehleisen** [comment]
Can you share that file please? In principle there is no limit to the number of row groups.

**Comment by Prussian1870** [comment]
I can't because the file is 5 gig. There is a 10mb limit on github

**Comment by hannesmuehleisen** [comment]
You can use wetransfer to hannes@cwi.nl

**Comment by Prussian1870** [comment]
wetransfer only took 2gig. So I made a new file and sent it to you.

After looking at it again the problem is not with the row groups but the json column which contains a gig or more of text data split over 164284 rows.

Would there be a limitation on the quantity of text in a single column?

**Comment by hannesmuehleisen** [comment]
Thanks for sending the file. There is also no limitation on the amount of text.

**Comment by hannesmuehleisen** [comment]
Indeed this spends a lot of time decoding thrift, but eventually finishes for me. What exact query did you run?

**Comment by Prussian1870** [comment]
Yep that worked.
Feel free to close the issue.
