### ISSUE TITLE
Terminal interaction and use of ctrl-left ctrl-right ctrl-c

### ISSUE THREAD

**Issue by skinkie** [cwida/duckdb#1523]
Using longer queries in the CLI DuckDB scrolls horizontally, opposed to other databases that allow for multiline interaction. I guess this is a matter of taste, but in this way it is impossible to copy the query. While it is possible to use ctrl-a and ctrl-e work to go to the start or the end of the line, using ctrl-arrowleft or ctrl-arrowleft do not skip entire words, this would make interaction more easy. In addition I would expect ctrl-c just to skip the current query, not to terminate the process.

**Comment by Mytherin** [comment]
Have had a go at fixing this in #1550.

**Comment by hannesmuehleisen** [comment]
Should be fixed. @skinkie can you confirm please?

**Comment by skinkie** [comment]
@hannesmuehleisen @Mytherin thanks, this behaves very elegantly!
