### ISSUE TITLE
Parquet reader glob pattern traversing the "whole" path?

### ISSUE THREAD

**Issue by dforsber** [cwida/duckdb#1529]
I came across a quite interesting 100x slow down on DuckDB query that relates to Parquet reading glob pattern. I'm guessing, but due to the fact that AWS EFS directory listing is really slow (thus 100x slower query!), I think I hit this caveat with DuckDB Parquet glob pattern that runs the file listing.

It turned out that when I give full path glob pattern for `parquet_scan()` it probably lists the folder from the root of it, not from the point where the glob starts?

When reverting back to the case where the "globbing" is done outside DuckDB and using `UNION ALL`, I got back the normal performance again. This requires using `VIEW` to make it a general pattern, which is ok. [we need to give full paths as the paths may vary and can't just change working dir and have "local" dir glob pattern.]

I guess, DuckDB could also do similar thing - i.e. only run `readdir()`, possibly recursive, starting from the path where the first wildcards/lists occur - in order to minimise the latency for listing a lot files that would not essentially match with the filter. Anyway, this sounds a bit complex to implement in a general fashion, so maybe just knowing this caveat is enough (maybe add into docs). This was a bit tricky to find out and caused  due to the massive performance downgrade. 

The upside is that performance testing is many times good to do in a "slow system" to get the bottle necks visible. Thus, even with a local SSD filesystem, I guess listing huge directories would still impose some performance hits.

All this said, I'm not sure how DuckDB does the glob pattern listing at the moment, but tests seem to hint this way as described above :).

**Comment by Mytherin** [comment]
Thanks for the report!

The globbing code is [here](https://github.com/cwida/duckdb/blob/27ec51f2ab66ae0c70e6efcb49827087efcc6282/src/common/file_system.cpp#L745). The globbing should only run the directory listing for entries that have a glob in them. So e.g. for the following query the list dir is only called once:

```sql
SELECT * FROM parquet_scan('/path/to/my/file/*.parquet');
```

However, if you have multiple globs in your expression, paths are expanded incrementally. So, if you have the following query, the directory listing will be called N+1 times, where N is the amount of directories in the `/path/to/my` directory.

```sql
SELECT * FROM parquet_scan('/path/to/my/*/*.parquet');
```

Perhaps the code for [ListFiles](https://github.com/cwida/duckdb/blob/27ec51f2ab66ae0c70e6efcb49827087efcc6282/src/common/file_system.cpp#L289) is to blame here? Although a 100X seems strange to me.

**Comment by dforsber** [comment]
Thank you! 👍🏻 

I think we are still using a quite old version still (didn't realise that when I opened the ticket).
So the latest version doesn't sound like it would have this issue (we only used lowest level `filename.*parquet`).

Yes, that directory listing is amazon specific weirdness on the EFS, not on DuckDB side. But yes, it is literally like 13s vs 100ms :). I.e. once the glob is resolved, DuckDB starts to run the query and completes in no time. DuckDB is awesome.

So, I'm closing this, all good.

**Comment by dforsber** [comment]
Now, I know what the issue was. We had pattern in the form of `/full/path/.*parquet`. This matches both `.` and `..` directories, which means DuckDB probably lists `..` as well. And in our case the parent dir had quite many entries and is thus slow to list (on EFS).

**Comment by Mytherin** [comment]
Are you sure this is the problem? The [ListFiles has code to explicitly ignore the "." and ".." directories](https://github.com/cwida/duckdb/blob/27ec51f2ab66ae0c70e6efcb49827087efcc6282/src/common/file_system.cpp#L303). `.*parquet` also should not match `.` or `..` (since it requires `parquet` to be at the end). Perhaps these special directory markers are called differently on EFS?

**Comment by dforsber** [comment]
> Are you sure this is the problem? The [ListFiles has code to explicitly ignore the "." and ".." directories](https://github.com/cwida/duckdb/blob/27ec51f2ab66ae0c70e6efcb49827087efcc6282/src/common/file_system.cpp#L303). `.*parquet` also should not match `.` or `..` (since it requires `parquet` to be at the end). Perhaps these special directory markers are called differently on EFS?

Yes, the code looks very good actually! I will test this again with v0.2.5 and try to get to the bottom of this.

**Comment by igorbb** [comment]
Is there anyway to get recursive directory traversing ?

In the cases where the number of directories is to large to be replicating alll `/*/*` ?

```
SELECT * FROM parquet_scan('/path/to/my/file/**/*.parquet');
````
Or is there an option for us to provide the list of files without relying on Union ALL?
Since, one can get the list of files using glob & python
```
parquet_files = glob(f"path/to/data/**/*.parquet", recursive=True)
```
