### ISSUE TITLE
Window clause is ignored by the parser

### ISSUE THREAD

**Issue by hawkfish** [cwida/duckdb#1535]
The test in `test/sql/parallelism/intraquery/test_over_grouping.test_slow` uses a `WINDOW` clause to generate shared partitions but the resulting window functions have no`OVER` parameters.

**Comment by hawkfish** [comment]
Looks like `Transformer::TransformFuncCall` is looking for the `name` (which is used by the `WINDOW` clause to _define_ the window specification) instead of the `refname` (which is the name of the _referenced_ window specification).

**Comment by hawkfish** [comment]
The problem is more subtle than I originally believed... There are two syntaxes, which should do the same thing but don't:

```sql
select sum(x) over w as shared, sum(x) over (w) as refined from table window w as (...)
```
The first sets the `name` and is intended for reuse. The second sets `rename` and is intended to be used as a starting point for refining the `WINDOW` clause definition.  The bug is that the second appears to be a NOP at the moment.

**Comment by hawkfish** [comment]
According to `parsenodes.hpp`:

```cpp
/*
 * PGWindowDef - raw representation of WINDOW and OVER clauses
 *
 * For entries in a WINDOW list, "name" is the window name being defined.
 * For OVER clauses, we use "name" for the "OVER window" syntax, or "refname"
 * for the "OVER (window)" syntax, which is subtly different --- the latter
 * implies overriding the window frame clause.
 */
```

**Comment by hannesmuehleisen** [comment]
Super interesting find, never thought you could modify these things!

**Comment by hawkfish** [comment]
Yeah, neither did I. None of the vendor pages I looked at describe it either. I had to read the parser comments!
