### ISSUE TITLE
VectorOperations::Copy for LISTs grows buffers unnecessarily

### ISSUE THREAD

**Issue by hawkfish** [cwida/duckdb#1551]
I ran into this while testing #1367 with `LIST`s. 

The code for `VectorOperations::Copy` simply concatenates the two buffers and does some offset arithmetic. This is very wasteful when the caller is concatenating a small number of values through a selection vector.  It is also not the way strings work, which seems inconsistent.

**Comment by hannesmuehleisen** [comment]
@pdet can you have a look at this please?

**Comment by pdet** [comment]
Happy to, I can see there are already some commits from @hawkfish referencing this issue though.

@hawkfish what's your status on it? If you like I can try to build on top of what you doing.

**Comment by hawkfish** [comment]
@pdet my status is it is ready to go.

**Comment by hawkfish** [comment]
I can just make a pull request for `hawkfish-copy-list`?

**Comment by hawkfish** [comment]
I'll check whether `STRUCT` has the same issue.

**Comment by hawkfish** [comment]
`STRUCT` doesn't have any problems.
