### ISSUE TITLE
Copy queries and multiline history 

### ISSUE THREAD

**Issue by skinkie** [cwida/duckdb#1553]
At this moment I fail to see what would be a quick way to copy a query (other than using .duckdb_history). I have also tried going multi line, to make it visually more attractive. The downside of multi line queries within duckdb are that is it not possible to go to the previous line, not is it possible to go back in history to the entire query (only line by line).

I would be nice if the query history could be considered until ";" or as a single execution block. Then it is up to the user if the horizontal scrolling is appreciated. Alternatively a way to disable this behavior and allow wrapping could be an alternative.

**Comment by Mytherin** [comment]
Had a brief look at this and [linenoise does support a multi-line mode which enables wrapping](https://github.com/cwida/duckdb/blob/3678bd652fea3ad19d4b8bc17a2c588366b9c30c/tools/shell/linenoise.cpp#L135), however, this needs to be extended for proper unicode support as well as syntax highlighting.
