### ISSUE TITLE
SQL parser not white-space / text-formatting/layout oblivious

### ISSUE THREAD

**Issue by drstmane** [cwida/duckdb#1555]
========
$ ../duckdb/build/release/duckdb --version
--------
v0.2.5 f480a3293
========
$ cat x.sql
--------
select 1.0 / 2.0;
========
$ cat x.sql | ../duckdb/build/release/duckdb 
--------
┌───────────┐
│ 1.0 / 2.0 │
├───────────┤
│ 0.5       │
└───────────┘
========
$ ../duckdb/build/release/duckdb < x.sql 
--------
┌───────────┐
│ 1.0 / 2.0 │
├───────────┤
│ 0.5       │
└───────────┘
========
$ cat y.sql
--------
select
1.0
/
2.0
;
========
$ cat y.sql | ../duckdb/build/release/duckdb 
--------
┌─────┐
│ 1.0 │
├─────┤
│ 1.0 │
└─────┘
Error: near line 4: Parser Error: syntax error at or near "2.0"
LINE 1: 2.0
        ^
========
$ ../duckdb/build/release/duckdb < y.sql 
--------
┌─────┐
│ 1.0 │
├─────┤
│ 1.0 │
└─────┘
Error: near line 4: Parser Error: syntax error at or near "2.0"
LINE 1: 2.0
        ^
========

**Comment by drstmane** [comment]
$ ../duckdb/build/release/duckdb x.DB 'select 1.0 / 2.0;'
┌───────────┐
│ 1.0 / 2.0 │
├───────────┤
│ 0.5       │
└───────────┘

$ ../duckdb/build/release/duckdb x.DB '
select
1.0
/
2.0
;
'
┌───────────┐
│ 1.0 / 2.0 │
├───────────┤
│ 0.5       │
└───────────┘

**Comment by Mytherin** [comment]
Thanks for the report! I think this is related to the shell itself, not to the parser. I will have a look at fixing it.

**Comment by Mytherin** [comment]
This seems to be done on purpose in the SQLite shell. This is down to the SQLite shell accepting Oracle's "/" as a query terminator. This is the culprit:

```cpp
/*
** Return TRUE if the line typed in is an SQL command terminator other
** than a semi-colon.  The SQL Server style "go" command is understood
** as is the Oracle "/".
*/
static int line_is_command_terminator(const char *zLine){
  while( IsSpace(zLine[0]) ){ zLine++; };
  if( zLine[0]=='/' && _all_whitespace(&zLine[1]) ){
    return 1;  /* Oracle */
  }
  if( ToLower(zLine[0])=='g' && ToLower(zLine[1])=='o'
         && _all_whitespace(&zLine[2]) ){
    return 1;  /* SQL Server */
  }
  return 0;
}
```

So when typing 
```sql
SELECT 1
/
```

this is equivalent to typing

```sql
SELECT 1
;
```

I have removed this behavior in #1557 which should fix this issue.

**Comment by Mytherin** [comment]
This should be fixed now
