### ISSUE TITLE
Benchmark LIKE implementation vs REGEX and see if it is better to switch LIKE to regex

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#157]
Probably it is better if the LIKE expression is a constant; since the re2 regex implementation is very efficient.

The current LIKE expression likely (ha) performs better when a regex needs to be compiled for every string.

This should be benchmarked and potentially LIKE should be replaced by the regex implementation in certain/all scenarios.

**Comment by hannesmuehleisen** [comment]
For now I see the LIKE implementation being ca. 2x faster than RE2, using the existing `regexp_matches` function, which compiles the regex once...

**Comment by Mytherin** [comment]
That is quite a significant difference. I suppose with the compilation for every tuple it will still be slower but if that difference is not too big it might still make sense to entirely replace the current LIKE implementation with RE2 just for code simplicity and proper support for ILIKE. 

We can later add optimizations for specific cases like MonetDB has (e.g. 'X%', '%X%') if that turns out to be faster than just using RE2, but even that might not be the case as RE2 will probably handle these cases pretty elegantly as well. That should be benchmarked too.

**Comment by hannesmuehleisen** [comment]
I agree, we get ILIKE for free with RE2. I LIKE!

**Comment by taniabogatsch** [comment]
> We can later add optimizations for specific cases like MonetDB has (e.g. 'X%', '%X%') if that turns out to be faster than just using RE2, but even that might not be the case as RE2 will probably handle these cases pretty elegantly as well. That should be benchmarked too.

With `SF=2.5` I get:
```
H 11 :
0.14
l_shipinstruct LIKE 'DE%I%ER%'
~~(l_shipinstruct, DE%I%ER%)

H 12 :
0.9759999999999998
l_comment NOT LIKE '%str%'
!~~(l_comment, %str%)

H 13 :
0.834
l_shipinstruct SIMILAR TO 'DE.*I.*ER.*'
regexp_matches(l_shipinstruct, DE.*I.*ER.*)

H 14 :
1.248
l_comment NOT SIMILAR TO '.*str.*'
!(regexp_matches(l_comment, .*str.*))
```

**Comment by Mytherin** [comment]
I'm closing this issue, we did benchmarks and the result is that RE2 is slower than using specialized code here, so the conclusion is that we should stick with using specialized code for the LIKE statement.

**Comment by mbasmanova** [comment]
CC: @aditi-pandit @biswapesh
