### ISSUE TITLE
Ignore Byte Order Mark (BOM) characters while csv loading 

### ISSUE THREAD

**Issue by chilarai** [cwida/duckdb#1570]
Many CSV files contain BOM at the start of the file ( hidden characters provided at the start of a CSV file to indicate the encoding type of the file). Now if such a CSV file is used to create a table using the following command, the first column in the table is always prepended by this BOM character. eg `ï»¿ColumnName`

```
CREATE TABLE ontime AS SELECT * FROM read_csv_auto('test.csv');
```

Is there a way to ignore these characters while loading CSV files using the `read_csv_auto`  method? Sample CSV file attached
[People.zip](https://github.com/cwida/duckdb/files/6251859/People.zip)

**Comment by chilarai** [comment]
I have tried `CREATE TABLE ontime AS SELECT * FROM read_csv_auto('test.csv', ENCODING=UTF8);`. 
But, it throws `Binder Error: TABLE FUNCTION parameter cannot contain column names`. Also, ALL_VARCHAR=TRUE doesn't help
`

**Comment by hannesmuehleisen** [comment]
Indeed the sequence `0xEF,0xBB,0xBF` should just be ignored at the start of CSV files.

**Comment by hannesmuehleisen** [comment]
@tdoehmen can you have a look at this please?

**Comment by tdoehmen** [comment]
I made a PR (#1573) which should fix this. Note that there is not "ENCODING" parameter at the moment. CSV files are expected in UTF-8 and/or compatible character encodings.

**Comment by hannesmuehleisen** [comment]
should be fixed
