### ISSUE TITLE
ILIKE, case insensitive like

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#164]
```sql
 SELECT 'hello' ILIKE 'HELLO';
```

Also, sqlite has this pragma parameter we might want to support:

https://sqlite.org/pragma.html#pragma_case_sensitive_like

> PRAGMA case_sensitive_like = boolean;
> The default behavior of the LIKE operator is to ignore case for ASCII characters. Hence, by default 'a' LIKE 'A' is true. The case_sensitive_like pragma installs a new application-defined LIKE function that is either case sensitive or insensitive depending on the value of the case_sensitive_like pragma. When case_sensitive_like is disabled, the default LIKE behavior is expressed. When case_sensitive_like is enabled, case becomes significant. So, for example, 'a' LIKE 'A' is false but 'a' LIKE 'a' is still true. This pragma uses sqlite3_create_function() to overload the LIKE and GLOB functions, which may override previous implementations of LIKE and GLOB registered by the application. This pragma only changes the behavior of the SQL LIKE operator. It does not change the behavior of the sqlite3_strlike() C-language interface, which is always case insensitive.

**Comment by hannesmuehleisen** [comment]
Also see #157 in this context. It could make sense to just generate a regex and be done with it. But depends on speed diff.

**Comment by dfooz** [comment]
@taniabogatsch will you do this Issue? Or may I try?

**Comment by taniabogatsch** [comment]
Go for it!

**Comment by danishjalil2991** [comment]
Hey, I have started working on this issue. Could someone assign it to me?. Are there are any particular benchmarks I need to ensure to make sure my implementation of ILIKE is fast enough?

**Comment by danishjalil2991** [comment]
Oops sorry I didn't realize you were working on it. Will take a look at the PR :)

**Comment by Mytherin** [comment]
This is implemented
