### ISSUE TITLE
Create index_t to replace size_t and data_t to replace uint8_t*/char* data pointers

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#177]
Currently we use uint8_t* and char* to refer to buffer pointers (i.e. not strings) interchangeably in different places. We should replace them with a typedef data_t that is a uint8_t*.

For index-ish accesses (e.g. loops over vectors, etc), we should create a typedef called index_t that we then use everywhere instead of uint64_t as we currently do.

**Comment by hannesmuehleisen** [comment]
Going to put this into my branch
