### ISSUE TITLE
API for prepared statements

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#186]
So one does not have to generate SQL queries like a caveman

**Comment by Mytherin** [comment]
Added in 6e864480151c3a1849556f88c8fe44d4c3da0ddb

Examples of usage can be found in `test_prepared_api.cpp`

**Comment by marcboeker** [comment]
@hannesmuehleisen I've added prepared statements to the Go driver. To make it fully work, I'd need another helper function to determine the number of parameter placeholders. Also the Go SQL interface requires a function that returns the number of prepared parameters.

See https://github.com/marcboeker/go-duckdb/blob/b1a8009806ef4e21a47bf7e01fcb118fb2a665ce/connection.go#L55

Thanks!

**Comment by hannesmuehleisen** [comment]
@marcboeker I have added this function:
`duckdb_state duckdb_nparams(duckdb_prepared_statement prepared_statement, index_t* nparams_out)`

**Comment by marcboeker** [comment]
@hannesmuehleisen Awesome, I've added the function and merged prepared statements into master https://github.com/marcboeker/go-duckdb/commit/87f2644d3f724ca827378c8555247116911aca05

**Comment by hannesmuehleisen** [comment]
great thanks!
