### ISSUE TITLE
Function Compatibility with Other Systems

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#193]
Merging a few issues into one here.

# Numeric Scalar
- [x] ACOS, ASIN, ATAN, COS, SIN, TAN, COT, ATAN2 [MySQL, PostgreSQL]
- [x] BIT_AND, BIT_COUNT, BIT_LENGTH, BIT_OR, BIT_XOR, ~ [MySQL]
- [x] CEIL, CEILING, FLOOR [MySQL, PostgreSQL]
- [x] LOG, LOG10, LOG2, LN [MySQL, PostgreSQL]
- [x] PI [PostgreSQL]
- [x] RANDOM
- [x] SQRT, POWER, CBRT [PostgreSQL]
- [x] LEAST, GREATEST

https://www.postgresql.org/docs/8.4/functions-math.html
https://dev.mysql.com/doc/refman/8.0/en/func-op-summary-ref.html

### Operators
PostgreSQL
- [x] IS (NOT) DISTINCT FROM
- [x] ^ (exponent)
- [x] @ (absolute value)
- [x] ! (factorial)

# Date Functions
- [x] DAY, MONTH, DAYOFYEAR, WEEK, QUARTER, YEAR
- [x] DAYOFMONTH, DAYNAME, LAST_DAY, MONTHNAME, WEEKDAY, WEEKOFYEAR, YEARWEEK [MySQL, https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_year]
- [x] CURRENT_DATE
- [X] AGE
- [X] DATE_PART, DATE_TRUNC

# Timestamp Functions
- [x] NOW
- [x] MICROSECOND, MINUTE, SECOND, HOUR
- [x] TIMEOFDAY
- [x] DATE_TRUNC
- [x] AGE

https://www.postgresql.org/docs/9.1/functions-datetime.html

# String Functions
- [X] UPPER, LOWER [SQLite, PostgreSQL]
- [X] LENGTH
- [X] (NOT) LIKE
- [X] REGEXP_MATCHES, REGEXP_REPLACE
- [x] UCASE, LCASE [MySQL]
- [x] RTRIM, LTRIM [SQLite, MySQL] 
- [x] PRINTF [SQLite] 
- [x] REPLACE [SQLite] 
- [x] INSTR [SQLite] 
- [x] REVERSE [MySQL]
- [x] REPEAT [MySQL]
- [x] REVERSE [MySQL]
- [x] CONCAT, CONCAT_WS [MySQL] #217
- [x] LPAD, RPAD [MySQL]
- [x] typeof [SQLite]
- [x] unicode [SQLite]

https://dev.mysql.com/doc/refman/8.0/en/string-functions.html
https://www.postgresql.org/docs/9.1/functions-string.html
https://sqlite.org/lang_corefunc.html
https://www.oracletutorial.com/oracle-string-functions/

# Set Returning Functions
- [x] GENERATE_SERIES [PostgreSQL]

https://www.postgresql.org/docs/9.1/functions-srf.html

# Sequences
- [X] NEXTVAL (PostgreSQL)

# Nested Types
- [ ] generate_subscripts (PostgreSQL)

# Other
- [x] IF, IFNULL [MySQL]
- [X] RANDOM, SETSEED

# Aggregates
- [X] COUNT, MIN, MAX, SUM, AVG
- [X] FIRST
- [X] STRING_AGG
- [x] GROUP_CONCAT (same as STRING_AGG?)  [SQLite, MySQL]
- [X] STDDEV_SAMP, STDDEV_POP, VAR_POP, VAR_SAMP
- [X] COVAR_POP, COVAR_SAMP

More possible functions ->
Oracle: https://www.techonthenet.com/oracle/functions/index.php
SQL Server: https://www.techonthenet.com/sql_server/functions/index.php
Clickhouse: https://clickhouse.tech/docs/en/query_language/functions/

**Comment by geokollias** [comment]
It seems LOG, LOG10, LOG2, LN are already there, right?

**Comment by hawkfish** [comment]
I can look at the date functions. I've already implemented similar functions in another system.

**Comment by hawkfish** [comment]
I'm working on the string functions. `UCASE`, `LCASE`, `LTRIM`, `RTRIM`, `TRIM`.

**Comment by hawkfish** [comment]
Now working on the rest of the string functions.

`STRING_AGG` is the same as `GROUP_CONCAT` (Postgres vs MySQL), but the `ORDER BY` clause needs to be implemented for both of them.

**Comment by hawkfish** [comment]
`LPAD` and `RPAD` appear to return `NULL` in MySQL for invalid arguments (e.g., negative lengths and empty pad strings.) Is that what we want also, and what is the correct way to indicate a `NULL` string?

**Comment by Mytherin** [comment]
I think returning an error in this case might be better, but I'm fine with returning NULL for compatibility purposes as well. You can return an error simply by throwing an exception.

For the null value you need to set the NULL value of the result for the specified tuple. If you are using the TernaryExecutor this is a bit tricky as this is not exposed there currently. You would need to adopt the TernaryExecutor to add an OPWRAPPER similar to how this is done in the BinaryExecutor.

**Comment by hawkfish** [comment]
Ah, so I can't just return a `string_t NullValue()`?

**Comment by Mytherin** [comment]
No, that is only used in hash tables currently (and might be removed entirely). The correct way to mark a tuple as null is to set the flag in the nullmask.

**Comment by hawkfish** [comment]
The functionality is actually rather painful - you return `NULL` only if you _need_ padding but you don't have any.

**Comment by Mytherin** [comment]
From my perspective just throwing an error if the padding is empty seems more logical. It seems unlikely that returning NULL sometimes when the padding is empty is the desired behavior. I think this will most likely occur if someone means to put a space, but by accident puts an empty string as padding.

**Comment by hawkfish** [comment]
What about negative lengths? Empty string? That actually seems more reasonable than an exception or `NULL`.

**Comment by Mytherin** [comment]
I'm fine with returning an empty string in that case.

**Comment by hawkfish** [comment]
Regarding `typeof`... do we support heterogeneous columns? Because if not, the result should be a `ConstantColumn`, no?

**Comment by hawkfish** [comment]
Have we started using ICU?

**Comment by hawkfish** [comment]
Related to that, are we not validating UTF-8 on insert? If you don't, then you have to do it every time the string gets used, which is an unnecessary performance hit.  I'm looking at the case conversion functions and their loops check every character for validity.

**Comment by Mytherin** [comment]
> Have we started using ICU?

Kind of, we have an optional extension now that uses a subset of ICU to implement collations. There is also support in there for timezone stuff but it is not used yet.

> Related to that, are we not validating UTF-8 on insert? If you don't, then you have to do it every time the string gets used, which is an unnecessary performance hit. I'm looking at the case conversion functions and their loops check every character for validity.

We are, UTF-8 validity is only checked during execution in debug mode. The check in the caseconvert should be changed to an assertion indeed.

**Comment by hawkfish** [comment]
OK, I just finished merging from master into my string function branch, but I was going to take another pass to start using the new utf8 functions. I'll fix the case functions while I'm at it, unless someone else is working on that?

**Comment by Mytherin** [comment]
No, feel free to change the checks to assertions there.

**Comment by Mytherin** [comment]
By the way @hawkfish, for what exact functionality did you need ICU? The date conversion, or something else? 

> Regarding typeof... do we support heterogeneous columns? Because if not, the result should be a ConstantColumn, no?

Only just saw this, apologies. The result indeed should just be a constant. In fact, I think we should just resolve this function entirely in the binder.

**Comment by hawkfish** [comment]
I wasn't using ICU, but it has a lot of character scanning macros that I assumed were being used. I just wrote my own (or copied what was in existing string functions) but I can make everything uniform before I submit the pull request.

**Comment by hawkfish** [comment]
The binder sounds right, so I'll leave `typeof` for later.

**Comment by Mytherin** [comment]
> I wasn't using ICU, but it has a lot of character scanning macros that I assumed were being used. I just wrote my own (or copied what was in existing string functions) but I can make everything uniform before I submit the pull request.

If you want to have an iterator over grapheme clusters we provide that with  the `utf8proc_grapheme_callback` method. See for example the `length` function for how that works. The nice part about using that is that it also handles composite unicode characters (such as those found in `test/sql/function/test_complex_unicode.cpp`), which isn't handled by simple code point iteration.

**Comment by hawkfish** [comment]
`BIT_LENGTH` is actually a [string function](https://dev.mysql.com/doc/refman/8.0/en/string-functions.html#function_bit-length).

**Comment by hawkfish** [comment]
Can we update the checklist at the top?

**Comment by Mytherin** [comment]
Yeah, done

**Comment by hawkfish** [comment]
I think a bunch of the date functions have been done too.

**Comment by Mytherin** [comment]
Yeah indeed, let me check and split them up

**Comment by hawkfish** [comment]
I'm looking at `IF` right now, and I've noticed that we do not implicitly cast `DATE` to `TIMESTAMP`.  Is this an oversight?

The issue here is that I am trying to avoid the combinatorial explosion of implementations by just implementing `IF( bool, type, type) : type` Without the implicit cast, everything is turned into a string, which is not what the user would expect.

**Comment by hawkfish** [comment]
Any clarity?

**Comment by Mytherin** [comment]
Whoops, apologies. Missed this one. 

> I'm looking at IF right now, and I've noticed that we do not implicitly cast DATE to TIMESTAMP. Is this an oversight?

Yes, this is an oversight. This implicit cast should indeed be added. 

> The issue here is that I am trying to avoid the combinatorial explosion of implementations by just implementing IF( bool, type, type) : type Without the implicit cast, everything is turned into a string, which is not what the user would expect.

Can't the IF be implemented by using the existing CASE statement? Or is there a subtle difference in behavior I'm not aware of?

**Comment by hawkfish** [comment]
Actually I think that might make it easier - and produce less code!  I presume it would be a rewrite rule of some kind?

**Comment by Mytherin** [comment]
I would do this in the transformer (`transform_function.cpp`), producing a CaseExpression instead of a FunctionExpression if the function name is "if". Rewrite rules are only executed in the optimizer, and we want to produce a valid plan in both the optimized and unoptimized case.

**Comment by erezsh** [comment]
- `hex()` not supported

**Comment by erezsh** [comment]
This fails:

```sql
SELECT substr('SQLite substr', - 6, 6);
```

(Taken from: https://www.sqlitetutorial.net/sqlite-functions/sqlite-substr/)

**Comment by hawkfish** [comment]
So basically a Python slice operation. This is probably pretty simple, and we should match SQLite, no?

**Comment by hawkfish** [comment]
Boundary condition: It looks like an offset of `0` is legal and acts like the string has a non-existent character at that position:

```sql
substr('SQLite substr', 0, 6)
--
SQLit
```

**Comment by Mytherin** [comment]
Implement functions from the SQLite extension suite: https://github.com/codingforfun/sqlite3-extension-functions

**Comment by hawkfish** [comment]
Not sure I like their approach for quantiles.  It uses more storage (`map`'s pointers), requires special casing for each data type and uses an `O( N log N )` algorithm (QuickSelect is `O( N )`) It does compress duplicates, but that seems more relevant for `mode`.   In a column store like DuckDB I think it works better to have an internal column per aggregation bin and then use QuickSelect to pick out the quantile at the end. In fact, if you can arrange to share the column structure between different `quantile` calls on the same value (e.g., deciles), the calls to QuickSelect for the different quantile values will progressively reorganise the column making all the calls more efficient.  See http://www.vldb.org/pvldb/vol9/p1221-wesley.pdf

**Comment by Mytherin** [comment]
Thanks for the heads up! That indeed sounds much better. Indeed I think this is just a list of functions we should support, not necessarily implementations we need to copy :)

Thanks for the paper, looks excellent!

**Comment by hawkfish** [comment]
I've had a look at the new `array_agg` function and that looks like a good template for holistic aggregate construction. I think the sharing functionality would be important, however, and that is related to #267.

The reason I say sharing is important is because a very nasty test case that blew up Hyper in the early days was computing 20 quintiles on a large data set. Sharing fixed their problem, although in their case they were creating 20 instances of window operator(!) and the fix was to compute multiple windowed aggregates that share the same partitioning in a single operator. For proper holistic aggregates, we would want to do something analogous, and the solution I am proposing is one I prototyped in the old Tableau Data Engine, so I have some evidence that it works(!)

**Comment by Mytherin** [comment]
I completely agree that the sharing is important. The main consideration I have is how this would be exposed as an API. In #267, you describe essentially an expression rewrite. @lnkuiper is actually implementing something very similar in #1064 right now (and will be merged soon). We were indeed thinking about using this for the average as you have suggested there, which allows for re-use of the sum and count components, but I'm not sure how percentiles would benefit here. 

My initial thought for solving the percentile issue would be to introduce an operator that would compute multiple percentiles at once, e.g. `percentile(X, 0.5, 0.7, 0.9)`. We could then have an optimizer that would rewrite `percentile(X, 0.5), percentile(X, 0.7)` into `percentile(X, 0.5, 0.7)` internally. That should solve at least this problem, but perhaps future aggregates would need a more versatile API interface for this.

What do you think?

**Comment by hawkfish** [comment]
That sounds plausible... so the idea is that the internal `percentile(X, pct...)` would return a list? And would the second argument be a list or a variable argument? (An empty list could default to 0.5?)

**Comment by hannesmuehleisen** [comment]
Closing this venerable issue. We will track missing functions in individual issues. Great work everyone implementing this long list of stuff and the API to do so!
