### ISSUE TITLE
Optimize CSV loader performance

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#207]
Reportedly ~7x slower than MonetDBLite's one.

**Comment by Mytherin** [comment]
We have a benchmark for this already as well: https://www.duckdb.org/benchmarking/

**Comment by Mytherin** [comment]
Idea for this: we can perform vectorized CSV reading by reading 1024 rows, performing the splitting of those lines and placing the resulting strings in VARCHAR vectors, then performing a cast on the entire vector. That should be significantly faster than the current per-value conversion.

**Comment by hannesmuehleisen** [comment]
Great idea. For the tokeniser, a state machine might be the correct way forward. In the future, the typecasting could be parallelized.

**Comment by Mytherin** [comment]
Did this in 7de5d405cd4ba96deb2ce6bb45ee5313c798df9c, seems to give a ~2X speedup. The next bottleneck seems to be the Date::FromString method (which currently involves copying the string and using a stringstream), might look into grabbing MonetDB's date conversion method.

**Comment by Mytherin** [comment]
Took MonetDB's date conversion method now: 5ba0316adae7aa0273785edc3a7c2e37c75f7b5b, seems to give another 2X speedup on parsing lineitem

**Comment by Mytherin** [comment]
Done in bb67bd1f93fe16a76b00e61472fca8327b99d6e1
