### ISSUE TITLE
Errors from dplyr::compute() (e.g. not implemented T_VaccumStmt)

### ISSUE THREAD

**Issue by cboettig** [cwida/duckdb#219]
It looks like any calls I try to `dplyr::compute()` (complement of `dplyr::collect`, returning the results of an SQL query in the DB as a new table instead of in memory in R) throw errors about missing implementation:

```r
db_con <- DBI::dbConnect(duckdb::duckdb())
DBI::dbWriteTable(db_con, "airlines", nycflights13::airlines)
dplyr::tbl(db_con, "airlines") %>% dplyr::mutate(new = "stuff") %>%  dplyr::compute()
```

gives error

```r
Error in dbSendStatement(conn, statement, ...) : 
  duckdb_query_R: Error: Not implemented: T_VacuumStmt
```

and also: 

```r
dplyr::tbl(db_con, "airlines") %>% dplyr::mutate(new = "stuff") %>%  dplyr::compute()
```

gives error:

```r
Error in dbSendStatement(conn, statement, ...) : 
  duckdb_query_R: Error: Not implemented: Expr of type 127 not implemented
```

Replacing `compute()` with `collect()` works fine, but in my cases I want to store the resulting table in `duckdb` for further operations; it may not fit in memory in R.  

Thanks for all the work on `duckdb` by the way!  Experience has been great so far and really looking forward to the first release of the R package 😄

**Comment by hannesmuehleisen** [comment]
A tip: If you create your connection like so
`db_con <- DBI::dbConnect(duckdb::duckdb(), debug=TRUE)`
There will be a log created of all queries sent to the DB, this would simplify our life to find out what's going on. In this case the output is

````
> dplyr::tbl(db_con, "airlines") %>% dplyr::mutate(new = "stuff") %>%  dplyr::compute()
Q SELECT *
FROM "airlines" AS "zzz1"
WHERE (0 = 1)
S CREATE TEMPORARY TABLE "fywlszvssu" AS SELECT "carrier", "name", "new"
FROM (SELECT "carrier", "name", 'stuff' AS "new"
FROM "airlines") "dpofnrqmyq"
S ANALYZE "fywlszvssu"
Error in dbSendStatement(conn, statement, ...) : 
  duckdb_query_R: Error: Not implemented: T_VacuumStmt
````

So no problem we will probably make `ANALYZE` and `VACUUM` it a NOP for now.

**Comment by cboettig** [comment]
Thanks!  And thanks for the tip, that's good to know. I'll include the debug info in future.

**Comment by hannesmuehleisen** [comment]
Should be fixed
