### ISSUE TITLE
Move headers into a duckdb folder

### ISSUE THREAD

**Issue by xhochy** [cwida/duckdb#229]
Currently the headers assume that they don't conflict with any other system header but have quiet general names. When installing them into a system-wide folder, this can easily cause conflicts. Thus it would be good when the headers were moved into a `duckdb/` folder.

**Comment by Mytherin** [comment]
Agreed, this is a good idea. This should be done on the next major refactor.

**Comment by hannesmuehleisen** [comment]
@xhochy the actual move is trivial, but did you request to also change the includes in the cpp files/examples? so for example in the c++ example, go from

`#include "duckdb.hpp"` to
`#include "duckdb/duckdb.hpp"`
?

**Comment by xhochy** [comment]
When the headers are installed in e.g. `/usr/include/duckdb/*.hpp` I guess the examples should also use `#include "duckdb/duckdb.hpp"` to make the use of the path more visible.

**Comment by hannesmuehleisen** [comment]
I am curious, we don't install the headers anywhere, so why should we be dealing with this? because people who package DuckDB might do this? If someone wants to provide DuckDB headers system-wide, can't they put them in a subfolder themselves and adjust the `-I` path?

**Comment by xhochy** [comment]
@hannesmuehleisen Yes, I'm trying to install the headers in a conda environment, thus I have this need. I'm a bit concerned by using `-I/.../include/duckdb` as there are some headers with very generic names like `common/common.hpp` and thus expect some when searching on my path. I can try using it like that and report back once I really run into an issue-

**Comment by ankoh** [comment]
@hannesmuehleisen

It would help a lot, if the CMakeLists would at least contain an install command for the headers. That would immediately fix the header path problem for all those, that want to embed duckdb via cmake.
(Even though I think that moving all headers into include/duckdb as suggested by @xhochy  would still be a good idea).

Just as an example, I ended up using [this](https://gist.github.com/ankoh/84565a440ef3be10fd9e0df84bd96bd7) to bundle duckdb, which leads to quite undesirable includes like `#include "common/vector_operations/vector_operations.hpp"`.

**Comment by ankoh** [comment]
Unfortunately, such a change would touch most of the files in the project...
If you were willing to do that, https://github.com/cwida/duckdb/pull/256 should do most of the annoying work.

**Comment by hannesmuehleisen** [comment]
This is now merged
