### ISSUE TITLE
CSV import float precision

### ISSUE THREAD

**Issue by JanMultmeier** [cwida/duckdb#232]
I have the following `csv` file:

Rom;80;95;0.1;2019-07-02
Paris;75;90;0.2;2019-07-02
Madrid;90;120;0;2019-07-02

When I copy it to my `weather` table, floating point numbers are not identical to the input:

`query = "CREATE TABLE weather (city VARCHAR, temp_lo INTEGER, temp_hi INTEGER, prcp REAL, date DATE);"`
`cursor.execute(query)`
`cursor.execute("COPY weather FROM 'C:\\Users\\multmeierj\\weather.csv' DELIMITER ';';")`
`cursor.execute("SELECT * FROM weather").fetchall()` 

[['Rom', 80, 95, 0.10000000149011612, 737607], ['Paris', 75, 90, 0.20000000298023224, 737607], ['Madrid', 90, 120, 0.0, 737607]]

The csv imports correctly in R and pandas, is this related to numpy in the background?

EDIT: I guess this is no really a bug, but depends on python's handling of floating numbers

`

**Comment by hannesmuehleisen** [comment]
I think its a printing issue. But we will double check.

**Comment by hannesmuehleisen** [comment]
Hey it works on windows ^^

**Comment by Mytherin** [comment]
This is likely just related to floating point precision, as "REAL" is a 4-byte float which cannot represent numbers like 0.2 accurately. Switching to DOUBLE might reduce the issue, but we need DECIMAL support to fix this properly.
