### ISSUE TITLE
specify duckdb does not support python2 in the document

### ISSUE THREAD

**Issue by djvulee** [cwida/duckdb#233]
When I run the following example in the [website](https://www.duckdb.org/docs/current/tutorials/installation.html), I got the the segmentation fault

```python
import duckdb
cursor = duckdb.connect(':memory:').cursor()
print(cursor.execute('SELECT 42').fetchall())
```

```
[1]    46090 segmentation fault  ipython
```

this is only in python2.

**Comment by hannesmuehleisen** [comment]
#188

**Comment by hannesmuehleisen** [comment]
I have added a clarification to the website
