### ISSUE TITLE
Recursive CTE Support

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#239]

**Comment by hannesmuehleisen** [comment]
Some say (TM) that two ops are needed for this. One that executes the CTE until no new rows are added and one that scans the result of this.

**Comment by ray6080** [comment]
@hannesmuehleisen Hi, Is there any plan on the implementation of this?
I'm interested in `RECURSIVE`, which is a feature that I really need.
I can take a look at this if no one is currently working on.

**Comment by hannesmuehleisen** [comment]
The University of Tübingen wanted to have a look: https://db.inf.uni-tuebingen.de/theses/ExtendDuckDBwithSupportforWITHRECURSIVE.html
Perhaps coordinate with them

**Comment by ray6080** [comment]
Great! Thanks for sharing this.

**Comment by hannesmuehleisen** [comment]
This is supported now
