### ISSUE TITLE
Please add a Python label on Python issues

### ISSUE THREAD

**Issue by xhochy** [cwida/duckdb#245]
Hello DuckDB authors, I'm really excited with your first release and I also played around a bit and it seems to meet my expectations, thus I'm filing some issues that to show how to improve the Python user experience and I might also make some PRs later to fix them. For browsing the Python issues, it would be really good if they would have a `Python` label as the R issues have an `R` label.

**Comment by Mytherin** [comment]
Thanks, it's very much appreciated. We do have the Python and R labels, but I'm not sure if all issues are properly labeled. I will take a quick look.
