### ISSUE TITLE
Support for Q

### ISSUE THREAD

**Issue by kmatt** [cwida/duckdb#246]
I'm looking to see what is needed for Q (http://harelba.github.io/q/) to use the DuckDB Python package instead of sqlite3. At the start I see that Q calls create_function and executemany which are either not supported by DuckDB, or are implemented differently.

Before I go too far, could a DuckDB backend improve query times when aggregates are involved? For example "SELECT key, count(*) FROM file.csv GROUP BY FILE" ?

**Comment by hannesmuehleisen** [comment]
@kmatt, yes, aggregates are certainly a kind of query where DuckDB can improve. Adding `executemany()` and `create_function` to the Python client should be fairly straightforward.

**Comment by hannesmuehleisen** [comment]
@kmatt, Out of curiosity, what would you like to use `executemany()` for? data loading?

**Comment by hannesmuehleisen** [comment]
We now support `executemany()`, can you have a look? @kmatt

**Comment by hannesmuehleisen** [comment]
Tracking the `create_function` in a separate issue #471 and closing here.
