### ISSUE TITLE
create reloadable database in Python

### ISSUE THREAD

**Issue by AdaZheng98** [cwida/duckdb#248]
Hello, I'm trying to use duckdb in my code, but each time I connect to the database I need to create table and import csv file. The code I use is:
def create_connection(self):
        connection = duckdb.connect('')
        cursor = connection.cursor()
        cursor.execute("""
        CREATE TABLE flight(
        c1 real,
        c2 real,
        c3 real,
        c4 real)
        """)
        cursor.execute("copy flight from '/home/user/datasets/flight.csv' header ")
        return connection, cursor

How can I create and save a database? The documentation says "no data is persisted on disk. To persist data on disk you should also pass a database path to the shell. The database will then be stored at that path and can be reloaded from disk later.", but how do I pass the database path to the shell? Any help will be really appreciated.

**Comment by Mytherin** [comment]
You can create a persistent database by passing a path to the "duckdb.connect()" functon, e.g. like so:

```python
connection = duckdb.connect('test.db')
cursor = connection.cursor()
cursor.execute("""
CREATE TABLE flight(
c1 real,
c2 real,
c3 real,
c4 real)
""")
```

Note that the storage system in DuckDB is still in v0.1, and might change soon invalidating your current database files.

**Comment by AdaZheng98** [comment]
I did `
connection = duckdb.connect('test.db')
cursor = connection.cursor()
cursor.execute("""
CREATE TABLE flight(
c1 real,
c2 real,
c3 real,
c4 real)
""")
cursor.execute("copy flight from '/home/user/datasets/flight.csv' header ")
print(cursor.execute("SELECT * from flight").fetchall())
`
It works fine. Then when I want to access the database again, like `
import duckdb
cursor=duckdb.connect('test.db').cursor()
print(cursor.execute("SELECT * from flight").fetchall())
`
I got the following error: `duckdb.DatabaseError: Catalog: Table or view with name flight does not exist!`
Still can't reload the database. Am I missing something here?

**Comment by arjenpdevries** [comment]
Just guessing here, but did you do `COMMIT;`?

**Comment by AdaZheng98** [comment]
That might be the problem? I tried to do `connection.commit()` but got this error `AttributeError: 'duckdb.Connection' object has no attribute 'commit'`. Then I tried `cursor.execute("commit;")`, got `duckdb.DatabaseError: TransactionContext: cannot commit - no transaction is active`. 
How can I properly commit? Sorry I'm very new to sql.

**Comment by Mytherin** [comment]
This works for me:
```python
import duckdb
con = duckdb.connect('test.db')
c = con.cursor()
c.execute("""
CREATE TABLE flight(
c1 real,
c2 real,
c3 real,
c4 real)
""")
c.execute("copy flight from 'flight.csv'")
print(c.execute("SELECT * from flight").fetchall())
```
And then:
```python
import duckdb
con = duckdb.connect('test.db')
c = con.cursor()
print(c.execute("SELECT * from flight").fetchall())
```

Which Python version are you using?

**Comment by AdaZheng98** [comment]
Problem solved! Thank you.

**Comment by akbaritabar** [comment]
Thank you @Mytherin for your guide above.

May I ask how would you do this part of your Python script inside the DuckDB CLI?

```python
import duckdb
con = duckdb.connect('test.db')
```

In other words, how can one build a simple (empty) database file in the DuckDB command line terminal (CLI) ?
I have tried building a sample table and then using export command to write the database, but it does so to a pair of load/schema `.sql` files and not a `.db` file that I can then reload into DuckDB.

Thanks a lot.
