### ISSUE TITLE
Code Refactor

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#254]
* Put all includes in duckdb/ subdirectory (#229)
* .gitignore should filter test directories (#252)
* use move() for vector/strings that are passed as arguments to constructors

**Comment by hyperxor** [comment]
@Mytherin What about not using `std::move` in return statements?

**Comment by Mytherin** [comment]
> @Mytherin What about not using `std::move` in return statements?

I have tried this, as recent GCC versions complain about this. However, older GCC versions (GCC4.9 at least, which is the oldest one we test) cannot handle implicit moves of inherited types.

So for example, the following function does not compile in GCC 4.9:

```cpp
unique_ptr<Expression> GetExpression() {
    unique_ptr<ComparisonExpression> result = ...;
    return result;
}
```
Adding the move fixes the error. However, this results in a warning in GCC9:

```cpp
unique_ptr<Expression> GetExpression() {
    unique_ptr<ComparisonExpression> result = ...;
    return move(result);
}
```

For now we will stick to the second version to avoid breaking builds on old GCCs. When the type matches, however, there is no need to use `move` explicitly.
