### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#260]
There is a concurrency bug in "Multiple concurrent updaters" that gets triggered at times

**Comment by leibatt** [comment]
Hi, any progress on this bug? We want to test concurrency with DuckDB and it's not clear whether it is safe to use DuckDB for concurrent queries.

**Comment by Mytherin** [comment]
I have not looked at it yet, but I will take a look at it this week. Read-only queries should have no problems, the bug is related to concurrent UPDATE statements.

**Comment by hannesmuehleisen** [comment]
have not seen this one in a while, it might be fixed?

**Comment by Mytherin** [comment]
This issue should be fixed in the buffermanager branch, it is still present in the master branch though.

**Comment by Mytherin** [comment]
This issue has been fixed now that the buffermanager branch has been merged
