### ISSUE TITLE
Time::FromString silently truncates milliseconds

### ISSUE THREAD

**Issue by xhochy** [cwida/duckdb#270]
`Time::ToString(Time::FromString("14:42:04.5"))` returns `"14:42:04"` whereas one would expect `"14:42:04.5"`. This is because https://github.com/cwida/duckdb/blob/c29057f91cd041912e8362312ef7d691dd00f747/src/common/types/time.cpp#L45-L61 ignores all input after the part for the seconds.

**Comment by Mytherin** [comment]
Indeed, the function should also be optimized as stringstreams are quite inefficient. This optimization has been done before in the date parsing function (date.cpp). These types of conversion functions can easily become a bottleneck in e.g. CSV parsing so their performance is quite critical.

**Comment by hannesmuehleisen** [comment]
I'm on it I need this for the R client too

**Comment by hannesmuehleisen** [comment]
See also #278

**Comment by hawkfish** [comment]
`stringstream`s are also effectively single-threaded (they typically grab a global `locale` mutex), which makes parallel parsing impossible.

**Comment by hannesmuehleisen** [comment]
@hawkfish @Mytherin the `stringstream` thing is gone already

**Comment by Mytherin** [comment]
Excellent, then this can be closed I think. The current code looks efficient enough.

**Comment by hannesmuehleisen** [comment]
No, milliseconds still have to be added. Will do that tomorrow.

**Comment by hannesmuehleisen** [comment]
@hawkfish 
> `stringstream`s are also effectively single-threaded (they typically grab a global `locale` mutex), which makes parallel parsing impossible.

wow that's pretty bad

**Comment by hannesmuehleisen** [comment]
Fixed
