### ISSUE TITLE
How to implement `stddev_*`

### ISSUE THREAD

**Issue by xhochy** [cwida/duckdb#274]
I want to implement the `stddev_*` aggregation functions. With numerical stable version of Welford's algorithm as outlined in https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance, one can compute the variance/standard deviation in a single pass / incrementally. But this requires us to hold two intermediate values. Currently `duckdb::WindowSegmentTree` only deals with a scalar. Should we subclass this for `stddev` implementations and add a second intermediate value holder or is there a more sophisticated approach using the `Value` class I'm not seeing here?

**Comment by Mytherin** [comment]
The stddev aggregate functions themselves are already there, only the window functions are missing. The window functions should be replaced similar to how the aggregate functions were replaced, as done by @hawkfish in PR #253. Currently the functions are hardcoded in the window segment tree but they should be extensible similar to how the aggregate functions are now extensible (see e.g. [stddev.cpp](https://github.com/cwida/duckdb/blob/master/src/function/aggregate/algebraic/stddev.cpp)).

**Comment by hawkfish** [comment]
@xhochy I  think I have this working now (as well as windowed `COVAR`) but some test data would be nice before I commit. Or I can just make some up if you don't have any.

**Comment by hawkfish** [comment]
Pull request #275 submitted.

**Comment by xhochy** [comment]
> @xhochy I think I have this working now (as well as windowed `COVAR`) but some test data would be nice before I commit. Or I can just make some up if you don't have any.

No, I don't have any specific test data. 

Thanks for taking a stab at implementing this!

**Comment by hawkfish** [comment]
This should be working now.
