### ISSUE TITLE
Compare and contrast with sqlite 

### ISSUE THREAD

**Issue by xiaodaigh** [cwida/duckdb#290]
Is it faster better or just different?

**Comment by Mytherin** [comment]
DuckDB is designed for analytical workloads, i.e. big queries that touch a lot of data at once, whereas SQLite is designed for transactional workloads, i.e. small queries that update or scan individual rows. DuckDB is faster than SQLite at analytical workloads, but likely slower for OLTP workloads, although we have not tested that in-depth.

**Comment by arjenpdevries** [comment]
Also, see https://dl.acm.org/citation.cfm?id=3299869.3320212

(Mark, you are too modest - advertise your work :-))
