### ISSUE TITLE
Compare and contrast with Clickhouse

### ISSUE THREAD

**Issue by xiaodaigh** [cwida/duckdb#292]
How does DuckDB compare to Clickhouse? Both seem equipped to do analytics workloads

**Comment by hannesmuehleisen** [comment]
ClickHouse is focused on aggregations and only supports a subset of SQL. For example, when I checked last time, table-table JOINs were not supported. DuckDB in contrast supports generic SQL queries. Furthermore, DuckDB has far fewer dependencies than ClickHouse. 

GitHub issues are perhaps not the place to ask general questions like that.

**Comment by xiaodaigh** [comment]
> GitHub issues are perhaps not the place to ask general questions like that.

Should I email the author directly? Here are some gracious replies elsewhere from github https://github.com/fstpackage/fst/issues/129 on similar questions

I just thought this would help others find the answers via google, cos it was difficult to understand the basic questions an outsider like myself would have before deciding to try duckdb.

**Comment by l1t1** [comment]
https://db-engines.com/en/system/ClickHouse%3BDuckDB

**Comment by l1t1** [comment]
https://www.libhunt.com/compare-duckdb-vs-ClickHouse
