### ISSUE TITLE
Checkpoint database on disconnect / manually

### ISSUE THREAD

**Issue by noamross** [cwida/duckdb#301]
I'm not sure if this is expected behavior, but data seems to remain in the write-ahead log file rather than the main database after disconnecting.  I think that the database should checkpoint  and remove the `.wal` file on disconnect, or at least implement `CHECKPOINT` so the user can do this manually.  and so the main on-disk file can be transferred to another machine without needing the larger temporary file.

An example:

``` r
library(duckdb)
con <- dbConnect(duckdb(), "reprex")
tab <- data.frame(x = 1:1e7, y=runif(1e7))
dbWriteTable(con, "tab", tab)
DBI::dbGetQuery(con, "SELECT COUNT(*) AS N FROM tab")
#>       n
#> 1 1e+07
dbDisconnect(con)
file.info("reprex")$size
#> [1] 12288
file.info("reprex.wal")$size
#> [1] 120185616
#file.remove("reprex", "reprex.wal")
```

<sup>Created on 2019-10-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Debian GNU/Linux 9 (stretch)
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2019-10-08                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                        
#>  assertthat    0.2.1      2019-03-21 [2] CRAN (R 3.6.0)                
#>  backports     1.1.5      2019-10-02 [1] CRAN (R 3.6.0)                
#>  callr         3.3.1      2019-07-18 [1] CRAN (R 3.6.0)                
#>  cli           1.1.0      2019-03-19 [2] CRAN (R 3.6.0)                
#>  crayon        1.3.4      2017-09-16 [2] CRAN (R 3.6.0)                
#>  DBI           1.0.0      2018-05-02 [2] CRAN (R 3.6.0)                
#>  desc          1.2.0      2018-05-01 [2] CRAN (R 3.6.0)                
#>  devtools      2.2.0      2019-09-07 [1] CRAN (R 3.6.0)                
#>  digest        0.6.21     2019-09-20 [1] CRAN (R 3.6.0)                
#>  DT            0.9        2019-09-17 [1] CRAN (R 3.6.0)                
#>  duckdb      * 0.1.0      2019-10-08 [1] Github (cwida/duckdb@6eaaa07) 
#>  ellipsis      0.3.0      2019-09-20 [1] CRAN (R 3.6.0)                
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 3.6.0)                
#>  fs            1.3.1      2019-05-06 [2] CRAN (R 3.6.0)                
#>  glue          1.3.1      2019-03-12 [2] CRAN (R 3.6.0)                
#>  highr         0.8        2019-03-20 [2] CRAN (R 3.6.0)                
#>  htmltools     0.3.6      2017-04-28 [2] CRAN (R 3.6.0)                
#>  htmlwidgets   1.3        2018-09-30 [2] CRAN (R 3.6.0)                
#>  knitr         1.25       2019-09-18 [1] CRAN (R 3.6.0)                
#>  magrittr      1.5        2014-11-22 [2] CRAN (R 3.6.0)                
#>  memoise       1.1.0      2017-04-21 [2] CRAN (R 3.6.0)                
#>  pkgbuild      1.0.5      2019-08-26 [1] CRAN (R 3.6.0)                
#>  pkgload       1.0.2      2018-10-29 [2] CRAN (R 3.6.0)                
#>  prettyunits   1.0.2      2015-07-13 [2] CRAN (R 3.6.0)                
#>  processx      3.4.1      2019-07-18 [1] CRAN (R 3.6.0)                
#>  ps            1.3.0      2018-12-21 [2] CRAN (R 3.6.0)                
#>  R6            2.4.0      2019-02-14 [2] CRAN (R 3.6.0)                
#>  Rcpp          1.0.2      2019-07-25 [1] CRAN (R 3.6.0)                
#>  remotes       2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                
#>  rlang         0.4.0      2019-06-25 [1] CRAN (R 3.6.0)                
#>  rmarkdown     1.15       2019-08-21 [1] CRAN (R 3.6.0)                
#>  rprojroot     1.3-2      2018-01-03 [2] CRAN (R 3.6.0)                
#>  sessioninfo   1.1.1      2018-11-05 [2] CRAN (R 3.6.0)                
#>  stringi       1.4.3      2019-03-12 [2] CRAN (R 3.6.0)                
#>  stringr       1.4.0      2019-02-10 [2] CRAN (R 3.6.0)                
#>  testthat      2.2.1      2019-07-25 [1] CRAN (R 3.6.0)                
#>  usethis       1.5.1.9000 2019-09-23 [1] Github (r-lib/usethis@a2342b8)
#>  withr         2.1.2      2018-03-15 [2] CRAN (R 3.6.0)                
#>  xfun          0.9        2019-08-21 [1] CRAN (R 3.6.0)                
#>  yaml          2.2.0      2018-07-25 [2] CRAN (R 3.6.0)                
#> 
#> [1] /home/noamross/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/local/lib/R/library
```

</details>

**Comment by Mytherin** [comment]
The storage right now (including checkpointing) is very much a work in progress. Right now the checkpoint is only run on database startup, and is run in its entirety. We are working on implementing automatic incremental checkpointing and manual checkpointing along with other changes to the storage (https://github.com/cwida/duckdb/issues/171#issuecomment-490218145). For now indeed there are a number of problems with the storage and it's very much in beta, don't use it yet to store anything important.

**Comment by noamross** [comment]
Thank you, looking forward to it.  My use-case is distributing a larger-than-memory, fully populated database to together with a client in an R package.

**Comment by hannesmuehleisen** [comment]
@noamross the use case you describe is also one of our target use cases

**Comment by hannesmuehleisen** [comment]
See #420

**Comment by tyluRp** [comment]
I see this is closed, but I have a naive question:  when I close a duckdb connection, e.g. `dbDisconnect`, should the `.tmp` and `.wal` files persist or should they be deleted?

**Comment by hathawayj** [comment]
Interested in where I can read about the `.wal` file and plans for what should happen with it as well.

**Comment by Alex-Monahan** [comment]
Hello! Would this discussion help answer some of your questions?
#1356

**Comment by hathawayj** [comment]
Well, I don't see a reference to `.wal` at the link.  My inexperience with databases doesn't connect the link to my question.  I am guessing that `.wal` has something to do with checkpoints.  But I am still a bit lost.

**Comment by Mytherin** [comment]
The `.wal` file is the write-ahead log. I don't think we have specific documentation about this yet, but perhaps the [SQLite docs can clarify some aspects of what the WAL is/does](https://sqlite.org/wal.html). Essentially the WAL contains a list of all the changes that have been committed/written to disk, but have not been checkpointed. A checkpoint is essentially the action of taking all the changes in the WAL and merging it into the main file. The reason the WAL exists is that it is much faster to write small changes to the WAL than it is to merge them into the main database file. The WAL essentially allows batch-merging of many changes at once during a checkpoint which speeds up processing of many small transactions.

**Comment by hathawayj** [comment]
Thanks @Mytherin.  I am using the Python duckdb package.  Can you direct me to where I could read about the Python method to commit the info in the `.wal` to the database?  Is that what `con.commit()` does?  Or is that done automatically when I use `con.close()`?

**Comment by Mytherin** [comment]
It is done automatically when the database system (not the connection) is shut down. Alternatively, you can call `CHECKPOINT` using the SQL interface.

**Comment by hathawayj** [comment]
Thanks.
