### ISSUE TITLE
Add index documentation

### ISSUE THREAD

**Issue by ray6080** [cwida/duckdb#307]
I'm happy to find that duckdb adds ART as an index solution.
I'm not sure if this is already available for use. If so, I think it might be better to document its usages, because I'm pretty confused by the grammar now.
I see some examples in the file `test/sql/index/test_art_index.cpp`, but still not pretty sure.
Maybe some docs can help? (If the docs already exist, that's great, and please let me know.)

**Comment by hannesmuehleisen** [comment]
@pdet ?

**Comment by pdet** [comment]
I'll add a index usage page to the documentation on https://www.duckdb.org/ later this week.

**Comment by pdet** [comment]
Done.
https://www.duckdb.org/docs/current/sql/indexes
