### ISSUE TITLE
Push all operators through planner and binder

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#312]
Right now, some operations are executed in `planner.cpp`. Don't do this.

**Comment by hannesmuehleisen** [comment]
This should probably include `PRAGMA` because otherwise the python client can't run them. This would require some support from the parser...

**Comment by Mytherin** [comment]
I will work on fixing this as part of fixing the SQLite API wrapper.

**Comment by Mytherin** [comment]
This should be implemented now
