### ISSUE TITLE
Wrong Print method call output of MaterializedQueryResult object for NULL value

### ISSUE THREAD

**Issue by hyperxor** [cwida/duckdb#320]
I have came accross the problem in output of `MaterializedQueryResult` object for `NULL` value.
Let's look at this code:
```cpp
...
DuckDB db(nullptr);
Connection con(db);
con.EnableQueryVerification();

con.Query("CREATE TABLE items(name VARCHAR, count BIGINT)");
con.Query("INSERT INTO items VALUES ('a1', 1)");
con.Query("INSERT INTO items VALUES ('b2', 4)");
con.Query("INSERT INTO items VALUES ('c3', NULL)");
con.Query("INSERT INTO items VALUES ('d4', NULL)");
auto result = con.Query("SELECT * FROM items");
result->Print();
...
```
After executing it I have the following output:
```
$ ./myexample 
name	count	
VARCHAR	BIGINT	
[ Rows: 4]
a1	1	
b2	4	
c3	4      <---- wrong
d4	4      <---- wrong
```
As you can see, for `c3` and `d4` names we have wrong printed `count` values.

Is it a known issue? Maybe we should check  the value in `MaterializedQueryResult::ToString` that is `NULL` and write `<null>` (or something like that). For instance:
```
a1	1	
b2	4	
c3	<null>
d4	<null>
```
Also it can be checked in `string Value::ToString(SQLType sql_type)` method, in `string Value::ToString` there is this check:
```cpp
string Value::ToString() const {
	if (is_null) {
		return "NULL";
	}
...
```
Or maybe problem deeper and should be researched (I can try).

**Comment by hannesmuehleisen** [comment]
confirmed, will investigate.

**Comment by hannesmuehleisen** [comment]
This should be fixed, thanks for reporting.

**Comment by hyperxor** [comment]
@hannesmuehleisen thank you so much!
