### ISSUE TITLE
Using LIMIT in a query gives no results

### ISSUE THREAD

**Issue by Chriskamphuis** [cwida/duckdb#327]
After loading in data a simple query like `SELECT * FROM tbl LIMIT 3` results in nothing being returned:

```
>>> c.execute('select * from dict limit 3;')
<duckdb.Cursor object at 0x7fd7ddb22070>
>>> c.fetchone()
>>>
```

While if I omit the limit statement:

```
>>> c.execute('select * from dict;')
<duckdb.Cursor object at 0x7fd7ddb22070>
>>> c.fetchone()
[0, '0', 10826]
>>> 
```

The same holds when using `fetchall()`. I am using duckdb through Python.

**Comment by hannesmuehleisen** [comment]
Good catch, this was due to a bug in the execution of prepared statements, which the python client generates internally.
