### ISSUE TITLE
Stabilizing the logical plan (aka `LogicalOperator`)

### ISSUE THREAD

**Issue by mdashti** [cwida/duckdb#331]
It would be great if we could plan on stabilizing the logical plan interface as an intermediate stage of `DuckDB` that other systems can hook into it.

I wanted to know if there is any plan for this and how we can make this happen. I already have a simple code generator for generating the C API for `LogicalOperator` ([in Julia](https://github.com/cwida/duckdb/files/3802660/DuckDBParserWrap.zip)).

However, without having a somewhat stable interface for it, it's not easy to keep this C interoperability API code generator (and other tools that depend on it) up-to-date.

**Comment by hannesmuehleisen** [comment]
Were there any recent changes that triggered this question? The logical plans should have been rather stable I think.

**Comment by mdashti** [comment]
Yeah, `AggregateExpression` and `UniqueIndex` were removed and the structures of `BoundAggregateExpression`and `Index` are completely changed. In addition, compound keys (in `CREATE TABLE`) were accepted before (and properly handled, at least as far as the logical plan was concerned), but those are now throwing errors (related to changes in the `APR` implementation, which rejects compound keys).

**Comment by hannesmuehleisen** [comment]
I see. I don't think we can commit to not changing the logical plan at this point in our development, but I expect changes there to reduce in frequency. We are quite happy with the SQL coverage at this point (except for `INTERVAL` of course :), so there is no need for changes there right now.

**Comment by mdashti** [comment]
Thanks @hannesmuehleisen. It makes sense.
