### ISSUE TITLE
Word-of-mouth, time to communicate?

### ISSUE THREAD

**Issue by GuillaumePressiat** [cwida/duckdb#350]
Hi,

Maybe it's too soon. Else why no communication is available about this work on most frequent blogroll (r-bloggers, etc.) ?

For information, in order to understand your migration from MonetDBLite to duckdb, I made [this](https://guillaumepressiat.github.io/blog/2019/10/duckdb)

**Comment by hannesmuehleisen** [comment]
I have seen your blog post, thanks a lot!

**Comment by hannesmuehleisen** [comment]
I would say whenever we close #171 we will go full broadside with communication
