### ISSUE TITLE
Add option to build without pthread

### ISSUE THREAD

**Issue by ankoh** [cwida/duckdb#352]
Lean builds always link pthread via re2, at the moment.
Are you planning to maintain a single-threaded version of duckdb?

Right now, a [WITH_THREADS](https://github.com/ankoh/duckdb/commit/cd76afa7443cde0edf4b81de66723734fb782158) cmake option still suffices.

**Comment by hannesmuehleisen** [comment]
This is a bug. I have opened a PR that should fix this.

**Comment by hannesmuehleisen** [comment]
Should be fixed, could you check?

**Comment by ankoh** [comment]
https://github.com/cwida/duckdb/commit/fed3560fe396e5c7b8b29d31b679980ad3cac8c7 Resolves the issue for me, thanks!

**Comment by hannesmuehleisen** [comment]
But indeed a very good point, when implementing #11, we should probably keep the threading optional. I guess this would otherwise also make the js implementation "difficult", right?

**Comment by ankoh** [comment]
I personally wouldn't care too much about WebAssembly limitations right now since its development is still at the very beginning.
I only ran into that issue at the weekend since only linking pthread in re2 broke with the recent version of the emscripten SDK.
Pthreads in WebAssembly require SharedArrayBuffers which were disabled in many browsers in response to Spectre.
Also, right now, pthreads make wasm memory accesses from js quite a bit slower.

But both issues should be temporary.
WebAssembly users will certainly also be interested in Intra-Query Parallelism eventually.
