### ISSUE TITLE
Rework String Representation

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#362]
Currently our string representation inside vectors is just a pointer to a null-terminated string. This means that for every single operation we perform on these strings we need to follow the pointer, and this also leads to many calls to `strlen` in our codebase. This is unfortunate because in many cases we already know the length of strings (e.g. when we read them from storage). We want to change the string representation to the following representation:

```cpp
struct string_t {
	char *data;
	uint32_t length;
};
```

The inclusion of a length field everywhere allows for more efficient operations (e.g. string comparisons can early abort when the length is different, and can use `memcmp` instead of `strcmp`). This has consequences for how strings are handled all over the execution engine, however, and thus is a reasonably sized change. I will start working on this soon.

**Comment by hyperxor** [comment]
@Mytherin Hello Mark, I have a question related to this issue. Why `std::string` cannot be used for solving problems that you wrote above?

**Comment by Mytherin** [comment]
> @Mytherin Hello Mark, I have a question related to this issue. Why `std::string` cannot be used for solving problems that you wrote above?

Apologies for the (extremely) late reply, I missed this reply at the time and am only now looking back at this issue. `std::string` is fine for non-performance sensitive strings, such as e.g. column names or table names in the planner, but `std::string` cannot be used for database internal strings because it performs significant internal copying. When working with large tables (e.g. millions of rows), performing millions of unnecessary copies of these strings becomes an immense performance bottleneck that is unacceptable. For that reason we have to perform our own management of strings inside the engine itself.

**Comment by Mytherin** [comment]
After reading the Umbra paper by Thomas Neumann I am convinced to use their string representation, which is as follows:

```cpp
struct string_t {
    uint32_t length;
    union {
        char data[12];
        struct {
            char prefix[4];
            char *data;
        };
    };
};
```

Basically, not only is the length stored with the string, but there is also a small prefix stored. This allows for a quick early-out of comparisons between larger strings and also for prefix lookups (in the case of e.g. LIKE statements). This is similar to the string presentation we thought of before that has a small 4-byte extract of the hash, but the prefix is more versatile than the hash (as the hash can only be used for equality comparisons, and the prefix can be used for prefix matching/range filters as well). The prefix is also much cheaper to compute.

Small strings (smaller than 11 bytes) are stored entirely in-line, avoiding the need for pointer chasing entirely.
