### ISSUE TITLE
Memory usage during large scan queries

### ISSUE THREAD

**Issue by ryanworl** [cwida/duckdb#364]
I am running a relatively simple query over a 500m row table.

`create table foo (x int, y int)`
`... insert 500m rows ...`
`select avg(y), x from foo group by x limit 10`

Cardinality of `x` is under 10K, so the hash table size is not the issue here. The specific query is not the issue either, which I deduced from running multiple different types of queries and seeing similar results.

The peak memory usage of this query is approximately 4Gb (8 bytes per tuple) which is suspiciously close to the size of two 32bit integers (from the schema) times 500m rows. It grows over the duration of the query and stops growing when the query ends. It is not freed while running in the shell.

Is there any effort made to re-use memory?

The execution performance is actually very good, so the lack of re-use is not causing a performance problem, but if the table gets much bigger (say 5B rows) it becomes untenable.

Even if I use a highly selective predicate while still scanning the table, it grows.

Edit: If I run the same query immediately after, the memory usage stays constant. That means some memory re-use is happening, but still not exactly the behavior I anticipated. Will continue investigating.

Edit 2: It appears this is the user-space buffer manager? I guess that makes sense now. 

Please just close this issue if I diagnosed it correctly. :smile:

**Comment by Mytherin** [comment]
Indeed we use a user-space buffer manager, in your initial run the table will be cached in memory. You can change the maximum memory of the buffer manager as follows:
```sql
PRAGMA memory_limit='1GB' -- insert desired maximum memory size 
```

The default size is currently `-1`, which is infinite, so no limit is set on how much data will be cached. Because of that the entire table will be loaded into memory.
