### ISSUE TITLE
Exposing pre-finalized aggregate function results

### ISSUE THREAD

**Issue by ryanworl** [cwida/duckdb#365]
Imagine two instances of DuckDB running the same query in parallel on different partitions of data. For distributive aggregates, combining the results is trivial. For algebraic aggregates which have a transformation to distributive aggregates (avg -> sum, count), combining the results is also trivial.

When adding a hypothetical approximate quantile function (#280), combining the results is not possible without exposing the underlying data structure used for the algorithm.

Will there be any consideration for this use case of combining results from queries ran in parallel, potentially on different machines or at different times?

One path I can see is extending the database's internal type system to support an intermediate aggregate type. This way a `Vector` of these intermediate results could be encoded into a `Vector` of blob, type ID pairs where the blob is a serialized form of the aggregation data structure and type ID is a small integer tag defined by the aggregate function implementation.

The ability to aggregate multiple of these intermediate results back into another intermediate result would also be useful. You can imagine a tree-like arrangement for processing which makes the intermediate results successively smaller until the root of the tree produces a final scalar value in the case of e.g. an approximate quantile.

Another analytics database called Clickhouse exposes this capability through "Aggregate Function Combinators". You can see the documentation [https://clickhouse.yandex/docs/en/query_language/agg_functions/combinators/](here), specifically the `State`, `MergeState`, and `Merge` combinators.

**Comment by Mytherin** [comment]
I believe we already have partial infrastructure for this in the algebraic aggregates, see e.g. the [covariance](https://github.com/cwida/duckdb/blob/master/src/function/aggregate/algebraic/covar.cpp). This is used for computing the aggregates inside hash tables for aggregates. In the future when we extend DuckDB to support parallel execution we are planning to extend these aggregates to support parallel computation and combining of partial aggregate results on a single machine. We are not planning to support distributed computation of anything in the main system, however, as that is outside the scope of an embedded database.

Loading the partial aggregated state into vectors is currently not yet supported. We could, as you mention, always place them in a `BLOB` field (once those are implemented!). This is indeed something we can consider to implement in the future.

Thanks for the feedback!

**Comment by hawkfish** [comment]
Combining states is already [part of the model](https://github.com/cwida/duckdb/blob/master/src/include/duckdb/function/aggregate_function.hpp):

```cpp
//! The type used for combining hashed aggregate states (optional)
typedef void (*aggregate_combine_t)(Vector &state, Vector &combined);
```

Is that what you meant by "Aggregate Function Combinators"?

**Comment by ryanworl** [comment]
> Combining states is already [part of the model](https://github.com/cwida/duckdb/blob/master/src/include/duckdb/function/aggregate_function.hpp):
> 
> ```c++
> //! The type used for combining hashed aggregate states (optional)
> typedef void (*aggregate_combine_t)(Vector &state, Vector &combined);
> ```
> 
> Is that what you meant by "Aggregate Function Combinators"?

This may be it, I'd have to look into it more. "Aggregate Function Combinators" is a ClickHouse-specific term that I've never seen outside of their documentation, but the general idea is you need to differentiate combining intermediate aggregate results into a final result vs combining intermediate aggregate results into another intermediate aggregate result.

**Comment by hannesmuehleisen** [comment]
@ryanworl yes that is what the combine function does.
