### ISSUE TITLE
Syntax error in python connection cursor gives segfault

### ISSUE THREAD

**Issue by Chriskamphuis** [cwida/duckdb#368]
I tried to start a transaction using 

```
cursor.execute('START TRANSACTION') 
```

and also the correct 

```
cursor.execute('BEGIN TRANSACTION') 
```
and both give a segfault. 

Random queries do not give a segfault:
```
>>> c.execute('abc')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
duckdb.DatabaseError: Parser: syntax error at or near "abc" [1]
```

Maybe catch the syntax error without killing the python session. 
Starting a transaction with the `connection.begin()` methods works fine.

**Comment by hannesmuehleisen** [comment]
This is related to #312 , but should indeed never happen.

**Comment by Mytherin** [comment]
Could you check whether this has been fixed on the master branch?

**Comment by Chriskamphuis** [comment]
This has not been fixed yet.

**Comment by Mytherin** [comment]
@Chriskamphuis 
The following snippet works as expected for me on the master branch (with Python3 and Linux):
```python
import duckdb
con = duckdb.connect(":memory:")
c = con.cursor()
c.execute("START TRANSACTION")
c.execute("blabla")
c.execute("ROLLBACK")
```
Are there steps I am missing here? Perhaps you are still using the older version from pip?

**Comment by Chriskamphuis** [comment]
Maybe `make` did not finish properly, I tried to re confirm my findings however I noticed it could not build duckdb right now. Maybe that also happened this morning. (and accidently reinstalled same pip version as before) 

```
test_ca_optimizer.cpp:0:71: fatal error: /home/chris/tmp/duckdb/test/optimizer/test_ca_optimizer.cpp: No such file or directory
compilation terminated.
```

**Comment by Mytherin** [comment]
Hm, perhaps try to do a clean build? It seems like it's trying to compile one of the files that has been deleted recently.

**Comment by Chriskamphuis** [comment]
it works thanks!
