### ISSUE TITLE
"DROP INDEX" gives segfault

### ISSUE THREAD

**Issue by gizemayydin** [cwida/duckdb#371]
Code for creating the database:

```
c.execute("CREATE TABLE A (A1 INTEGER,A2 VARCHAR, A3 INTEGER)")
c.execute("CREATE TABLE B (B1 INTEGER,B2 INTEGER, B3 INTEGER)")
c.execute("CREATE TABLE C (C1 VARCHAR, C2 INTEGER, C3 INTEGER)")
```

Code for inserting into table (the others are also similar):
c.execute(c.execute("COPY A FROM 'A1.csv' DELIMITER '|'"))

Code for creating index:

```
c.execute("CREATE INDEX A_index ON A (A1)")
c.execute("CREATE INDEX B_index ON B (B1)")
c.execute("CREATE INDEX C_index ON C (C2)")
```

This ran without problems. However, codes below give segfault:

`c.execute("DROP INDEX IF EXISTS A_index")`

```
#This worked before creating the index
c.execute("SELECT A2 FROM A WHERE A1=1")
```

(gives segfault for other tables as well)

**Comment by hannesmuehleisen** [comment]
@pdet can you have a look please?

**Comment by hannesmuehleisen** [comment]
@gizemayydin did you install the latest source version from master or via pip?

**Comment by gizemayydin** [comment]
I installed the latest source from master. Maybe this output may help further: (this is what happens when I executed the select query)
![image](https://user-images.githubusercontent.com/31890525/70322108-3edc0d80-183a-11ea-836e-d537ef38bc71.png)

**Comment by gizemayydin** [comment]
Previously, I ran the 'CREATE_INDEX' part on the database that was created by an old DuckDB version. Now, I tried re-creating everything from scratch using the new version (which I installed using the source yesterday); the 'select' queries work. However, 'DROP INDEX' or 'DROP INDEX IF EXISTS' still gives segfault.
![image](https://user-images.githubusercontent.com/31890525/70324295-240c9780-1840-11ea-9dae-b4ce1c496761.png)

**Comment by arjenpdevries** [comment]
Could be #368 problem again?

**Comment by pdet** [comment]
I've written a test with the described scenario and it passes. It is most likely related to the python API.

**Comment by Mytherin** [comment]
Could you check whether this has been fixed on the master branch?

**Comment by gizemayydin** [comment]
I checked and it has been fixed.
