### ISSUE TITLE
Reexport all of DBI

### ISSUE THREAD

**Issue by krlmlr** [cwida/duckdb#384]
Ideally we can use `dbGetQuery()` directly after loading duckdb. I wonder why the DBItest tests don't catch this.

``` r
library(duckdb)
dd <- data.frame(a = 1.5, b = "b")

con <- dbConnect(duckdb())
dbWriteTable(con, "dd", dd)

dbGetQuery(con, "SELECT round(a)")
#> Error in dbGetQuery(con, "SELECT round(a)"): could not find function "dbGetQuery"

dbGetQuery(con, "SELECT round(b)")
#> Error in dbGetQuery(con, "SELECT round(b)"): could not find function "dbGetQuery"
```

<sup>Created on 2020-01-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hannesmuehleisen** [comment]
Good point, I always only load DBI and not duckdb. How would i go about re-exporting DBI? Can you send a PR perhaps?

**Comment by jimhester** [comment]
I really don't think re-exporting the entire namespace is a good idea, this is what Depends is for...

**Comment by hannesmuehleisen** [comment]
@jmhester indeed that is the correct solution. Thanks for pointing this out!

**Comment by hannesmuehleisen** [comment]
Perhaps DBItest could then check for that accordingly, right now I get

````
── 1. Failure: DBItest[duckdb]: Getting started: package_dependencies (@spec-get
3207"DBI" %in% pkg_imports isn't true.
````
So adding it into both Depends and Imports.

**Comment by krlmlr** [comment]
I'm not sure you can add to both Depends and Imports. Reexporting feels slightly neater than "Depends", and allows downstream packages to import only {duckdb} instead of both {duckdb} and {DBI}.

On the flip side, I see that "Depends" will make all methods (even new ones) available when users use `library(duckdb)`, and is much less effort for the DBI driver. I'm not sure we need to update {DBItest} right away, let's keep this in mind.
