### ISSUE TITLE
Missing uninstall for python package

### ISSUE THREAD

**Issue by arjenpdevries** [cwida/duckdb#385]
The installation procedure does not have an "undo", you cannot do `pip uninstall`.

**Comment by xhochy** [comment]
Shouldn't `pip uninstall` be provided automatically with `pip` indenpent of the package?

**Comment by arjenpdevries** [comment]
Apparently not - pip install detects an installed versiin and then complains it cannot uninstall.

**Comment by hannesmuehleisen** [comment]
@arjenpdevries can you post your error message please? Is this the version from pip or installed from source?

**Comment by arjenpdevries** [comment]
The error I get is when I install locally using a prefix, using pip (without modifications).

The first time:

    $ pip install --prefix $DUCKDB_PREFIX -e tools/pythonpkg 
    Obtaining file:///home/arjen/gh/duckdb/tools/pythonpkg
    Requirement already satisfied: numpy>=1.14 in /usr/lib64/python3.7/site-packages (from duckdb==0.1.2.dev488+g0e4e7cf1) (1.17.4)
    Collecting pandas>=0.23 (from duckdb==0.1.2.dev488+g0e4e7cf1)
      Using cached https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a1538bc8a6d62a82d0439693192aef541d7b123769/pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl
    Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3.7/site-packages (from pandas>=0.23->duckdb==0.1.2.dev488+g0e4e7cf1) (2019.2)
    Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3.7/site-packages (from pandas>=0.23->duckdb==0.1.2.dev488+g0e4e7cf1) (2.8.0)
    Requirement already satisfied: six>=1.5 in /home/arjen/.local/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas>=0.23->duckdb==0.1.2.dev488+g0e4e7cf1) (1.12.0)
    Installing collected packages: pandas, duckdb
      Running setup.py develop for duckdb
    Successfully installed duckdb pandas-0.25.3

The second time:

    $ pip install --prefix $DUCKDB_PREFIX -e tools/pythonpkg 
    Obtaining file:///home/arjen/gh/duckdb/tools/pythonpkg
    Requirement already satisfied: numpy>=1.14 in /usr/lib64/python3.7/site-packages (from duckdb==0.1.2.dev488+g0e4e7cf1) (1.17.4)
    Collecting pandas>=0.23 (from duckdb==0.1.2.dev488+g0e4e7cf1)
      Using cached https://files.pythonhosted.org/packages/63/e0/a1b39cdcb2c391f087a1538bc8a6d62a82d0439693192aef541d7b123769/pandas-0.25.3-cp37-cp37m-manylinux1_x86_64.whl
    Requirement already satisfied: pytz>=2017.2 in /usr/lib/python3.7/site-packages (from pandas>=0.23->duckdb==0.1.2.dev488+g0e4e7cf1) (2019.2)
    Requirement already satisfied: python-dateutil>=2.6.1 in /usr/lib/python3.7/site-packages (from pandas>=0.23->duckdb==0.1.2.dev488+g0e4e7cf1) (2.8.0)
    Requirement already satisfied: six>=1.5 in /home/arjen/.local/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas>=0.23->duckdb==0.1.2.dev488+g0e4e7cf1) (1.12.0)
    Installing collected packages: pandas, duckdb
      Found existing installation: duckdb 0.1.2.dev488+g0e4e7cf1
        Can't uninstall 'duckdb'. No files were found to uninstall.
      Running setup.py develop for duckdb
    Successfully installed duckdb pandas-0.25.3

The process states `Can't uninstall 'duckdb'.`.

PS: BTW, testing this to get the error, I first build with `clang` and got `clang-9: error: unknown argument: '-fstack-clash-protection'` when building using a debug version using `clang`. The above logs are with `gcc`.

**Comment by xhochy** [comment]
Is the editable install (`-e`) intentionally here? What is the content of your `site-packages` directory? There should be at least some duckdb metadata in there.

**Comment by arjenpdevries** [comment]
Yes, it is here, I was installing from source.

And yes, the second time there is a duckdb package there, because I installed it the first time :-) The point was that I expected the second install to first uninstall the current version, and then install the new version (of course, that was only emulated here).

**Comment by hannesmuehleisen** [comment]
I think this is related to https://github.com/pypa/pip/issues/4438 / https://github.com/pypa/pip/issues/1895
Could you try to see what happens if you get a recent pip version?

**Comment by arjenpdevries** [comment]
The report is with `pip 19.1.1`.

**Comment by arjenpdevries** [comment]
Same problem with `pip 20.0.1`.

(Installed packaged version for FC31, upgraded using `sudo pip install --upgrade pip`.)

**Comment by hannesmuehleisen** [comment]
Ok, I really have no clue what to do about this. Any ideas?

**Comment by hannesmuehleisen** [comment]
The Python package setup has closed since it now uses the amalgamation, so closing this.
