### ISSUE TITLE
Sub-second precision for TIMESTAMP

### ISSUE THREAD

**Issue by wallflower** [cwida/duckdb#389]
I was just wondering if someone could answer some questions around the timestamp type in duckdb?

Using fetchall:
```
>>> print(cursor.execute("SELECT TIMESTAMP '2020-01-10 00:00:00.500' as test_time").fetchall())
[[3168822576022004]]
```

Simple question... If I am creating a TIMESTAMP column, how would I convert the stored number back to a python datetime?

Using fetchnumpy:
```
>>> print(cursor.execute("SELECT TIMESTAMP '2020-01-10 00:00:00.500' as test_time").fetchnumpy())
{'test_time': masked_array(data=['2020-01-10T00:00:00.000'],
             mask=False,
       fill_value=numpy.datetime64('NaT'),
            dtype='datetime64[ms]')}
```
Looks like it is truncating the millisecond part of the timestamp.  Is that correct?

I received the same result using 0.1.1 and 0.1.2

**Comment by hannesmuehleisen** [comment]
This is a known open issue, see #244 
Basically we need to implement this conversion still

**Comment by hannesmuehleisen** [comment]
@wallflower  Can you try to install from source to confirm this is fixed?

**Comment by wallflower** [comment]
Two of the three methods now seem good to me...

fetchnumpy seems good now (before it was truncating milliseconds)
```
>>> import duckdb
>>> con = duckdb.connect(':memory:')
>>> cursor = con.cursor()
>>> print(cursor.execute("SELECT TIMESTAMP '2020-01-10 00:00:00.500' as test_time").fetchnumpy())
{'test_time': masked_array(data=['2020-01-10T00:00:00.500'],
             mask=False,
       fill_value=numpy.datetime64('NaT'),
            dtype='datetime64[ms]')}
```

fetchdf seems good now (before it was just printing date)
```
>>> print(cursor.execute("SELECT TIMESTAMP '2020-01-10 00:00:00.500' as test_time").fetchdf())
                test_time
0 2020-01-10 00:00:00.500
```

fetchall stills seems wrong to me
```
>>> print(cursor.execute("SELECT TIMESTAMP '2020-01-10 00:00:00.500' as test_time").fetchall())
[[3168822576022004]]
```
Should this not return a datetime, iso8601 string, unix timestamp, etc.?  what is that number and how does one convert it to a python datetime if it is correct?

**Comment by wallflower** [comment]
Thank you for fixing this.  I downloaded 0.1.6 and all seems well.
