### ISSUE TITLE
Support of UDFs in SQLite API.

### ISSUE THREAD

**Issue by johnfouf** [cwida/duckdb#394]
Hello, implementation of the SQLite API allows the integration with applications written on top of SQLite, 
    however SQLITE's API support the registration of user defined functions (scalar, aggregate, virtual tables), 
    and given the existence of Python wrappers (e.g., https://rogerbinns.github.io/apsw/) this allows the users to easily register Python functions in the database. 
    Currently, APSW, which is build on top of SQLITE, does not work with DuckDB.
    Do you intend to extend your compatibility with SQLite API to support such functionality? Or do you think that Duck DB's internals may support such functionality?

**Comment by hannesmuehleisen** [comment]
At the moment, we do not yet have support for SQLite UDFs. But there is no conceptual reason why this could not be done in the future. Happy to review a PR!

**Comment by hannesmuehleisen** [comment]
This is now tracked in #471
