### ISSUE TITLE
README section "why and when use DuckDB?"

### ISSUE THREAD

**Issue by lorenzwalthert** [cwida/duckdb#401]
Hi @hannesmuehleisen, we met at an R user meetup in Zurich where you presented your work. Cool. I think for people who are not DB gurus, it would be great if the README could quickly give some insights on why and when to use duckdb and what are the advantages against alternative solutions in general? I remember you told me "it's in memory, so it's much faster and optimizes reading, not writing, because when you are analyzing, you are reading" (right?), but then my next naive question to ask would be "why not SQLite?" and also I can't see that easily see how fast it really is even if I look at the benchmarks. Maybe also just link some resources in the README if they exist? I think that would be helpful to lower the entry barrier. Carry on the good work :+1:

**Comment by hannesmuehleisen** [comment]
That's an excellent idea. We should write this up and add to website/README.

**Comment by lorenzwalthert** [comment]
Website also yes, good point. It the first thing people see which I think it has a big impact on think about the project and if they look into it further.
