### ISSUE TITLE
parallel / threaded query execution a la MonetDBLite?

### ISSUE THREAD

**Issue by cboettig** [cwida/duckdb#407]
apologies for a rather ignorant question here.  Migrating an existing package from MonetDBLite use to duckdb use, I notice that SQL queries that were executing in parallel on MonetDBLite seem to run on a single thread now on duckdb (and thus take ~ 2x longer than when MonetDBLite is used as the backend engine).  Is this something that I need to enable, or something on the roadmap, or is there another particular reason execution is not threaded in `duckdb` for cases where it does appear threaded in MonetDBLite?  Thanks much!

**Comment by hannesmuehleisen** [comment]
We are working on this, see #11

**Comment by hannesmuehleisen** [comment]
Closing this here

**Comment by cboettig** [comment]
Thanks for confirming!  Watching #11 now. :eyes:
