### ISSUE TITLE
Incorrect result for COUNT DISTINCT used as Window function

### ISSUE THREAD

**Issue by vogelsgesang** [cwida/duckdb#408]
The query
```
WITH t AS (SELECT col0 AS a, col1 AS b FROM (VALUES(1,2),(1,1),(1,2),(2,1),(2,1),(2,2),(2,3),(2,4)) v)
SELECT *, COUNT(b) OVER(PARTITION BY a), COUNT(DISTINCT b) OVER(PARTITION BY a) FROM t
```
returns incorrect results. The last column contains ordinary counts instead of distinct counts.

The most straightforward fix is probably to reject the DISTINCT keyword inside window queries. At least that's what Postgres decided to do, and the SQL 2011 standard forbids the DISTINCT keyword inside window queries, too

**Comment by Mytherin** [comment]
Good catch! Indeed, DISTINCT should throw an error when used in Window functions. It seems like it is just ignored silently currently.

**Comment by Mytherin** [comment]
Should be fixed now, thanks for the report :)

**Comment by vogelsgesang** [comment]
thanks for the quick fix :)

Still reproes in https://duckdbdemo.project.cwi.nl/select.html, but I guess the server is just not updated yet

**Comment by vogelsgesang** [comment]
Ok, now that I took a look at your commit, I found another case which you probably want to forbid:

```
WITH t AS (SELECT col0 AS a, col1 AS b FROM (VALUES(1,2),(1,1),(1,2),(2,1),(2,1),(2,2),(2,3),(2,4)) v)
SELECT *, COUNT(b ORDER BY x) OVER(PARTITION BY a) FROM t
```

**Comment by Mytherin** [comment]
Interesting, I never saw this syntax before. I suppose it is used for aggregates where input order matters, e.g. `STRING_AGG`? I think in general we should forbid this for now, as it is unsupported right now.

> Still reproes in https://duckdbdemo.project.cwi.nl/select.html, but I guess the server is just not updated yet

Indeed the server still needs to be updated.

**Comment by Mytherin** [comment]
> Ok, now that I took a look at your commit, I found another case which you probably want to forbid:
> 
> ```
> WITH t AS (SELECT col0 AS a, col1 AS b FROM (VALUES(1,2),(1,1),(1,2),(2,1),(2,1),(2,2),(2,3),(2,4)) v)
> SELECT *, COUNT(b ORDER BY x) OVER(PARTITION BY a) FROM t
> ```

Should be fixed as well now, and also disallowed the FILTER syntax for aggregates for now. Thanks again!
