### ISSUE TITLE
Implement `CHECKPOINT`

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#420]
Battle plan: Lock connection manager, lock all connections, run checkpoint, unlock.

**Comment by Mytherin** [comment]
Some notes on this: 

* Currently the CHECKPOINT internally restarts the database system entirely. The reason for that is mostly simplicity, but this should be changed when we allow it to be called while the system is running.

* Even if the system is locked I don't think it is easy to do this as we still need to consider transactions that are in progress that may have pending changes. We should only flush data that has been committed, but uncommitted data still needs to be available after the checkpoint is performed.

* When running a checkpoint is that all the segments of the table need to be updated to point at the new blocks, and that all the indices need to either be recreated or updated (as row_ids change by removing deleted rows). Care should also be taken with currently alive prepared statements.

**Comment by hannesmuehleisen** [comment]
I think it might be fair in a first iteration to clear all prepared statements and abort all transactions before checkpointing.

**Comment by hannesmuehleisen** [comment]
Actually, refusing checkpoint when transactions are running or prepared statements are open is the better option. Then future updates can relax this and nobody will depend on the "everything is cancelled" behaviour.
