### ISSUE TITLE
Upload R package to CRAN

### ISSUE THREAD

**Issue by waynelapierre** [cwida/duckdb#428]
When will the R package be registered at CRAN?

**Comment by hannesmuehleisen** [comment]
There are no fundamental reasons left why we cannot upload to CRAN. One big blocker was the amalgamation build. Now its a matter of getting the package through the various checks of `R CMD check`. If someone would like to help with that, that would be greatly appreciated.

**Comment by hannesmuehleisen** [comment]
DuckDB now builds on Solaris, a first step of suffering on the long road to CRAN

**Comment by hannesmuehleisen** [comment]
As a side note, duckdb can now be installed using R's `install.packages`:

````R
install.packages("duckdb", repos=c("http://download.duckdb.org/alias/master/rstats/", "http://cran.rstudio.com"))
````

**Comment by hannesmuehleisen** [comment]
There are two major issues left before we can submit to CRAN:

- [ ] R documentation, still on the fence whether to use roxygen for this or not
- [ ] C/C++ code still references std::cout, stderr & stdout 

Once this is resolved, we need to run with valgrind etc. and submit. Help is appreciated.

**Comment by cboettig** [comment]
@hannesmuehleisen you probably know about this already, but [`rhub` package](https://github.com/r-hub/rhub) already has built in functions to run tests with valgrind, sanitizers, etc, and across most platforms (see `rhub::platforms()`).  Tests can run on their remote r-hub, and the linux-based ones can be run locally: https://r-hub.github.io/rhub/articles/local-debugging.html

**Comment by hannesmuehleisen** [comment]
@cboettig Yes, I know of `rhub`, we will certainly use them again in preparation. I had recently looked into using their Solaris builder but found it too unstable unfortunately.

**Comment by waynelapierre** [comment]
any update?

**Comment by hannesmuehleisen** [comment]
Just sent 0.2.1 to CRAN. Let see what happens.
