### ISSUE TITLE
Initialization fails with duckdb.connect(':memory:') 

### ISSUE THREAD

**Issue by tdoehmen** [cwida/duckdb#436]
The Python API example on [https://www.duckdb.org/docs/current/python/api.html](https://www.duckdb.org/docs/current/python/api.html) suggests to create an in-memory database using `con = duckdb.connect(':memory:')`. On Windows, this causes the Python process to crash. The underlying issue is that the `BufferManager` wants to create a `:memory:.tmp` folder which is not a valid folder name on Windows. 

A quick fix is to choose `.tmp` as temporary_directory, regardless of whether `""` or `":memory:"` was passed as dbdir/path. I have a pull request ready for that.

------

In the course of fixing this I also encountered irregularities in the handling of the `""` and `":memory:"` parameters between the Python/R API and the CLI.

- Python API:
  - `":memory:"` -> crash (*now fixed*) ❌  -> ✔️ creates .tmp
  - `""` -> ✔️ creates .tmp 
- R API:
  - `":memory:"` -> ❌ does not create .tmp
  - `""` -> ❌ does not create .tmp
- DuckDB CLI:
  - `":memory:"` -> ❌does not create .tmp
  - `""` -> ✔️creates .tmp

If no temporary folder was created, the BufferManager will throw an IOException if the optional `memory_limit` gets exceeded. It is probably a rare case, but I would suggest to align the behavior across the different interfaces. It is an easy fix. Just not sure, which one reflects the intended behavior.

------

It is not in scope of this issue, but in general, the error handling of the Python API should be improved to the point that exceptions from within the duckdb package do not affect the Python process itself.

**Comment by hannesmuehleisen** [comment]
I agree this should be consistent!

**Comment by Mytherin** [comment]
This should be fixed now
