### ISSUE TITLE
duckdb fails to install on R version 3.6.2 on Windows 10

### ISSUE THREAD

**Issue by joysan7** [cwida/duckdb#441]
I tried to install duckdb in RStudio Version 1.3.820 running R version 3.6.2 on Windows 10 via method described in https://www.duckdb.org/docs/current/tutorials/installation.html

I'm pasting the console here:

```
> remotes::install_github("cwida/duckdb/tools/rpkg", build = FALSE)
Downloading GitHub repo cwida/duckdb@master
Installing package into ‘C:/Users/DAC-04/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'duckdb' ...
** using staged installation

   **********************************************
   WARNING: this package has a configure script
         It probably needs manual configuration
   **********************************************


** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.2/include" -DNDEBUG       -I.   -O2 -Wall  -mtune=generic -c duckdbr.cpp -o duckdbr.o
duckdbr.cpp:1:20: fatal error: duckdb.h: No such file or directory
 #include "duckdb.h"
                    ^
compilation terminated.
make: *** [C:/PROGRA~1/R/R-36~1.2/etc/x64/Makeconf:215: duckdbr.o] Error 1
ERROR: compilation failed for package 'duckdb'
* removing 'C:/Users/DAC-04/Documents/R/win-library/3.6/duckdb'
Error: Failed to install 'duckdb' from GitHub:
  (converted from warning) installation of package ‘D:/rTemp/Rtmpy43djl/remotes2f5c27c21512/cwida-duckdb-fb28e87/tools/rpkg’ had non-zero exit status
> 
```
Any insights?

Background: I'm currently working with 84 GB csv file with disk.frame package. I'm also playing with sparklyr package saving data as parquet. It would be convenient to use RDBMS methods but I don't want to install Postgres. If duckdb could allow importing large csv, running queries and export results to csv, it would be nice.

**Comment by hannesmuehleisen** [comment]
Yes this is a documentation issue, apologies. Try:

`install.packages("duckdb", repos=c("http://download.duckdb.org/alias/master/rstats/", "http://cran.rstudio.com"))`

This should even give you the binary version on Windows.

**Comment by hannesmuehleisen** [comment]
Updated the documentation accordingly

**Comment by san-r** [comment]
It worked. Thanks for fast response. Please try adding practical examples to documentation, especially about working with large files where RDBMS are supposed to shine.
