### ISSUE TITLE
Make a DuckDB homebrew package

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#446]
We would like to be able to install DuckDB with `brew install duckdb`.

**Comment by hannesmuehleisen** [comment]
Added bonus for scripting the version update for the package, although we might be able to get away with using the `master` branch always.

**Comment by ankane** [comment]
Hey @hannesmuehleisen, happy to help out here. I started a Homebrew formula here: https://github.com/Homebrew/homebrew-core/compare/master...ankane:duckdb

The current issue is DuckDB builds its own version of 3rd party libraries, which can conflict with Homebrew installed libraries.

```txt
-- Installing: /usr/local/Cellar/duckdb/0.1.7/lib/libhyperloglog.a
-- Installing: /usr/local/Cellar/duckdb/0.1.7/lib/libfmt.a
-- Installing: /usr/local/Cellar/duckdb/0.1.7/lib/libpg_query.a
-- Installing: /usr/local/Cellar/duckdb/0.1.7/lib/libre2.a
-- Installing: /usr/local/Cellar/duckdb/0.1.7/lib/libminiz.a
-- Installing: /usr/local/Cellar/duckdb/0.1.7/lib/libutf8proc.a
```

It look likes Homebrew has formulas for `fmt`, `re2`, and `utf8proc`, so if there was a CMake flag to use system libraries when available, I think this could be added.

Build log: https://github.com/ankane/homebrew-core/runs/702845273?check_suite_focus=true

**Comment by hannesmuehleisen** [comment]
Hey @ankane thanks for getting started on this! Why do you think these libraries conflict? We statically link them into our binaries. I would not use system libraries because we modified some of them quite heavily. For the releases, I removed the prerelease tag from the last release 0.1.7.

**Comment by ankane** [comment]
Re tag: thanks!

The library builds successfully, but `make install` installs the libraries mentioned above. From the build log:

```txt
The formula built, but is not symlinked into /usr/local
Could not symlink lib/libutf8proc.a
Target /usr/local/lib/libutf8proc.a
is a symlink belonging to utf8proc. You can unlink it:
  brew unlink utf8proc
```

The error message mentions a symlink since instead of installing directly into `/usr/local`, Homebrew uses a custom `CMAKE_INSTALL_PREFIX` and then creates symlinks to `/usr/local`, essentially mirroring the default `make install` behavior.

Homebrew has a utf8proc formula, so installing a separate version of `libutf8proc.a` conflicts with it.

**Comment by ankane** [comment]
I updated the formula to only install the CLI for now. https://github.com/Homebrew/homebrew-core/compare/master...ankane:duckdb

I can try to submit to Homebrew as is if there's not an easy solution to the `lib` issue. Let me know what you'd prefer.

**Comment by hannesmuehleisen** [comment]
I think we need to update the install target in CMake to use the amalgamation

**Comment by ankane** [comment]
That would do it. Thanks @hannesmuehleisen! Submitted here: https://github.com/Homebrew/homebrew-core/pull/55227

**Comment by ankane** [comment]
Was just accepted, so Mac users can now do:

```sh
brew install duckdb
```

**Comment by ankane** [comment]
Also, it looks like the C headers aren't included in the amalgamation build. Noticed it when trying to install the Ruby client, which finds the library correctly (`-lduckdb`) but not `duckdb.h`. Is this something that could be added?

**Comment by dtrodrigues** [comment]
> Hey @ankane thanks for getting started on this! Why do you think these libraries conflict? We statically link them into our binaries. I would not use system libraries because we modified some of them quite heavily. For the releases, I removed the prerelease tag from the last release 0.1.7.

Can the prerelease tag be removed from 0.1.8 -- https://github.com/Homebrew/homebrew-core/pull/56059 ?

**Comment by hannesmuehleisen** [comment]
@dtrodrigues have done that, sorry

**Comment by dtrodrigues** [comment]
Thanks!

**Comment by hannesmuehleisen** [comment]
This exists now https://formulae.brew.sh/formula/duckdb

**Comment by ankane** [comment]
Hey @hannesmuehleisen, what do you think about including the C headers in the amalgamation build (re: https://github.com/cwida/duckdb/issues/446#issuecomment-633657597)? This would allow the Ruby bindings to work with the Homebrew version.

**Comment by hannesmuehleisen** [comment]
@ankane I'm not opposed to this. Could you send a PR?

**Comment by kojiromike** [comment]
When I installed duckdb with homebrew, it didn't have support for `parquet_scan`, even though it was 0.2.9, the latest version as of now. However, the macos binary does support that table function. Is there a way to enable `parquet_scan` with the homebrew-installed duckdb?

**Comment by omo** [comment]
I guess you can ask update on the homebrew side to have `-DBUILD_PARQUET_EXTENSION`

 * https://github.com/Homebrew/homebrew-core/blob/master/Formula/duckdb.rb
