### ISSUE TITLE
In Python, fetchdf and fetchnumpy segfault while fetchall works 

### ISSUE THREAD

**Issue by lepennec** [cwida/duckdb#447]
Hi,

I'm playing with duckdb in Python and I've stumbled with a segfault issue:
````Python
import duckdb 
con = duckdb.connect(':memory:')                                        
c = con.cursor() 
c.execute("CREATE TABLE items(item VARCHAR, value DECIMAL(10,2), count INTEGER)") 
c.execute("INSERT INTO items VALUES ('jeans', 20.0, 1)") 
c.execute("SELECT * FROM items") 
print(c.fetchall()) 
df = c.execute("SELECT item FROM items").fetchdf() 
print(df)                                                               
````
I've got the same issue with fetchnumpy.

I'm using Python 3.7.6 with a Fedora 31 Linux distribution and I've installed duckdb with pip.

Please let me know how I can help.

Thank you,

Erwan

**Comment by hannesmuehleisen** [comment]
Confirmed.  Its the `VARCHAR` that breaks this. I think this might be related to a recent change with string types, we are probably missing a test case. You can help by adding those? See `tools/pythonpkg/tests`.

**Comment by lepennec** [comment]
Here is an attempt:
https://github.com/cwida/duckdb/pull/448

**Comment by hannesmuehleisen** [comment]
This should be fixed now, but you will have to install from the repo till the next pip release.

**Comment by lepennec** [comment]
And it's working perfectly.
