### ISSUE TITLE
DATE type is not converted correctly in Python

### ISSUE THREAD

**Issue by lepennec** [cwida/duckdb#456]
I'm playing with both R and Python and I've stumbled with a difference with respect to the DATE type.
Whereas it is correctly converted in R, it is extracted as an int32 in Python.
```
c.execute("SELECT DATE '2020-01-10' as test_time").fetchnumpy()

{'test_time': masked_array(data=[737799],
              mask=False,
        fill_value=999999,
             dtype=int32)}
```
where c is a cursor to a db. I assume that the return value should be of Date python type.

I see in the Python package code that there is a special handling for the DATETIME type but none for the DATE one, so I assume this is the reason.

I've tried to build a skeleton for the DATE type at:
https://github.com/lepennec/duckdb/tree/date
but this is not (yet) working as I don't know (yet) the inner code of duckdb. 

Are you interested in such a pull request?

Erwan

**Comment by hannesmuehleisen** [comment]
Yes, please send a PR

**Comment by lepennec** [comment]
OK. I will try to work on it.

Erwan

**Comment by lepennec** [comment]
Here it is:
https://github.com/cwida/duckdb/pull/458
