### ISSUE TITLE
duckdf - SQL for R dataframes

### ISSUE THREAD

**Issue by phillc73** [cwida/duckdb#459]
Once upon a time in R land there was the [sqldf](https://github.com/ggrothendieck/sqldf) package. In short, it allows one to query R dataframes using SQL syntax in a single line function. Originally, `sqldf` just used sqlite as a back-end, but now supports other server based databases too.

I've just created a very basic [`duckdf`](https://github.com/phillc73/duckdf) package which does something similar, in not so nearly a comprehensive way, for `duckdb`.

```r
library(duckdf)
duckdf("SELECT mpg, cyl FROM mtcars WHERE disp >= 200")
```
It's really just a set of convenience wrappers around the basic `DBI` functions.

Anyway, I thought you might be interested. I would appreciate all feedback and input.

My imagined next step is to incorporate csv reading with [`COPY`](https://www.duckdb.org/docs/current/sql/copy.html)

**Comment by hannesmuehleisen** [comment]
This looks great, thanks! How is the table creation handled, is every data frame in the current scope written to DuckDB? We were thinking about something along these lines, where we lazily wrap the data frame so actual writing would not be required...

**Comment by phillc73** [comment]
In reality mine is a pretty brittle implementation as a first approach. The supplied SQL query is string split and whatever word follows "FROM" is assumed to be the dataframe required. `dbWriteTable()` is then used to create a `duckdb` db.

This doesn't support JOINs yet, but should work quite fine for other queries working on only a single dataframe.

I'd for sure be interested to hear more about your lazy wrapping approach.

The current functions are quicker than those in `sqldf`, but much less robust I suspect, and still a long way short of the speed of `data.table`.

**Comment by hannesmuehleisen** [comment]
We plan to add a feature that allows you to register a R data frame as a virtual table in a DuckDB instance. The `duckdf` package could use that by looking at the current environment and registering all data frames as virtual tables. Would that work for you?

**Comment by phillc73** [comment]
That sounds pretty good actually and sure to make things quicker.

**Comment by hannesmuehleisen** [comment]
For now, is there anything we should do from a duckdb perspective to better support `duckdf` besides the wrapping of R tables?

**Comment by phillc73** [comment]
I don't think so. I have a few development tasks to complete, such as adding the CSV loading code, but in general it just needs more users to file the bugs!

**Comment by hannesmuehleisen** [comment]
I have added a link to duckdf to our website, closing this for now.

**Comment by hannesmuehleisen** [comment]
@phillc73 We now have support for registering data frames as tables:

```R
library("DBI")
con <- dbConnect(duckdb::duckdb())
df <- data.frame(col_1=c(1, 2, 3), 
	col_2=c("one", "two", "three"))

duckdb::duckdb_register(con, "df_view", df)

dbGetQuery(con, "SELECT * FROM df_view LIMIT 2")
````

**Comment by phillc73** [comment]
@hannesmuehleisen Great! I'll look to implement this in [duckdf](https://github.com/phillc73/duckdf) this week.
