### ISSUE TITLE
Import local data in R

### ISSUE THREAD

**Issue by waynelapierre** [cwida/duckdb#460]
I am looking for a function similar to the monetdb.read.csv in MonetDBLite in the R packge duckdb to import a local data set to duckdb.

**Comment by hannesmuehleisen** [comment]
I ported the `monetdb.read.csv` function to DuckDB, once my linked PR is merged this will be available as `duckdb.read.csv` or `read_csv_duckdb`. The parameters are mostly the same to allow use as drop-in replacement as far as possible.
