### ISSUE TITLE
Weird (?) behaviour of dbConnect

### ISSUE THREAD

**Issue by jfb-h** [cwida/duckdb#461]
I am trying to load the PATSTAT EU patent statistics database into an on-memory duckDB with R.

I noticed that when I create a local db with 
`con = dbConnect(duckdb::duckdb(), dbdir = "C:/Users/Jakob/Documents/PATSTAT/DuckDB/PATSTAT.duckdb")` , create and fill tables and then close the db with `dbDisconnect(con)`, all the data seems to sit in the .wal file, judging by size. When I open the db again in a new session via` dbConnect()`, it seems that the data is transferred to the .duckdb file, which takes a lot of time and a lot of memory.

 I was wondering whether this is expected behaviour or a bug or whether I just messed things up (as I'm pretty new to DuckDB and databases in general).

**Comment by hannesmuehleisen** [comment]
See #301 and #420
