### ISSUE TITLE
Unexpected memory behavior in R?

### ISSUE THREAD

**Issue by edrubin** [cwida/duckdb#464]
First off: Thank you for starting such an amazing project.

I'm observing some unexpected behavior when creating DuckDB databases from R.

1. When creating the database from some in-memory object, writing the database requires **more** memory (RAM) than the size of the object.
2. The **first** time I connect to the new database (after disconnecting), memory spikes for a while—maxing out at about 1/2 of the object's actual memory.

Are these behaviors expected? (I replicated my work with SQLite via `RSQLite` and did not observe the same behaviors.) 

I'm new to DuckDB—and DBs—so I apologize if this behavior is clearly expected and I'm missing something obvious. 

I wrote up a little script to track R's memory throughout the process and labeled the different changes (y-axis is percentage of my memory, which is 32GB; I tried a similar task on a much larger Ubuntu workstation with 128GB of RAM and had a similar issue).

![duck-memory-test-labeled](https://user-images.githubusercontent.com/6801166/77124289-ae4bc680-69ff-11ea-87ee-a3916a47bbbf.png)

The R code underlying this figure:

```R

# Setup ------------------------------------------------------------------------
  # Packages
  library(pacman)
  p_load(tidyverse, duckdb, parallel, data.table, magrittr, here)

Sys.sleep(10)

# Build dataset ----------------------------------------------------------------
  # Create a big-ish data table
  tmp = mclapply(
    X = 1:10,
    FUN = function(i) {
      data.table(
        x1 = rnorm(1e7),
        x2 = rnorm(1e7),
        x3 = rnorm(1e7),
        x4 = rnorm(1e7),
        x5 = rnorm(1e7)
      )
    },
    mc.cores = 10
  ) %>% rbindlist()
  # Garbage control
  invisible(gc())

Sys.sleep(10)

# Build database ---------------------------------------------------------------
  # Create connection
  duck_con = dbConnect(duckdb::duckdb(), here("test-duck-memory"))
  # Write the file to the database
  dbWriteTable(
    conn = duck_con,
    name = "flights",
    value = tmp,
    append = T
  )
  # Disconnect
  dbDisconnect(duck_con, shutdown = T)
  duckdb::duckdb_shutdown(duckdb::duckdb())
  rm(duck_con)
  invisible(gc())

Sys.sleep(10)

# Clean up ---------------------------------------------------------------------
  # Drop the dataset
  rm(tmp)
  invisible(gc())

Sys.sleep(10)

# Connect ----------------------------------------------------------------------
  # Connect
  duck_con = dbConnect(duckdb::duckdb(), here("test-duck-memory"))
  # Disconnect
  dbDisconnect(duck_con, shutdown = T)
  duckdb::duckdb_shutdown(duckdb::duckdb())
  rm(duck_con)
  invisible(gc())

Sys.sleep(10)

# Connect again ----------------------------------------------------------------
  # Connect
  duck_con = dbConnect(duckdb::duckdb(), here("test-duck-memory"))
  # Disconnect
  dbDisconnect(duck_con, shutdown = T)
  duckdb::duckdb_shutdown(duckdb::duckdb())
  rm(duck_con)
  invisible(gc())

Sys.sleep(10)

# Connect once more ------------------------------------------------------------
  # Connect
  duck_con = dbConnect(duckdb::duckdb(), here("test-duck-memory"))
  # Disconnect
  dbDisconnect(duck_con, shutdown = T)
  duckdb::duckdb_shutdown(duckdb::duckdb())
  rm(duck_con)
  invisible(gc())

Sys.sleep(10)
```

**Comment by hannesmuehleisen** [comment]
Very nice analysis! By default DuckDB uses memory as available for caching purposes. You can set a memory limit like so: `PRAGMA memory_limit='10GB';` With this, you should be able to control the amount of memory while loading. You may have to load the data in chunks with a commit in between to fully achieve this, see also #321

**Comment by edrubin** [comment]
@hannesmuehleisen Thank you so much for your response (and kind words), and sorry for my slow response (things are a *little* crazy right now).

One quick follow up (perhaps helpful to other rookies like me): Am I correct in understanding that the `PRAGMA memory_limit='10GB'` solution only works while working in the shell (as suggested in #321 for Python)? Or is there a way to set the limit from within R (*e.g.*, how `RSQLite` has implemented setting `cache_size`)?

I tried setting the memory limit from within R via
```R
dbExecute(some_con, "PRAGMA memory_limit='4GB'")
```
but it did not appear to work.

Quick additional question: Could this behavior explain issues in #322?

Thank you again for your work and your response!

**Comment by rfsaldanha** [comment]
I am observing the same with currently. Any advance about how to declare `PRAGMA memory_limit` within R?

**Comment by hannesmuehleisen** [comment]
`dbExecute(con, "PRAGMA memory_limit=10GB")` for example?

**Comment by rfsaldanha** [comment]
Thank you! Just had to include quotes: `dbExecute(con, "PRAGMA memory_limit='10GB'")`.
