### ISSUE TITLE
COPY for csv import tries to import header when it shouldn't in R

### ISSUE THREAD

**Issue by phillc73** [cwida/duckdb#466]
Trying to use the COPY functionality to read in a csv file, as [documented here](https://www.duckdb.org/docs/current/sql/copy.html)

Specifically:
```
-- Copy the contents of a comma-separated file 'test.csv' without a header into the table 'test'
COPY test FROM 'test.csv';
```

However, in R, COPY appear to be trying to write the csv file headers to the existing duckdb table, which can throw a type mismatch error.

Example code:

```r
# write mtcars to csv
write.csv(mtcars, "mtcars.csv")

# read in mtcars csv with base R and check col types
mtcars_csv_test <- read.csv("mtcars.csv", stringsAsFactors = FALSE)
str(mtcars_csv_test)
# NB: mpg col is of type numeric

# make mtcars dataframe rownames a column
mtcars <- DBI::sqlRownamesToColumn(mtcars, "model")

# create a DuckDB connection
con <- DBI::dbConnect(duckdb::duckdb(), ":memory:")

# Initially write a new table to the db with mtcars dataframe
DBI::dbWriteTable(con, "mtcars", mtcars)

# check table exists and the columns
dbListTables(con)
dbListFields(con, "mtcars")

# Read in same mtcars data from csv file and try to write to db
DBI::dbExecute(con, "COPY mtcars FROM 'mtcars.csv'")
```

This throws the following error:

```r
Error in dbSendStatement(conn, statement, ...) : 
  duckdb_query_R: Failed to run query COPY mtcars FROM 'mtcars.csv'
Error: Conversion: Could not convert string 'mpg' to numeric
```

The only way I can think to interpret this error is COPY is trying to write the header, with strings, to existing numeric columns.

**Comment by Mytherin** [comment]
If the CSV has a header, you can use the HEADER parameter to instruct the system to ignore the header, as follows:

```sql
-- Copy the contents of a comma-separated file with a header into the 'category' table
COPY category FROM 'categories.csv' ( HEADER );
```

Could you check if that works for you?

**Comment by phillc73** [comment]
Yes that works.

Apologies, but I see now I misinterpreted the way in which the documentation has been written.

```
-- Copy the contents of a comma-separated file 'test.csv' without a header into the table 'test'
COPY test FROM 'test.csv';
``
I thought this meant copy all data from a csv, but without the header. Not that the csv file has no header.

```
-- Copy the contents of a comma-separated file with a header into the 'category' table
COPY category FROM 'categories.csv' ( HEADER );
```

And I thought this meant copy the content from the csv file, including the header, to the table. Not that this would drop the header if present.

I understand now and it works fine. Thanks.

**Comment by Mytherin** [comment]
No worries, great that it worked :) CSV files can be annoying. One of our goals is to make the CSV reader automatically detect such common patterns in CSV files.
