### ISSUE TITLE
Segfault on fetchall() with empty cursor

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#485]
This produces a segfault for me in the function `duckdb_cursor_iternext(duckdb_Cursor*) + 158 (cursor.cpp:645)`:

```python
import duckdb
con = duckdb.connect(':memory:')
c = con.cursor()
c.fetchall()
```

**Comment by hannesmuehleisen** [comment]
I get `RuntimeError: no open result set` with your example (as one would expect). Could you be more specific?

**Comment by Mytherin** [comment]
Turns out this was my bad: I cross-compiled wrong versions together :) Closing this issue
