### ISSUE TITLE
SIMILAR TO results in an "Unknown error -1"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#493]
Consider the following statement:

```sql
SELECT '' SIMILAR TO ''; -- Error: Unknown error -1
```
While I would expect the statement to fetch `{true}`, it returns an error `Error: Unknown error -1`. According to the [documentation](https://www.duckdb.org/docs/current/sql/functions/regex.html), this should work.

I found this based on commit d7964630b45facae0b2965b302849e4bc240459c.

**Comment by mrigger** [comment]
This seems to only affect the release build, and not the debug build.

**Comment by Mytherin** [comment]
Good catch, will take another look.

**Comment by Mytherin** [comment]
Seems to be [this error](https://stackoverflow.com/questions/51584960/stdcall-once-throws-stdsystem-error-unknown-error-1) being thrown by RE2, that uses the std::call_once in the init. Will look into removing that.

**Comment by Mytherin** [comment]
This commit fixes it for me 403219728c302ad1eba1cf9e30934b85539a8945, could you check if that works for you too? Thanks!

**Comment by mrigger** [comment]
Yes, it works for me as well. Thanks for the fix!
