### ISSUE TITLE
Comparison on UNIQUE NUMERIC column causes a query to omit a row in the result set

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#495]
Consider the following statements:

```sql
CREATE TABLE t0(c0 NUMERIC UNIQUE);
INSERT INTO t0(c0) VALUES (1163404482), (0), (488566);
SELECT * FROM t0 WHERE 0.1 < c0; -- expected: {}, actual: {1163404482.0, 488566.0}
```
I would expect the query to fetch two rows. However, only one is fetched. When omitting the `UNIQUE` constraint, the result is as expected (i.e., two rows are fetched). This bug seems to affect only `NUMERIC` columns and cannot be reproduced with `INT` or `REAL`. The bug seems to be sensitive to the numbers' magnitudes. For example, removing a digit from either `1163404482` or `488566` causes DuckDB to fetch the expected result set.

I found this bug based on commit d7964630b45facae0b2965b302849e4bc240459c.

**Comment by Mytherin** [comment]
Looks like this is related to the ART index, perhaps @pdet can take a look?

**Comment by mrigger** [comment]
I found a number of test cases where an incorrect result set is fetched when using an index. I noticed that all of these test cases require at least three rows to be inserted. I suspect that many (all?) of them  trigger the same underlying bug. Maybe this information helps with debugging @pdet.

**Comment by Mytherin** [comment]
This is likely caused by the ART index having a bug related to prefix suppression, which is why it is also data dependent. Indeed that will only be triggered when there are multiple elements in the index that are sufficiently different (i.e. have a different prefix).
