### ISSUE TITLE
[Feature request] querying the database schema

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#498]
SQLancer queries the DBMS under test to retrieve the database schema. From what I saw, there is currently no way of listing the columns and data types of a view, which blocks me from testing views. It would be great if there was something like `PRAGMA table_info` to get this information. It seems that there is also no way of listing the tables and views in database. I'm currently just trying names of a fixed format to check if they exist. Having something like `SHOW TABLES` would be useful. The same goes for indexes.

**Comment by Mytherin** [comment]
Good idea, I will expand the `PRAGMA table_info` to support views in the PR I am making right now.

As for querying the schema - we support `SELECT * FROM sqlite_master()` (note: as a function) that has the same semantics as `sqlite_master` from sqlite. We do plan to add `SHOW TABLES` and such as well. Currently there is nothing yet for indexes - I will look into adding something for that later as well.

**Comment by mrigger** [comment]
Okay, great! Thanks for pointing out `SELECT * FROM sqlite_master()`. That is really helpful for me!

**Comment by Mytherin** [comment]
Is there current implementation of `SHOW TABLES/DESCRIBE [table]` sufficient? Or are there more features w.r.t. schema querying that you are missing?

**Comment by mrigger** [comment]
I just tried it and it works as needed for SQLancer. Thanks for implementing this!

**Comment by Mytherin** [comment]
No worries :) Thanks for all the bugs you are finding! It is extremely helpful. I will close this issue then.
