### ISSUE TITLE
SELECT causes JDBC driver to crash

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#500]
Consider the following statements (note that the newline is significiant):

```sql
CREATE TABLE t0(c0 VARCHAR, c1 DOUBLE);
CREATE TABLE t1(c0 DOUBLE, PRIMARY KEY(c0));
INSERT INTO t0(c0) VALUES (0), (0), (0), (0);
INSERT INTO t0(c0) VALUES (NULL), (NULL);
INSERT INTO t1(c0) VALUES (0), (1);

SELECT t0.c0 FROM t0, t1; -- A fatal error has been detected by the Java Runtime Environment
```

When executing the statements using the Java code below, the JVM crashes:

```java
Connection con = DriverManager.getConnection("jdbc:duckdb:");
for (String s : fileContent.split("\n")) {
    try (Statement st = con.createStatement()) {
        try {
            st.execute(s);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
con.close();
```

Note that for the newline, the following exception is thrown:
```
java.sql.SQLException: No statement to prepare!
	at nl.cwi.da.duckdb.DuckDBNative.duckdb_jdbc_prepare(Native Method)
	at nl.cwi.da.duckdb.DuckDBStatement.execute(DuckDBStatement.java:22)
	at reproduce.ExecuteDuckDB$2.run(ExecuteDuckDB.java:51)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
The original test case that crashed the JVM did not have a newline in it.

The logs suggest that the following was executed during the crash:
```
j  nl.cwi.da.duckdb.DuckDBNative.duckdb_jdbc_fetch(Ljava/nio/ByteBuffer;)[Lnl/cwi/da/duckdb/DuckDBVector;+0
j  nl.cwi.da.duckdb.DuckDBResultSet.<init>(Lnl/cwi/da/duckdb/DuckDBStatement;Ljava/nio/ByteBuffer;)V+34
j  nl.cwi.da.duckdb.DuckDBStatement.execute(Ljava/lang/String;)Z+36
```
I found this bug based on commit c2ce42268b23967de165a0c54460b6c974c5e3e1.

**Comment by hannesmuehleisen** [comment]
confirmed. I suspect its an issue with an empty statement indeed.

**Comment by mrigger** [comment]
I noticed from 2a48f95's commit message that you cannot reproduce this. I built DuckDB based on this commit, but the JVM still crashes. I've uploaded a complete log of the crash at https://gist.github.com/mrigger/237db7a4561ab45254d3c66b98bcd41f, in case that helps.

While reducing my reproduction test runner, I figured out that the crash only occurs when some code runs before connecting to DuckDB, which might explain why you couldn't reproduce this. The minimal test runner, which makes the crash reproducible for me for every execution is available at https://gist.github.com/mrigger/665e49d3a1db3c30bcaba0c86cc05721. Note that the directory `logs/DuckDB` is empty for me.

**Comment by hannesmuehleisen** [comment]
@mrigger thanks! indeed that makes the thang crash reliably.

**Comment by mrigger** [comment]
Great! Sorry for not providing my test runner earlier. It's the first time I've stumbled onto a bug where the code that is executed before connecting to the DBMS affected a crash.

**Comment by hannesmuehleisen** [comment]
@mrigger I think we fixed it in the `rigger` branch. Can you check it out please?

**Comment by mrigger** [comment]
I can confirm that this works now. Thanks!
