### ISSUE TITLE
duckdb.org website issue

### ISSUE THREAD

**Issue by phillc73** [cwida/duckdb#502]
Not sure if this is the right place to post this, nor exactly how to trouble shoot it.

Around 50% of the time I visit the duckdb.org website I see an "Under Construction" message.

![duckdbwebsite_error](https://user-images.githubusercontent.com/815126/78935781-b1d9e700-7aad-11ea-8363-41836abb0d01.png)

A hard `shift-refresh` once or more times fixes the issue.

Browser is Firefox, multiple versions as it's been happening for a few weeks and I've updated to the latest version of Firefox. Currently 74.0.1. Windows and Linux.

**Comment by Mytherin** [comment]
This is the right place to post this! Maybe a problem relating to the DNS or to HTTPS? We don't do our own hosting as the website is simply a Github pages entry. Perhaps @hannesmuehleisen can take a look.

**Comment by phillc73** [comment]
Could be a certificate problem (see the small yellow triangle near the lock). I don't have that when the website loads correctly.

Checking my browser I have an exception added for duckdb.org for a certificate which expired in 2018.

![hannescert2](https://user-images.githubusercontent.com/815126/78939815-16e50b00-7ab5-11ea-97d1-04c3a4f72167.png)

![hannescert](https://user-images.githubusercontent.com/815126/78939826-1a789200-7ab5-11ea-8a58-a620d1934f30.png)

I've deleted that certificate now and will update this issue if I still see the "Under Construction" message in the coming days.

**Comment by hannesmuehleisen** [comment]
This seems odd and is the first time I have heard of this. The current cert is valid till 10 June 2020, so it might indeed be related to the exception. Why was the exception required in the first place? We paid money to have a proper cert...

**Comment by phillc73** [comment]
This morning, after deleting the certificate last night, I am asked to add the exception again.

![duckdbwarning](https://user-images.githubusercontent.com/815126/78976577-bbe40000-7b16-11ea-91b7-74caed3a2427.png)

A hard `shift-refresh` eventually loads the website.

**Comment by hannesmuehleisen** [comment]
Strange, just tried with firefox and can't see that. Is your system clock all right? Also, is there any more information behind "Learn more" and "Advanced"?

**Comment by phillc73** [comment]
Yes, system clock is fine. When (if) I see the error again, I'll screen shot the `Learn more...` and `Advanced` expansions.

**Comment by phillc73** [comment]
Happened again this morning.

`Learn more...` links [here](https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect?as=u&utm_source=inproduct).

`Advanced` opens the following dialog:

![Screenshot from 2020-04-11 11-12-17](https://user-images.githubusercontent.com/815126/79039979-5c085a80-7be5-11ea-87ce-f0c58f39f5f0.png)

As usual, a hard refresh eventually fixes the problem. I've also tried clearing my browser cache before going to the URL.

**Comment by arjenpdevries** [comment]
![image](https://user-images.githubusercontent.com/642221/79052347-2049b100-7c36-11ea-813d-baf112d06be1.png)
Same here

**Comment by arjenpdevries** [comment]
![image](https://user-images.githubusercontent.com/642221/79052455-f6dd5500-7c36-11ea-8fb1-782fb6fe584a.png)

It seems somehow directed to the muehleissen site and using an expired cert there - but I am far from an expert here :-)

**Comment by Mytherin** [comment]
Hm, perhaps this is a DNS issue then?

**Comment by arjenpdevries** [comment]
```
[arjen@bm 2020]$ host duckdb.org
duckdb.org has address 185.199.108.153
duckdb.org has address 185.199.109.153
duckdb.org has address 185.199.111.153
duckdb.org has address 185.199.110.153
duckdb.org mail is handled by 50 mx0.duckdb.org.
```

Those are not the `github` pages servers I think?

**Comment by arjenpdevries** [comment]
If I use `curl` instead of FF, I get a page saying `301 Moved Permanently`

**Comment by arjenpdevries** [comment]
But...
```
 1047  curl https://www.duckdb.org
 1048  curl -4 https://www.duckdb.org
```
First gives
```url: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

Second gives HTML output that is probably correct.

**Comment by arjenpdevries** [comment]
See the difference between `duckdb.org` and `cwida.github.io` that should be aliases I suspect - they mention different certificates.

```
[arjen@bm 2020]$ host -a cwida.github.io
Trying "cwida.github.io"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41625
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;cwida.github.io.               IN      ANY

;; ANSWER SECTION:
cwida.github.io.        3600    IN      CAA     0 issuewild "digicert.com"
cwida.github.io.        3600    IN      CAA     0 issue "digicert.com"
cwida.github.io.        3600    IN      A       185.199.108.153
cwida.github.io.        3600    IN      A       185.199.111.153
cwida.github.io.        3600    IN      CAA     0 issue "letsencrypt.org"
cwida.github.io.        3600    IN      A       185.199.109.153
cwida.github.io.        3600    IN      A       185.199.110.153

Received 197 bytes from 192.168.178.1#53 in 14 ms
[arjen@bm 2020]$ host -a duckdb.org
Trying "duckdb.org"
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8066
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;duckdb.org.                    IN      ANY

;; ANSWER SECTION:
duckdb.org.             83884   IN      NS      ns1.hans.hosteurope.de.
duckdb.org.             44      IN      SOA     ns1.hans.hosteurope.de. hostmaster.duckdb.org. 2019062812 16384 2048 1048576 2560
duckdb.org.             83884   IN      A       185.199.108.153
duckdb.org.             83884   IN      A       185.199.109.153
duckdb.org.             83884   IN      A       185.199.110.153
duckdb.org.             83884   IN      NS      ns2.hans.hosteurope.de.
duckdb.org.             83884   IN      A       185.199.111.153

Received 193 bytes from 192.168.178.1#53 in 4 ms
```

**Comment by Mytherin** [comment]
Thanks for the investigative work! That could indeed be the problem. Will need Hannes to take a look though, as I don't have access to the DNS/certificates.

**Comment by hannesmuehleisen** [comment]
Super odd, but will have a look

**Comment by hannesmuehleisen** [comment]
There was a rogue `AAAA` DNS entry, I have removed it, could you try again?

**Comment by phillc73** [comment]
@hannesmuehleisen I don't immediately see the problem again. If you've made the DNS change, I think this may as well be closed and can be re-opened if the problem isn't solved.
