### ISSUE TITLE
Creating an empty table results in a crash

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#507]
Consider the following statement:

```sql
CREATE TABLE t0();
```
Unexpectedly, the `CREATE` results in a segfault:
```
SQLite version DuckDB 340d867b
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE t0();
Segmentation fault
```
I found this bug on the latest commit on master (340d867b232b56faf198594e40adba733ecb7bc8) using a SQL reducer developed by Jonas Müntener, starting from a different crash bug.

**Comment by Mytherin** [comment]
Fixed this in a56a90108d8e0e012abbbd0b97bfc224555c6a11 by disallowing the creation of empty tables. PostgreSQL does allow this, with I assume the idea that you can later add on columns (using `ALTER TABLE`), but for us currently we feel the drawbacks of allowing this outweigh the benefits. SQLite and MySQL also don't allow the creation of empty tables.
