### ISSUE TITLE
LEFT JOIN with comparison on integer columns results in "Not implemented: Unimplemented type for nested loop join!"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#513]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t1(c0) VALUES (0);
INSERT INTO t0(c0) VALUES (0);
SELECT * FROM t0 LEFT JOIN t1 ON t0.c0 <= t1.c0; -- Not implemented: Unimplemented type for nested loop join!
```
Unexpectedly, the `SELECT` results in an error `Error: Not implemented: Unimplemented type for nested loop join!`.

I can reproduce this on the latest master (commit c52fc9bafd22e41a5554d3305530ebc1bf8364f9) and the current fix branch (commit 5c4cde52e3c3ddc4ad4d78a7adf0101f7e61861f).

**Comment by Mytherin** [comment]
I added support for LEFT JOINs in the nested loop join in 215e40cd5cdb7eee68797df4982219c63f04e2a9, so this should work now :)
