### ISSUE TITLE
Query with a negative shift predicate yields an incorrect result

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#515]
Consider the following statements:

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT8, c1 DOUBLE);
INSERT INTO t1(c0) VALUES (0);
INSERT INTO t1(c1, c0) VALUES (1, 1);
INSERT INTO t0 VALUES (0);
SELECT * FROM t1 JOIN t0 ON t1.c1 WHERE NOT (t1.c0<<-1); -- expected: {1|1|0}, actual: {}
```
Unexpectedly, this query does not fetch a row. That the predicate should evaluate to `TRUE` can be seen through the following:
```sql
SELECT NOT (t1.c0<<-1) FROM t1; -- {true, true}
```
When removing the `NOT`, no row is fetched, which is expected:
```sql
SELECT * FROM t1 JOIN t0 ON t1.c1 WHERE (t1.c0<<-1); -- {}
```

I can reproduce this on the latest master (commit c52fc9bafd22e41a5554d3305530ebc1bf8364f9) and the current fix branch (commit 5c4cde52e3c3ddc4ad4d78a7adf0101f7e61861f).

**Comment by Mytherin** [comment]
Fixed in 7e1234d8f414f1e1de4e15a57939594036d74f37, this had to do with the shift by a negative number triggering undefined behavior. I have modified it so a left or right shift by a negative number results in 0.
