### ISSUE TITLE
Query with comparison on boolean column results in "Invalid type: Invalid Type [BOOL]: Invalid type for index"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#516]
Consider the following statements:

```sql
CREATE TABLE t0(c0 BOOL UNIQUE);
INSERT INTO t0(c0) VALUES (0);
SELECT * FROM t0 WHERE t0.c0 = true; -- Error: Invalid type: Invalid Type [BOOL]: Invalid type for index
```
Unexpectedly, the `SELECT` results in an error `Error: Invalid type: Invalid Type [BOOL]: Invalid type for index`.

I found this issue based on the latest master branch (commit 9795d18b6a6e250a4076fa448f248287e76f5693).

**Comment by Mytherin** [comment]
Fixed in 331cce4a0c88ee1b477d5859de7211c455664349, this is a continuation of #504, with another missing boolean type in the index except now for lookups. All the boolean types should now be properly handled by the index.
