### ISSUE TITLE
Casting a large number to REAL and multiplying it with zero results in -nan

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#522]
Consider the following statement:
```sql
SELECT 1e100::real*0; -- -nan
```

Unexpectedly, the `SELECT` results in `-nan`. As with https://github.com/cwida/duckdb/issues/521, this can cause unexpected results (I discovered this as part of a larger test case where a predicate evaluated to an unexpected value).

I found this based on the latest master commit (c52fc9bafd22e41a5554d3305530ebc1bf8364f9) and also verified that it can be reproduced on the latest fix branch (commit 215e40cd5cdb7eee68797df4982219c63f04e2a9)

**Comment by Mytherin** [comment]
This and #523 triggered some discussion, we are planning to solve this as described in #530.

**Comment by mrigger** [comment]
Okay, I'll stop reporting issues related to NaN values until #530 has been addressed.

**Comment by Mytherin** [comment]
The checks have been added in #541, if you find any instances of NaN or INF appearing please open a bug report now :)

**Comment by mrigger** [comment]
Will do, thanks!
