### ISSUE TITLE
Convert NaN and Infinity to NULL

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#530]
Several floating point operations (see #518, #522, #523) can cause NaN and infinity values to enter the system. This can generally cause confusing behavior, and these values are also not supported by the SQL Standard. Instead, we would like to replace these values with NULL values anywhere where they are generated. We need strict verification to make sure that these values are not accidentally created or inserted into the system anywhere, similar to how we have checks for not allowing invalid UTF8 strings into the system.

**Comment by besquared** [comment]
NaN, Infinity, and -Infinity aren't invalid values and they also aren't NULL. This makes it impossible to clearly define the semantics of things like COUNT(), SUM(), etc. These values have specific floating point representations that need to be checked for when the values are being operated on.

**Comment by Mytherin** [comment]
We have been considering reverting this and allowing special floating point values into the system. I can certainly see why infinity should be treated differently than NULL, but could you perhaps expand on why you would want NaN and NULL to behave differently and would not want to map NaN to NULL on import?

**Comment by rkennedy-mode** [comment]
`NaN` is an actual value, whereas `NULL` indicates no value. So there's a semantic difference when viewed through the lens of:

```sql
SELECT count(float_values) FROM table_with_float_values
```

Handling `NaN` separately from `NULL` there is the difference between counting a value in a given row and not counting it.

**Comment by besquared** [comment]
Well if I understand correctly this patch applies to storage as well. Please correct me if I misunderstand.

If we have a table T with column C and I want to store the (single or double) floating point representations of  [ 1.0f, INFINITY, 2.0f ] and I load it into the system then it will be stored as [ 1.0f, NULL, 2.0f ]. On the surface this already seems bad since the database is no longer accurately reflecting the representation that my application specified.

Additionally when I run SELECT COUNT(C) FROM T I will see that the answer will be incorrect. The correct answer is 3 but the database will return the value 2. This is simply incorrect from the perspective of my application (and more importantly my application's users).

**Comment by besquared** [comment]
Additionally the SQL standard does in fact specify the approximate types FLOAT, REAL, and DOUBLE which are presumably being supported here using IEEE 754. IEEE 754 is very specific about how these values ought to be treated w.r.t. both representations and operations. While I think "IEEE 754 with some exceptions" is ok in some scenarios (snowflake makes exceptions w.r.t. comparison to enable a strict ordering), I don't personally think that removing values from the domain is one of them.

https://en.wikipedia.org/wiki/IEEE_754

**Comment by hannesmuehleisen** [comment]
@besquared we are happy to prioritise this issue for you, email me if you'd like to discuss potential setups hannes@duckdblabs.com

**Comment by Alex-Monahan** [comment]
For Pandas compatibility, I have really liked the existing automatic mapping of NaN to NULL. I believe Pandas uses NaN to indicate missing values just as DuckDB uses NULL. 

If that were to change, it is possible to have a configuration flag to retain the old behavior? I am flexible on the infinity handling though!

**Comment by krlmlr** [comment]
Special values are also a use case for the R client, see e.g. https://github.com/duckdb/duckdb/pull/2926/files#diff-9478bcd11e94e27217725c164390b02a189f58da45aa85e1f3ddf3f10c6935a5R141-R144.

**Comment by krlmlr** [comment]
If we revert, are we going to get Postgres-style literals back? https://www.postgresql.org/docs/14/datatype-numeric.html#DATATYPE-FLOAT

**Comment by rsund** [comment]
FYI, related things were also briefly discussed in the DuckDB Discord General channel on Jan 17, 2022.

I warmly welcome any improvements in this issue that would put DuckDB to be in line with other systems.

It would also be nice to have functions `IS_NAN`, `IS_INF`, and `IS_FIN`, although I noticed that as far as no better options exists, `PRINTF('%f',"column")` can be used for checking those as it writes out **nan**, **inf** and **-inf**.

That techique is the one utilized in [the use case for R client](https://github.com/duckdb/duckdb/pull/2926/files#diff-9478bcd11e94e27217725c164390b02a189f58da45aa85e1f3ddf3f10c6935a5R141-R144) mentioned above.
