### ISSUE TITLE
Overflow when casting from REAL to INT results in "Invalid TypeId -1"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#533]
Consider the following statements:

```sql
CREATE TABLE t0(c0 REAL);
INSERT INTO t0(c0) VALUES (10000000000);
SELECT t0.c0 ::INT FROM t0; -- Error: Conversion: Invalid TypeId -1
```
It is somewhat unexpected that the conversion results in an error `Invalid TypeId -1`, which seems like an internal error message to me. I would expect a truncation or a message explaining that an overflow occurred. I found this based on commit 3f0eb5134512c6097805998ccc5eb44476534736.

**Comment by Mytherin** [comment]
Fixed this in 7905e332b02cd069c238c0ea878afdf4cf8c0419, this was actually an exception being thrown while throwing the correct exception  as REAL was not a valid type there :)
