### ISSUE TITLE
GROUP BY clause results in non-deterministic result

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#535]
Consider the following statements:
```sql
CREATE TABLE t0(c0 NUMERIC);
INSERT INTO t0(c0) VALUES (-515965088);
INSERT INTO t0(c0) VALUES (1), (-5.15965088E8);
CREATE INDEX i0 ON t0(c0);
SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0); -- non-deterministic result
```
Unexpectedly, the query's result set is non-deterministic. In most executions, `-515965088.0` is contained twice in the result set, but sometimes it is contained only once.

For example, the following console output demonstrates that the result can change:
```
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0);
-515965088.0
-515965088.0
1.0
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0);
-515965088.0
-515965088.0
1.0
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0);
-515965088.0
-515965088.0
1.0
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0);
-515965088.0
1.0
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0);
-515965088.0
1.0
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0);
-515965088.0
```
When executing this based on a debug build, an assertion error occurs:
```sql
sqlite> SELECT t0.c0 FROM t0 GROUP BY t0.c0, REVERSE(t0.c0); -- cardinality: 27;
duckdb_cli: /duckdb/src/common/types/string_type.cpp:27: void duckdb::string_t::Verify(): Assertion `prefix[i] == dataptr[i]' failed.
Aborted
```
I can reproduce this on the latest master commit (3f0eb5134512c6097805998ccc5eb44476534736).

**Comment by Mytherin** [comment]
Fixed in 03eafe5d77900714f56f0c6e3d6fb3f0204926cf, the issue was that the string_t::Finalize() method was not properly called in REVERSE. This lead to a null terminator not being properly set, which lead to undefined behavior as the string value depended on uninitialized memory. Nice find again :)
