### ISSUE TITLE
[JDBC] Special character causes the JVM to terminate with "basic_string::_M_construct null not valid"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#539]
Consider the following statements:
```sql
CREATE TABLE(c0 VARCHAR);
INSERT INTO t0 VALUES('?'); -- terminate called after throwing an instance of 'std::logic_error'
```
The `INSERT` causes the JVM to abort with the following error:
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
```
Note that the `?` is a special character. To reproduce this, I encoded it in the following way:
```java
String.format("CREATE TABLE(c0 VARCHAR);INSERT INTO t0 VALUES('%c')", 55995)
```
I found this based on commit 80ec7ae484002fab41fb4e6fdc99083ee5cc3a11.

**Comment by hannesmuehleisen** [comment]
Confirmed, this crashes.

**Comment by hannesmuehleisen** [comment]
This is interesting, JNI has this function `GetStringUTFChars` that I assumed to return UTF8. This is wrong, it returns something called "modified" UTF8. Now we do this conversion in Javaland and then pass the byte array to JNI, which seems to fix the issue. Good catch!
