### ISSUE TITLE
Unexpected result for SUM() upon overflow

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#543]
Consider the following statements:
```sql
CREATE TABLE t0(c1 BIGINT);
INSERT INTO t0(c1) VALUES (2);
INSERT INTO t0(c1) VALUES (9223372036854775807);
SELECT SUM(t0.c1) FROM t0; -- expected: {9223372036854776000}, actual: {-9223372036854775807}
```
The overflow here might be unexpected. DBMS like Postgres and MySQL seem to return a floating-point result, avoiding the wraparound. SQLite outputs an integer overflow error. Interestingly, an exact overflow results in `NULL` being computed for DuckDB, which might also be an expected behavior for an overflow:
```sql
CREATE TABLE t0(c1 BIGINT);
INSERT INTO t0(c1) VALUES (1);
INSERT INTO t0(c1) VALUES (9223372036854775807);
SELECT SUM(t0.c1) FROM t0; -- NULL
```
Whether this is a bug is less clear than other cases. Feel free to close this issue, if this is the expected behavior. I found this based on commit b4aada80e3b0614029ec957de01cac0a14d8a785.

**Comment by Mytherin** [comment]
This is indeed a bug, but it is one we are quite aware of :) This is related to #74 and #111 , however, it has ended up on the backburner for some time already. Fixing it by itself is quite trivial (e.g. double promotion), but we want to fix it with a minimal performance impact, which requires a lot more work to do properly. I will leave this issue open, as we can use these test cases when we get around to fixing it.

**Comment by mrigger** [comment]
Okay, thanks for the feedback! I'll consider this a duplicate bug report then. Feel free to close this issue now or later, depending on what is more convenient for you.
