### ISSUE TITLE
SELECT on view with text constant in ORDER BY crashes

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#544]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
INSERT INTO t0(c0) VALUES (0);
CREATE VIEW v0(c0) AS SELECT 1 FROM t0;
SELECT * FROM v0 ORDER BY 'a'; --  Assertion `types.size() > 0' failed (original test case crashed)
```
Unexpectedly, the `SELECT` results in an assertion error when executing the debug build:
```
/build/debug$ ./duckdb_cli 
SQLite version DuckDB ee09b60a5
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> CREATE TABLE t0(c0 INT);
sqlite> INSERT INTO t0(c0) VALUES (0);
sqlite> CREATE VIEW v0(c0) AS SELECT 1 FROM t0;
sqlite> SELECT * FROM v0 ORDER BY 'a'; -- crash or Assertion `types.size() > 0' failed
duckdb_cli: /home/manuel/research/projects/duckdb_test/duckdb/src/common/types/data_chunk.cpp:25: void duckdb::DataChunk::Initialize(std::vector<duckdb::TypeId>&): Assertion `types.size() > 0' failed.
Aborted
```
The original (larger) test cases resulted in a segfault in the release build. I reduced this test case based on the debug build. I found this based on commit ee09b60a58a5d235b18fd1dc7be4843868efa00a.

**Comment by Mytherin** [comment]
Fixed in 72491b0046cd45cd0702fc60d5f42d4234f82d54. The problem was that the order by of a constant was optimized away (as it has no effect), leaving an empty ORDER BY node. That then caused strange behavior when executed and triggered the assertion. Thanks!
