### ISSUE TITLE
Top N implementation

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#55]
Right now for ORDER BY + LIMIT we perform a sort of the whole result and then limit the result. This could be done more efficiently with a rewrite of ORDER BY+LIMIT->TOP-N and an implementation of a good TOP-N algorithm.

**Comment by hannesmuehleisen** [comment]
I think a min heap would be best here since we don't know the

**Comment by hannesmuehleisen** [comment]
Fixed in PR https://github.com/cwida/duckdb/pull/287
