### ISSUE TITLE
Query using PREFIX() results in an error std::bad_alloc

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#572]
Consider the following statements:
```sql
CREATE TABLE t0(c0 VARCHAR);
SELECT * FROM t0 WHERE PREFIX(t0.c0, ''); -- Error: std::bad_alloc
```
Unexpectedly, the `SELECT` results in an error `Error: std::bad_alloc`. I found this based on commit a09d2f484db83ac9e27c9501f439bcd32b0083ec.

**Comment by hannesmuehleisen** [comment]
Interestingly, this does not happen on OSX with clang, but does happen on Linux with GCC.
