### ISSUE TITLE
DuckDB Performance using C++ 

### ISSUE THREAD

**Issue by sroycode** [cwida/duckdb#577]
1. I am inserting about 50 million data points in chunks of 5000 on a 32 GB ubuntu-18 ec2 c4.2xlarge instance. Addition using the code below appears to take 500 ms second per aforesaid 5000 records. This is quite consistent.

2. The RAM usage shoots up  to about 29GB while adding data ( 10k chunks). The WAL file is about 20 GB.

3. When I restart after clearing the memory , the data seems to take 220 seconds to load and occupies 16GB RAM. Running several hundred queries does not significantly add memory usage.

```
    Connection conn(db);
    conn.Query("START TRANSACTION");

    // record_id,price,shop,category,name,brand,color,model
    // see reference https://github.com/cwida/duckdb/issues/568

    conn.Query("INSERT INTO mytable VALUES (....) ");
    conn.Query("UPDATE mytable SET ... WHERE record_id=....");
    conn.Query("INSERT INTO mytable VALUES (....) ");
    ....  this about 5000 times.

    auto result = conn.Query("COMMIT");
    if (!result->success)
      LOG(INFO) << "Transaction Result has error ";
```

4. A Typical query that touches about 15 million records takes around 8 seconds,

```
SELECT shop, category, brand, color , COUNT(*) as count, STDDEV_SAMP(price) as price_std
FROM pricedata WHERE category in ('electronics') GROUP BY shop, category, brand, color;
```

Is this the expected behavior ?

**Comment by Mytherin** [comment]
For now this is indeed the expected behavior. DuckDB does not support incremental checkpointing yet, so while inserting data it will only append to the WAL. On startup, DuckDB will perform a full checkpoint. That means that the first load after a large insert is very slow, as essentially the entire database is rewritten. This is still an open issue (#49), but for now not high priority as we are not focussing on the storage for the first release.

**Comment by sroycode** [comment]
Just posting my observations.
Following your comments , I replaced the strings by hashed integers in the database. This reduced the memory usage significantly , though this means I cannot do LIKE queries ( which at this moment I do not need. 
I am inserting about 100 million data points in chunks of 5000 on a 32 GB ubuntu-18 ec2 c4.2xlarge instance. Addition appears to take 500 ms second per aforesaid 5000 records. This is quite consistent. The RAM is about 37GB while adding data ( 2*10k chunks).
On reloading it takes about 180 seconds for first reload , 13 seconds for subsequent reloads if data does not change. 
First query if heavy takes 15 seconds , most subsequent queries take 2-6 seconds , I guess this has something to do with caching , so a warm-up may help.

**Comment by Mytherin** [comment]
Thanks for the update :) This is still the same workload that you described above with the synthetic data, correct? 

The data loading seems quite slow. Are these still the same rows with 8~ columns, or are these wider rows? Are you still loading them with the CSV reader, or are you using another loading method now?

In my benchmarks I can load around 600K rows per second of the lineitem table, which has 16 columns and looks like this:

```
1|15519|785|1|17|24386.67|0.04|0.02|N|O|1996-03-13|1996-02-12|1996-03-22|DELIVER IN PERSON|TRUCK|egular courts above the
1|6731|732|2|36|58958.28|0.09|0.06|N|O|1996-04-12|1996-02-28|1996-04-20|TAKE BACK RETURN|MAIL|ly final dependencies: slyly bold 
```

Are you perhaps using individual `INSERT INTO` statements to load the data? If so, you might consider switching to using an appender (see [here](https://github.com/cwida/duckdb/blob/master/src/include/duckdb/main/appender.hpp) for the API).

**Comment by sroycode** [comment]
Yes, the same workload. These are now 10 rows but all are either BIGINT or DOUBLE , no strings ( that seems to have made tremendous performance impact).
I will try out the appender and let you know.

**Comment by sroycode** [comment]
@Mytherin  is there an easy way for creating tables programmatically ? The sample program fuses too many things and I could not find a test case for this.

**Comment by Mytherin** [comment]
For now there is no way of doing this, but I will have a look at adding it as it is something we wanted for some time now.

**Comment by sroycode** [comment]
I did the changes , the code now looks like below. The inserts are now taking under 250 ms for every 5k records instead on 500 ms. Note that I am also storing the base records in rocksdb after some validations so that tales about 50 ms as well .
So effectively insert is down to 200 ms per 5k records.

```
  conn.BeginTransaction();
  .....
  for ( .....loop .... ) {
    ::duckdb::Appender appender(conn, "tablename");
    appender.BeginRow();
    appender.Append<int64_t>(record->id());
    appender.Append<double>(record->price());
    appender.Append<int64_t>( GetHash( record->category() ));
    .... 
    appender.EndRow();
    appender.Close();
  }
  .....
  conn.Commit();
```

**Comment by Mytherin** [comment]
You should move the appender definitions out of the loop rather than constructing and closing it every iteration, like such:

```cpp
  conn.BeginTransaction();
  .....
  ::duckdb::Appender appender(conn, "tablename");
  for ( .....loop .... ) {
    appender.BeginRow();
    appender.Append<int64_t>(record->id());
    appender.Append<double>(record->price());
    appender.Append<int64_t>( GetHash( record->category() ));
    .... 
    appender.EndRow();
  }
  appender.Close();
  .....
  conn.Commit();
```

**Comment by sroycode** [comment]
Did as you asked but there is no difference in loading speed.

**Comment by Mytherin** [comment]
Strange. Did you compile an optimized build of DuckDB, or are you running in debug mode?

**Comment by sroycode** [comment]
Optimized build. 
Another problem I *may* have in future is that I can have some delete transactions along with appends , which are using the same connection transaction , but since I could not find the appender way of deleting, I am using Query("DELETE FROM ...")

**Comment by Mytherin** [comment]
Flush is not necessary, and doesn't need to be manually called unless you want to flush data before destroying the appender. Close() implicitly calls Flush() to finish writing everything.

The appender only supports inserts. For deletes or updates you can use prepared statements (`con.Prepare`).

I'm still confused about the insert performance here though. I made a [small benchmark program](https://gist.github.com/Mytherin/464ba72d92782a6e2395df85a1237d1c) based on your previous workload, and for me I can insert 1 million rows in around 2 seconds. That gives me an insert performance of 500K rows per second, including 6 string columns which are much slower to write than integer columns. 

```bash
$  clang++ -std=c++11 -Isrc/include -L build/release/src -lduckdb benchmark.cpp -o test_benchmark && rm -rf test.db* && time LD_LIBRARY_PATH=build/release/src ./test_benchmark
count()	
BIGINT	
[ Rows: 1]
1000000	



real	0m2.047s
user	0m1.688s
sys	0m0.257s
```

Moving the appender in the loop gives me a performance slowdown of factor ~3, to 150K rows per second:

```bash
real	0m5.630s
user	0m5.236s
sys	0m0.285s
```

Perhaps the bottleneck is elsewhere? The GetHash function maybe? Or using std::string copying somewhere in the pipeline?

**Comment by sroycode** [comment]
Hi:
Thank you for the help.
There is a total 50 ms overhead for the server query , and if I remove the DuckDB insert the rest of the program (with RocksDB inserts) runs at around 70 ms per 5k records .  The 300 ms looks quite ok to me , it is down from the original 1s ( using strings) and later 500 ms ( using SQL) . However , I will have to test a mixed workload of insert, update and deletes. I am anticipating an initial insert workload only, subsequent workloads will be update mostly.

**Comment by sroycode** [comment]
The Prepared statements are bound to connections, so I am assuming I will need to call the "PREPARE" for every new connection, am I right ?

**Comment by Mytherin** [comment]
Indeed, the prepared statements are bound to the connection and will run in the transaction context of that connection.
