### ISSUE TITLE
Comparing a string with a boolean yields an incorrect result after UPDATE

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#583]
Consider the following statements:
```sql
CREATE TABLE t0(c0 VARCHAR);
INSERT INTO t0(c0) VALUES (0);
UPDATE t0 SET c0=0;
UPDATE t0 SET c0=true;
SELECT * FROM t0 WHERE t0.c0 = true; -- expected: {true}, actual: {}
```
Unexpectedly, the `SELECT` does not fetch the row. When omitting the first `UPDATE` (whose value is again overwritten by the subsequent `UPDATE`), the query works as expected. I found this based on commit 1d2e40e01de260c9d3306a48c679bebd9a3f8744.

**Comment by pdet** [comment]
This was a bug where the zonemaps min/max indices were not updated for the second update. So we would incorrectly skip the segment.
