### ISSUE TITLE
A select with BETWEEN and VARCHAR cast results in an incorrect result

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#584]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INTEGER);
INSERT INTO t0(c0) VALUES (-2);
SELECT t0.c0 FROM t0 WHERE -1 BETWEEN t0.c0::VARCHAR AND 1; -- expected: {-2}, actual: {}
```
Unexpectedly, the `SELECT` does not fetch the row. I found this based on commit 1d2e40e01de260c9d3306a48c679bebd9a3f8744.

**Comment by Mytherin** [comment]
Fixes this in e8ec15172fab1dd5c0547f4259ed3dc8ce31f8e9. This was related to the cast moving optimizer. After optimization the expression was converted from an integer comparison into a varchar comparison, which resulted in the incorrect result being returned because `"-1" < "-2"`, but `-1 > -2`.
