### ISSUE TITLE
Predicate checking for an empty string yields an incorrect result

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#585]
Consider the following statements:
```sql
CREATE TABLE t0(c0 VARCHAR);
INSERT INTO t0(c0) VALUES (''), (0);
SELECT * FROM t0 WHERE t0.c0 = ''; -- expected: {''}, actual: {}
```
Unexpectedly, the `SELECT` does not fetch the row. When not inserting the `0`, the query works as expected. I found this based on commit 1d2e40e01de260c9d3306a48c679bebd9a3f8744.

**Comment by pdet** [comment]
This was a very nice catch, the way the min/max indices were initialized was related to the strings being empty. Which would cause the first '' insertion to not be considered for the indexes. So even an INSERT INTO t0(c0) VALUES (0), (''); would work.
