### ISSUE TITLE
Creating an index on rowid results in an internal error "Failed to bind column reference"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#589]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
CREATE INDEX i0 ON t0(rowid, c0); -- INTERNAL: Failed to bind column reference "c0" [0.1] (bindings: [0.0])
```
Unexpectedly, the `CREATE INDEX` results in an error `Error: INTERNAL: Failed to bind column reference "c0" [0.1] (bindings: [0.0])`. I found this based on commit dc352a3729f57252a1f6bfa18077fed9c4598a54.

**Comment by Mytherin** [comment]
Fixed in 0bfdbf39638c8b623056698850389349ec463ccc. Creating an index on the rowid column should not be possible, but it is a bug if an internal exception is ever thrown :) now a more descriptive error message is thrown.
