### ISSUE TITLE
STDDEV_POP unexpectedly does not fetch any rows

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#596]
Consider the following statements:
```sql
CREATE TABLE t0(c0 DOUBLE);
INSERT INTO t0(c0) VALUES(1E200), (0);
SELECT STDDEV_POP(c0) FROM t0; -- unexpected: does not fetch a row
```
Unexpectedly, the `SELECT` does not fetch any rows. In debug builds, an assertion fails:
```
/duckdb/src/common/types/vector.cpp:634: void duckdb::Vector::Verify(const duckdb::SelectionVector&, duckdb::idx_t): Assertion `Value::DoubleIsValid(*dbl)' failed.
```
I found this based on commit 96d5ae2e3a4b3aa52eab3878b78c5bdb8f6946b9.

**Comment by Mytherin** [comment]
Thanks! I fixed this in 2e03516e04ae94c33bff66201cb4290c1dc86662. This was a continuation on disallowing NaN to enter the system. I now added the check to the statistics functions that did not have it before.
