### ISSUE TITLE
GROUP BY does not take COLLATE into account

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#602]
Consider the following statements:
```sql
CREATE TABLE t0(c0 VARCHAR COLLATE NOCASE);
INSERT INTO t0(c0) VALUES ('a'), ('A');
SELECT t0.c0 FROM t0 GROUP BY t0.c0; -- expected: {'a'} or {'A'}, actual: {'a', 'A'}
```
Unexpectedly, the `GROUP BY` does not respect the `COLLATE` and fetches both `a` and `A`. I found this based on commit 50a9e7670827042c94302dc12a8acf0e8bb50fb2.

**Comment by Mytherin** [comment]
Good point! I had not considered the GROUP BY for collations yet. Fixed now :)
