### ISSUE TITLE
UTF8 Support seems to trigger constant rebuilds

### ISSUE THREAD

**Issue by hawkfish** [cwida/duckdb#605]
Ever since we added the `utf8proc` stuff I find that `make` has to rebuild _everything_ after some time interval (a day?). It works fine in the short term, but at some point it just starts over.

**Comment by Mytherin** [comment]
I noticed this as well but I noticed this as being related to using `git commit` or `git push`. Whenever I did anything involving git suddenly a full rebuild was triggered. Very strange, will need to look into this a bit more. For now ccache helps actually rebuilding though, which makes it a lot faster.

**Comment by hawkfish** [comment]
Ah that makes more sense than a random time interval. Is `ccache` something we do automatically or do I need to install it?

**Comment by Mytherin** [comment]
You need to install it if you don't have it. We have this in the cmake:

```
find_program(CCACHE_PROGRAM ccache)
if(CCACHE_PROGRAM)
  set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "${CCACHE_PROGRAM}")
endif()
```

So just check if `ccache --version` returns anything.

**Comment by Mytherin** [comment]
Ah, I think I figured it out. We add a define of the git source id:

```
execute_process(COMMAND git
                        log
                        -1
                        --format=%h
                WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
                OUTPUT_VARIABLE GIT_COMMIT_HASH
                OUTPUT_STRIP_TRAILING_WHITESPACE)
add_definitions(-DDUCKDB_SOURCE_ID="\""${GIT_COMMIT_HASH}"\"")
```

This changes when we commit. That's the culprit I think.

**Comment by Mytherin** [comment]
Should be fixed in #606, will merge after the tests pass.

**Comment by Mytherin** [comment]
This issue has been resolved for me now with #606. Can I close the issue?

**Comment by hawkfish** [comment]
Yes please!

I also remembered the `-j` option, so I'm using all 8 cores!

**Comment by Mytherin** [comment]
Ha, great :) I personally like to use Ninja instead of make. That tends to be a bit faster. You can use that with the cmake option `-G "Ninja"`, or by setting the environment variable `GEN=ninja` if you are using the root Makefile.
