### ISSUE TITLE
how about enrich the output of `duckdb_cli --version`

### ISSUE THREAD

**Issue by zz-jason** [cwida/duckdb#623]
the current output is:

```sh
➜ build/release/duckdb_cli --version
DuckDB c820266a6
```

rebuild `duckdb_cli` after some modification on the code without `git commit`, the output is changed:

```sh
➜ build/release/duckdb_cli --version
DuckDB 0e4b94f95
```

It would be nice to have these messages on the result of `--version`:

- the latest release version on the current build branch, for example, "v0.1.7" on master branch
- the git hash of the last commit, for example, it's `0e4b94f958b120fdaad45bda594933a2b84fced5` on master branch
- is there some uncommitted changes on the current build branch

It would be helpful when we need to investigate issues reported by users

**Comment by Mytherin** [comment]
> the latest release version on the current build branch, for example, "v0.1.7" on master branch

I think this is a good idea. We should have the tag name in there if there is one (and another marker like "unreleased version" otherwise). 

> the git hash of the last commit, for example, it's 0e4b94f958b120fdaad45bda594933a2b84fced5 on master branch

This is already there, no? Albeit a bit short.

> is there some uncommitted changes on the current build branch

I don't see much of a reason for this. If people are making changes, they are kind of on their own. It would also be a bit difficult to maintain this.

**Comment by hannesmuehleisen** [comment]
Should also be consistent to #672

**Comment by domoritz** [comment]
When installed via homebrew, duckdb prints the version as `b'XXXX'`, which looks somewhat odd. Is that expected? 

```
> duckdb --version
DuckDB b'd9bcedd'
```

**Comment by hannesmuehleisen** [comment]
I think we fixed this, this was indeed an issue in our build script

**Comment by domoritz** [comment]
Cool. I guess it will be fixed with the next release then.

**Comment by hannesmuehleisen** [comment]
This now outputs something like `0.2.4-dev389 fe8d8dd9f`

**Comment by domoritz** [comment]
Can confirm

```
$ duckdb --version
0.2.3 436f645
```
