### ISSUE TITLE
ALTER TABLE results in an assertion failure "Assertion `expr.return_type == vector.type' failed"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#624]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT, c1 VARCHAR);
INSERT INTO t0(c1) VALUES(NULL);
ALTER TABLE t0 ALTER c1 TYPE TIMESTAMP;
```
Unexpectedly, the `ALTER TABLE` results in an assertion failure:
```
/duckdb/src/execution/expression_executor.cpp:87: void duckdb::ExpressionExecutor::Verify(duckdb::Expression&, duckdb::Vector&, duckdb::idx_t): Assertion `expr.return_type == vector.type' failed.
```
I found this based on commit 289b2eaa836d22d7994154a912f8b786be48984b.

**Comment by Mytherin** [comment]
Thanks, fixed! This was a silly mistake: the vector that was scanned got the type of the first column of the table (INTEGER) rather than the type of the actual column that was changed (VARCHAR), which resulted in a type mismatch.
