### ISSUE TITLE
Integrate jemalloc

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#626]
We should integrate jemalloc, especially now that we are working on multithreading support.

https://github.com/jemalloc/jemalloc

**Comment by hannesmuehleisen** [comment]
Should we not first investigate if its worth it?

**Comment by Mytherin** [comment]
Yes, agreed, but I think it will be quite a bit better. There has been a paper written about this after all :) The system malloc is generally quite poor. In general the numbers I heard were around 10~20% on single-core workloads performance improvements, with higher percentages when dealing with NUMA nodes and multiple threads.

**Comment by hannesmuehleisen** [comment]
I have heard those numbers too but believe them to be coming more from transactional workloads. We shall see.

**Comment by Mytherin** [comment]
Ran TPC-H with and without jemalloc on Linux: 

| Query | System | Jemalloc |Speedup|
|:------|-------:|---------:|------:|
|Q01|0.470|0.469|0%
|Q02|0.064|0.057|11%
|Q03|0.157|0.155|1%
|Q04|0.149|0.164|-8%
|Q05|0.180|0.161|11%
|Q06|0.055|0.052|4%
|Q07|0.299|0.281|6%
|Q08|0.190|0.170|11%
|Q09|1.688|1.492|13%
|Q10|0.320|0.315|1%
|Q11|0.026|0.023|15%
|Q12|0.188|0.187|0%
|Q13|0.315|0.312|1%
|Q14|0.074|0.066|12%
|Q15|0.116|0.113|2%
|Q16|0.091|0.080|14%
|Q17|0.245|0.267|-8%
|Q18|0.682|0.678|0%
|Q19|0.421|0.372|13%
|Q20|0.089|0.095|-5%
|Q21|0.593|0.634|-6%
|Q22|0.063|0.068|-7%

Not too impressive, and many queries got worse as well. I think the difference might be bigger in multi-threaded workloads especially when NUMA is considered. On Windows the system allocator could be worse than on Linux as well, but I'm not sure about that. Either way, not a priority right now.

**Comment by hannesmuehleisen** [comment]
Closing this for now then
