### ISSUE TITLE
DROP column results in an assertion failure unique.index < base.columns.size() 2

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#628]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT, c1 INT UNIQUE);
ALTER TABLE t0 DROP c1; -- Assertion `unique.index < base.columns.size()' failed.
```
Unexpectedly, the `ALTER TABLE` results in an assertion failure:
```
/duckdb/src/planner/binder/statement/bind_create_table.cpp:60: void BindConstraints(duckdb::Binder&, duckdb::BoundCreateTableInfo&): Assertion `unique.index < base.columns.size()' failed.
```
This seems to be a very similar underlying issue as https://github.com/cwida/duckdb/issues/625. However, the fix for that issue does not fix the one reported in this bug report. I found this based on commit b6665e723c5f3d9cbd7b0018ce8c242260ac6dc3.

**Comment by Mytherin** [comment]
Indeed, very related :) Should be fixed now.
