### ISSUE TITLE
ALTER TYPE with USING results in an assertion failure "types.size() > 0"

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#629]
Consider the following statements:
```sql
CREATE TABLE t0(c0 INT);
ALTER TABLE t0 ALTER c0 TYPE VARCHAR USING ''; -- Assertion `types.size() > 0' failed.
```
Unexpectedly, the `ALTER TABLE` results in an assertion failure:
```
/duckdb/src/common/types/data_chunk.cpp:25: void duckdb::DataChunk::Initialize(std::vector<duckdb::TypeId>&): Assertion `types.size() > 0' failed.
```
I found this based on commit b6665e723c5f3d9cbd7b0018ce8c242260ac6dc3.

**Comment by Mytherin** [comment]
Thanks :) Fixed now. The problem was that since the USING clause did not contain any columns, an "empty scan" was attempted (i.e. a scan was initialised but it was a scan of zero columns). This triggered this assertion.
