### ISSUE TITLE
Compile JDBC drivers with older runtime version

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#647]
DBeaver fails to connect because

> nl/cwi/da/duckdb/DuckDBDriver has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by drudd75077** [comment]
I'm not super savvy in this area, but how can I view the database in dbeaver? I'd appreciate an example if possible. I don't see it as a connection option in dbeaver

**Comment by Mause** [comment]
There's some instructions here: https://github.com/cwida/duckdb/issues/1216#issuecomment-748438850
