### ISSUE TITLE
Can't find description on DB model

### ISSUE THREAD

**Issue by dmitryikh** [cwida/duckdb#648]
Bumped into your repo and was trying to understand how your DB operates internally.
But can't find any information in README and the site.

What I'd like to see:
* row or column oriented?
* lsm or btree data structure?
* is data durable persisted?
* are UPDATE operations support?
* what kind of indices are supported?
* are secondary indices supported?

May all these questions are addressed somewhere, but I'm out of luck finding the answers.

**Comment by kapilt** [comment]
if we're doing qa.. I'd also add I'm trying to understand how to reason about memory usage for duckdb, just using the cli, it seems to hold the entire db in memory (2.6gb).

also wrt to contributing to the docs, they don't appear to be in the repo? would be worth adding to contributing section on how to add to them.

**Comment by Mytherin** [comment]
The amount of memory that is buffered can be configured using the PRAGMA memory_limit (e.g. `PRAGMA memory_limit='1GB'`). Currently the default for this is infinite, which means the whole database will be buffered in memory.

The docs are in a separate repo, which is currently set to private. We might make it public soon, we haven't discussed about that yet. We are also currently reworking the website, so perhaps we can make it public after that.

**Comment by Mytherin** [comment]
> Bumped into your repo and was trying to understand how your DB operates internally.
> But can't find any information in README and the site.
> 
> What I'd like to see:
> 
> * row or column oriented?
> * lsm or btree data structure?
> * is data durable persisted?
> * are UPDATE operations support?
> * what kind of indices are supported?
> * are secondary indices supported?
> 
> May all these questions are addressed somewhere, but I'm out of luck finding the answers.

Excellent point, indeed we are trying to rework the documentation. Here are some simple answers:

* Column oriented
* Neither, custom block-based currently
* Yes, data is durably persisted. DuckDB is fully ACID.
* Update/deletes are supported. They are transactional, with snapshot isolation. 
* Secondary indices are supported, currently only the ART index is implemented (https://db.in.tum.de/~leis/papers/ART.pdf).

**Comment by kapilt** [comment]
for others that come across this issue, doc source is here https://github.com/cwida/duckdb-web for contribs.
