### ISSUE TITLE
Maven artifact & JDBC driver fat JAR

### ISSUE THREAD

**Issue by mrigger** [cwida/duckdb#649]
Are there any plans to publish a Maven artifact for DuckDB? We are in the process of open-sourcing SQLancer, so this would be very helpful for us (and likely also for other Java projects that want to use DuckDB).

**Comment by hannesmuehleisen** [comment]
Yes, that is something we would like to do. I have never done this before though so help is appreciated. We also would like to bake all the binaries into a single JAR file, at the moment they are still platform specific.

**Comment by hannesmuehleisen** [comment]
Created a request for maven hosting at https://issues.sonatype.org/browse/OSSRH-58177

**Comment by hannesmuehleisen** [comment]
turns out we need to control the domain derived from the artifact group id. So changed the package name to `org.duckdb` (was: `nl.cwi.da.duckdb`). Once this PR is merged, JDBC applications will update the driver class name to `org.duckdb.DuckDBDriver`.

**Comment by mrigger** [comment]
Thanks a lot for this! I've btw only started using Maven for SQLancer, and also don't have experience with this.

**Comment by hannesmuehleisen** [comment]
@mrigger welcome to dependency hell ^^

**Comment by hannesmuehleisen** [comment]
this works for me from Maven:
````XML
<dependency>
  <groupId>org.duckdb</groupId>
  <artifactId>duckdb_jdbc</artifactId>
  <version>0.1.8</version>
</dependency>
````
