### ISSUE TITLE
Add `PRAGMA` command to get DuckDB version

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#672]
We need some elegant way to figure out the DuckDB version from SQL. Add a PRAGMA that returns it.

**Comment by itsWill** [comment]
I took a stab at this one: https://github.com/cwida/duckdb/pull/808

It's my first foray into C++ and database implementation, so I'm sure there's room for improvement, but with some guidance i think it can get into a shippable state.
