### ISSUE TITLE
Case insensitivity for header names in read_csv_auto

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#673]
Currently the header names in read_csv_auto are read as-is, which means case is preserved.  For example, consider this CSV file:

**test.csv**
```
FlightDate|UniqueCarrier|OriginCityName|DestCityName
1988-01-01|AA|New York, NY|Los Angeles, CA
1988-01-02|AA|New York, NY|Los Angeles, CA
1988-01-03|AA|New York, NY|Los Angeles, CA
```

The file is correctly loaded:
```sql
SELECT * FROM read_csv_auto('test.csv');
```

|FlightDate|UniqueCarrier| OriginCityName  | DestCityName  |
|---------:|------------:|----------------:|--------------:|
|1988-01-01|AA           |New York, NY     |Los Angeles, CA|
|1988-01-02|AA           |New York, NY     |Los Angeles, CA|
|1988-01-03|AA           |New York, NY     |Los Angeles, CA|

However, the names must be quoted to use them in the query:

```sql
SELECT flightdate FROM read_csv_auto('test.csv');
-- error!
SELECT FlightDate FROM read_csv_auto('test.csv');
-- error!
SELECT "FlightDate" FROM read_csv_auto('test.csv');
-- correct
```

I think we should lowercase them before loading so the behavior is more "as expected".

**Comment by ak2k** [comment]
I just ran into this in my testing. I was about to report, but you beat me to it!

**Comment by Mytherin** [comment]
After some discussion we have decided to solve this in a different manner: in table and column name binding we will now also consider case insensitive alternatives when there are no conflicts. Eg if we have a column name with “FlightDate”, the column “flightdate” will match it as long as no conflicting alternative exists (e.g. if “FLIGHTDATE” also exists we will throw an error). In case of existing conflicts the name must match exactly.
