### ISSUE TITLE
Using the parquet reader support in binary/CLI

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#675]
Hi, Do I need to do something before being able to use the parquet reader?

SQLite version DuckDB cbf92c49c (master)

None of these seems to work for me from the CLI.

sqlite> SELECT * FROM parquet_scan('assets.parquet');
Error: Catalog: Table Function with name parquet_scan does not exist!

sqlite> select * from from_parquet('assets.parquet');
Error: Catalog: Table Function with name from_parquet does not exist!

sqlite> select * from read_parquet('assets.parquet');
Error: Catalog: Table Function with name read_parquet does not exist!

Thank you!

**Comment by hannesmuehleisen** [comment]
Did you build from source?

**Comment by hannesmuehleisen** [comment]
We still have to integrate the parquet reader in the shell. Thanks for the notification!

**Comment by hannesmuehleisen** [comment]
This should now work.
