### ISSUE TITLE
type conversion error in shell

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#678]
Here's a minimal repro of the error. This is a value dumped from sqlite to csv that I'm trying to import into duckdb.

sqlite> select '-1.10690397945634e+18'::REAL;
Error: Conversion: Could not convert string '-1.10690397945634e+18' to numeric

**Comment by hannesmuehleisen** [comment]
The `+` is the culprit, this works for me: select `'-1.10690397945634e18'::REAL;`. Should be an easy fix in `TryIntegerCast`

**Comment by Mytherin** [comment]
Should indeed be an easy fix, thanks for the report :) I can fix it tomorrow.
