### ISSUE TITLE
LIKE behaves differently when bound to a table (and errors)

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#680]
Hi!

It looks like LIKE may be broken in the shell.

Using binary built from source: SQLite version DuckDB 57c3ef72a

This works as expected:
```
sqlite> select 'abc' where 'abc' like 'a%';
abc       
----------
abc     
```
However, when the data come from a table, LIKE emits 'regex_error'
```
sqlite> create table t as (select 'abc' as c1);
sqlite> select * from t;
c1        
----------
abc       
sqlite> select * from t where c1 like 'a%';
Error: regex_error
```

Thank you!
Adam

**Comment by ak2k** [comment]
Hmm, it looks like regexp_matches doesn't appear to work in the shell. Perhaps it's related.

```
sqlite> select regexp_matches('abc','abc');
Error: Unknown error -1
```

The instr() function does appear to work:
```
sqlite> SELECT instr('abcdef', 'abc');
instr(abcdef, abc)
------------------
1               
```

**Comment by Mytherin** [comment]
Thanks for the report! My initial thought is that this seems to be related to linking pthread. A regex is used in the LIKE optimizer (`like_optimizations.cpp`), and the regex engine we use fails on Linux when pthread is not linked. The optimizer is not triggered in the first case as the entire expression is constant folded.

**Comment by hannesmuehleisen** [comment]
@ak2k which OS are you on with this?

**Comment by ak2k** [comment]
Hi, I'm using CentOS Linux release 7.5.1804 (Linux 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 GNU/Linux). 

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/runtime/gcc/9.1.0/libexec/gcc/x86_64-pc-linux-gnu/9.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ./configure --prefix=/runtime/gcc/9.1.0 --enable-languages=c,c++,lto --disable-multilib --with-arch=sandybridge --with-tune=broadwell
Thread model: posix
gcc version 9.1.0 (GCC)

$ cmake --version
cmake version 3.5.2

Make did seem to report that it found a pthread:
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  

Would it help if I sent the logfile of the build output?

**Comment by hannesmuehleisen** [comment]
Can you check whether the code in the `shellthreads` branch fixes your issue

**Comment by ak2k** [comment]
Yes, it does! Thank you!
