### ISSUE TITLE
index support in shell?

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#684]
When I create an index in the shell, any CREATE INDEX statement appears to succeed, but the file size on disk doesn't change. I can imagine this being because an additional page isn't needed, but it's suspicious enough that I wonder if there's a way that I can check that the index was created (and that it might be used)?

**Comment by ak2k** [comment]
I also notice that when I exit the shell and enter again, I can run the same CREATE INDEX statements as run previously without getting an error that an index with the same name already exists.

**Comment by hannesmuehleisen** [comment]
You can use `EXPLAIN` to see if queries use the index. For example, the following works for me in the shell:

```SQL
create table a (i integer);
explain select * from a where i=42;
-- ... SEQ_SCAN
create index idx1 on a(i);
explain select * from a where i=42;
-- .. INDEX_
```

**Comment by ak2k** [comment]
Thank you! That's helpful.

Is it expected that indexes aren't persisted?

$ duckdb repo.db
SQLite version DuckDB e4c5873d5
Enter ".help" for usage hints.
sqlite> create table a (i integer);
sqlite> explain select * from a where i=42;
explain_key   explain_value
------------  -------------------------------------
logical_plan  PROJECTION[i]
FILTER[i=42]
    GET(a)
logical_opt   PROJECTION[i]
GET(a)
physical_pla  PROJECTION[i]
SEQ_SCAN[a i=42]
sqlite> .width 30
sqlite> create index idx1 on a(i);
sqlite> explain select * from a where i=42;
explain_key                     explain_value
------------------------------  -------------------------------------
logical_plan                    PROJECTION[i]
FILTER[i=42]
    GET(a)
logical_opt                     PROJECTION[i]
FILTER[i=42]
    INDEX_
physical_plan                   PROJECTION[i]
FILTER[i=42]
    INDEX_
sqlite> .quit
$ duckdb repo.db
SQLite version DuckDB e4c5873d5
Enter ".help" for usage hints.
sqlite> explain select * from a where i=42;
explain_key   explain_value
------------  -------------------------------------
logical_plan  PROJECTION[i]
FILTER[i=42]
    GET(a)
logical_opt   PROJECTION[i]
GET(a)
physical_pla  PROJECTION[i]
SEQ_SCAN[a i=42]
sqlite>

**Comment by hannesmuehleisen** [comment]
> Is it expected that indexes aren't persisted?
entirely possible. @pdet ?

**Comment by pdet** [comment]
Yes, indexes are not persisted yet.

**Comment by hannesmuehleisen** [comment]
Closing this then for now. Thanks!

**Comment by ak2k** [comment]
Thank you!
