### ISSUE TITLE
LEAST() function

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#697]
Hi, I notice that the LEAST function doesn't appear to be implemented. Is it expected?

$ echo "SELECT LEAST(5::INT,6::INT);" | duckdb
Run Time: real 0.000 user 0.000129 sys 0.000066
Error: near line 1: Not implemented: Expr of type 130 not implemented

**Comment by Mytherin** [comment]
Indeed this function is not yet implemented. I will add it to issue #193. If you are feeling like it I would also be happy to review a PR :)

**Comment by Mytherin** [comment]
I decided to implement them after all :) So one question about preference, MySQL returns NULL if any value is NULL, whereas Postgres returns NULL only if all values are NULL, i.e.:

```sql
-- MySQL
SELECT LEAST(NULL, 1); -- NULL
-- PostgreSQL
SELECT LEAST(NULL, 1); -- 1
```

Any strong preference either way? Currently I have implemented the MySQL version as it seems more consistent with the way other database ops work.

**Comment by ak2k** [comment]
Thank you very much!!
Absolutely no strong preference -- your suggestion regarding consistency with other ops makes sense to me.
Thank you again!

**Comment by Mytherin** [comment]
No worries :) Happy to help. The functions are merged now.
