### ISSUE TITLE
R: Document all function arguments and add examples

### ISSUE THREAD

**Issue by pat-s** [cwida/duckdb#701]

**Comment by hannesmuehleisen** [comment]
Separate documentation into the following areas:

- Driver
  - `duckdb`
  - `duckdb_shutdown`
  - `dbConnect`
  - `src_duckdb`
- Connection
  - `dbBegin`
  - `dbColumnInfo`
  - `dbCommit`
  - `dbDataType`
  - `dbDisconnect`
  - `dbExistsTable`
  - `dbGetInfo`
  - `dbIsValid`
  - `dbListFields`
  - `dbListTables`
  - `dbRemoveTable`
  - `dbRollback`
  - `dbSendQuery`
  - `dbWriteTable`
- ResultSet
  - `dbBind`
  - `dbClearResult`
  - `dbHasCompleted`
  - `dbGetStatement`
  - `dbGetRowsAffected`
  - `dbGetRowCount`
  - `dbFetch`
  - `dbIsValid`
- Register/Unregister
- read_csv
