### ISSUE TITLE
R: Get R CMD Check passing without warnings and errors

### ISSUE THREAD

**Issue by pat-s** [cwida/duckdb#703]
- [ ] No warnings

- [ ] No errors

**Comment by hannesmuehleisen** [comment]
I zapped the references to `stderr`, `stdout` and `cout` in the `evilsymbols` branch, so the C part should be ok now pending some valgrind issues or something of that sort. CC @krlmlr

**Comment by pat-s** [comment]
R CMD check is passing with only 1 Note which relates to the size of the `libs` directory. Even if we reduce its size, we won't get rid of the NOTE entirely.

Hence I'd say this issue is solved.
