### ISSUE TITLE
TIMESTAMP error when using  FROM PARQUET_SCAN

### ISSUE THREAD

**Issue by wallflower** [cwida/duckdb#707]
Importing parquet files into duckdb does not seem to accept TIMESTAMP columns.

Executing the following against a parquet file works fine:

```
duckdb.from_parquet(<parquet_file>).limit(10)
```

However, using a select does not:

```
SELECT * FROM PARQUET_SCAN(<parquet_file>);
```

I tried importing directly, as well as creating a table with a TIMESTAMP column.  Both give me the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: TIMESTAMP
```

I will provide whatever additional information may be helpful.

Gerry.

**Comment by hannesmuehleisen** [comment]
Can you provide the parquet file please? TIMESTAMP should work.

**Comment by wallflower** [comment]
I did a bit more investigation around this and I think I know the source of the issue.  The original parquet file I was trying to access was generated vis pyarrow and was writing the timestamp to nanosecond precision.

Here is metadata about that timestamp column:
```
row_group       0       recordtime      type    INT96
row_group       0       recordtime      num_values      2565859
row_group       0       recordtime      compression     SNAPPY
row_group       0       recordtime      encodings       PLAIN,PLAIN_DICTIONARY,RLE
row_group       0       recordtime      compressed_size 2966167
row_group       0       recordtime      uncompressed_size       10322123
```

When I loaded that parquet file into pandas and resaved it (where pandas uses ms precision), then PARQUET_SCAN could read that parquet file without errors.

Here is metadata about the resaved timestamp column:
```
row_group       0       recordtime      type    INT64
row_group       0       recordtime      num_values      2565859
row_group       0       recordtime      compression     SNAPPY
row_group       0       recordtime      encodings       PLAIN_DICTIONARY,PLAIN,RLE
row_group       0       recordtime      compressed_size 1795696
row_group       0       recordtime      uncompressed_size       5505301
```

So, duckdb's parquet reader seems to only be able to handle ms precision?

Not sure if this is really a bug or not? Feel free to close this issue if not, and maybe we should rename this issue to reflect the resolution of timestamp?

**Comment by hannesmuehleisen** [comment]
could be the issue, again, can you please share the file?

**Comment by Mytherin** [comment]
Perhaps an idea, if you can't share the actual file for data privacy reasons, perhaps you can include a Python snippet that generates an example Parquet file using arrow that doesn't work?

**Comment by hannesmuehleisen** [comment]
Thanks for sending the file, was an easy fix. Once the tests pass I will merge the PR that should resolve the issue. You are welcome to try as well.
