### ISSUE TITLE
Timestamp type + functions

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#71]
For the DATE functions I just implemented them from the Postgres list of functions. The same should be done for TIMESTAMPs.

**Comment by hannesmuehleisen** [comment]
This is a good candidate to get started with DuckDB

**Comment by diegomestre2** [comment]
- [ ] Implement time and timestamp conversion from string and formatting for SELECT * FROM timestamp
Implement timestamp functions (https://www.postgresql.org/docs/9.6/functions-datetime.html)
- [ ] Extract
- [ ] NOW, CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, LOCALTIME, TIMEOFDAY, STATEMENT_TIMESTAMP()
- [ ] date_trunc

**Comment by hannesmuehleisen** [comment]
I'd argue we should not get into `LOCALTIME`...

**Comment by hannesmuehleisen** [comment]
`TIMEOFDAY` is just a timestamp with stupid formatting. Suggest we either make it an alias of CURRENT_TIMESTAMP or ignore it.

**Comment by hannesmuehleisen** [comment]
`STATEMENT_TIMESTAMP` returns the start of the current transaction, also something we don't have. Should we? I think not...

**Comment by hannesmuehleisen** [comment]
Calling this close enough for now
