### ISSUE TITLE
R: Failed Installation of v0.1.9 & master

### ISSUE THREAD

**Issue by alexanderjwhite** [cwida/duckdb#711]
duckDB is failing to install either available version in R. The issue appears to be with cmake not being installed, or cannot be found. Due to my server access, I cannot test whether or not installing cmake directly would fix this issue. 

> sessionInfo()

R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] arulesSequences_0.2-25 arules_1.6-5           Matrix_1.2-18         

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6      cla_0.0.0.9000    compiler_3.6.1    pillar_1.4.4     
 [5] tools_3.6.1       digest_0.6.25     evaluate_0.14     tsibble_0.8.6    
 [9] lubridate_1.7.8   tibble_3.0.1      lifecycle_0.2.0   lattice_0.20-41  
[13] anytime_0.3.7     pkgconfig_2.0.3   rlang_0.4.5       rstudioapi_0.11  
[17] yaml_2.2.1        parallel_3.6.1    xfun_0.14         knitr_1.28       
[21] furrr_0.1.0       dplyr_0.8.5       stringr_1.4.0     hms_0.5.3        
[25] generics_0.0.2    vctrs_0.2.4       globals_0.12.5    tictoc_1.0       
[29] grid_3.6.1        tidyselect_1.0.0  data.table_1.12.8 glue_1.4.0       
[33] listenv_0.8.0     R6_2.4.1          rmarkdown_2.2     readr_1.3.1      
[37] purrr_0.3.4       tidyr_1.0.2       magrittr_1.5      htmltools_0.4.0  
[41] codetools_0.2-16  ellipsis_0.3.0    assertthat_0.2.1  future_1.17.0    
[45] stringi_1.4.6     crayon_1.3.4    

**v0.1.9 installation attempt**

> install.packages("duckdb", repos=c("http://download.duckdb.org/alias/v0.1.9/rstats/", "http://cran.rstudio.com"))

Installing package into ‘Y:/AppData/R Studio/whit45661/lib’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository http://download.duckdb.org/alias/v0.1.9/rstats/bin/windows/contrib/3.6:
  cannot open URL 'http://download.duckdb.org/alias/v0.1.9/rstats/bin/windows/contrib/3.6/PACKAGES'
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘duckdb’
installing the source package ‘duckdb’

trying URL 'http://download.duckdb.org/alias/v0.1.9/rstats/src/contrib/duckdb_0.1.7.tar.gz'
Content type 'application/x-tar' length 1405175 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'duckdb' ...
** using staged installation
** libs

*** arch - i386
I:/R Foundation/R Tools/mingw_32/bin/g++  -std=gnu++11 -I"I:/R Foundation/R Project/include" -DNDEBUG       -I.   -O2 -Wall  -mtune=generic -c duckdbr.cpp -o duckdbr.o
sh: I:/R: No such file or directory
make: *** [I:/R Foundation/R Project/etc/i386/Makeconf:215: duckdbr.o] Error 127
ERROR: compilation failed for package 'duckdb'
* removing 'Y:/AppData/R Studio/whit45661/lib/duckdb'
Warning in install.packages :
  installation of package ‘duckdb’ had non-zero exit status

**master installation attempt**
> install.packages("duckdb", repos=c("http://download.duckdb.org/alias/master/rstats/", "http://cran.rstudio.com"))

Installing package into ‘Y:/AppData/R Studio/whit45661/lib’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository http://download.duckdb.org/alias/master/rstats/bin/windows/contrib/3.6:
  cannot open URL 'http://download.duckdb.org/alias/master/rstats/bin/windows/contrib/3.6/PACKAGES'
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘duckdb’
installing the source package ‘duckdb’

trying URL 'http://download.duckdb.org/alias/master/rstats/src/contrib/duckdb_0.2.0.tar.gz'
Content type 'application/x-tar' length 1409321 bytes (1.3 MB)
downloaded 1.3 MB

* installing *source* package 'duckdb' ...
** using staged installation
** libs

*** arch - i386
I:/R Foundation/R Tools/mingw_32/bin/g++  -std=gnu++11 -I"I:/R Foundation/R Project/include" -DNDEBUG       -I.   -O2 -Wall  -mtune=generic -c duckdbr.cpp -o duckdbr.o
sh: I:/R: No such file or directory
make: *** [I:/R Foundation/R Project/etc/i386/Makeconf:215: duckdbr.o] Error 127
ERROR: compilation failed for package 'duckdb'
* removing 'Y:/AppData/R Studio/whit45661/lib/duckdb'
Warning in install.packages :
  installation of package ‘duckdb’ had non-zero exit status

**Clone master & build installation attempt**
sh: line 3: cmake: command not found
make: *** [Makefile:53: release] Error 127

Exited with status 2.

**Comment by alexanderjwhite** [comment]
On further investigation - this could be due to the lack of a c++ compiler on the server. I'm not sure how/if I can check this. If this is the case, a more useful error upon installation attempt would probably be helpful.

**Comment by hannesmuehleisen** [comment]
Can you try with R version 4?

**Comment by nilescbn** [comment]
I've also been able to install v0.1.9 on Windows 10 and using R version 4.0. The install process appears to go okay. But trying to load the package with library(), I get this error:

> Error: package or namespace load failed for ‘duckdb’: package ‘duckdb’ was installed before R 4.0.0: please re-install it

I've tried this on two different laptops and get the same result. 

Happy to provide more info if helpful. Thanks!

**Comment by hannesmuehleisen** [comment]
> Happy to provide more info if helpful. Thanks!

Yes, that's indeed very odd. We are working to get DuckDB on CRAN which should fix those issues.

**Comment by nilescbn** [comment]
Great, very much appreciate those efforts to make it available from CRAN. I do not want to distract you all from those. 

I would just offer, in case helpful, that if I follow the "http://download.duckdb.org/alias/v0.1.9/rstats/" link in my browser, I'm redirected to: http://download.duckdb.org/rev/3c353fac49d37719d7592d1819dfeb76ac541736/rstats/.

And in that directory I only see files labeled v 0.1.7. The same is true for the bin and src folders too.

**Comment by pat-s** [comment]
v0.2.0 is available in the linked repository and the alias points to the correct version. Since all OS runners now successfully build and upload the artifacts, I think this can be closed.
