### ISSUE TITLE
Documentation: PRAGMA memory_limit

### ISSUE THREAD

**Issue by ak2k** [cwida/duckdb#713]
Hi,

Might it be practical at some point to store the web documentation content in github to facilitate community contributions to documentation?

Separately, I happened to notice that PRAGMA memory_limit doesn't seem to appear in the website documentation. And it just so happens to a potential PR that is othwerwise within my ability. :)

https://www.google.com/search?q=site%3Aduckdb.org+memory_limit

**Comment by hannesmuehleisen** [comment]
We have a separate repo for this, I just made it public: https://github.com/cwida/duckdb-web . I also added a FAQ entry to the website to explain this.

**Comment by Alex-Monahan** [comment]
Does the memory limit Pragma persist across multiple database connections, or is it per connection?
