### ISSUE TITLE
Blob type + functions

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#72]

**Comment by tiagokepe** [comment]
Hi all,
Can you assign this issue to me?
I will try to implement this in the next few days.
Thanks.

**Comment by Mytherin** [comment]
Sure :) Done

**Comment by Mytherin** [comment]
For blob conversion, we want to support the following inputs:

```sql
SELECT 'AAFFAA'::BLOB; -- 6 bytes, ascii values of the characters (65, 65, 70, 70, 65, 65)
SELECT '\xAAFFAA'::BLOB; -- 3 bytes, hexadecimal interpretation
SELECT x'AAFFAA'; -- 3 bytes, hexadecimal interpretation
SELECT 'AAGGAA'::BLOB; -- 6 bytes (65, 65, 71, 71, 65, 65)
SELECT '\xAAGGAA'::BLOB; -- error (G is not valid hexadecimal)
SELECT '\xAAFFA'; -- error (amount of bytes must be an even number)
SELECT x'AAFFA'; -- error (same as above, amount of bytes must be even)
```

Blob to string conversion uses the hexadecimal format, and is reversable (i.e. `BLOB::VARCHAR::BLOB` results in the same blob again). The output is lowercase (this is what PostgreSQL has as well).

```sql
SELECT '\xAA'::BLOB::VARCHAR; -- '\xaa'
```

There is no implicit casting to or from blobs. That is, inputting a blob into a function that only accepts VARCHAR will result in a conversion error, i.e.

```sql
SELECT regexp_matches('\xAA'::BLOB, ''); --error
```
