### ISSUE TITLE
R: Move {testthat} from Imports to Suggests

### ISSUE THREAD

**Issue by pat-s** [cwida/duckdb#726]
{testthat} usually lives in Suggests and should not be imported.

The import of `testthat::skip()` should be replaced.

https://github.com/cwida/duckdb/blob/acd392bf8b45e13a920ede21a08da1c5fd096953/tools/rpkg/R/Result.R#L223-L239

**Comment by hannesmuehleisen** [comment]
Please also take dbplyr out of the imports while you're at it as discussed
