### ISSUE TITLE
Remove exported symbols from Postgres parser

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#727]
There are a few `extern` functions and global variables in the Postgres parser that get exported - this can cause symbol conflicts as they are not namespaced properly (and hence live in the global namespace). This specifically causes issues when loaded into an application that has (another) version of the Postgres parser loaded.

**Comment by hannesmuehleisen** [comment]
See branch `pgparsernoextern`

**Comment by Mytherin** [comment]
Nice :), should make a test where we use DuckDB in a PostgreSQL UDF. I think we can install it with PL/Python support through:

```bash
sudo apt-get install postgresql-plpython
```

Then run a UDF, e.g.

```sql
CREATE EXTENSION plpythonu;
CREATE FUNCTION quack ()
  RETURNS integer
AS $$
  import duckdb
  con = duckdb.connect(':memory:')
  return con.execute('SELECT 42').fetchall()[0][0]
$$ LANGUAGE plpythonu;
SELECT quack();
```

**Comment by hannesmuehleisen** [comment]
Seeing a crash now in 
```
                #0  0x00007f4f460fadfd _Z12scanner_initPKcP18core_yy_extra_typePK13PGScanKeywordi (duckdb.so)
                #1  0x00007f4f460f6fa3 _Z10raw_parserPKc (duckdb.so)
                #2  0x00007f4f460e1b43 _Z15pg_parser_parsePKcP16parse_result_str (duckdb.so)
```
To me that looks like the symbols have been properly mangled already #progress
