### ISSUE TITLE
Parallel Aggregate Hash Tables

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#734]
Battle plan: Each thread allocates separate blocks for pointers and group/payload blobs. Separate column for hashes. Blocks of all threads are merged on combine

**Comment by jtommaney-alibaba** [comment]
Just a vote to prioritize this effort.   This represents a significant performance opportunity.

There seem to be significant advantages to models that include thread-local aggregation (with overflow behaviors at some condition) for performance with bounded group by cardinality use cases ( most BI/visualization tools, in my experience )

Slide 35 has a comparative graph that makes a strong argument for Adaptive model, but I suspect there are related solutions.   
https://people.csail.mit.edu/jshun/6886-s19/lectures/lecture12-2.pdf

with examples: 
   SQL1:   select group_by_buckets , sum(col2) from table group by group_by_buckets 
   SQL2:  select sum(col2) from table where group_by_buckets>0 ;
Ideal product behaviors for consistent performance:
1)  similar performance for SQL1 and SQL2 when number of group_by_buckets is small
2)  difference in performance between SQL1 and SQL2 is independent of # of rows in table
3)  smooth performance curve as number of group_by_buckets scales
4)  similar linear scalability for SQL1 and SQL2 when number of group_by_buckets is small
5)  efficient handling of skew: with 32 threads, 999 million tuples of bucket 1, then 1 million other buckets with 1 tuple.
      ideal processing model (Adaptive?) would allow for thread-local handling of bucket 1, other path for most other values.

**Comment by hannesmuehleisen** [comment]
We are almost done implementing this.

**Comment by hannesmuehleisen** [comment]
This has been merged
