### ISSUE TITLE
R: Split documentation

### ISSUE THREAD

**Issue by krlmlr** [cwida/duckdb#740]
The following functions should get their own man page:

- [x] `src_duckdb()` (unless #739)
- [ ] `duckdb_register()` and `duckdb_unregister()`
- [ ] `read_csv_duckdb()`

I'm not sure we need to redocument all DBI methods here, perhaps a link to DBI documentation is sufficient?

After #738.

**Comment by krlmlr** [comment]
@hannesmuehleisen: Should we rename `read_csv_duckdb()` to `duckdb_read_csv()` ? Do we need to maintain an alias?

**Comment by hannesmuehleisen** [comment]
yeah lets rename with alias, i think some ppl out there are using the former
