### ISSUE TITLE
RTRIM and LTRIM need a characters arguments

### ISSUE THREAD

**Issue by edgarrmondragon** [cwida/duckdb#743]
First of all, thanks for building this. I just recently found it and I'm already starting to incorporate it into my stack.

When trying to pass the `characters` argument to either function like this

```sql
SELECT RTRIM('x000', '0');
```

the following error is raised

```
Error: Unknown: No function matches the given name and argument types 'rtrim(VARCHAR, VARCHAR)'. You might need to add explicit type casts.
	Candidate functions:
	rtrim(VARCHAR) -> VARCHAR
```

The statement I tried to use produces the expected output in both PostgreSQL and SQLite.

By looking at the tests cases for the functions https://github.com/cwida/duckdb/blob/0c760c40819aa716fb4430dbf12b2f73d28994fc/test/sql/function/test_stringfunctions.cpp#L455-L463

it's clear the function signature doesn't expect the second argument, which would be pretty useful to remove characters other than simple spaces.

I'd be happy to contribute a PR for this but I'm not at all familiar with C++ code.

Version: master @ 0ae3c1c633b34db7cd8e8538ffbd6532ab6d5781

**Comment by Mytherin** [comment]
You are absolutely right, this should work similar to SQLite and Postgres. Thanks for submitting the issue.

If you are interested in working on it, please feel free :) otherwise I can take a look at it later. Take a look at `trim.cpp`.

**Comment by Mytherin** [comment]
Should be implemented now
