### ISSUE TITLE
parquet should show headers

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#744]
**Using the command line**, _select** * from parquet_scan('file.pq')_ produces just the data, not the name of the column using the command line. (edit: I realize this is just due to .headers being set to false).

In any case, I feel like this issue is related to the below:

dbGetQuery(con,'select * from parquet_scan("/home/alan/test.parquet") limit 5')
Error in .local(conn, statement, ...) : 
  duckdb_prepare_R: Failed to prepare query select * from parquet_scan("/home/alan/test.parquet") limit 5
Error: Unknown: TABLE FUNCTION parameter cannot contain column names

**Comment by hannesmuehleisen** [comment]
Try single quotes, like so
```R
dbGetQuery(con,"select * from parquet_scan('/home/alan/test.parquet') limit 5")
```

**Comment by alanpaulkwan** [comment]
ah.


*Alan Kwan*

+852-9794-9483 (HK)

(626)-216-4899 (USA)

**Comment by alanpaulkwan** [comment]
oh i see. i should have conjectured single and double quotes are treated differently
