### ISSUE TITLE
Will there ever be a node.js/TypeScript SDK?

### ISSUE THREAD

**Issue by ali-habibzadeh** [cwida/duckdb#745]

**Comment by Mytherin** [comment]
We are planning to release a Javascript version at some point. Some work has been done on compiling DuckDB to asm.js. See #310 for more info on that. Unfortunately we are not very well versed in Javascript, so it hasn't been a particular priority for us. We would welcome any contributions towards making this happen though :)

**Comment by hannesmuehleisen** [comment]
See also #661

**Comment by ali-habibzadeh** [comment]
I am happy if you like us to arrange a conversation and see if DeepCrawl can help CWI in this? We also are interested in improvement in parquet reader and streaming.

**Comment by Mytherin** [comment]
For sure :) We would welcome any contributions on these fronts. Perhaps you could email Hannes or me and we can arrange a Zoom call or so.

**Comment by hannesmuehleisen** [comment]
Continuing in #661
