### ISSUE TITLE
Is there a plan for duckdb to support blob type?

### ISSUE THREAD

**Issue by csbinghu** [cwida/duckdb#749]
From the information of website:www.duckdb.org, duckdb is not support blob type. Is there a plan for duckdb to support blob type?

**Comment by Mytherin** [comment]
Thanks for the issue! The blob type is currently supported, and should be in all the releases. It appears the documentation is outdated. I have just updated the documentation to include the blob type.

**Comment by Mytherin** [comment]
Going to close this issue, the docs can be found [here](https://duckdb.org/docs/sql/data_types/blob).
