### ISSUE TITLE
Fail builds where R CMD has NOTEs

### ISSUE THREAD

**Issue by krlmlr** [cwida/duckdb#764]
e.g. https://travis-ci.org/github/cwida/duckdb/builds/708595115#L713 from #757 has 3 NOTEs but is successful.

For this, {tic} will come in very handy. Need to find a way to integrate with existing infrastructure (e.g. S3 upload).

Let's merge #762 before tackling this.

**Comment by pat-s** [comment]
Usually `rcmdcheck::rcmdcheck(error_on = "note")` is used for this. We usually use {tic} for that which makes installation and execution easy.

However, we probably won't ever get rid of the following NOTE

```
  installed size is 62.2Mb

  sub-directories of 1Mb or more:

    libs  61.9Mb
```

and enforcing this restriction would mean that the R builds will never succeed? @krlmlr

**Comment by krlmlr** [comment]
Can we `error_on = "warning"` here, and perhaps accept at most one note?

`strip -g` reduces to 7.3 MB, this might even get rid of the NOTE. I wonder why it's not run on CRAN -- need to double-check that.

OTOH, CRAN doesn't seem to care about this particular NOTE that much.
