### ISSUE TITLE
Build 32-bit version on Windows

### ISSUE THREAD

**Issue by krlmlr** [cwida/duckdb#767]
The compiler currently exits with out of memory after compiling ~50k of ~150k lines of C++ amalgamation code. Need to find a way to avoid amalgamation in R~~, requires a custom `Makevars` file generated by `configure`~~.

- Run `cmake` as part of `configure`
- Statically link resulting `src/libduckdb_static.a` and `duckdbr.cpp`

**Comment by krlmlr** [comment]
@hannesmuehleisen Are we still trying to switch to an amalgamation per library (instead of one big file) to lessen the burden on the compiler?

**Comment by hannesmuehleisen** [comment]
Fixed in #833
