### ISSUE TITLE
Unify scan ops and allow filter and projection pushdown into table functions (e.g. CSV/Parquet reader)

### ISSUE THREAD

**Issue by Schaefer-Thomas** [cwida/duckdb#782]
Hi,

is it already possible to read only specific columns from (gzipped) csv-files  into an existing table?
It would save us from preprocessing files or loading unneeded data.

(unfortunately, read_csv_auto might crash, if data type is guessed incorrectly)

**Comment by Mytherin** [comment]
This is not possible yet, but is on the agenda for extra features. Currently all the columns of the CSV file are always read.

**Comment by Schaefer-Thomas** [comment]
Do you have a preference on where this should be implemented? 
Filtering rows to import by field value would be cool, too.

**Comment by Mytherin** [comment]
My idea would be to implement it as part of the CSV scan, where any filters and projections are automatically pushed into the scan. E.g. if you do:

```sql
-- test.csv has 4 columns (col1, col2, col3, col4)
SELECT col1 FROM read_csv('test.csv') WHERE col4=1;
```
Only col1 and col4 will be read, and values of col1 will only be read for which col4 is equal to 1.

The table scans that we have that scan the base tables already do something similar, and we have plans to extend that support to any scans (including scans over external files, like parquet/csv files).

**Comment by Mytherin** [comment]
Going to reopen this with a new title, as we don't have an issue for it yet but it's something I want to do sooner rather than later :)

**Comment by hannesmuehleisen** [comment]
Parquet reader already does projection pushdown

**Comment by Mytherin** [comment]
Fair point ^^, but currently in an orthogonal way to the main scan, right? I think the unification will clean up the code a lot here.

**Comment by hannesmuehleisen** [comment]
correct, it will
