### ISSUE TITLE
R CMD check detects pragmas that suppress diagnostics

### ISSUE THREAD

**Issue by krlmlr** [cwida/duckdb#787]
https://travis-ci.org/github/cwida/duckdb/jobs/711921270#L2108

> File which contains pragma(s) suppressing diagnostics:
> ‘src/duckdb.cpp’

`R CMD check` looks for regular expressions of the form `"^\\s*#pragma (GCC|clang) diagnostic ignored"`, see https://github.com/wch/r-source/blob/trunk/src/library/tools/R/QC.R#L9352.

Can we strip these macros off of the amalgamation, at the expense of noise when building the R package? I have no idea why `R CMD check` does this, it seems this check has been introduced ~2 years ago. I haven't found a mention of this check in R-exts.

**Comment by hannesmuehleisen** [comment]
Yeah those should indeed not be there, need to figure out where they come from.

**Comment by hannesmuehleisen** [comment]
I have created a branch `nopragmadiag` where those should be zapped.

**Comment by hannesmuehleisen** [comment]
Merged
