### ISSUE TITLE
Potential performance opportunity with 2 phase distinct

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#793]
Data set is tpch lineitem at sf100.

There may be a performance opportunity to apply a local distinct at the vector level prior to the final distinct of the merged sets.  This may allow for collapsing the intermediate results earlier.

The SQL below is designed to model the expected performance benefits.  Performance uplift for group by with few values may be as much as 2x.  This may also allow for better linear scaling when parallel.  

Following examples below can be thought of as pseudo-code to apply to a group by + distinct.  Vector-level distinct would effectively group by the group by columns + any/all distinct columns. 

This may be some small trade-off when # distinct approaches # rows (PK).  (see last examples)

>>> print(cursor.execute('select count(*)  from lineitem').fetchall())
[(600027902,)]
>>> 
>>> start = timer()
>>> print(cursor.execute('select count(distinct(l_linenumber))  from lineitem').fetchall())
[(7,)]
>>> print(timer() - start)
15.9663889408
>>> 
>>> start = timer()
>>> print(cursor.execute('select count(*) from ( select l_linenumber from lineitem group by 1) a').fetchall())
[(7,)]
>>> print(timer() - start)
8.36377191544
>>> 
>>> 
>>> start = timer()
>>> print(cursor.execute('select l_linenumber, count(distinct(l_quantity)) from lineitem group by 1').fetchall())
[(7, 50), (4, 50), (1, 50), (5, 50), (2, 50), (6, 50), (3, 50)]
>>> print(timer() - start)
22.8657059669
>>> 
>>> start = timer()
>>> print(cursor.execute('select l_linenumber, count(*) from ( select l_linenumber, l_quantity from lineitem group by 1,2 ) a group by 1').fetchall())
[(7, 50), (4, 50), (1, 50), (5, 50), (2, 50), (6, 50), (3, 50)]
>>> print(timer() - start)
16.3370838165
>>> 
>>> 
>>> 
>>> start = timer()
>>> print(cursor.execute('select l_linenumber, count(distinct(l_partkey)) from lineitem group by 1').fetchall())
[(7, 13185917), (4, 19746814), (1, 19991564), (5, 19235106), (2, 19973328), (6, 17702604), (3, 19917841)]
>>> print(timer() - start)
60.4416091442
>>> 
>>> start = timer()
>>> print(cursor.execute('select l_linenumber, count(*) from ( select l_linenumber, l_partkey from lineitem group by 1,2 ) a group by 1').fetchall())
[(7, 13185917), (4, 19746814), (1, 19991564), (5, 19235106), (2, 19973328), (6, 17702604), (3, 19917841)]
>>> print(timer() - start)
57.3285169601

>>> start = timer()
>>> print(cursor.execute("select l_linenumber, count(distinct(l_orderkey)) from lineitem  where l_shipdate < '1993-01-01' group by 1").fetchall())
[(7, 2716370), (4, 10862707), (1, 19006867), (5, 8148588), (2, 16292599), (6, 5432163), (3, 13575734)]
>>> print(timer() - start)
19.1697640419
>>> 
>>> start = timer()
>>> print(cursor.execute("select l_linenumber, count(*) from ( select l_linenumber, l_orderkey from lineitem  where l_shipdate < '1993-01-01' group by 1,2 ) a group by 1").fetchall())
[(7, 2716370), (4, 10862707), (1, 19006867), (5, 8148588), (2, 16292599), (6, 5432163), (3, 13575734)]
>>> print(timer() - start)
20.8474109173

**Comment by hannesmuehleisen** [comment]
We are working on parallelising the aggregate hash table in #734, which does also create local aggregates first and then merges them. So I think that this proposal is subsumed by that.

**Comment by jtommaney-alibaba** [comment]
Sounds good.
