### ISSUE TITLE
Feature request:  modify degree of parallelism at statement/session level

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#794]
This may already be implemented, but it would be useful for performance profiling if the degree of parallelism can be set at a statement level via a hint or other syntax, and at the session level via sql interface/wrapper.

**Comment by hannesmuehleisen** [comment]
Did you try `PRAGMA threads=8` ?

**Comment by jtommaney-alibaba** [comment]
let me know if I am missing something:  example query seems to be 1.2 seconds at DoP (degree of parallelism) 1,4,16

>>> start = timer()
>>> print(cursor.execute("select count(*) from lineitem where l_shipdate <> '1993-01-01' and l_quantity <> 50 and l_partkey <> 25;").fetchall())
[(74514713,)]
>>> print(timer() - start)
1.20809102058
>>> 
>>> print(cursor.execute('PRAGMA threads=4;').fetchall())
[]
>>> start = timer()
>>> print(cursor.execute("select count(*) from lineitem where l_shipdate <> '1993-01-01' and l_quantity <> 50 and l_partkey <> 25;").fetchall())
[(74514713,)]
>>> print(timer() - start)
1.2104549408
>>> 
>>> print(cursor.execute('PRAGMA threads=16;').fetchall())
[]
>>> start = timer()
>>> print(cursor.execute("select count(*) from lineitem where l_shipdate <> '1993-01-01' and l_quantity <> 50 and l_partkey <> 25;").fetchall())
[(74514713,)]
>>> print(timer() - start)
1.20305895805
-------------------


import math
import duckdb
from timeit import default_timer as timer

conn = duckdb.connect(':memory:', read_only=False )
cursor = conn.cursor()

cr_sql="""CREATE TABLE lineitem (L_ORDERKEY integer NOT NULL,L_PARTKEY integer NOT NULL,L_SUPPKEY integer NOT NULL,L_LINENUMBER integer NOT NULL,L_QUANTITY decimal(15,2) NOT NULL,L_EXTENDEDPRICE decimal(15,2) NOT NULL,L_DISCOUNT decimal(15,2) NOT NULL,L_TAX decimal(15,2) NOT NULL,L_RETURNFLAG char(1) NOT NULL,L_LINESTATUS char(1) NOT NULL,L_SHIPDATE date NOT NULL,L_COMMITDATE date NOT NULL,L_RECEIPTDATE date NOT NULL,L_SHIPINSTRUCT char(25) NOT NULL,L_SHIPMODE char(10) NOT NULL,L_COMMENT varchar(44) NOT NULL) """
cursor.execute(cr_sql);

l_sql="""copy lineitem from '/home/j.tommaney/tpch/100/o_lineitem.tbl.1' (delimiter '|')"""
cursor.execute(l_sql)

**Comment by Mytherin** [comment]
Did you install DuckDB through pip or from source? The version from pip doesn't have parallelism enabled yet.

**Comment by jtommaney-alibaba** [comment]
From pip.

**Comment by Mytherin** [comment]
Try installing the latest version with `pip install duckdb --pre --upgrade`

**Comment by jtommaney-alibaba** [comment]
Yes, that works, thank you.  closing here.

with partial tpch100 data set
select count(*) from lineitem where l_shipdate <> '1993-01-01' and l_quantity <> 50 and l_partkey <> 25;

DoP 1  -  1.56
DoP 2  -  1.13
DoP4  -  0.87
DoP6  -  0.84

**Comment by Mytherin** [comment]
Great, thanks for the numbers! Not so great yet, but we will get there :) I suspect contention in the scan or buffer manager to be the culprit.

**Comment by Mytherin** [comment]
By the way, as you have some experience here, what do you think we are missing in terms of profiling parallel queries? Any tips?
