### ISSUE TITLE
Build of trunk on MSYS2 failed in test suite

### ISSUE THREAD

**Issue by tenko** [cwida/duckdb#803]
Building fails in the test suite:

` from C:/msys64/home/rute/dev/pkg/duckdb-git/src/duckdb/test/sqlite/test_sqllogictest.cpp:28,
                 from test_sqllogictest.cpp:
C:/msys64/home/rute/dev/pkg/duckdb-git/src/duckdb/src/include/duckdb/common/file_system.hpp:56:27: error: expected unqualified-id before numeric constant
   56 |  static constexpr uint8_t FILE_CREATE = 1 << 3;
      |                           ^~~~~~~~~~~
C:/msys64/home/rute/dev/pkg/duckdb-git/src/duckdb/src/include/duckdb/common/serializer/buffered_file_writer.hpp:22:101: error: expected unqualified-id before numeric constant
   22 |  BufferedFileWriter(FileSystem &fs, string path, uint8_t open_flags = FileFlags::WRITE | FileFlags::FILE_CREATE);
      |                                                                                                     ^~~~~~~~~~~
`

Disabling the unit test temporary fixes the problem. Not sure about the
cause. Perhaps the symbol is defined elsewhere?

**Comment by Mytherin** [comment]
Seems to be an issue with the FILE_CREATE macro being defined by windows.h. We should rename the FILE_CREATE, perhaps to DFILE_CREATE_NEW or so.

**Comment by hannesmuehleisen** [comment]
Its not windows.h, its the bastardised version of it that mingw uses... But indeed, another rename is probably in order.

**Comment by tenko** [comment]
I can confirm that renaming the symbol fixes the build problem.

These are a bit tricky as for sure a common name will collide
on some exotic platform or combination in the future.

Perhaps a unique prefix like DDB_[NAME] could be used?

Not sure if these symbols are end user visible (API) though,
probably do not want to change to much of that.

**Comment by Mytherin** [comment]
Should be fixed now, feel free to reopen if the issue persists
