### ISSUE TITLE
ALIAS syntax, can't use single quotes  

### ISSUE THREAD

**Issue by luxint** [cwida/duckdb#812]
In DuckDB I cannot do this:
`sqlite> select region as 'my region' from bigsales limit 10;`
`Error: Parser: syntax error at or near "'my region'" [18]`

However in sqlite3 this is no problem:
`sqlite> select region as 'my region' from sales limit 10;`
`Sub-Saharan Africa`
`Middle East and North Africa`
`Australia and Oceania`
I know I can use double quotes in DuckDB (and in sqlite3), the reason I'm asking, is because I'm generating dynamic sql and I have to escape the double quotes with backslash in the generated sql and later remove the backslash, could be much simpler if I could use quotes like in sqlite3!

**Comment by Mytherin** [comment]
Interesting, I didn't know that this worked in SQLite. I will have a look to see if I can add it.

**Comment by Alex-Monahan** [comment]
We also have some users that use this syntax, so this would be helpful! So far, I have just dissuaded them by reminding them that it isn't good, standard SQL! :-)

**Comment by Mytherin** [comment]
So I had a look and it seems easy for me to add it to the parser as long as the `AS` clause is used, i.e. this would work:

```sql
select region as 'my region'
```

But this would not:
```sql
select region 'my region'
```

The reason for that is that it causes ambiguity in the parser. e.g. if you have the following statement:

```sql
select region ! 'my region'
```
It is not clear if 'my region' is an alias to the expression `region !`, or if it is a single expression `region ! 'my region'` without an alias.

Would only adding support as long as "AS" is used be acceptable?

**Comment by Alex-Monahan** [comment]
That is the most common pattern I've seen with our SQLite users, so that would work well for me!

**Comment by luxint** [comment]
yes, only for 'AS' would work for me !

**Comment by Mytherin** [comment]
Should be implemented now in the master :)
