### ISSUE TITLE
CLI-mode ".tables" command is not working

### ISSUE THREAD

**Issue by mrayva** [cwida/duckdb#815]
sqlite> .tables
Error: Parser: syntax error at or near "ORDER" [2]

**Comment by Mytherin** [comment]
Can confirm this breaks, will have a look.

**Comment by mrayva** [comment]
Thanks! same with .databases :

sqlite> .databases
Error: Catalog: Table with name pragma_database_list does not exist!

**Comment by Mytherin** [comment]
Fixed as well, while I'm at it :)

**Comment by Mytherin** [comment]
Merged now
