### ISSUE TITLE
add DATEFORMAT as parameter to copy function

### ISSUE THREAD

**Issue by luxint** [cwida/duckdb#818]
It would be helpful if the copy function also would have a DATEFORMAT parameter so that dates in for instance m/d/Y format would be automatically converted to yyyy-mm-dd and imported into your date columns. This would avoid to pre-process the csv file first.

example: copy sales from 'sales2020.csv' (DATEFORMAT '%m/%d/%Y');

**Comment by Mytherin** [comment]
I have implemented this now in the strftime branch, following [the specifiers used in Python](https://strftime.org) (which I believe are the same ones used in C?).

**Comment by Mytherin** [comment]
Merged into master, see [here](https://duckdb.org/docs/sql/functions/dateformat) for the documentation.
