### ISSUE TITLE
Clean up exported symbols

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#827]
Right now, there are plenty of symbols exported by DuckDB, a condensed list can be produced like so:
`nm -C --defined-only build/release/src/libduckdb.so  | grep -v duckdb | grep -v std:: | grep -v GLIBC`

Relevant entries:
- [x] hll_* functions from hyperloglog
- [x] mz_*, tdefl_* and tinfl_* functions from miniz
- [ ] utf8proc_* from utf8proc
- [x] tons of stuff from postgres, base_yylex, copyObject, makeString etc.
- [x] LogMessage:: from re2
- [x] ReplayState::, FunctionState::, AggregateState::, RandomBindData::, UnixFileHandle:: etc. from duckdb

None of this stuff should be exported globally

**Comment by hannesmuehleisen** [comment]
See #828 as well

**Comment by hannesmuehleisen** [comment]
CC @charlesmccarthy

**Comment by hannesmuehleisen** [comment]
utf8proc_ is used by linenoise in the the shell hence we cannot namespace it directly yet. calling this sufficient otherwise.

**Comment by charlesmccarthyirl** [comment]
@hannesmuehleisen For the #define things, will they be addressed separately? (#define's are scoped globally even if they're within a namespace). e.g. of one: `#define TINFL_DECOMPRESS_MEM_TO_MEM_FAILED ((size_t)(-1))`. Though there may be full-on function ones too in the libraries, I haven't checked. I guess a regex replace on all #define's under the external dir would be quick and DUCKDB_ could be prepended or something

**Comment by hannesmuehleisen** [comment]
@charlesmccarthyirl i think defines are only problematic in the header file, not in the .cpp file. As of now I see those:

````C++
#define DUCKDB_AMALGAMATION 1
#define DUCKDB_SOURCE_ID "b'3b5725f9e'"
#define DEFAULT_SCHEMA "main"
#define TEMP_SCHEMA "temp"
#define INVALID_SCHEMA ""
#define suint64_t int64_t
#define STANDARD_VECTOR_SIZE 1024
#define ASSERT_RESTRICT(left_start, left_end, right_start, right_end)                                                  \
#define FILE_BUFFER_SIZE 4096
#define SERIALIZER_DEFAULT_SIZE 1024
````

Most should indeed be renamed so all use the `DUCKDB_` prefix.
