### ISSUE TITLE
performance opportunity on large scans

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#829]
It looks like this may already be identified, (fixme comment on InitializeScanWithOffset), but there appears to be a non-linear performance in scans that becomes impactful beyond about 100 million rows scanned.   

create table l_16m as select l_partkey, l_linenumber from lineitem limit 16000000
. . .
create table l_2048m as select l_partkey, l_linenumber from lineitem limit 2048000000

select  count(*) from  l_<size>m  where l_partkey < 13000000 and l_linenumber <=3

Result: about 53.5 million rows/second at 16 million rows scanned.
             about 18.5 million rows/second at 1024 million rows scanned.
             about 10.8 million rows/second at 2048 million rows scanned.

![duck_scans](https://user-images.githubusercontent.com/41884051/89958664-4b95da00-dbef-11ea-99e5-4683d1464f81.png)
GDB shows ColumnScanState::Next and InitializeScanWithOffset becoming dominant.
<img width="2008" alt="Screen Shot 2020-08-11 at 4 05 19 PM" src="https://user-images.githubusercontent.com/41884051/89959160-99f7a880-dbf0-11ea-8e9b-2205512f57e7.png">
<img width="2008" alt="Screen Shot 2020-08-11 at 4 05 05 PM" src="https://user-images.githubusercontent.com/41884051/89959187-ac71e200-dbf0-11ea-8db1-4252e491772a.png">

**Comment by Mytherin** [comment]
Thanks for the detailed comments and profiler output! I had already forgotten about this FIXME :) I will have a look to see if I can fix this behavior.

**Comment by Mytherin** [comment]
This should be fixed now. Could you verify that it is fixed if/when you have time? Thanks!

**Comment by Mytherin** [comment]
Looking at the stack trace it also seems that a significant amount of time is spent in the version manager - which makes sense as I have not looked at optimizing that at all yet. The versions should (1) be cleaned up properly after no longer being required, and (2) be optimized for bulk appends by versioning entire vectors instead of individual rows.

**Comment by jtommaney-alibaba** [comment]
Confirmed, clean fix of issue now shows linear scaling. 

![Scan_Rate_V338_update](https://user-images.githubusercontent.com/41884051/90194825-f38cde00-dd7c-11ea-86c5-c69455cc0c8f.png)

**Comment by Mytherin** [comment]
Thanks for verifying, great :)
