### ISSUE TITLE
Remove Duplicate Aggregates

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#84]
Right now the AGGREGATE_AND_GROUP_BY node will happily perform all aggregates in the query, even if the aggregate occurs multiple times (i.e. `SELECT SUM(x), SUM(x) + 2` will result in both aggregates being executed). The duplicates should be removed here.

**Comment by aris-koning** [comment]
I think I am dropping my idea of extending the CommonSubExpressionOptimizer. I don't think a solution in that direction is going to behave/look nicely in the PhysicalOperator implementations.

What probably works better is a separate Optimizer that checks for projections bounded to the output of an aggregate expression. Before optimization, for a protoypical example like "select sum(i), sum(i) from foo;" the plan looks like
PROJECTION[#0, #1](AGGREGATE_AND_GROUP_BY[SUM(0.0), SUM(0.0)](GET(foo)))
In a separate optimizer, I am basically going to transform this into
PROJECTION[#0, #0](AGGREGATE_AND_GROUP_BY[SUM(0.0)](GET(foo)))

**Comment by Mytherin** [comment]
Ah sorry, I meant to respond to you but I totally forgot. Yes, I think removing the duplicate aggregates from the LogicalAggregate and updating the references in the LogicalProjection underneath is the way to go. 
- You can use the Expression::Equals method to check for equality between the different aggregates.
- You can create an unordered_map that checks for Expression equality using the ExpressionHashFunction and ExpressionEquality, e.g.:

> unordered_map<Expression *, size_t, ExpressionHashFunction, ExpressionEquality>

Hope that helps.

**Comment by aris-koning** [comment]
Ok, sorry that it takes some time. But I am getting somewhere :)

I think I have the above example working. Next challenge is to get this one going:
```
select i, sum(i), i, sum(i) from foo group by i;
PROJECTION[#0, #1, #0, #2](AGGREGATE_AND_GROUP_BY[SUM(0.0), SUM(0.0)][0.0](GET(foo)
=>
PROJECTION[#0, #1, #0, #1](AGGREGATE_AND_GROUP_BY[SUM(0.0)][0.0](GET(foo)
```
Probably also have to check what happens when using filters like WHERE and HAVING.

Are there any other follow up cases to be aware of? 

I would like to stuff my work in a local feature branch. Should I offer that as a pull request?

**Comment by aris-koning** [comment]
Like I said, I have a branch ready named common-aggregate-expression on my local clone of this repo. I don't have write privileges on this github repo yet. So if you intend to keep it that way for now, I would need to need to know what the best way is to create a pull request. As far as I can tell from github documentation I should have my own fork of this repo on github en then request a pull request from there. And you probably want me to mark this fork as a private repo within my own account or something. 

Is that the way to go or can you just give me write access so I can push an innocent branch :)

**Comment by aris-koning** [comment]
Like I said, I have a branch ready named common-aggregate-expression on my local clone of this repo. I don't have write privileges on this github repo yet. So if you intend to keep it that way for now, I would need to need to know what the best way is to create a pull request. As far as I can tell from github documentation I should have my own fork of this repo on github en then request a pull request from there. And you probably want me to mark this fork as a private repo within my own account or something. 

Is that the way to go or can you just give me write access so I can push an innocent branch :)

**Comment by Mytherin** [comment]
I think sending a pull request is the way to go, but for a relatively small feature like this making a new branch is a bit overkill. I would say run the `make allunit` and `make format` commands and make sure all the tests pass, add your own tests, and then send a pull request to the main repo. We should have a contributors guidelines to make these steps more clear. I will add them. Thanks for the effort!

**Comment by aris-koning** [comment]
I have just created a fork with a separate branch in it plus a pull request. I didn't notice you guys shifted to a public repository. I have never worked with pull requests before.  But now I have seen it working in action, I have to admit that they are pretty cute. From now on I'll push my work to the pull request.

**Comment by aris-koning** [comment]
@Mytherin 
I was waiting for a commit in which 'subqueryflatten' is merged into 'master'? I think it is already done this weekend right? So I can pick it up again from there.

**Comment by Mytherin** [comment]
Yes the subqueryflatten branch has been merged indeed
