### ISSUE TITLE
Safer way of getting the column names and types of last query/result

### ISSUE THREAD

**Issue by luxint** [cwida/duckdb#840]
At the moment there is no accessor function to get the column names and type of column of the last query/result, in sqlite3 there are sqlite3_column_name and sqlite3_column_type functions which do this. At the moment you've got the result pointer and then you need to use the duckdb_result struct and the duckdb_column struct to get the column name(s) and types. I can imagine you might want to change these structs in the future which could possible break some bindings to duckdb. Especially when you are dynamically generating sql these functions would be nice.

**Comment by Mytherin** [comment]
Thanks for the suggestion! This is about the C API, correct?

**Comment by luxint** [comment]
Yes, it is about the C api.

**Comment by Mytherin** [comment]
This should be added now
