### ISSUE TITLE
Support column name aliases in CTE definitions

### ISSUE THREAD

**Issue by rainmaple** [cwida/duckdb#849]
when i run the Query in terminnal, the description of the error confused me:
*Error: Not implemented: Column name aliases not supported in CTEs*

`with recursive extended_tags(s_subtagclassid,s_supertagclassid) as (
	select tc_tagclassid, tc_tagclassid from tagclass
	UNION
	select tc.tc_tagclassid, t.s_supertagclassid from tagclass tc, extended_tags t
		where tc.tc_subclassoftagclassid=t.s_subtagclassid
)
select p_personid, p_firstname, p_lastname, array_agg(distinct t_name), count(*)
from person, message p1, knows, message p2, message_tag, 
	(select distinct t_tagid, t_name from tag where (t_tagclassid in (
  		select distinct s_subtagclassid from extended_tags k, tagclass
		where tc_tagclassid = k.s_supertagclassid and tc_name = 'BasketballPlayer') 
   )) selected_tags
where
  k_person1id = 15393162793684 and 
  k_person2id = p_personid and 
  p_personid = p1.m_creatorid and 
  p1.m_c_replyof = p2.m_messageid and 
  p2.m_c_replyof is null and
  p2.m_messageid = mt_messageid and 
  mt_tagid = t_tagid
group by p_personid, p_firstname, p_lastname
order by 5 desc, 1
limit 20;`

the other example is:
`WITH RECURSIVE chain(parent, child) as(
	SELECT m_c_replyof, m_messageid FROM message where m_messageid = 1236950581248
	UNION ALL
	SELECT p.m_c_replyof, p.m_messageid FROM message p, chain c where p.m_messageid = c.parent 
)
select f_forumid, f_title, p_personid, p_firstname, p_lastname
from message, person, forum
where m_messageid = (select coalesce(min(parent), 236950581248) from chain)
  and m_ps_forumid = f_forumid and f_moderatorid = p_personid;`

Does the existing version of duckdb not support the CTEs? Or any other problems exists in my query mentioned above? 
ps: the sql comes from the LDBC Benchmark for pg. [source](https://github.com/ldbc/ldbc_snb_implementations/blob/dev/postgres/queries/interactive-complex-12.sql)

**Comment by hannesmuehleisen** [comment]
Indeed aliasing is not yet supported there, should be eventually. For now you can achieve the same effect by adding the alias to the select clause like so:
````SQL
with recursive extended_tags as ( select tc_tagclassid AS s_subtagclassid, tc_tagclassid AS s_supertagclassid from tagclass UNION select tc.tc_tagclassid, t.s_supertagclassid from tagclass tc, extended_tags t where tc.tc_subclassoftagclassid=t.s_subtagclassid ) select p_personid, p_firstname, p_lastname, array_agg(distinct t_name), count(*) from person, message p1, knows, message p2, message_tag, (select distinct t_tagid, t_name from tag where (t_tagclassid in ( select distinct s_subtagclassid from extended_tags k, tagclass where tc_tagclassid = k.s_supertagclassid and tc_name = 'BasketballPlayer') )) selected_tags where k_person1id = 15393162793684 and k_person2id = p_personid and p_personid = p1.m_creatorid and p1.m_c_replyof = p2.m_messageid and p2.m_c_replyof is null and p2.m_messageid = mt_messageid and mt_tagid = t_tagid group by p_personid, p_firstname, p_lastname order by 5 desc, 1 limit 20;
````

**Comment by rainmaple** [comment]
Thanks ! It really helped me. Another point is the addup of the func array_agg() , oh this is just my advice.

**Comment by hannesmuehleisen** [comment]
`array_agg` is not supported at this time. I opened an issue for it, see #851

**Comment by Mytherin** [comment]
This is implemented now
