### ISSUE TITLE
Fix R builds

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#850]
Currently, Linux R builds fail with
````
The command "eval curl -fLo /tmp/R-devel-$(lsb_release -cs).xz https://travis-ci.rstudio.org/R-devel-$(lsb_release -cs).xz " failed.
````
Maybe @krlmlr could check with RStudio what's going on there?

**Comment by krlmlr** [comment]
Confirmed.

@jimhester @jeroen: Do we still support R binaries for Linux on Travis CI?

**Comment by jeroen** [comment]
This will be fixed when this gets merged: https://github.com/travis-ci/travis-build/pull/1941

A workaround is to use `dist: xenial` for now

**Comment by jeroen** [comment]
FYI `dist: bionic` should now work again.
