### ISSUE TITLE
Support array aggregation

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#851]
e.g. `array_agg`, see https://www.postgresqltutorial.com/postgresql-aggregate-functions/postgresql-array_agg-function/

**Comment by Mytherin** [comment]
Is there any difference between `ARRAY_AGG` and our current `LIST` aggregate, or would an alias be sufficient?

**Comment by Alex-Monahan** [comment]
Would you be open to adding a group_concat alias as well, or is the behavior different? It would help migration from SQLite!

**Comment by Mytherin** [comment]
`GROUP_CONCAT` seems to be equivalent to `STRING_AGG`, not to `ARRAY_AGG`. ARRAY_AGG returns a list, whereas GROUP_CONCAT returns a string. As far as I know SQLite does not have support for nested types.

I can add the alias for string_agg.

**Comment by Alex-Monahan** [comment]
Ah, I see! Thank you!

**Comment by Mytherin** [comment]
This is implemented now
