### ISSUE TITLE
SIMD extensions

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#855]
Are there places where specific SIMD instructions are currently used or plan to be used?

**Comment by hannesmuehleisen** [comment]
No, *explicit* SIMD is currently not used anywhere. We are however careful to provide the compiler  [auto-vectorizers](https://gcc.gnu.org/projects/tree-ssa/vectorization.html) with plenty of opportunity to insert SIMD instructions and they are doing that. In a recent performance comparison of our vector library with a proprietary competitor that is using explicit SIMD no relevant performance differences was found. 

Explicit SIMD also has the disadvantage of greatly reducing binary compatibility and requiring more complex linker flags for the end-user's application, both of which are quite problematic for a *library*. That being said, if a very clear performance benefit could be shown that can only be achieved through explicit SIMD and not with (clever) scalar code, we would be open to reconsider.

**Comment by jtommaney-alibaba** [comment]
Sounds good, thanks for the update.

Understand disadvantage of greatly reducing binary compatibility

**Comment by msmshazan** [comment]
How about using Intel® Implicit SPMD Program Compiler for auto parallelization ? https://ispc.github.io/index.html
@hannesmuehleisen

**Comment by hannesmuehleisen** [comment]
@msmshazan would indeed be interesting to see if this intel compiler could improve performance. It would also be interesting if the resulting binaries run on AMD and friends.

**Comment by msmshazan** [comment]
It supports arm neon. I don't think cross architecture shouldn't be an issue unless we have to target MIPS or PowerPC architectures in which case we can fallback to normal non ispc vectorization code
