### ISSUE TITLE
Vector-optimized fixed length character fields

### ISSUE THREAD

**Issue by jtommaney-alibaba** [cwida/duckdb#856]
Add optimization to allow for fixed length character fields to deliver performance close to corresponding length numeric for equality compare operations.

examples from TPC-H schema the l_returnflag and l_linestatus with only a few distinct values.

Possible scope support for fixed length of 1 , 2 , 3 or 4 characters?  This may overlap with optimizations made possible by DICTIONARY_VECTOR mentioned in #396.  Support for ENUM may also provide corresponding performance uplift.  

Currently about a 3x overhead for fixed length strings vs corresponding integer map.
  
>>> start = timer()
>>> print(cursor.execute("""
... select l_returnflag, l_linestatus, count(*) from lineitem where l_linestatus in ('F','O') and l_returnflag in ('A','N','R') group by 1,2 order by 1,2;""").fetchall());
[(u'A', u'F', 14804077), (u'N', u'F', 385998), (u'N', u'O', 29987794), (u'R', u'F', 14808183)]
>>> print('elapsed-', timer() - start)
('elapsed-', 2.4747610092163086)
>>> 
>>> 
>>> start = timer()
>>> print(cursor.execute("""
... select l_returnflag_int, l_linestatus_int, count(*) from lineitem where l_linestatus_int in (1,2) and l_returnflag in (1,2,3) group by 1,2 order by 1,2;""").fetchall());
[]
>>> print('elapsed-', timer() - start)
('elapsed-', 0.8592000007629395)

**Comment by hannesmuehleisen** [comment]
I would argue that this is an optimisation for the aggregate hash table.

**Comment by jtommaney-alibaba** [comment]
There is also an impact on compare operations with count(*), although smaller:

>>> start = timer()
>>> print(cursor.execute("""
... select  count(*) from lineitem where l_linestatus in ('F','O') and l_returnflag in ('A','N','R');""").fetchall());
[(59986052,)]
>>> print('elapsed-', timer() - start)
('elapsed-', 1.288905143737793)
>>> 
>>> 
>>> 
>>> start = timer()
>>> print(cursor.execute("""
... select   count(*) from lineitem where l_linestatus_int in (1,2) and l_returnflag in (1,2,3) ;""").fetchall());
[(0,)]
>>> print('elapsed-', timer() - start)
('elapsed-', 0.8259851932525635)

**Comment by jtommaney-alibaba** [comment]
A nice to have feature is relatively consistent performance across data types (when the domain size is consistent).

**Comment by Mytherin** [comment]
I'm not sure how relevant this optimization will be after we have implemented dictionary compression. Small strings tend to have many duplicates, and a dictionary representation should provide similar performance there while being more flexible. The problem with a fixed-width representation is that the use cases are very limited; i.e. they can basically only be used with `VARCHAR(1)` because of unicode (as `VARCHAR(1)` can already contain 4-bytes per field).

**Comment by jtommaney-alibaba** [comment]
Agree dictionary compression has superior flexibility vs. fixed length.

One user-facing goal is to allow a field with "few" distinct values to have similar profile regardless of data type/data modeling.  Dictionary accomplishes this across more use cases than fixed width.

**Comment by hannesmuehleisen** [comment]
Closing this then
