### ISSUE TITLE
Python binary wheels

### ISSUE THREAD

**Issue by occasionallydavid** [cwida/duckdb#861]
The DuckDB build process is fairly heavyweight, I guess due to lots of templated C++ (haven't checked the code yet ;)). Additionally I notice cc1 using at least 5GB memory during build, limiting the kinds of VMs DuckDB could even be installed.

Would it be possible to provide binary wheels for PyPI instead, at least for Linux? Assuming the dependency situation is straightforward (just libstdc++ for example), this may be as straightforward as 'pip install wheel twine' 'python setup.py bdist_whl', 'twine upload dist/*.whl' or similar.

Thanks

**Comment by hannesmuehleisen** [comment]
We have those, what platform are you trying to install DuckDB on? See for example here: https://pypi.org/project/duckdb/#files

**Comment by hannesmuehleisen** [comment]
@occasionallydavid ?

**Comment by Mytherin** [comment]
Closing this issue for now. We have revamped the build process for Python/R so it should not use as much memory, and we do already provide binary wheels. Feel free to re-open if you encounter an issue with the binary wheels.
