### ISSUE TITLE
Feature request: callback hook for Parquet blob reading

### ISSUE THREAD

**Issue by dforsber** [cwida/duckdb#877]
# Feature request: callback hook for Parquet blob reading

It would be nice to abstract out the Parquet reader filesystem calls (open, seek, read, close) away from the module to the DuckDB client so that it would be possible to fetch the Parquet byte blobs from any storage, e.g. S3, while not requiring linking into DuckDB any new SDKs.

For example while consuming DuckDB API, allow optional callbacks to be passed that are called instead of FS system calls if present.

**Comment by hannesmuehleisen** [comment]
From which API do you want to do this? C++?

**Comment by dforsber** [comment]
> From which API do you want to do this? C++?

Yes. Eventually from TS, but since that's not available and I think it is best to do node module with C++ SDK.

**Comment by dforsber** [comment]
> > From which API do you want to do this? C++?
> 
> Yes. Eventually from TS, but since that's not available and I think it is best to do node module with C++ SDK.

But we are currently prototyping with Python :).

That said we hacked AWS C++ SDK for AWS S3 (S3 TransferManager) into DuckDB build (python module) and modified the Parquet reader to get data from S3 instead of local filesystem. It works fine, except that round trips with S3 are expensive and thus caching should be used for metadata at least (can e.g. skip the magics too). To achieve caching, it would be easier to just push out actual FileSystem calls out of the module and handle that part separately. Plus, it would have the benefit of not requiring DuckDB build to have the libs in place. On the other hand, there would be slight overhead via the module interface I guess, which should be negligible compared to S3 latency for example.

**Comment by Mytherin** [comment]
So our current [File System class](https://github.com/cwida/duckdb/blob/8dd67a066832d041b27d807947a60a355f345bbf/src/include/duckdb/common/file_system.hpp) is implemented using virtual functions, and a different file system can be implemented and passed onto the system in the C++ API. See [here](https://github.com/cwida/duckdb/blob/ef8385f0b9b26fb10a1f3ca314baa196f7a3f47a/test/sql/storage/test_readonly.cpp) for example. Is this sufficient for you to achieve your desired behavior? I did see that the Parquet reader does not use this file system class, however, that can of course be fixed.

**Comment by hannesmuehleisen** [comment]
Since the parquet reader now uses the FileSystem class and therefore the read from disk can be redirected I think this can be closed.
