### ISSUE TITLE
Parquet BOOL column COUNT mismatch with Presto/parquet-tools/Drill

### ISSUE THREAD

**Issue by dforsber** [cwida/duckdb#878]
# Parquet optional BOOL column COUNT mismatch with Presto/parquet-tools/Drill (DuckDB v0.2.1 & v0.2.0)

Found out a weird situation where a single Parquet file being queried with DuckDB and Presto (AWS Athena) produce differing results over counts of an optional boolean column. We are running DuckDB with python38.

```
SELECT COUNT(url), b FROM tableA GROUP BY b ORDER BY b
```

```
Athena		DuckDB	parquet-tools	Drill
76889	FALSE	76901	76889		76889
11983	TRUE	11971	11983		11983
11079	NULL	11079	-		11079
```

```
Total
99951		99951
```

`parquet-tools` shows that the column is boolean. Also, we are using Glue Database on AWS and the `SHOW CREATE TABLE` there also shows boolean value for the field. Both queries run over a single Parquet file.

```
% parquet-tools cat data.parquet | grep -e '^<column> ' > col_b.dat
% grep true col_b.dat | wc
11983
% grep false col_b.dat | wc
76889
% cat col_b.dat | grep -v true | grep -v false | wc
0
```

Along the same lines with Apache Drill in embedded mode and over local parquet file gives the same results as Presto with the same SQL query.

- The Parquet file is generated by AWS Athena (Presto) with bucket count 1.
- There are like 250 columns on the table. Snappy.

**Comment by dforsber** [comment]
@Mytherin Kindly notifying you about this ticket's existence :). For us this is a current blocker on using DuckDB for any reliable query results, but we can't find out where the problem would be, unless it is e.g. DuckDB Parquet reader issue. We have been running the tests on OSX laptop, in AWS Lambda and both have the same issue.

**Comment by hannesmuehleisen** [comment]
It's entirely possible there is a bug in the Parquet reader for boolean columns. It would help if you could provide us with a Parquet file where the issue is exposed.

**Comment by hannesmuehleisen** [comment]
Could be related to #800

**Comment by dforsber** [comment]
> It's entirely possible there is a bug in the Parquet reader for boolean columns. It would help if you could provide us with a Parquet file where the issue is exposed.

I'll contact you via email about this. 👍🏻
