### ISSUE TITLE
Feature Request: Network Address datatype

### ISSUE THREAD

**Issue by skannan89** [cwida/duckdb#881]
I would like to store IP v4 and v6 addresses. I am thinking about storing them as `blob` or two `bigint`. It would be nice if there was a network address datatype (and functions) like [postgresql](https://www.postgresql.org/docs/12/datatype-net-types.html). Thanks for this amazing database.

**Comment by hannesmuehleisen** [comment]
This seems a bit far out for now, you could indeed use int or bigint to store those with some UDFs to extract/construct them.

**Comment by abdullahdevrel** [comment]
Is there any plans for this feature in the near future?  Network address datatypes would be awesome.

**Comment by Mytherin** [comment]
There is some work on this in the [inet extension](https://github.com/duckdb/duckdb/blob/master/test/sql/inet/test_inet_storage.test), but more work remains to be done to fully achieve postgres compatibility there.

**Comment by abdullahdevrel** [comment]
That is really great. Thank you.

**Comment by marklit** [comment]
Are there any plans to implement arithmetic functions? Is there any workaround for calculating IPv4 counts between two arbitrary IPv4 addresses?

```sql
select CAST(end_ip AS INET)::uint32 - CAST(start_ip AS INET)::uint32 + 1 AS num_ipv4s
FROM 'ipv4s.csv.gz'
```

```
Error: Conversion Error: Unimplemented type for cast (inet -> UINTEGER)
```

**Comment by szarnyasg** [comment]
DuckDB now supports IPv4 and IPv6 addresses: https://duckdb.org/docs/extensions/inet

**Comment by ivan-tkatchev** [comment]
The inet extension seems entirely useless at the moment, since it doesn't support any operations for IP addresses.

At the very minimum the subnet inclusion operations are needed: https://www.postgresql.org/docs/current/functions-net.html

(To allow searching for addresses in a table properly.)

**Comment by Maxxen** [comment]
@ivan-tkatchev In the works! https://github.com/duckdb/duckdb/pull/12575
