### ISSUE TITLE
Bug or wrong usage of Arrow (#866)?

### ISSUE THREAD

**Issue by DonIvanCorleone** [cwida/duckdb#890]
Hi there,

I came across something I do not fully understand:

This works perfectly:
```
rel = duckdb.from_parquet("TestFile.parquet")
print(rel.query("parquet", "SELECT * FROM parquet LIMIT 10").df())
```
I saw in #866 the initial Arrow support and gave it a try. Unfortunately, this did not work:

```
my_arrow_table  = pyarrow.parquet.read_table("TestFile.parquet")
rel = duckdb.arrow(my_arrow_table) # or just arrow() 
print(rel.query("arrow", "SELECT * FROM arrow LIMIT 10").df())
```
**Error** `RuntimeError: Not implemented: Unsupported Arrow type n`

Installed and tested with 

- duckdb 0.2.1 and 0.2.2.dev74
- pyarrow 1.0.0 and 1.0.1
- Python 3.7

Am I doing something stupid or is this some bug? Any ideas?

Cheers

**Comment by hannesmuehleisen** [comment]
Could be an unsupported type, can you share the test file?

**Comment by DonIvanCorleone** [comment]
Unfortunately I cannot share the testfile. At least not very easy. 
But I would love to check it against the `arrownull` branch. I will come back after I tested it.
