### ISSUE TITLE
duckdb_read_csv for out-of-memory data

### ISSUE THREAD

**Issue by waynelapierre** [cwida/duckdb#894]
I used to use MonetDBLite to work with out-of-memory CSV datasets. It seems MonetDBLite is no longer maintained while the old MonetDB.r package gets renovated. 

I heard DuckDB is a new implementation of MonetDB. To work with out-of-memory datasets in R, does the R package DuckDB hold any advantages over MonetDB.r in terms of speed and capacity?

**Comment by hannesmuehleisen** [comment]
DuckDB is absolutely **not** a new implementation of MonetDB. The query processing paradigm underlying DuckDB is vectorized query processing, MonetDB uses something else. DuckDB holds many advantages over MonetDB.R, the most striking would be no need to run an external MonetDB server and much faster query result transfer.

**Comment by waynelapierre** [comment]
Let me be more specific. If my desktop RAM is 16 GB, and I have a 100 GB CSV dataset. Could I use the duckdb_read_csv function to import it in R?

**Comment by Mytherin** [comment]
Yes, that should be possible. DuckDB is intended to support out-of-memory computation. You may need to set `PRAGMA memory_limit='16GB'` as currently DuckDB does not yet default to the systems' memory limit.

**Comment by waynelapierre** [comment]
I am trying to find some tutorials of the R package duckdb. The CRAN page only provides a manual with very limited information.

**Comment by hannesmuehleisen** [comment]
@waynelapierre i don't think there is much in the way of a tutorial yet. what would you expect from such a text?

**Comment by waynelapierre** [comment]
I believe there should be a tutorial in the Cran page to illustration a complete workflow of using the R package duckdb, including import data, clean data, analyze data, and write results.

**Comment by Mytherin** [comment]
There is some basic documentation [here](https://duckdb.org/docs/api/r) for the R package. Indeed that should be included in the CRAN page.

**Comment by waynelapierre** [comment]
I think it is better to use a big dataset to illustrate the capability of r package duckdb to handle out-of-memory data. For in-memory data, there are many other options in r and I don't think users would like to use the r package duckdb for small datasets.

**Comment by hannesmuehleisen** [comment]
Hey we would really appreciate it if you would create such a tutorial!
