### ISSUE TITLE
Serialization : Cannot copy BoundSubqueryExperssion

### ISSUE THREAD

**Issue by rainmaple** [cwida/duckdb#895]
when i do the ldbc benchmark using duckdb engine, of which the version is the latested, the sql below came crossed a error info:
``Serialazation : Cannot copy BoundSubqueryExperssion``
ps:I have tried in Postgresql 10, the sql can be successfully excuted. 

The sql came from the  [source](https://github.com/ldbc/ldbc_snb_implementations/blob/dev/postgres/queries/bi-5.sql)
```
WITH top100_popular_forums AS (
  SELECT fp_forumid AS forumid
    FROM forum_person fp
       , person p
       , place ci
       , place co
   WHERE 1=1
     AND fp.fp_personid = p.p_personid
     AND p.p_placeid = ci.pl_placeid
     AND ci.pl_containerplaceid = co.pl_placeid
     AND co.pl_name = 'Egypt'
   GROUP BY fp_forumid
   ORDER BY count(*) DESC, fp_forumid
   LIMIT 100
)
SELECT au.p_personid AS "person.id"
     , au.p_firstname AS "person.firstName"
     , au.p_lastname AS "person.lastName"
     , au.p_creationdate
     , count(DISTINCT p.m_messageid) AS postCount
  FROM top100_popular_forums t
       INNER JOIN forum_person fp ON (t.forumid = fp.fp_forumid)
       -- author of the post
       INNER JOIN person au ON (fp.fp_personid = au.p_personid)
       LEFT JOIN message p ON (1=1
                        AND au.p_personid = p.m_creatorid
                        AND p.m_ps_forumid IN (SELECT forumid from top100_popular_forums)
                        AND p.m_c_replyof IS NULL
                           )
 GROUP BY au.p_personid, au.p_firstname, au.p_lastname, au.p_creationdate
 ORDER BY postCount DESC, au.p_personid
 LIMIT 100
;
```

**Comment by hannesmuehleisen** [comment]
That is indeed a bug. Good catch!

**Comment by rainmaple** [comment]
Nice, duckdb is a good team always have quick response!

**Comment by Mytherin** [comment]
Thanks for opening the issue! Indeed this was a bug, I fixed it in #897. The query still does not work, however, because subqueries in non-inner joins are not supported at the moment.

**Comment by Alex-Monahan** [comment]
Would you mind clarifying a bit about which sub queries aren't supported, just so I can be careful? 
Is it just subqueries within a left join's ON statement that are not supported at the moment? I'm assuming that doing a left join to a subquery works.

**Comment by Mytherin** [comment]
Most subqueries are supported, there are a small amount of subqueries that are not supported right now:

* Correlated subqueries that contain window functions
* Correlated subqueries that contain FULL/LEFT OUTER JOIN
* Correlated subqueries inside the ON statement of a FULL/LEFT OUTER JOIN. This is allowed in some cases now, but not yet in all. 

None of these are very difficult to fix, but non-trivial and it hasn't been a priority yet. If you find a use case for any of them feel free to open an issue.

**Comment by Alex-Monahan** [comment]
You are 100% correct that those are suuuper edge cases and not worth prioritizing. I do not have any need of those today. Thanks for explaining them for me though!

**Comment by Mytherin** [comment]
Should be fixed now
