### ISSUE TITLE
Support Python date/datetime in binding arguments

### ISSUE THREAD

**Issue by jwills** [cwida/duckdb#915]
I hit the issue yesterday where I was trying to use a `date` in an argument binding and got a runtime exception about dates/datetimes not being supported yet; I wrote https://github.com/jwills/duckdb/commit/4b9bd881b28bd48e4e0ed52fafb986ef76d2a565 as a workaround, but I'm wondering if there is something more involved here to get this working that I'm missing?

**Comment by hannesmuehleisen** [comment]
It needs to be implemented still

**Comment by jwills** [comment]
Yeah totally, I'm just asking-- is the commit I wrote above the implementation? Or is there some additional complexity to doing this correctly that I missed?

**Comment by Mytherin** [comment]
Looks totally fine to me. I don't think there's any complexity here, the original author just didn't get around to implementing it in the first pass. If you have some time and submit that together with some test cases I would be happy to merge it :)

**Comment by jwills** [comment]
Awesome-- will turn it into a real PR w/tests and what not. Thanks!
