### ISSUE TITLE
Cannot find duckdb database file and unknown file extension

### ISSUE THREAD

**Issue by GitHunter0** [cwida/duckdb#917]
When I run this in R:
```
con <- DBI::dbConnect(duckdb::duckdb(), dbname="my_duckdb")
DBI::dbWriteTable(con, "tab1", mtcars)
DBI::dbDisconnect(con, shutdown=TRUE) 
```
I would expect the creation of a datebase file "my_duckdb" in my working directory as RSQLite does, however I cannot find anything. So where can I find duckdb database?

Also what is the file extension of duckdb databases? (duckdb equivalent of SQLite extension `.sqlite`)?

I would much appreciate if someone can clarify those simple basic questions since it would be very helpful (and faster) for me to use duckdb in R instead of RSQLite.

**Comment by hannesmuehleisen** [comment]
Try 
`con <- DBI::dbConnect(duckdb::duckdb(), dbdir="my_duckdb")`
or just
`con <- DBI::dbConnect(duckdb::duckdb(), "my_duckdb")`

The file extension is whatever you want, but you might want to use `my.duckdb` or something like that

**Comment by hannesmuehleisen** [comment]
This is also explained here: https://duckdb.org/docs/api/r

**Comment by GitHunter0** [comment]
@hannesmuehleisen , thank you very much, now I can finally use duckdb, it is a great advantage over SQLite to have time/date type support.

Just one more simple question, I saw it creates an additional file `.wal`, what is that for? Is it indispensable or can I erase it to work with just one file?

**Comment by Alex-Monahan** [comment]
WAL stands for write ahead log, and it is an important part about how
DuckDB stores your data! Any data in the WAL file has not yet been merged
into the main database file. So, you don't want to delete that file if it
has any data in it.

In order to force a checkpoint (or the writing of the WAL into the database
file) you just need to disconnect and then reconnect to the database. Then
you can use that single database file and it will be up to date, and the
WAL will be tiny.

However, as a small note, DuckDB files are not guaranteed to remain
compatible with future versions of DuckDB, so I wouldn't use it for long
term storage. For that use case, I would save the data as a Parquet file
and then read that into DuckDB later in the future when you need it again
(it's very fast!).

Does that help?

Happy SQL-ing!

**Comment by GitHunter0** [comment]
For sure @Alex-Monahan , thank you, it was very helpful!  

Just a few more questions if I may:  
(1) Nice to know about Parquet, I read very good reviews, what packages/commands do you recommend to integrate it in R workflow (e.g. easy reading and writing Parquet files)?  

(2) duckdb is taking more than double the space of the SQLite's for my database, 2GB vs 4.5 GB, is that normal?  

(3)  Unfortunately, duckdb seems to not allow multiple R sessions to connect to a single database concurrently as RSQLite does. As soon as a single R session loads an embedded server, that server is locked down and inaccessible to other R consoles. Wouldn't that be a problem for an application which has to retrieve data from the database to provide data for multiple concurrent users?

**Comment by Alex-Monahan** [comment]
Unfortunately I only have experience in Python, JS,and SQL, so I am no help for your R question!

The space may depend on your data's shape. How many rows/columns and what data types are you using? DuckDB has compressed storage on the roadmap so that is highly likely to improve soon!

DuckDB should allow multiple connections to the same database as long as they are read only connections. Only a single writer is allowed at time.

**Comment by GitHunter0** [comment]
@Alex-Monahan , no problem! The informations you provided so far have been crucial for me to be able to start with duckdb, so thanks a lot for that! 

My table has 27 million rows and 8 columns (6 Numeric, 1 Date and 1 Character). My concern is that the gap between SQLite in this regard seems quite significant. However I 'm sure duckdb is going to improve soon, I'm excited to see the future of this project 👍

**Comment by hannesmuehleisen** [comment]
@GitHunter0 could you elaborate on what the gap is and what kind of queries you are running? Thanks!

**Comment by hannesmuehleisen** [comment]
> Just a few more questions if I may:
> (1) Nice to know about Parquet, I read very good reviews, what packages/commands do you recommend to integrate it in R workflow (e.g. easy reading and writing Parquet files)?

DuckDB has built-in Parquet support so no additional packages are required. In case you are wondering how to read Parquet from SQL, see here: https://duckdb.org/docs/data/parquet

> (2) duckdb is taking more than double the space of the SQLite's for my database, 2GB vs 4.5 GB, is that normal?

Yes its an area of active development and this is not unexpected. We also plan to improve this soon.


> (3) Unfortunately, duckdb seems to not allow multiple R sessions to connect to a single database concurrently as RSQLite does. As soon as a single R session loads an embedded server, that server is locked down and inaccessible to other R consoles. Wouldn't that be a problem for an application which has to retrieve data from the database to provide data for multiple concurrent users?

You can access DuckDB databases from multiple R sessions at the same time, but only in read-only mode. For example:

`dbConnect(duckdb::duckdb(), dbdir="my_dir", read_only=TRUE)`

**Comment by GitHunter0** [comment]
> 
> 
> @GitHunter0 could you elaborate on what the gap is and what kind of queries you are running? Thanks!

Hey @hannesmuehleisen , of course, the gap I'm referring is the compression capability. As I mentioned, my duckdb database file is 2.5 times bigger than my SQLite's (4.5 GB vs 2 GB). However it is nice that you guys are already working on that 👍 

I also noted that my duckdb queries are taking longer. It is hard to provide a reproducible example since my data is big and restricted but one basic rotine example is something like this:

```
db_con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "db_fi.duckdb", read_only=TRUE)

# "my_table" has 27 millin rows, 8 columns, 2GB SQLite, 4.5GB duckdb                         
tab_con <- dplyr::tbl(db_con, "my_table")

tab_con %>% 
  filter(var1 %in% c(value11, value12), var2 > value2, var3 > value3) %>%
  select(var1, var2, var3) %>% 
  collect()
```
Time to complete the query: SQLite took 29.95 sec VS. duckdb 38.69 sec .
I observed that the key difference was in the time taken to retrieve data from the database to R, via collect() 

Lastly, sometimes duckdb takes a long time (minutes) to open the connection (via DBI::dbConnect(...)), which I believe is due to the behavior described by @Alex-Monahan , in which the .wal content is merged into the main database file when the connection is opened. If instead that behavior happened while closing the connection, this issue could be avoided, right?

**Comment by GitHunter0** [comment]
> 
> 
> > Just a few more questions if I may:
> > (1) Nice to know about Parquet, I read very good reviews, what packages/commands do you recommend to integrate it in R workflow (e.g. easy reading and writing Parquet files)?
> 
> DuckDB has built-in Parquet support so no additional packages are required. In case you are wondering how to read Parquet from SQL, see here: https://duckdb.org/docs/data/parquet
> 
> > (2) duckdb is taking more than double the space of the SQLite's for my database, 2GB vs 4.5 GB, is that normal?
> 
> Yes its an area of active development and this is not unexpected. We also plan to improve this soon.
> 
> > (3) Unfortunately, duckdb seems to not allow multiple R sessions to connect to a single database concurrently as RSQLite does. As soon as a single R session loads an embedded server, that server is locked down and inaccessible to other R consoles. Wouldn't that be a problem for an application which has to retrieve data from the database to provide data for multiple concurrent users?
> 
> You can access DuckDB databases from multiple R sessions at the same time, but only in read-only mode. For example:
> 
> `dbConnect(duckdb::duckdb(), dbdir="my_dir", read_only=TRUE)`

Good to know @hannesmuehleisen , thank you for the answers! 
For R users I also discovered 2 functions that might be handy (although they require one additional package):
```
arrow::write_feather()
arrow::read_feather()
```

**Comment by GitHunter0** [comment]
> 
> 
> > @GitHunter0 could you elaborate on what the gap is and what kind of queries you are running? Thanks!
> 
> Hey @hannesmuehleisen , of course, the gap I'm referring is the compression capability. As I mentioned, my duckdb database file is 2.5 times bigger than my SQLite's (4.5 GB vs 2 GB). However it is nice that you guys are already working on that 👍
> 
> I also noted that my duckdb queries are taking longer. It is hard to provide a reproducible example since my data is big and restricted but one basic rotine example is something like this:
> 
> ```
> db_con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "db_fi.duckdb", read_only=TRUE)
> 
> # "my_table" has 27 millin rows, 8 columns, 2GB SQLite, 4.5GB duckdb                         
> tab_con <- dplyr::tbl(db_con, "my_table")
> 
> tab_con %>% 
>   filter(var1 %in% c(value11, value12), var2 > value2, var3 > value3) %>%
>   select(var1, var2, var3) %>% 
>   collect()
> ```
> 
> Time to complete the query: SQLite took 29.95 sec VS. duckdb 38.69 sec .
> I observed that the key difference was in the time taken to retrieve data from the database to R, via collect()
> 
> Lastly, sometimes duckdb takes a long time (minutes) to open the connection (via DBI::dbConnect(...)), which I believe is due to the behavior described by @Alex-Monahan , in which the .wal content is merged into the main database file when the connection is opened. If instead that behavior happened while closing the connection, this issue could be avoided, right?

Hi @hannesmuehleisen , should I open a separate new issue to discuss these matters?
