### ISSUE TITLE
CROSS JOIN on DEMO site appears to not return results

### ISSUE THREAD

**Issue by jafin** [cwida/duckdb#919]
## Action
I use demo page https://duckdb.org/demo/
I enter query:
```sql
SELECT COUNT(*) FROM lineitem as x CROSS JOIN lineitem as y
```
I wait, but no results are returned.

## Expected Result: 
Cartersian product COUNT is returned.

**Comment by hannesmuehleisen** [comment]
The result is `36 014 581 476 225`. It might simply time out.
