### ISSUE TITLE
Column name aliases not supported in CTEs

### ISSUE THREAD

**Issue by erezsh** [cwida/duckdb#921]
This basic code fails. How can I realistically use CTEs if I can't name the columns?

```python
import duckdb

conn = duckdb.connect(':memory:')
c = conn.cursor()

c.execute("""
    WITH my_list(value) AS (VALUES (1), (2), (3))
    SELECT * from my_list WHERE value > 1;
""")
print(c.fetchall())
```

**Comment by hannesmuehleisen** [comment]
This was already fixed in master. Your example works there. Try installing the pre-release version of DuckDB (`pip install duckdb --upgrade --pre`)
