### ISSUE TITLE
Constraint type not handled yet! (foreign key)

### ISSUE THREAD

**Issue by erezsh** [cwida/duckdb#923]
Cannot declare a foreign key:

```SQL
CREATE TABLE IF NOT EXISTS "Person" ("id" INTEGER, "country" INTEGER, FOREIGN KEY(country) REFERENCES "Country"(id))
```

This is a basic construct in sql, which sqlite allows. I think it just ignores it, as there's no harm in doing so.

It would make it easier to copy schemas from other databases.

**Comment by hannesmuehleisen** [comment]
Indeed foreign keys are not supported yet. However, silently ignoring things seems rather dangerous to me. We could convert it to a warning?

**Comment by hannesmuehleisen** [comment]
See also #46, closing here.
