### ISSUE TITLE
Add missing PRAGMAs to documentation

### ISSUE THREAD

**Issue by wizzard0** [cwida/duckdb#925]
various issues mention `PRAGMA memory_limit`, but it gives an error:

```
sqlite> pragma memory_limit=2GB;
Run Time: real 0.000 user 0.000000 sys 0.000000
Error: Parser: syntax error at or near "GB" [22]
```
working syntax seems to be `pragma memory_limit='2gb'` instead

so, it would be great if the list was available in shell and\or on website somewhere

otherwise, thanks a lot! performance looks kinda impressive so far

**Comment by hannesmuehleisen** [comment]
there is this page: https://duckdb.org/docs/sql/pragmas
But it is missing some of the more recent PRAGMAs.

**Comment by hannesmuehleisen** [comment]
I've updated the website to contain all pragmas.
