### ISSUE TITLE
Time series database

### ISSUE THREAD

**Issue by webfolderio** [cwida/duckdb#928]
Hi,

Is it suitable tp use DuckDB as time series db?

**Comment by hannesmuehleisen** [comment]
In general yes but depends on what you do?

**Comment by hawkfish** [comment]
Time series management is a [big area](https://drops.dagstuhl.de/opus/volltexte/2019/11634/pdf/dagrep_v009_i007_p024_19282.pdf). If you can describe your task, maybe we can help?

**Comment by webfolderio** [comment]
Is there a specific sql function for data aggregation?

I would like to insert perf monitor data and downsample time-series data (hourly, daily etc...)

thanks

**Comment by hannesmuehleisen** [comment]
Yes, there are various aggregate functions, both non-grouped, grouped and windowed. To downsample data by hour or day, you can use the `EXTRACT` function to generate appropriate groups.

**Comment by hannesmuehleisen** [comment]
Closing this for now. Feel free to reopen with a more specific issue.
