### ISSUE TITLE
shell/CLI: make the "filename" argument optional

### ISSUE THREAD

**Issue by pacien** [cwida/duckdb#930]
The duckdb CLI tool turns out to be very handy to quickly extract some statistics from CSV files (with `read_csv_auto`) from the command line for example.

This kind of operations can be fully done in-memory and doesn't require persisting a file to disk, but the CLI tool still requires a "FILENAME" to be given as first argument, and otherwise opens an interactive subshell instead of executing the SQL statement given as second argument.

This mandatory argument should perhaps be made optional instead.

**Comment by hannesmuehleisen** [comment]
Ha, that's a nice use case we have not thought of. We use the sqlite shell unmodified, but there are two options to achieve what you describe

1: `stdin`:

`echo "select * from read_csv_auto('test.csv')" | ./duckdb`

2: special db file name `:memory:"

`./duckdb ":memory:" "select * from read_csv_auto('test.csv')"`

You could make an alias in your shell for this as well
