### ISSUE TITLE
duckdb with SQLite-3.33.0+ REPL

### ISSUE THREAD

**Issue by jgranduel** [cwida/duckdb#931]
Hi, 

As far as I understand, Duckdb usses SQLite REPL. SQLite 3.33 has brought about [enhancements in CLI](https://www.sqlite.org/releaselog/3_33_0.html), mainly:
-    Added four new output modes: "box", "json", "markdown", and "table".
-    The "column" output mode **automatically expands columns** to contain the longest output row and automatically turns ".header" on if it has not been previously set.
-    The "quote" output mode honors ".separator"

Is an upgrade doable and maybe on the roadmap?
Thanks !

**Comment by Mytherin** [comment]
We mostly use the shell as-is so this is definitely feasible. It might even be almost a drop-in replacement.

**Comment by hannesmuehleisen** [comment]
let me give this a try

**Comment by hannesmuehleisen** [comment]
It compiled, lets see what the tests say, see branch `newshell`

**Comment by derekmahar** [comment]
Does DuckDB share only the SQLite REPL?  Does it use any other code from SQLite?

**Comment by jgranduel** [comment]
How responsive you are!! Thanks a lot!

**Comment by hannesmuehleisen** [comment]
> Does DuckDB share only the SQLite REPL? Does it use any other code from SQLite?

No that's the only thing we use.

**Comment by hannesmuehleisen** [comment]
> How responsive you are!! Thanks a lot!

Our pleasure! Thanks for bringing this up.

**Comment by Mytherin** [comment]
> > Does DuckDB share only the SQLite REPL? Does it use any other code from SQLite?
> 
> No that's the only thing we use.

I should add to that: the core system doesn't share any code with SQLite. In addition to the shell, we do also use their testing framework, as well as a lot of their tests. We also use the header `sqlite3.h` as basis for our SQLite API wrapper :)

**Comment by Mytherin** [comment]
This has been merged into master now.
