### ISSUE TITLE
No exported functions in windows dll

### ISSUE THREAD

**Issue by Giorgi** [cwida/duckdb#934]
When I open duckdb.dll in [DLL Export Viewer](https://www.nirsoft.net/utils/dll_export_viewer.html) I see an empty list but when I open sqlite3.dll I see all of the functions:

SQLite:
![image](https://user-images.githubusercontent.com/580749/93755431-555e2480-fc14-11ea-9b3c-60fc015da729.png)

Duckdb:
![image](https://user-images.githubusercontent.com/580749/93755497-76267a00-fc14-11ea-9e5e-bd9f6a738779.png)

**Comment by Mytherin** [comment]
I think we need to add some DLL export flags to our functions for Windows to solve this problem. Have to look into it in more detail.

**Comment by msmshazan** [comment]
I have made a PR for a fix to this issue

**Comment by Giorgi** [comment]
When can we expect a new build ?

**Comment by hannesmuehleisen** [comment]
You can already download the pre-release binaries. But beginning of next month would normally be the time when we make a new release.
