### ISSUE TITLE
SQLite: Double query parsing

### ISSUE THREAD

**Issue by jdahlin** [cwida/duckdb#946]
From sqlite3_api_wrapper.cpp:

`ExtractStatements` and `Prepare` are both eventually calling `ParseStatements()` which means that queries are parsed twice.

**Comment by Mytherin** [comment]
Nice find, indeed that is the case. We could expand the Connection API so that Prepare can also be called with an already-parsed statement. That way the double-parsing can be avoided.

**Comment by Mytherin** [comment]
This issue is fixed in PR #1102. The parser is now invoked only once.
