### ISSUE TITLE
ARMv7 (Raspberry Pi 3/4) Binaries 

### ISSUE THREAD

**Issue by D1plo1d** [cwida/duckdb#948]
The website presents me with x64 builds but I want to download a binary for my headless raspberry pi. Are there builds available for the Raspberry Pi? Where do I download them from?

**Comment by hannesmuehleisen** [comment]
Which Raspberry Pi are we talking about here? We should indeed provide Arm binaries. Related to #941

**Comment by hannesmuehleisen** [comment]
We now build and provide binaries for Raspberry Pi as part of our nightly builds and releases.

**Comment by dickoa** [comment]
Hi @hannesmuehleisen,

Thanks for this,  is this build compatible with `aarch64` too ?
I use Arch Linux Arm 64 bit with Pi 4 (4Gb version) and when I try to use the CLI build, I get this error: 

```
-bash: ./duckdb: cannot execute binary file: Exec format error
```

Here're the info on my Kernel and architecture

```
Linux archpi64 5.8.9-2-ARCH #1 SMP Tue Sep 15 00:48:59 UTC 2020 aarch64 GNU/Linux
```

Is there something I can follow to build it myself ?

Thanks again,
Ahmadou

**Comment by hannesmuehleisen** [comment]
@dickoa you can try to build from source of course, or use the 32-bit image maybe? We should also have those 64 bit binaries eventually, but need to figure out how to cross compile those.

**Comment by dickoa** [comment]
Thanks @hannesmuehleisen, I manage to build the cli + library.
Now, I just need to move from sd card to ssd to start testing against a large dataset!
Thanks again
