### ISSUE TITLE
Full Text Search extension

### ISSUE THREAD

**Issue by mskyttner** [cwida/duckdb#952]
The RSQLite embeds a SQLite3 library which has a full text search extension (https://www.sqlite.org/fts5.html). 

It can be used like in this example https://github.com/mskyttner/factbook/blob/master/R/factbook.R#L109-L123 to enable full text search querying against a bundled database. 

What I like so much with this feature is that it comes with the library since a few years back. 

It can sometimes offer a nice simple embeddable "poor man's" alternative to solutions like Elastic Search etc that are heavier on resources and more complex to deploy.

Example use case for such functionality can be for example in packages such as https://docs.ropensci.org/taxadb/reference/name_contains.html when doing name matching etc where MATCH and NEAR could be useful for non-numerical data. 

In general also with cube/OLAP data, it could be useful when searching / matching values in dimensions or to use when grouping/MATCHing together dimensions that are NEAR before aggregating?

**Comment by hannesmuehleisen** [comment]
Yes, this is certainly an interesting extension to DuckDB. Building an inverted index from strings is not so crazy, but fuzzily matching them is a bit more involved. We should have a look at how SQLite implements this.

**Comment by hannesmuehleisen** [comment]
This has been implemented by @lnkuiper
