### ISSUE TITLE
Support Pandas Int64 type and timezone-aware Timestamp

### ISSUE THREAD

**Issue by amotl** [cwida/duckdb#959]
Dear @Mytherin and @hannesmuehleisen,

first things first: Thanks a bunch for conceiving this excellent project - DuckDB is really amazing!

We recently added DuckDB-support to [Wetterdienst](https://github.com/earthobservations/wetterdienst) through https://github.com/earthobservations/wetterdienst/pull/158 and it was a real pleasure to get started with.

While playing with some weather forecast data (https://github.com/earthobservations/wetterdienst/pull/114) by using the DuckDB feature to query Pandas DataFrames in memory using SQL, we found that DuckDB will croak on a) timezone-aware Pandas Timestamps and b) Pandas Int64 types:
```
RuntimeError: unsupported python type datetime64[ns, UTC]
RuntimeError: unsupported python type Int64
```

The example test cases [`pandas_duckdb_test.py`](https://gist.github.com/amotl/a7547aa114f085fa0f96a357190ee493) will invoke the simple query `SELECT * FROM data` against different Pandas DataFrames in order to demonstrate our observations.

Is there anything you can do about it?

Keep up the spirit and with kind regards,
Andreas.

**Comment by Mytherin** [comment]
Thanks for the report and the test cases! These types indeed are not supported right now, but it shouldn't be too much effort to implement them. I will have a look.

**Comment by Mytherin** [comment]
Should be implemented in #960. Could you have a look to see if that fixes your issue?

**Comment by amotl** [comment]
Dear Mark,

that was really quick, thanks a bunch! While [ignoring the timezone for now](https://github.com/cwida/duckdb/pull/960/files#diff-82e3181a7465c4f7cd6e1d7096a95621R403), everything works just perfectly now.

With kind regards,
Andreas.

**Comment by Mytherin** [comment]
Should be fixed now then

**Comment by amotl** [comment]
Dear @Mytherin,

thanks a bunch! We just activated SQL support for [wetterdienst](https://github.com/earthobservations/wetterdienst) through https://github.com/earthobservations/wetterdienst/pull/194 again. Everything works as expected.

Cheers,
Andreas.

**Comment by Mytherin** [comment]
Very cool, let me know if you run into more issues :)
