### ISSUE TITLE
Arrow/Feather support?

### ISSUE THREAD

**Issue by hannesmuehleisen** [cwida/duckdb#96]
Let's consider supporting query results to apache arrow and querying feather files or arrow in-memory structures. advantage: tooling in third party environment

**Comment by hannesmuehleisen** [comment]
Arrow can read Parquet, so #97 is solved by this as well.

**Comment by hannesmuehleisen** [comment]
Not going to happen because dependencies in Arrow :/

**Comment by aris-koning** [comment]
What do you mean exactly with dependencies in Arrow?

**Comment by eric-jesover** [comment]
@hannesmuehleisen  based on #151 
Do you have an idea when we can read a Parquet file directly in DuckDB?

**Comment by hannesmuehleisen** [comment]
We are working on a duckdb-native Parquet reader. Should be merged within four weeks.
