### ISSUE TITLE
A mechanism for virtual tables

### ISSUE THREAD

**Issue by patrickdevivo** [cwida/duckdb#968]
I apologize if this has been asked already or is possible in some way currently - but something like the [virtual table mechanism of sqlite](https://sqlite.org/vtab.html) could be really interesting, and possibly enable some cool use cases (queries over APIs or across different types of data on disk). I understand there are some mechanisms for UDFs, features like `parquet_scan`almost act like a virtual table, and same with the python dataframes integration. Though it could be very cool to support something that looks similar to sqlite3 vtabs.

Would be curious to know what folks think!

**Comment by hannesmuehleisen** [comment]
Yes, indeed you can create a table producing user-defined function and that has the same effect.  We should probably expose this API better. But indeed if you look at how the Parquet reader does this, you can do the same already: Create a `TableFunction` instance and register it using `db.catalog->CreateTableFunction(*conn.context, ...);`

**Comment by patrickdevivo** [comment]
thank you @hannesmuehleisen for the context, that is helpful!
