### ISSUE TITLE
Integer vs. floating point division

### ISSUE THREAD

**Issue by tdoehmen** [cwida/duckdb#971]
I tried to calculate the ratio of null values for a particular column as in following example:

```
CREATE TABLE IF NOT EXISTS test (
  a int,
  b int
);

INSERT INTO test (a, b) VALUES
  (1, 0),
  (2, 1),
  (null, 2);

SELECT  SUM(CASE WHEN a IS NULL THEN 1 ELSE 0 END)/COUNT(*) from test;
```

Thereby I stubled over the fact that DuckDB performs an integer divsion which results in 0, while I was expecting 0.3333. This is perfectly reasonable as I am dividing two integers. However, having worked with Spark SQL a lot, I apparently got quite used to the convenience of implicit floating point divisions for integers.

I just tried out a few different systems and it seems like there is no real consensus on the "right" way of doing it. 

MySQL 5.6: floating point division
PostgreSQL 12.4: integer division
SQLite 3.33.0: integer division
MS SQL Server 2019: integer division
MariaDB 10.4.12: floating point division
SparkSQL 2.3.1: floating point division

I don't have a true favorite, but I might be a bit biased towards the floating point division style for data-sciency work. Just want to leave it here as a possible discussion point.

**Comment by hannesmuehleisen** [comment]
Yes this is indeed a point of contention. I have heard someone say that integer division is required by the SQL standard, but would have to check. I think going with Postgres & SQLite is pretty sane here.

**Comment by hawkfish** [comment]
Yes the standard requires this. A simple change makes the query portable:

```SELECT  SUM(CASE WHEN a IS NULL THEN 1.0 ELSE 0.0 END)/COUNT(*) from test971```
