### ISSUE TITLE
Support RENAME TABLE/VIEW while previous table/view is not cleaned up yet

### ISSUE THREAD

**Issue by Mytherin** [cwida/duckdb#980]
Currently a `DROP` followed by a `RENAME` to the dropped entry in the same transaction fails because the mapping still contains the index pointing to the dropped entry. In order to fix this, the mapping in the `CatalogSet` needs to be transaction controlled as well, so multiple references to different tables from the same name can exist. See [this comment here](https://github.com/cwida/duckdb/pull/979#issuecomment-701993795) for more info.

**Comment by jwills** [comment]
Think we're good to close this-- thanks @Mytherin!
