### ISSUE TITLE
query-specific progress bars

### ISSUE THREAD

**Issue by alanpaulkwan** [cwida/duckdb#983]
Very sorry if this already exists

Bigquery tells you the query stage, and to some extent the query progress. Clickhouse has an explicit progress bar. Is there a way to do this with DuckDB? 

It would be helpful for query profiling, be neat to look at, and for super large queries give a forecasted run time basically.

**Comment by hannesmuehleisen** [comment]
No this does not exist yet but should.

**Comment by pdet** [comment]
The progress bar is now implemented.
It works with table scans, CSV, parquet, and pandas.

To enable it:
PRAGMA enable_progress_bar

By default, it only shows up for queries that take longer than 2s. If you desire to change this time
PRAGMA set_progress_bar_time=${time_in_milliseconds}
