### ISSUE TITLE
duckdb_fdw

### ISSUE THREAD

**Issue by alitrack** [cwida/duckdb#993]
I create a repo named [duckdb_fdw](https://github.com/alitrack/duckdb_fdw)

it bases on [sqlite_fdw](https://github.com/pgspider/sqlite_fdw)(fork and with modification).

by now,

it support select and insert, still not support update and delete.

**Comment by hannesmuehleisen** [comment]
Thanks for letting us know, I have added you project to our "Other Projects" list at https://duckdb.org/docs/why_duckdb.html
